### ISSUE TITLE
Can I pass CLI options in addition to route?

### ISSUE THREAD

**Issue by developer99** [bcosca/fatfree#1001]
Hello,

```
php index.php /my-awesome-update-route
```
.. works fine.  

But I would like to use this.  **Is there a way?**

```
php index.php /my-awesome-update-route -opt1=value1 -opt2=value3
```
I know that I can use route parameters but these option values will have special chars and spaces in them that I would have to obfuscate to make them pass through the route.

I have rearranged the CL many different ways but they don't seem to be picked up in index.php when specifying the route.

Thank you.

**Comment by xfra35** [comment]
It has been implemented recently, but it's not in the docs yet.
Cf. https://github.com/bcosca/fatfree-core/issues/134

**Comment by developer99** [comment]
Excellent. Very cool.  thank you.  I will take a look.
