### ISSUE TITLE
PDO fail if using php 7.0 and php-apcu be installed

### ISSUE THREAD

**Issue by rsandrade** [bcosca/fatfree#1003]
When I installed php-apcu on Ubuntu 16.04 with apache2 and PHP 7.0, the app started to fail sometimes to access the database. I got that errors a time every 5 to 10 hit.

PDO: near "FROM": syntax error, referer: www.thedomain.com

In apache error.log I got: [:error] [pid 19693] [client 177.158.198.109:56067] PDO: no such table: nameoftable

**Comment by royhg** [comment]
Hello rsandrade,
Can I know what kind of php-apcu? is it like some caching method? the fatfree is already had something to take care of that and I had been succeed using php70 without error..

**Comment by KOTRET** [comment]
If that happens only once upon a time, it sounds more like a server issue. You tried to deactivate apcu for testing purposes? Also, can you please provide some more informations, like a stacktrace or sth like that (enable exceptions for PDO)?

@royhg apcu is the user-cache-part of apc, as opcache is built in in php7.

**Comment by rsandrade** [comment]
@royhg I just installed the php-apcu package and the errors started to appear. When I removed the package, turned back normal and I did not had the error again.

@KOTRET The problem happened during the time the php-apcu was installed and I did not tried to repeat. 

And I was using an updated SQLite.
