### ISSUE TITLE
No document about [cli] request type

### ISSUE THREAD

**Issue by chinkung** [bcosca/fatfree#1005]
I can see [cli] request type in CHANGELOG

3.6.0 (19 November 2016)
*	NEW: [cli] request type
*	NEW: console-friendly CLI mode

but nothing on https://fatfreeframework.com/3.6/home describe about it.

**Comment by ikkez** [comment]
yes you're right. we should probably update https://fatfreeframework.com/3.6/routing-engine#RoutinginCLImode
You can find some details here: http://slides.com/ikkez/fat-free-v3-6#/9

**Comment by eazuka** [comment]
Yes in support of this issue, there is need for proper documentation of this CLI feature, especially how to get the CLI to work in command line.

**Comment by xfra35** [comment]
Done in https://github.com/F3Community/F3com-data/commit/3b8bc695760db7e9378398e0f80c9a134e493997

It should be visible at https://fatfreeframework.com/3.6/routing-engine#RoutinginCLImode soon.
