### ISSUE TITLE
Web->minify breaks some CSS rules

### ISSUE THREAD

**Issue by leonardfischer** [bcosca/fatfree#1008]
Hi there,

I'm using the `Web::instance()->minify(...);` snippet to compress multiple CSS files into one. But now, this happens:

The original CSS...
```
.widget > div :first-child {
	margin-top: 0;
}

.widget > div :last-child {
	margin-bottom: 0;
}
```

...gets minified to:
`.widget>div:first-child{margin-top:0;}.widget>div:last-child{margin-bottom:0;}`

But it SHOULD look like this:
`.widget>div :first-child{margin-top:0;}.widget>div :last-child{margin-bottom:0;}`

Is there something I missed? Maybe some kind of option to configure the minify process?

Best regards,
Leo

**edit**
By the way the last `;` of each block can be stripped in CSS.

**Comment by ikkez** [comment]
Should be fixed now. And the last `;` is also stripped now.

**Comment by leonardfischer** [comment]
Awesome! Thank you very much!
