### ISSUE TITLE
Reroute and minify issues

### ISSUE THREAD

**Issue by adeko** [bcosca/fatfree#1010]
After last upgrade I had 2 issues.

**1. Reroute**
https://github.com/bcosca/fatfree/blob/master/lib/base.php
function reroute
line 1377: `$port=in_array($port,[80,443])?'':':'.$port;`

I'm using iptables prerouting redirect, redirecting port 80 to 8088, cause I can't bind to port 80 in some cases. Thus I have to add more ports to array to ignore them on route building. 

Could you please add some way to add extra ports from settings, which should be omitted, without editing the core.

**2. Minify** 
https://github.com/bcosca/fatfree/blob/master/lib/web.php
function minify
line 591: `is_bool(strpos($save,'../')) &&`

I'm not sure what's the purpose of this line, but because of it 'minify' stopped working for me. 
I had to remove it to make it work. I'm using relative $path to css/js files' folder.

Please check.

**Comment by Rayne** [comment]
Regarding the second bullet point: It's not allowed to traverse parent directories. You could add the required path to the `UI` system variable.

Please have a look at the following issue: https://github.com/bcosca/fatfree-core/issues/199.

**Comment by adeko** [comment]
Regarding minify, now I understand the issue, I'll update my $path variable. Thanks.

What about rerouting? Is it possible?

**Comment by Rayne** [comment]
You could test the following workaround:

```php
$f3 = Base::instance();
$f3->set('PORT', 80);
```

**Comment by adeko** [comment]
Yes, maybe I should do something like this:

```php
$port = $_SERVER['SERVER_PORT'];
if ($port == 8082) $f3->set('PORT', 80);
if ($port == 8083) $f3->set('PORT', 443);
```

Then this might work `$port=in_array($port,[80,443])?'':':'.$port;`

Thanks.
