### ISSUE TITLE
Using if/option for set tag in template?

### ISSUE THREAD

**Issue by royhg** [bcosca/fatfree#1011]
Dear Bong Cosca,

Can we using set tag with if inside? like using include tag?
<set if='{{@exp}}' var1='' var2='' />

Regards,
Roy

**Comment by KOTRET** [comment]
please add an example of what you are trying to achieve.
Setting variables in Views _imho_ is not recommend / "bad style".
Beside that you can call a function that does this for you.

**Comment by royhg** [comment]
as example;

<set if='{{@expr1}}' var1=x var2=xxx />
this set variables is just on current template and behaviour is temporer purpose before show up to the screen.

**Comment by ikkez** [comment]
What about a ternary, @royhg ? `<set var1="{{ @expr1 ? @x : @y }}" />`
