### ISSUE TITLE
DB/SQL.log() not updating when template being rendered

### ISSUE THREAD

**Issue by devzing** [bcosca/fatfree#1012]
v3.5 (haven't checked 3.6)
I create a connection and save it in the hive. I have verified that I do not create another connection.
The calls recorded in DB/SQL.log() stop when rendering a template. I believe this is because the hive is being duplicated to prevent child-templates from interfering with parent templates, but can't find exactly where this is happening. 
Verified by adding error_log() calls in DB/SQL.exec(). Many more entries in the php log than reported by DB/SQL.log()

**Comment by sn0opy** [comment]
Could you post your code? Did you access log() via the hive? Something like “$f3->DB->log()”?

**Comment by devzing** [comment]
I will try to get a succinct example put together.

**Comment by Rayne** [comment]
The system or custom `$hive` is only copied when auto escaping is enabled:

1. [View->sandbox() @ L2695](https://github.com/bcosca/fatfree-core/blob/29c543d192b924fae6a376e97bbd064f8968f9ea/base.php#L2695)
2. [Base->recursive() @ L818](https://github.com/bcosca/fatfree-core/blob/29c543d192b924fae6a376e97bbd064f8968f9ea/base.php#L818)

**Solution**

```php
echo Base::instance()->esc(Base::instance()->get('SQL')->log())
```

As `Template` template (not tested):
```
{{ Base::instance()->esc(Base::instance()->get('SQL')->log()) }}
```

**Comment by devzing** [comment]
https://github.com/devzing/fff-bug shows the behavior.

Changing to @Rayne suggestion fixes the issue, although calling esc() threw and error the following worked:
`{{ Base::instance()->get('db')->log() }}`

**Comment by Rayne** [comment]
My bad. It throws an exception as there isn't a `Base->esc()` method. It should be `$this->esc()` or `Template::instance()->esc()`. The best and recommended solution would use a `Template` filter:

```
{{ Base::instance()->get('SQL')->log() | esc }}
```
