### ISSUE TITLE
CACHE doesn't work with php-memcached module ?

### ISSUE THREAD

**Issue by nailarch** [bcosca/fatfree#1013]
System: Ubuntu 16.04, php7.1-fpm, memcached and php-memcached(https://github.com/php-memcached-dev/php-memcached).
With this setting:
$f3->set('CACHE','memcache=localhost:11211');
- cache is still using /tmp/cache folder.

But with "php-memcache" module works good: /tmp/cache is empty.

I want to use php-memcached with igbinary serializer. How to get it work in fat free framework?

**Comment by bcosca** [comment]
Use `$f3->set('CACHE','memcached=localhost:11211');` instead. Make sure you use the dev branch.
