### ISSUE TITLE
Multiple row save at once

### ISSUE THREAD

**Issue by royhg** [bcosca/fatfree#1025]
Hi BCosca,
Do you have a way to save multiple rows at once using model instance?
I had troubled mysql lost connection to save each cursor using model instance
But I was suceed using model->db->exec at once.
But using the last mehod I should to rebuild model hooks manual before executing script..
Regards,

**Comment by KOTRET** [comment]
The mapper-objects provide additional features like before-/after-insert-triggers and other things. These functions operate on one record at a time, so it is not possible to perform the operation you trying to achieve. `exec` is the way to go when inserting multiple records at a time.

**Comment by ikkez** [comment]
Please reopen if the answer didn't helped.
