### ISSUE TITLE
Include css file in my view is not working

### ISSUE THREAD

**Issue by shahzadthathal** [bcosca/fatfree#1026]
Hi,

I'm trying to include custom css file in my view but it is not working.
What is the issue?

URL: directory/controller/index

Index.html
```<link href="{{@BASE}}/css/bootstrap-wizard.css" type="text/css" rel="stylesheet" />```

Thanks

**Comment by bcosca** [comment]
https://groups.google.com/forum/#!forum/f3-framework is the right venue for questions regarding usage.
