### ISSUE TITLE
SEED issue with 3.6.1

### ISSUE THREAD

**Issue by ptdev** [bcosca/fatfree#1028]
Hi guys, just updated some apps to 3.6.1 and noticed an issue.

Before upgrading, I had a SEED set (say: myseed) and my cache entries were saved like:

`myseed.2fiubxqhv1a8c.url`

After the upgrade my cache entries are getting saved as:

`1.2fiubxqhv1a8c.url`

Can anybody else confirm this? Thanks

EDIT: using php 7.1 and APCu cache engine

EDIT 2: The issue seems to be at line [2614](https://github.com/bcosca/fatfree/blob/master/lib/base.php#L2614).

This line:
`$this->prefix=$seed?:$fw->SEED;`

If I change it to:

`$this->prefix=$fw->SEED;`

It fixes the issue. I saw on the changelog something regarding a more flexible "SEED" but didn't really get what changes were made or if any changes are required on the code on our end.
Looking at that line I have to say I don't really get what that's doing. If there's a $seed, then set prefix to nothing? Otherwise use the hive's seed?

**Comment by KOTRET** [comment]
the ternary reads like "if `$seed` is falsy then use `$fw->SEED`, otherwise use `$seed`".
So an empty string, number `0`, the value `null` or boolean `false` are resulting in using `$fw->SEED`.
Imho commit https://github.com/bcosca/fatfree-core/commit/de79e0ef8e4e0326fc0e30997b968a7c90d72a50 cannot be responsible for that

**Comment by xfra35** [comment]
The ternary is correct. But there's an issue with [this line](https://github.com/bcosca/fatfree-core/blob/de79e0ef8e4e0326fc0e30997b968a7c90d72a50/base.php#L354).

Looks like a remnant from an old version.

**Comment by ptdev** [comment]
> The ternary is correct.

Is it though?
If you pass a string as $seed to the load() method (allowed according to the phpdoc: @param $seed bool|string), that $seed won't ever be set and only be used as a kind of boolean check? I'm probably missing something obvious but I don't think that's right.

**Comment by xfra35** [comment]
`$seed?:$fw->SEED` is a shorthand for `$seed?$seed:$fw->SEED` so the string would be used.

**Comment by ptdev** [comment]
Oops, you're right, since php 5.3 apparently so I'm way late to this party! Learn something everyday 👍 

Anyway, my initial issue still stands though. Have you been able to confirm you also get the prefix behavior I mentioned on my first post?

**Comment by xfra35** [comment]
@ptdev should be fixed in https://github.com/bcosca/fatfree-core now.

**Comment by ptdev** [comment]
Great, thanks @xfra35 
I hope this gets merged into 3.6.1-Release.
