### ISSUE TITLE
Template incorrectly setting header

### ISSUE THREAD

**Issue by sevn** [bcosca/fatfree#1032]
$html = Template::instance()->render("index.html", null);
echo Template::instance()->render("test.css", "text/css");

Results in "text/html" as the mimetype sent to the browser.

$html = Template::instance()->render("index.html", "text/plain");
echo Template::instance()->render("test.css", "text/css");

Results in "text/plain" as the mimetype sent to the browser.

Instead, the correct mimetype should be "text/css".

**Comment by ikkez** [comment]
this was fixed in 3.6.1

**Comment by sevn** [comment]
I'm at the current commit in this repo though? And currently looking at the code to solve myself I can't see how it is fixed.

**Comment by ikkez** [comment]
reference https://github.com/bcosca/fatfree-core/commit/442caaa6a18834c7931fe67e0a58769bdbf37dbd
