### ISSUE TITLE
Feature Request: provide handler name in beforeroute and afterroute hooks

### ISSUE THREAD

**Issue by RenaudParis** [bcosca/fatfree#1035]
Hi,

In base.php line 1608, method "run()", there is this code:
```php
// Call route handler
$result=$this->call($handler,[$this,$args],
```
But the `$args` variable does not contain the handler name, which is sad because it would be useful to help determine, for example, if a logged user is needed for that route before processing it (yes, I use controller classes with several handlers in each). And whithout knowing the handler name in the hooks, we can't do this (at least I did not find a way to do it).

Please just add the handler to the `$args` value, it's a 10 seconds fix, and it would be awesome!! :)

Alternatively you could do the fix inside the `call()` method, on line 1781 of the same file (just before `// Execute pre-route hook if any`), this way the handler will already be "interpreted and split into an array" (when applicable), and it would be even easier to use it inside the hooks, and it would have the other advantage to be centralized.

Thank you and best regards,

Renaud

**Comment by xfra35** [comment]
Done in https://github.com/bcosca/fatfree-core/commit/39507df84e9c7ddfa827cb9533a81b4ae5c6d489.

**Comment by RenaudParis** [comment]
Hi!

Sorry, did not see the notification.

Thank you a lot for this awesomeness!!! :+1: :smile: 

Best regards,
