### ISSUE TITLE
SQL bind parameter question

### ISSUE THREAD

**Issue by gexeh** [bcosca/fatfree#1038]
I have a website which is supposed to suggest entries from a database using ajax, however I cannot seem to get the results to return as expected.

I know the javascript side is working correctly and the parameters are being passed to the route and subsequently the controller.

I can get the results when using vanilla PHP, MySQL and PDO but I want to use F3.

The code is as follows;

```php
$field_id = $this->f3->get('POST.field_id');
$content = $this->f3->get('POST.content');

$suggestion = $this->db->exec('SELECT :field_id FROM cars WHERE :field_id2 LIKE :content', array(':field_id' => $field_id, ':field_id2' => $field_id, ':content' => '%' . $content . '%'));

echo $this->db->log();

print_r($suggestion);
```

This is the output;

`(0.1ms) SELECT 'car' FROM cars WHERE 'car' LIKE '%corsa%' Array ( )`

As you can see, no results are returned. When I run the same query in phpMyAdmin I also do not get any results returned.

However, if I run the following;

```sql
SELECT car FROM cars WHERE car LIKE '%corsa%'
```

I get the desired results.

How do I go about removing the apostrophes from the field names in the query when using db->exec?

If there's a better way to achieve this I'm all ears.

Any help would be much appreciated.

@bcosca

**Comment by ikkez** [comment]
I'm not sure if it is possible to put bind parameters to the fieldlist.. I think they can actually only be used to bind values to parameters, mostly in the WHERE condition. So just use this instead:

```php
$suggestion = $this->db->exec(
  'SELECT car FROM cars WHERE car LIKE :content', 
  array(':content' => '%' . $content . '%')
);
```

**Comment by KOTRET** [comment]
It is not possible to bind a param as column selector - see [Stackoverflow](http://stackoverflow.com/questions/23482104/can-i-use-a-pdo-prepared-statement-to-bind-an-identifier-a-table-or-field-name) for a detailed explanation.

**Comment by gexeh** [comment]
Thanks for the tips, I've managed to produce a workaround using a switch with a case for each field;

```php
		function suggest(){

			$field_id = $this->f3->get('POST.field_id');
			$content = $this->f3->get('POST.content');

			switch ($field_id){
				case 'car':
					$suggestions = $this->db->exec('SELECT car FROM cars WHERE car LIKE :content LIMIT 1', array(':content' => '%' . $content . '%'));
					break;
				case 'colour':
					$suggestions = $this->db->exec('SELECT colour FROM cars WHERE colour LIKE :content LIMIT 1', array(':content' => '%' . $content . '%'));
					break;
				case 'location':
					$suggestions = $this->db->exec('SELECT location FROM cars WHERE location LIKE :content LIMIT 1', array(':content' => '%' . $content . '%'));
					break;
				case 'registration':
					$suggestions = $this->db->exec('SELECT registration FROM cars WHERE registration LIKE :content LIMIT 1', array(':content' => '%' . $content . '%'));
					break;
			}

			echo "<li onclick='SuggestApply(\"" . $field_id . "\",\"" . $suggestions[0][$field_id] . "\"); return false;'>" . $suggestions[0][$field_id] . "</li>";

		}
```

If there's a better way to do this please let me know.

**Comment by KOTRET** [comment]
follow the DRY-principle 😉
declare an array with allowed columns (or read them from the model), check if the term is in that array and replace the part in the query.
But hey, thats your job as dev...

Guess the issue can be closed

**Comment by gexeh** [comment]
Thanks @KOTRET I've changed my code to the above.

Happy to close this one out.
