### ISSUE TITLE
SQL Mapper LIMIT/OFFSET handling SQL Server 2008 breaks sorting

### ISSUE THREAD

**Issue by dexwerx** [bcosca/fatfree#1039]
Can't use a subselect in a filter, when using limit/offset 
because the limit/offset handling does a replace on all "SELECT" in the sql.
It should only replace the first "SELECT".

but then it breaks the order... so not sure how to handle this yet.

**Comment by KOTRET** [comment]
please add an example query

**Comment by dexwerx** [comment]
```
    $device = new \Model\Device;
    $pages = (object) $device->paginate(1, 50,
        ["device.town_code IN (SELECT town_code FROM town WHERE town_name LIKE '%ATTL%')"]);
```

**Comment by dexwerx** [comment]
Fixed here: https://github.com/bcosca/fatfree-core/pull/225

Thanks!
