### ISSUE TITLE
reset file based cache: key pattern does not match

### ISSUE THREAD

**Issue by marcus-at-localhorst** [bcosca/fatfree#1041]
Hi,
I'm using the file based cache and can't reset the file, since the regex pattern does not match.

```
$f3->cache->reset('page_xxx');
```
produces this regex-pattern in `Cache::reset()` 

```
1\..+page_xxx
```
which doesn't match with

```
E:\WEB\f3.de/cache/data/1.page_xxx
```
https://regex101.com/r/lP1F0D/1

So I don't know what the `.+` between prefix and suffix is supposed to match.

I also wish I could delete groups with writing: `$f3->cache->reset('page_');` and then match these files:

```
E:\WEB\f3.de/cache/data/1.page_2014-05-31-Fort
E:\WEB\f3.de/cache/data/1.page_2015-03-29-Wickham-Statues-Palmyra-TN
```
The regex should be:
```
$regex='/'.preg_quote($this->prefix.'.','/').preg_quote($suffix,'/').'.*/';
```
This would work for:

```php
$f3->cache->reset('page_'); // resetting all
$f3->cache->reset('page_2015-03-29-Wickham-Statues-Palmyra-TN'); // reset only one file
```

**Comment by ptdev** [comment]
Are you using the latest version? Can you try with the latest master from https://github.com/bcosca/fatfree-core/ ?

I'm not really sure if reset() can be used like that to delete a single cache entry.

It's also strange that your cache prefix is "1" and not an autogenerated string.
Are you specifically setting it to "1" using the SEED variable?

**Comment by nickedgar** [comment]
having this issue with 3.6.2

for file/folder based cache I think the regex quantifier in reset() between the prefix and suffix should be .* not .+ to match 0 or more characters, not 1 or more characters.

the .+ quantifier works fine for removing this file :

PREFIX.3vjyoawxo5ycg.Permission.89.sql

but not this file :

PREFIX.EnrollmentRule.31

the regex assumes there will always be something between PREFIX. and the cache key when there isn't.

**Comment by ikkez** [comment]
The `$cache->reset ()` parameter is named `$suffix` because it'll wipe keys based on the end of a cache key. To make use of that, you should find a naming syntax for your cache keys that is build up like a reserve domain. Some simple samples could be

```php
// load some records from db with cache tags
$mp = new \DB\SQL\Mapper($f3->DB,'permissions');
$mp->find(['id = ?', 89], null, [3600,'89.permission']);
// clear cache
$cache->reset('sql'); // reset all cached SQL queries
$cache->reset('permission.sql'); // reset all SQL queries tagged with `permission`
$cache->reset('id89.permission.sql'); // reset all permission queries from id 89
```

In case we switch the regex from `.+` to `.*` it would probably solve your issue, but makes this whole concept invalid and backward incompatible.

**Comment by nickedgar** [comment]
We're using Cache->set(), not SQL caching. e.g.

```
$Cache = \Cache::instance();
$Cache->set('foo','bar', 10000);
var_dump($Cache->exists('foo'));

//cache file produced is /tmp/cache/BACON.foo

$Cache->reset('foo');
var_dump($Cache->exists('foo'));
```

using clear isn't an option as I'd like to clear more than one key, e.g. foo.x or foo.x.y

Altering our logic to use prefix or suffix keys has no effect as the file produced by Cache->set() is in the format :

/tmp/cache/PREFIX.foo

which will never match the current reset regex

unlike cache files produced by SQL caching which are in the format :

/tmp/cache/PREFIX.3tubg71nzq80s.foo.sql

which do match the current reset regex.

I suppose we could add something in front of the cache key :

```
$Cache->set('.foo','bar', 10000);
$Cache->reset('foo');
```

but this feels too hacky, we opted to change the regex instead

**Comment by xfra35** [comment]
@ikkez I was just wondering: why doesn't [the regex](https://github.com/bcosca/fatfree-core/blob/baa6015ebbf481d0ae9df034385bd8fe03738116/base.php#L2518) have a start and end delimiters?

Like `'/^'.preg_quote($this->prefix.'.','/').'.+'.preg_quote($suffix,'/').'$/'`?

@nickedgar you wrote:
> using clear isn't an option as I'd like to clear more than one key, e.g. foo.x or foo.x.y

What do you mean exactly? The `reset()` method takes a suffix argument, not a prefix. Or did you intend to take advantage of the missing `$` in the regex?

**Comment by nickedgar** [comment]
if i set key to **foo** file cache generates a file /tmp/cache/bacon.foo

if i reset **foo** it doesn't reset
if i reset **oo** it will.

**foo** is a prefix AND a suffix
**oo** is also a suffix. 

reset seems to rely on the cache file being generated in SQL and being in the format :

/tmp/cache/bacon.jhkasdhjkasd.suffix.sql

cache set generates files in the format

/tmp/cache/bacon.suffix

which fails the regex whether you label the reset parameter a prefix or a suffix?

**Comment by nickedgar** [comment]
I'll reframe as a question, building on @ikkez earlier example, if i set some cached content using these keys, some of which describe content that goes from the specific to the general...

```
$Cache = \Cache::instance();
$Cache->set('permission','permission', 10000);
$Cache->set('89.permission','permission_89', 10000);
$Cache->set('92.permission','permission_92', 10000);
$Cache->set('774.92.permission','permission_92_774', 10000);
```
How do I reset one or more or all of the keys above?

**Comment by ikkez** [comment]
exactly the same as in my sample above

```php
$cache->clease('permission'); // one
$cache->clease('92.permission'); // one
$cache->reset('permission'); // reset all keys with `permission` at the end
$cache->reset('92.permission'); // reset all permission keys from id 92
```

or another one

```
$cache->set('page_foo','bar', 10000);
$cache->set('nav_foo','bar', 10000);
$cache->set('content_foo','bar', 10000);
$cache->reset('_foo');
```

@xfra35 Yes I see your point. Well I'm not entirely sure about this $suffix var and if it's really meant to be this way I am interpreting it. Perhaps I'm putting to much tension to the name "suffix" but I think, in first place, it was meant to select different cached parts of the system (`.sql` for DB queries, `.var` for hive vars, `.schema` for table schemes, `.url` for web->requests and so one)
Adding an end delimiter seems correct to me.

**Comment by xfra35** [comment]
Then if we add the end delimiter to the regex, we could replace `.+` with `.*`, couldn't we?

This should fix the bug described by @nickedgar which is, if I understood it well, that `$cache->reset('permission')` does reset all keys that end with `permission` except `permission` itself.

**Comment by ikkez** [comment]
Sounds reasonable to me. 👍

**Comment by ikkez** [comment]
fixed

**Comment by dfumagalli** [comment]
@ikkez The cache behavior had been crafted [partly to address a database caching issue we had with F3 in my company](https://groups.google.com/forum/#!topic/f3-framework/t0hYxPVuFeE). It has been discussed on the forum and then [implemented](https://groups.google.com/forum/#!topic/f3-framework/YiWttadsP7U). We needed a way to clear multiple cache tags.

I am soon to update our F3 to latest versione. I hope these last changes did not break our backend!
