### ISSUE TITLE
Route placeholder breaks link when protocol is specified

### ISSUE THREAD

**Issue by acseven** [bcosca/fatfree#1045]
Hi,
I don't have the skills to be sure this is a bug or some kind of inconsistency with how I'm using f3, but here goes.

When I have a named route configured to accept different protocols, like so:
``` 
POST @rtMediaUpload:	/media/add 	[sync] 		= UserMediaController->handleImportedMedia
POST @rtMediaPublish:	/media/add 	[ajax] 		= UserMediaController->storeImportedMedia
```
When I try to build an URL in the frontend with the named route (I'm issuing the url into an element's attribute so that I can use it for an ajax call), it will break (error 500):
`<a href="" my-action="{{ @BASE }}{{ 'rtMediaPublish' | alias }}">link here</a>`

Removing `[ajax]` and changing the route to something else works as it should. It's not too troublesome for me, but I was reporting this just in case it is a bug.

Cheers

**Comment by xfra35** [comment]
Can you check the error log and provide more details about that error 500? It could be anything.

**Comment by acseven** [comment]
Sorry about this, it was related to code error.
Thanks in any case
