### ISSUE TITLE
JIG session CSRF always returns NULL

### ISSUE THREAD

**Issue by AnandPilania** [bcosca/fatfree#1049]
Recently I followed the official guide regarding SESSION and CSRF (https://fatfreeframework.com/3.6/session),

Here is the code:

     // config.ini => DB_PATH=db/
     // $f3->config('config.ini');

     $db = new DB\Jig ( $f3->get('DB_PATH'), DB\JIG::FORMAT_JSON );

      $session = new DB\Jig\Session ( $db, 'sessions', TRUE, NULL, 'CSRF' );

      $f3->copy ( 'CSRF', 'SESSION.CSRF' );

      var_dump ( [
        'f3->csrf' => $f3->CSRF, // returns NULL
        'Session->csrf()' => $session->csrf() // holds the CSRF value
      ]);

Here `f3->csrf` has `NULL` value but it must holds the `CSRF` token as `Session->csrf()`.

I also posted this question on F3 Google Group: https://groups.google.com/forum/#!topic/f3-framework/bZXfMMIJXgY

**Comment by ikkez** [comment]
The constructor does not have a 5th parameter. It should be:
`new DB\Jig\Session ( $db, 'sessions', NULL, 'CSRF' );`

I fixed it in the docs here https://github.com/F3Community/F3com-data/commit/dd79ce060aff9e13079d55d8f98a576fb8af29d2

**Comment by AnandPilania** [comment]
@ikkez : Thanks, its working now.
