### ISSUE TITLE
What about minifying HTML output?

### ISSUE THREAD

**Issue by radioboss** [bcosca/fatfree#1054]
Feature request. When templates are processed, it would be nice to get the resulting HTML also minified.

**Comment by eydun** [comment]
You can do that with the excellent assets plugin: http://f3.ikkez.de/assets

**Comment by radioboss** [comment]
Looks great, but from what I read, it's about minimizing and managing JS/CSS, not HTML. Or I didn't understand something?

**Comment by eydun** [comment]
I think you are right.

**Comment by bilabar** [comment]
It is simple. Just run function render template. But dont echo it. Remove whitespace and new line using regex. Then echo it. Like:

$unminified = View::instance()->render('layout.htm');
$minified = preg_replace('/\s\s+/sui', '', $unminified);
// or use $minified = preg_replace('/\s\s+|\r|\n|\t/', '', $unminified);
echo $minified;

**Comment by radioboss** [comment]
It's not that simple... I tried it and my app stopped working :)

**Comment by xfra35** [comment]
Are you sure there's a benefit in minifying HTML?

Compressing the output (using [mod_deflate](https://httpd.apache.org/docs/current/mod/mod_deflate.html) for example) is more effective for reducing the output size.

**Comment by radioboss** [comment]
Compressing and minifying are not mutually exclusive - I use them both.  For me, the main point is to remove comments, but I thought why not minify it? Given that framework already provides CSS and JS minifiers, HTML minifier feels like a good and logical addition.

For comments I currently use preg_replace('//', '', $html) but I'd prefer framework minifying option.

**Comment by ikkez** [comment]
You can use the php tidy extention for this http://php.net/manual/en/book.tidy.php
or in case you're using local build tool for frontend work, `gulp-minify-html` is an option as well.
I don't see this coming as a reinvented framework addition, as the task isn't that trivial as it might look at first. Think of conditional comments like `<!--[if IE ]>` for special browser treatment you may not remove, ignored markup within `<pre>` blocks, and whitespace in text nodes in general. Too many pitfalls for what benefit? gzip your response has a much bigger effect.
btw: `//` isn't even a valid html comment syntax

**Comment by KOTRET** [comment]
While minifying css and js is easy, because there are fixed rules in code, minification of HTML would depend heavily on the used doctype and therefore requires several optimizations for specific doctypes. Additionally this must forgive errors in html syntax like browsers do.
I agree with ikkez saying this is a too big Task.

**Comment by bcosca** [comment]
From a front-end perspective, not all whitespaces in HTML are unwanted. We don't want to start a war between designers and developers.

**Comment by radioboss** [comment]
It appears that it's not an easy feature as I thought at first. Thanks for consideration.

@bcosca, thanks for the great framework by the way!
