### ISSUE TITLE
copyFrom turns NULL into 0

### ISSUE THREAD

**Issue by developer99** [bcosca/fatfree#1055]
Hi,

I prepare db fields in a hive variable then use the following to hydrate the mapper.

`$tbl = new DB\SQL\Mapper($f3->get('DB'), 'user');`
`$tbl->copyFrom('PAYLOAD');`

NULL values in the hive turn into 0 in the mapper.  **Is this expected behaviour?**

Thanks.

![copyfrom-image](https://user-images.githubusercontent.com/394186/29073277-0990475a-7c19-11e7-8908-4a16d96584aa.jpg)

**Comment by developer99** [comment]
This appears to happen when using the mapper ->load method.  I need to search for a field that is actually NULL.

`$user->load(['user_email=? and user_password=? and airlineid=? and retailerid=? and user_status=?', 
                    $f3->get('PAYLOAD.user_email'), $upassword, $sysairlineid, NULL , $f3->get('US_Confirmed')]);
`

`(0.0ms) SELECT `userid`,`airlineid`,`ffpcustomerid`,`retailerid`,`user_status`,`user_status_date`,`user_email`,`user_password`,`user_type`,`user_key`,`user_fname`,`user_lname`,`user_addr1`,`user_addr2`,`user_addr3`,`user_city`,`user_state`,`user_postalcode`,`user_country`,`user_phone1`,`user_email1`,`email_confirm_time`,`pwd_reset_key`,`createdate`,`updatedate`,`createuser`,`updateuser` FROM `user` WHERE user_email='john.doe@acmejobs.com' and user_password='CVMSXxupSPmOeEgjDar2nF9ha-3ci3J_idVX-8-MBlk' and airlineid=1 and retailerid=0 and user_status='CONFIRMED'`

Guess I could check the code myself.  But there is possibly multiple occurrences of this behaviour.

Thanks.

**Comment by developer99** [comment]
Hm.. Looks like it might be getting the attributes from the DB and checking if it is nullable.  But I have the fields set to NULL.

![userdb](https://user-images.githubusercontent.com/394186/29093861-4f8f4e1e-7c59-11e7-93b5-465f40672fa7.jpg)

**Comment by ikkez** [comment]
Hi. Well finding a record with a NULL field in raw SQL goes like this:

```php
$user->load(['retailerid IS NULL']);
```

When you set a value to a mapper field, it is casted to the field type. This step is aware of a "nullable" flag in the table schema and should work as you are expecting it. What F3 version do you use?

**Comment by developer99** [comment]
VERSION='3.6.0-Release';

**Comment by developer99** [comment]
Well if I do not set the field to anything, it will be NULL on $tbl-save().  I can work with that.

I didn't know you could use ->load with raw SQL.  That is neat.

Maybe later I will check the nullable flag and see what it or I am missing.

**Thanks for a great framework!**

**Comment by ikkez** [comment]
I've made a quick test with the current version:

```php
$f3->route('GET /mappertest',function( Base $f3, $params) {
	$schema = new \DB\SQL\Schema($f3->DB);
	if (!in_array('mappertest',$schema->getTables())) {
		$table = $schema->createTable('mappertest');
		$table->addColumn('name')->type_varchar();
		$table->addColumn('customerid')->type_int()->nullable(true);
		$table->build();
	}

	$mp = new \DB\SQL\Mapper($f3->DB,'mappertest');

	$data = [
		'name' => 'John',
		'customerid' => NULL
	];
	$mp->copyfrom($data);
	var_dump($mp->cast());
	$mp->save();
	var_dump($mp->cast());
	$mp->reset();
	$mp->load();
	var_dump($mp->cast());
});
```

result:

```
array (size=3)
  'id' => null
  'name' => string 'John' (length=4)
  'customerid' => null

array (size=3)
  'id' => int 1
  'name' => string 'John' (length=4)
  'customerid' => null

array (size=3)
  'id' => int 1
  'name' => string 'John' (length=4)
  'customerid' => null
```

seems to work just fine here.

**Comment by developer99** [comment]
Ok.  Thanks for the test.  I will try it here and see what I get.


----- Original message -----

**Comment by developer99** [comment]
I am not quite sure your example is an equivalent to my environment.  I just upgraded from 3.6.0 to 3.6.2 and an interesting change came.

`
$user->load(['user_email=? and user_password=? and airlineid=? and retailerid=? and user_status=?', 
                    $f3->get('PAYLOAD.user_email'), $upassword, $sysairlineid, NULL , $f3->get('US_Confirmed')]);
`

gives this in 3.6.2

`
(0.2ms) SELECT `userid`,`airlineid`,`ffpcustomerid`,`retailerid`,`user_status`,`user_status_date`,`user_email`,`user_password`,`user_type`,`user_key`,`user_fname`,`user_lname`,`user_addr1`,`user_addr2`,`user_addr3`,`user_city`,`user_state`,`user_postalcode`,`user_country`,`user_phone1`,`user_email1`,`email_confirm_time`,`pwd_reset_key`,`createdate`,`updatedate`,`createuser`,`updateuser` FROM `user` WHERE user_email='john16@acmejobs.com' and user_password='Pwyg1anO16ZH_3aZGB6DSWUgnxet7HigB-aFVRjeYjw' and airlineid=1 and
retailerid='' and 
user_status='CONFIRMED'
`

And this in 3.6.0

`
(0.0ms) SELECT `userid`,`airlineid`,`ffpcustomerid`,`retailerid`,`user_status`,`user_status_date`,`user_email`,`user_password`,`user_type`,`user_key`,`user_fname`,`user_lname`,`user_addr1`,`user_addr2`,`user_addr3`,`user_city`,`user_state`,`user_postalcode`,`user_country`,`user_phone1`,`user_email1`,`email_confirm_time`,`pwd_reset_key`,`createdate`,`updatedate`,`createuser`,`updateuser` FROM `user` WHERE user_email='john16@acmejobs.com' and user_password='Pwyg1anO16ZH_3aZGB6DSWUgnxet7HigB-aFVRjeYjw' and airlineid=1 and
retailerid=0 and 
user_status='CONFIRMED'
`

Notice the retailerid in each.  I am not sure if I am on to something but I do need to get these values set to NULL.  I know there are workarounds but would really like to stick with the PDO provided.

I am fishing around the DB classes trying to find out where the determination of retailerid is happening.  If you can point me to it, I could maybe detect what is going on an why.

Thank you.

**Comment by ikkez** [comment]
Your SQL query wrong for the `NULL`parameter.. in raw PDO it's 
`$user->load(['retailerid IS NULL']);`
not 
`$user->load(['retailerid = ?', NULL ]);`

( except you're using Cortex)

**Comment by developer99** [comment]
Ok understood.  `IS NULL` vs `= NULL`.   A little special handling for NULL values I guess.

Thank you.
