### ISSUE TITLE
SQL Mapper's select does not respect custom field names

### ISSUE THREAD

**Issue by chaosflaws** [bcosca/fatfree#1057]
To reproduce this bug, create the following MySQL table:

```
CREATE TABLE `Test` (
  `c1` INT,
  `c2` TEXT
);

INSERT INTO `Test` VALUES
  (1, "a"),
  (2, "a"),
  (2, "b")
```

Then run the following PHP code:

```
<?php

$f3 = require('f3/base.php');

$f3->set('DEBUG', 3);

$f3->set('DB', new DB\SQL('mysql:host=localhost;port=3306;dbname=test_', 'root', ''));

$mapper = new \DB\SQL\Mapper(\Base::instance()->get('DB'), 'test');
$count = $mapper->select('c2, COUNT(*) AS count', '', array('group' => 'c2'));

foreach ($count as $row) {
    print($row->c2 . '<br>');
}

foreach ($count as $row) {
    print($row->count . '<br>');
}
```

The values from `c2` can be accessed via the mapper array while the values from `count` cannot, throwing an Internal Server Error `Undefined field count`.

**Comment by xfra35** [comment]
That doesn't work because computed fields need to be declared first.

Try:
```php
$mapper = new \DB\SQL\Mapper(\Base::instance()->get('DB'), 'test');
$mapper->count = 'COUNT(*)';
$rows = $mapper->find('',['group'=>'c2']);
```

That makes me wonder why the `select()` method isn't protected, as it's not very useful apart for internal use.

**Comment by chaosflaws** [comment]
In the [docs](https://fatfreeframework.com/3.6/databases#SeekandYouShallFind), the use of `select` is encouraged, stating:

> There's also a `select()` method that's similar to `find()` but provides more fine-grained control over fields returned.

(The example right below the text will show my exact problem.)

I feel like `select` would be quite useful to compute aggregates other than `count` if it would be able to keep track of aliases in the select clause.

**Comment by chaosflaws** [comment]
@xfra35 Your suggestion works, but I will probably just use native SQL.
