### ISSUE TITLE
Automatically append missing trailing slash to folders

### ISSUE THREAD

**Issue by chaosflaws** [bcosca/fatfree#1059]
I just tried:

```
<?php

$f3 = require('f3/base.php');

$f3->set('CACHE', 'folder=tmp');

new Session();
$f3->set('SESSION.test', 'test');
```

And f3 is generating file names that look like `tmp2sphqo45akoww.gp0bs4v9g1c440eug4u8rbop87.@` in the root dir instead of in the `tmp` folder.

**Comment by xfra35** [comment]
F3 folders (`UI`, `LOGS`, `CACHE`, etc.) usually end with a slash.

So `$f3->set('CACHE', 'folder=tmp/')` should fix your issue.

**Comment by chaosflaws** [comment]
I am aware of that, but it is rather common to add the trailing slash to a path if it is not there. Maybe not a bug, rather an enhancement that could be applied to the other globals as well.

**Comment by dfumagalli** [comment]
If you want backwards compatibility, beware with the automatisms. You never know if you are working on a virtual file system with limitations or weird behaviors in case of unexpected trailing characters.
