### ISSUE TITLE
Missing SERVER_NAME causes routing to fail

### ISSUE THREAD

**Issue by marcovn** [bcosca/fatfree#1060]
Hey,

Just something I ran in today that needs mentioning. My stack currently consists of a NGINX/fastcgi/php setup (using docker images).

Noticed that after updating from 3.6.1 to 3.6.2. all my routes where failing with a 404. After some digging around I tracked it to line 2251 in base.php

`		$uri=parse_url((preg_match('/^\w+:\/\//',$_SERVER['REQUEST_URI'])?'':
			'//'.$_SERVER['SERVER_NAME']).$_SERVER['REQUEST_URI']);
`

The parse_url fails when $_SERVER['SERVER_NAME'] is empty: it cannot handle relative URLs. This also is an issue in 3.6.1 (and possibly earlier versions) which I was using, but it did not cause any routes to fail in my case.

Solution was to explicitly set the SERVER_NAME in your nginx.conf like this:

`        fastcgi_param SERVER_NAME some_host_name;
`

Hope this helps somebody!

**Comment by xfra35** [comment]
The case where `SERVER_NAME` is set to an empty string (which seems to be quite common with Nginx) is now taken into account.
See https://github.com/bcosca/fatfree/issues/1084
