### ISSUE TITLE
Wrong Values on save()

### ISSUE THREAD

**Issue by bkrith** [bcosca/fatfree#1062]
Hi the save method not working correct.. sometimes saves the values correct and some others not!
Here i have a sample of object and mysql statements..
`Array ( [generator] => 14540427227084660294 [generatorRS] => BURST-T9L8-JT6E-V7SC-ETHLM [baseTarget] => 215244 [height] => 397685 [timestamp] => 96213450 [blockId] => 5376608400674127695 [generatorName] => JUAN AMYACH - WALLET [pool] => 7979631613202555765 [poolRS] => BURST-NSVP-PLHQ-FNQZ-8SCHX [poolName] => Ninja Reloaded V3 pool account [netDiff] => 85136 [deadline] => 96213450 [reward] => 1577 [fee] => 4500000000 ) 
INSERT INTO `blocks` (`blockId`,`height`,`generator`,`generatorRS`,`generatorName`,`pool`,`poolRS`,`poolName`,`timestamp`,`netDiff`,`deadline`,`reward`,`fee`) VALUES (5376608400674127695,397685,9223372036854775807,'BURST-T9L8-JT6E-V7SC-ETHLM','JUAN AMYACH - WALLET',7979631613202555765,'BURST-NSVP-PLHQ-FNQZ-8SCHX','Ninja Reloaded V3 pool account',96213450,85136,96213450,1577,4500000000) `

This stupid value is everywhere!! 9223372036854775807
Can anyone help me?
Thanks in advance!

**Comment by geniuswebtools** [comment]
Looks like you're hitting the max PHP integer for your OS instance.  Try using varchar(255) for your generator column and see if that resolves your issue.

**Comment by bkrith** [comment]
wth? my brean is soup! :D @geniuswebtools ty bro!!! you are amazing!!
