### ISSUE TITLE
Bcc and other additional headers are sent

### ISSUE THREAD

**Issue by cnd-jmu** [bcosca/fatfree#1065]
I want to send HTML emails with additional attachments (Excel files). 
For protocol purpose I want to send these emails to another address via Bcc.

Here are many headers inserted like Bcc, Message-Id and others, that don't belong there (as far as I know): 
https://github.com/bcosca/fatfree/blob/0539cd4c0bba2e6e8231dbca64156123725c9184/lib/smtp.php#L294 

It seems the conditions at https://github.com/bcosca/fatfree/blob/0539cd4c0bba2e6e8231dbca64156123725c9184/lib/smtp.php#L250 need to be revised and/or the `$str` should be removed at the line above.

As a current workaround I just removed the insertion:
`$out.=/*$str.*/$eol;`

**Comment by ikkez** [comment]
fixed
