### ISSUE TITLE
Template resolve() do not work as expected

### ISSUE THREAD

**Issue by SylwesterZarebski** [bcosca/fatfree#1066]
Hi,

  I'm trying to use resolve() method to render my templates from strings (from database) and not from files like render() method.
Simple call to `\Template::instance()->resolve($template)` do not render any variables inside template - just empty strings are returned instead.

Example of template - with `$f3->set('test', 'example')`:
```
{{ @test }}<br/>
abc
```

What is returned:
```
<br/>
abc
```

What should be returned
```
example<br/>
abc
```

Documentation shows example:
```
$tmpl = \Preview::instance();
$f3->set('title','<b>F3 rocks</b>');
$content = '<p>{{ @title | esc }}</p>';
echo $tmpl->resolve($content);
// return: <p>&amp;lt;b&amp;gt;F3 rocks&lt;/b&amp;gt;</p>
```

Which do not work at all, it returns `<p></p>`.

I've found a workaround by using call to `\Template::instance()->resolve($template, null, 0, true)` instead.

Please help, what should i do, is my workaround good way or there are caveats?

**Comment by ikkez** [comment]
Tested with the latest version and it works as expected here. What version do you use?

**Comment by SylwesterZarebski** [comment]
Sorry, it was my fault using mixed version of 3.6.2 with some code from 3.6.0 and Your patches for performance of configs. It was mixed up, after reverting it works now. Sorry for confusing.
