### ISSUE TITLE
Optional Route Parameters

### ISSUE THREAD

**Issue by gexeh** [bcosca/fatfree#1067]
Hi, I have the following route defined in routes.ini

`GET @cars_view: /cars/@colour-@car-@location.@id=CarsController->view`

I'm generating the links in my view with the following code;

`<a href="{{@BASE}}{{ 'cars_view', 'colour=' . @car.colour . ',car=' . str_replace(' ', '-', @car.car) . ',location=' . str_replace(' ', '-', @car.location) . ',id=' . @car.id | alias }}" title="View {{@car.car}}">`

This works great and generates the links as expected, for example;

`/cars/Red-Golf-R-Newcastle-upon-Tyne.1386`

However, if for example one of my entries in the database doesn't have a colour defined it generates the following link which still works but doesn't look SEO friendly at all;

`/cars/,car=Civic-@car-Yorkshire.1391`

How do I make my named parameters optional so that the link would gracefully change for example;

`/cars/Civic-Yorkshire.1391`

I'm not great at F3 so any in depth help on this would be much appreciated.

**Comment by ikkez** [comment]
Hi. Well questions like that would probably fit better to the [F3 google board](https://groups.google.com/forum/#!forum/f3-framework).

Nevertheless, I'd suggest you first create a custom template filter for rendering car links, so it does not get that messy in your templates. Then create a 2nd route for cars that does not contain the `colour` parameter, so links can be build correctly. This could look like this:

```ini
GET @cars_view: /cars/@car-@location.@id=CarsController->view
GET @cars_view_colour: /cars/@colour-@car-@location.@id=CarsController->view
```

```php
\Template::instance()->filter('carLink',	'\ViewHelper::instance()->carLink');
```

```php
class ViewHelper extends \Prefab {
	function carLink($car) {
		/** @var \Base $f3 */
		$f3 = \Base::instance();
		$href = $f3->BASE;
		$args = [
			'id' => $car['id'],
			'car' => str_replace(' ', '-', $car['car']),
			'location' => str_replace(' ', '-', $car['location']),
		];
		if (!empty($car['colour'])) {
			$args['colour'] = $car['colour'];
			$alias = 'cars_view_color';
		} else {
			$alias = 'cars_view';
		}
		return $href.$f3->alias($alias,$args);
	}
}
```

```html
<a href="{{ @car | carLink }}" title="View {{@car.car}}">
```

**Comment by gexeh** [comment]
Thanks @ikkez I wasn't aware of the google board. I'll use that for questions from now on.

I've implemented your changes, thanks very much for the in-depth tutorial. Much appreciated!

Happy to close this one out!
