### ISSUE TITLE
JSON error response does not respect DEBUG level

### ISSUE THREAD

**Issue by ladislavmoravek** [bcosca/fatfree#1071]
https://github.com/bcosca/fatfree/blob/0539cd4c0bba2e6e8231dbca64156123725c9184/lib/base.php#L1243

It always shows trace

Don't forget! Stack traces may contain paths, file names, database commands, user names and passwords. You might expose your Web site to unnecessary security risks if you fail to set the DEBUG global variable to 0 in a production environment.

still in love with this framework :)

**Comment by xfra35** [comment]
Fixed. Thanks for reporting.

**Comment by ikkez** [comment]
Is that really the case? Isn't `ERROR.trace` populated by `Base->trace` just some lines above? And since that should filter the backtrace by the DEBUG setting as well, I cannot spot the issue on first sight.

**Comment by xfra35** [comment]
The backtrace is indeed filtered but it still contains the file path.

**Comment by ladislavmoravek** [comment]
your welcome,

many thanks for fixing it.
