### ISSUE TITLE
Remove use of eval function on lib/base.php

### ISSUE THREAD

**Issue by cromvuack** [bcosca/fatfree#1077]
im using sonarqube (https://www.sonarqube.org/) in order to verify the quality of my code, it detects as a critical vulnerability the use of eval function mainly on line 451 of base.php file:

eval('unset('.$this->compile('@this->hive.'.$key).');');

and also on line 2878 of the same file:

eval(' ?>'.$this->build($node).'<?php ');

is it possible to be changed somehow?

**Comment by bcosca** [comment]
Not all instances of eval is evil. This is a fallacy. It is only dangerous when its argument comes from user input. eval's use in the framework is limited to templates, which is provided by the developer.
