### ISSUE TITLE
"The (unset) cast is deprecated" after update to PHP 7.2.0

### ISSUE THREAD

**Issue by dabajabaza** [bcosca/fatfree#1080]
**PHP:** 7.2.0 (cli) (built: Nov 29 2017 00:17:00) ( ZTS MSVC15 (Visual C++ 2017) x86 )
**Fat Free Framework:** 3.6.2 (26 June 2017)
**Apache**: 2.4.23

**Internal Server Error**

The (unset) cast is deprecated

[E:/xampp/htdocs/site/public/lib/base.php:2178] Base->error()
[E:/xampp/htdocs/site/public/lib/base.php:2039] Base->{closure}()
[E:/xampp/htdocs/site/public/lib/base.php:2039] require()
[E:/xampp/htdocs/site/public/app/controllers/Controller.php:20] spl_autoload_call()
[E:/xampp/htdocs/site/public/lib/base.php:1741] ReflectionClass->newInstanceArgs()
[E:/xampp/htdocs/site/public/lib/base.php:1762] Base->grab()
[E:/xampp/htdocs/site/public/lib/base.php:1612] Base->call()
[E:/xampp/htdocs/site/public/index.php:74] Base->run()

[Full error text on pastebin](https://pastebin.com/ZXBzRDMr)

**Comment by KOTRET** [comment]
fixed 4 months ago with commit https://github.com/bcosca/fatfree-core/commit/dce9d6e0cb5596004591c1bf7e5867afad411aeb
please update

**Comment by dabajabaza** [comment]
@KOTRET thanks for reply. I'm using last stable version of fff 3.6.2 from https://packagist.org/packages/bcosca/fatfree
and `return (unset)$val;` is still there.

**Comment by Ayesh** [comment]
This `unset()` casts, `each()` calls (e.g 90a95376c2da10) are fixed in the current master branch, but there is no tagged release yet. Hopefully there will be a 3.6.3 version soon and it will contain all such fixes. I have scanned the current master branch (as of b579938d363788307ee7 at least) and I couldn't find any issues that might raise warnings/notices in PHP 7.2.

**Comment by dabajabaza** [comment]
@Ayesh thanks. I'm sorry for maybe stupid question,but why is there two reps https://github.com/bcosca/fatfree and https://github.com/bcosca/fatfree-core? 
The line that causes issue in the first one
https://github.com/bcosca/fatfree/blob/0539cd4c0bba2e6e8231dbca64156123725c9184/lib/db/sql.php#L127

**Comment by Rayne** [comment]
@dabajabaza The [fatfree](https://github.com/bcosca/fatfree) repository ships the latest [fatfree-core](https://github.com/bcosca/fatfree-core) release bundled with a small guide and an overview which shows and explains which PHP modules are missing or are required for a specific feature. It also has a `dev` branch with unit tests. The `fatfree-core` repository is the one where the development of the library happens and the one *I* would recommend to use for developing applications.

**Comment by Ayesh** [comment]
See bcosca/fatfree-core#226 for 7.2-compatible release updates.
