### ISSUE TITLE
PDO Quirks (PDO::ATTR_EMULATE_PREPARES, Decimal fields)

### ISSUE THREAD

**Issue by marcus-at-localhorst** [bcosca/fatfree#1085]
I have a fairly complex SQL Query (MySQL 5.5 Windows) that I tried to make work with f3 this way:

```php
return $this->db->exec('SELECT *, ( 3959 * acos( cos( radians(:lat) ) * cos( radians( lat ) ) * cos( radians( lng ) - radians(:lng) ) + sin( radians(:lat) ) * sin(radians(lat)) ) ) AS distance_from_query
	FROM places
	WHERE source LIKE :source
	AND
	(CASE WHEN :swlat < :nelat
		THEN lat BETWEEN :swlat AND :nelat
		ELSE lat BETWEEN :nelat AND :swlat
		END)
	AND
	(CASE WHEN :swlng < :nelng
		THEN lng BETWEEN :swlng AND :nelng
		ELSE lng BETWEEN :nelng AND :swlng
		END)
	HAVING distance_from_query < :maxdistance
	ORDER BY distance_from_query',
	array(
		':lat'         => $param['lat'],
		':lng'         => $param['lng'],
		':swlat'       => $param['swlat'],
		':swlng'       => $param['swlng'],
		':nelat'       => $param['nelat'],
		':nelng'       => $param['nelng'],
		':maxdistance' => $this->f3->get('discovery.maxdistance'),
		':source'      => ($source) ? $source : '%'
	)
);
```
unfortunately, the query turned out like this (many duplicated  :placeholder weren't rendered)

```sql
SELECT *, ( 3959 * acos( cos( radians('33.75') ) * cos( radians( lat ) ) * cos( radians( lng ) - radians('-84.39') ) + sin( radians(:lat) ) * sin(radians(lat)) ) ) AS distance_from_query
FROM places
WHERE source LIKE '%'
AND
(CASE WHEN '33.54940663754663' < '33.94905609818093'
	THEN lat BETWEEN :swlat AND :nelat
	ELSE lat BETWEEN :nelat AND :swlat
	END)
AND
(CASE WHEN '-84.60571289062501' < '-84.16900634765626'
	THEN lng BETWEEN :swlng AND :nelng
	ELSE lng BETWEEN :nelng AND :swlng
	END)
HAVING distance_from_query < 40
ORDER BY distance_from_query
```

I didn't understand why I can't use multiple placeholder, but I found the [explanation](https://stackoverflow.com/a/42244257/814031).

Adding `\PDO::ATTR_EMULATE_PREPARES` as option, didn't do anything:
```php
$this->db = new DB\SQL(
	$f3->get('database.server'),
	$f3->get('database.user'),
	$f3->get('database.password'),
	[
		\PDO::ATTR_EMULATE_PREPARES => TRUE
	]
);
```

To use multiple placeholder, I had to write something like that:

```php
...
ORDER BY distance_from_query',
array(
	':lat'         => $param['lat'],
	':lat2'        => $param['lat'],
	':lng'         => $param['lng'],
	':swlat'       => $param['swlat'],
	':swlat2'      => $param['swlat'],
	':swlat3'      => $param['swlat'],
	':swlng'       => $param['swlng'],
	':swlng2'      => $param['swlng'],
	':swlng3'      => $param['swlng'],
	':nelat'       => $param['nelat'],
	':nelat2'      => $param['nelat'],
	':nelat3'      => $param['nelat'],
	':nelng'       => $param['nelng'],
	':nelng2'      => $param['nelng'],
	':nelng3'      => $param['nelng'],
	':maxdistance' => $this->f3->get('discovery.maxdistance'),
	':source'      => ($source) ? $source : '%'
)
...
```

Not very pretty, but $db->log() revealed, that all placeholders got replaced and it works as indented:

```sql
SELECT *, ( 3959 * acos( cos( radians('33.75') ) * cos( radians( lat ) ) * cos( radians( lng ) - radians('-84.39') ) + sin( radians('33.75') ) * sin(radians(lat)) ) ) AS distance_from_query
FROM places
WHERE source LIKE '%'
AND
(CASE WHEN '33.549406637547' < '33.949056098181'
	THEN lat BETWEEN '33.549406637547' AND '33.949056098181'
	ELSE lat BETWEEN '33.949056098181' AND '33.549406637547'
	END)
AND
(CASE WHEN '-84.605712890625' < '-84.169006347656'
	THEN lng BETWEEN '-84.605712890625' AND '-84.169006347656'
	ELSE lng BETWEEN '-84.169006347656' AND '-84.605712890625'
	END)
HAVING distance_from_query < 40
ORDER BY distance_from_query
```

But now mathematical operations won't work anymore - e.g. `WHEN '33.549406637547' < '33.949056098181'` – because I was comparing strings instead of decimal numbers (the `BETWEEN` statements seem to work)

Casting those numbers `WHEN CAST(:swlat AS DECIMAL(10,8)) < CAST(:nelat AS DECIMAL(10,8))` in the sql statement works fine, but this is a weird way to write a query and not at all intuitive.
(This was the first time I really used PDO so I don't know too much about option etc, but the f3 docs were so good, they lead me to PDO::ATTR_EMULATE_PREPARES.
Also, as far as I understand (<https://github.com/bcosca/fatfree/issues/984>), f3 is casting only placeholder fields if they are existent in the database.

This wasn't working: ':swlat' => (float) $param['swlat'],`` 

So my question, I guess is: Is there a way to write this more intuitive? Did I get something wrong? Or is that an edge case? I spend two confusing hours figuring this out.

**Comment by ikkez** [comment]
> many duplicated :placeholder weren't rendered

Well yes this is a PDO limitation and there isn't a workaround built into the framework. 
The trick with `\PDO::ATTR_EMULATE_PREPARES => TRUE` seems good, but I'm not sure if that really works,.. it could be that the sql class needs an adjustment for this as well. But the usual way actually is to write multiple placeholders, yes.

> e.g. WHEN '33.549406637547' < '33.949056098181' – because I was comparing strings instead of decimal numbers 
> Casting those numbers WHEN CAST(:swlat AS DECIMAL(10,8)) < CAST(:nelat AS DECIMAL(10,8)) in the sql statement works fine

Well I think the problem here is based on PDO too. The "float" (decimal) bind values for a placeholder are PDO::PARAM_STR because there is no type for float. And in case you cast them to float before, it could create some inaccuracy in the precision when i recall #984 correctly.
So I guess it has to be this way and casting it manually 🤔

**Comment by marcus-at-localhorst** [comment]
Thanks for clarifying. That helped a lot!
