### ISSUE TITLE
Templates Within Templates Not Working

### ISSUE THREAD

**Issue by 5987dogking** [bcosca/fatfree#1086]
Main.php
function home()
{
	$view=new View;
        echo $view->render('home.html');
}

header.html
<p>test</p>

home.html
<include href="header.html" />
<p>HI</p>

I wantna show "header.html" with "home.html"
<p>test</p>
<p>HI</p>

But it not work
Chrome show
<include href="header.html" />
<p>HI</p>

**Comment by ikkez** [comment]
Hi Mark. Please use this issue tracker only to report framework bugs or discuss code related things and use our [google board](https://groups.google.com/forum/#!forum/f3-framework) or [slack channel](https://fatfreeframework-slack.herokuapp.com/) to find help about getting things to work. 
thanks.
