### ISSUE TITLE
insert() doesnt seem to keep the previous sets()

### ISSUE THREAD

**Issue by WilliamStam** [bcosca/fatfree#1093]
````
$a = new \DB\SQL\Mapper($f3->get("DB"), $this->table);
$a->load(['uuid = ?', $ID], ['order' => 'ID desc', "limit"=>"1"] );
if (!$a->dry()){
    $a->deleted = '1';
    $a->insert();
}
````

expected behavior: the full record found via load inserted as a new record with deleted = 1
actual behavior: everything blank except for deleted ='1'

i need to make a full copy of the record on each "deleted" marking it as deleted. tried some clever -`->copyFrom()` to include the data but didnt work. setting `$a->ID = 0` didnt work either. it MADE the ID field 0 (primary auto increment field) which is strange cause mysql (mariadb) if you set the AI field to 0 it goes up to the next auto incremented value

**Comment by ikkez** [comment]
fixed

**Comment by stehlo1** [comment]
I am not sure whether you realise that fiddling with this code introduced backward incompatible changes that absolutely corrupt functionality.
I have been donating to this project exactly for the reason that I could rely on it. Well, not anymore(?).

**Comment by stehlo1** [comment]
This change corrupted the way the data is returned after insert into PostgreSQL, namely it is now returning ALL fields with NULL values. This change affects all projects which are using F3. Every single record of every single table manipulated.

I have an emergency here now (after upgrading from 3.6.5 to 3.7.2.

**Everything** is fucked up. All functionality dealing with data entry doesn't work.

**Comment by sn0opy** [comment]
> I have an emergency here now (after upgrading from 3.6.5 to 3.7.2.

Dude, calm down and be nice if you need help. If you having issues with an update you did without testing beforehand, you should probably downgrade again and wait for a proper fix.

**Comment by timoleary** [comment]
Your lack of testing before push code to production is hardly the fault of the maintainers. Roll back to your last working version until the problem is fixed... jeez

**Comment by stehlo1** [comment]
I am perfectly calm.

However, I don't know how long you "dude" have been using F3, but I haven't seen such damaging changes being introduced in a decade.

May I ask why are you inserting yourself into this issue, considering that you didn't originate the code change. Just to flame?

_[this message will be deleted shortly]_

**Comment by sn0opy** [comment]
Here's an issue created just for your reported problem. Please add a proper description of the rror your're experiencing right now https://github.com/bcosca/fatfree/issues/1192
