### ISSUE TITLE
Issue with content-type on multiple renderings

### ISSUE THREAD

**Issue by eazyliving** [bcosca/fatfree#1095]
Hiho,

switched to 3.6.3 these days and found smth strange today:

```
$t = new \Template();
$mail_body = $t->render("test.txt","text/text");
echo $t->render("test.html","text/html");
```

In a route I first render some text for mails, then output the real page. I left out some uninteresting code here, this is enough to show the bug (if it is one).

What happens, is that the second rendering will be output as text/text, not text/html. 

Any ideas?

**Comment by eazyliving** [comment]
It's about this one in function sandbox() in base.php:
It checks, if there's already a content-type header set. If so, it won't be set again or replaced:

`!preg_grep ('/^Content-Type:/',headers_list())`

3.5.0, from which I switched to 3.6.3 did not have that check. Would it be ok to remove the content-type header before setting it again?

**Comment by xfra35** [comment]
As far as I can imagine, there's no reason to specify different mime headers. The new check is just there to ensure the `header()` function doesn't get called several times when using nested templates.

Maybe the docs didn't make it clear that the `$mime` parameter is just there to *send* the mime header to the browser, nothing more. So it is not needed in the case of an email:
```php
$mail_body = $t->render("test.txt",NULL);
```

**Comment by eazyliving** [comment]
m) That solves my problem, thanks!

But isn't there something with XML? Can't remember the details, maybe it's about encoding...
But for now: closed!
