### ISSUE TITLE
White screen with default installation.

### ISSUE THREAD

**Issue by GrumpyCrouton** [bcosca/fatfree#1097]
I downloaded the package and unpacked it to my web server. I have not altered anything else. When loading the webpage, I just get a blank screen. When I inspect the page, nothing is shown except the default page layout, nothing from F3 is loaded.

No errors are displayed on the page, and no error_log file is generated.

I can provide any other information needed to possibly get a solution to this, unfortunately, I do not know where to start or what information is needed.

EDIT: I recently switched to a new host, I realized after posting this that I should check if error reporting was disabled by default - and it was. I turned it on, and now this error_log is being generated:

```
[06-Mar-2018 16:20:54 GMT] HTTP 404 (GET /index.php)
[06-Mar-2018 16:20:54 GMT] [lib/base.php:1660] Base->error()
[06-Mar-2018 16:20:54 GMT] [index.php:86] Base->run()
```

**Comment by MarcVertigo** [comment]
Same thing happened to me. Not sure if I need to run composer install or something...

**Comment by MarcVertigo** [comment]
Fresh git clone and I get: 
<img width="388" alt="screen shot 2019-01-09 at 6 11 43 pm" src="https://user-images.githubusercontent.com/39630945/50941522-18e79680-143a-11e9-8a56-26bd836280f0.png">

**Comment by GrumpyCrouton** [comment]
Are you guys on an apache server? If so, there is a file that's included in the server files called `htaccess.apache`, you should change the name of this file to `.htaccess`
