### ISSUE TITLE
Error reporting level assumed in construct of base and not changeable

### ISSUE THREAD

**Issue by Joseffb** [bcosca/fatfree#1098]
Can we add something like this to pick up a custom config var (called ERROR_REPORTING) for error reporting level?
`$default_error_reporting = !$this->devoid($this->hive['ERROR_REPORTING'])?$this->hive['ERROR_REPORTING']:"(E_ALL|E_STRICT)&~(E_NOTICE|E_USER_NOTICE)";
$check=error_reporting($default_error_reporting);`

Currently we ran into issue on php7 migration where opcache wouldn't allow of a lower issue (i.e. notice, deprecated, etc) to crashthe app but without opcache it would error out the app.

We'd like to tell the error hander at what level to kick in.

**Comment by xfra35** [comment]
This wouldn't work as the error reporting is set at instantiation time.

But you can easily override the default reporting level:
```php
$f3=require('lib/base.php');
error_reporting(E_ALL|E_STRICT);
```

**Comment by ikkez** [comment]
Please reopen if the problem is still there
