### ISSUE TITLE
Help w/ QA Code Coverage

### ISSUE THREAD

**Issue by bartonhammond** [bcosca/fatfree#1099]
I'm a QA guy testing a FF site using Behat.  

I'd like to generate Code Coverage stats using [https://github.com/sebastianbergmann/php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage).  What I need to do is wrap each page request w/ a `start instrumentation / run the page / stop instrumentation and dump those results` kind of thing.

I see our `index.php` has a`$f3->run()`.   What I'm looking for is the one place that all requests start/stop (pass through) that I could add this `start/run/stop and dump` code around.  What would you suggest?  

Could this be accomplished w/ a plugin or something similar?

thanks

**Comment by ikkez** [comment]
Hi. You can probably use `$f3->run()` and suppress the output with [`QUIET`](https://fatfreeframework.com/3.6/quick-reference#QUIET). The response is available at [`RESPONSE` ](https://fatfreeframework.com/3.6/quick-reference#RESPONSE) variable. Additionally the [mock](https://fatfreeframework.com/3.6/base#mock) feature cloud also be useful for this purpose.

**Comment by bartonhammond** [comment]
I followed this approach [http://tarunlalwani.com/post/php-code-coverage-web-selenium/](http://tarunlalwani.com/post/php-code-coverage-web-selenium/) and it worked great
