### ISSUE TITLE
base::render function error with multiple view folders

### ISSUE THREAD

**Issue by massimoregi** [bcosca/fatfree#1101]
Hi,
if you set the UI parameter with more than one folder, the render() function looks up only in the last one folder. An "Unable to open file" error can be raised, if the view file isn't inside the last folder. Rows from 2750 to 2764 in lib/base.php should be enclosed in the foreach.

**Comment by ikkez** [comment]
Thanks for submitting this. It was already fixed in https://github.com/bcosca/fatfree-core/commit/d3bb55bfdd17bdac98a311d3857f2445e07cc475 , so it'll be in the next release.
Ref: https://github.com/bcosca/fatfree/issues/1083
