### ISSUE TITLE
Google Cloud Storage - exclusive lock

### ISSUE THREAD

**Issue by AndrewEQ** [bcosca/fatfree#1109]
When doing file writing to storage, googles php throws an error about exclusive locks on this line:

https://github.com/bcosca/fatfree/blob/dee4d73918a42076d5ac7db64d6d39706c7f328a/lib/base.php#L2015

A quick fix we currently use is:

```LOCK_NB``` instead of ```LOCK_EX```

**Comment by xfra35** [comment]
Is that the `LOCK_EX` flag which causes the issue or the `FILE_APPEND` flag?

I'm asking because the [Google Storage docs](https://cloud.google.com/storage/docs/key-terms#immutability) state that appending data is not permitted while overwriting is:

> In practice, this means that you cannot make incremental changes to objects, such as append operations or truncate operations. However, it is possible to overwrite objects that are stored in Cloud Storage

**Comment by AndrewEQ** [comment]
Hmm, good question, I just changed the ```LOCK_EX``` and it worked but it could be the ```FILE_APPEND```.
