### ISSUE TITLE
preserve inline styles

### ISSUE THREAD

**Issue by daslicht** [bcosca/fatfree#1110]
Hi,
I like to output some html which contains inline styles so i tried the ```raw``` pipe and ```$f3->set('ESCAPE', false);``` 
Both output the formatted html, but all inline styles still get removed.

Is there any way to preserve inline styles please?
Workaround ?

**Comment by Rayne** [comment]
Please share more information, e.g. input, code and template.

**Comment by daslicht** [comment]
I just traced it back, it has nothing to do with f3 the db seams to stipt the style whyever !

**Comment by daslicht** [comment]
I try to reproduce in a smaller example
