### ISSUE TITLE
Count issue

### ISSUE THREAD

**Issue by SaphiLC** [bcosca/fatfree#1114]
Im having a issue, with the latest F3's build ("bcosca/fatfree-core": "^3.6"), whenever i do a query that uses count (for example, paginate, or count itself) i get a log with this inside (table has around 638,098 records)
```
SELECT COUNT(*) AS _rows FROM (SELECT * FROM beta_directory_business WHERE 'status' = 'active' AND 'visible' = 1 AND 'indexable' = 1) AS _temp
```
That subselect makes the query take 30-40 seconds and its not needed, using exec and  when i change count to
```
$db->exec('SELECT count(*) AS total FROM beta_directory_business WHERE status = "active" AND visible = 1 AND indexable = 1');
```
Then the query takes 0-1 seconds instead of 30-40... so this type of select strategy is only needed when a group is involved and not required always. And this problem affects paginate too since it uses count :(

thanks

**Comment by iFlash** [comment]
I just ran into the same. The inner SELECT is killing performance. In case there are `$options` they need to be included in the main select dropping the inner one.

**Comment by ikkez** [comment]
Should be fixed in the latest commit.
Ref. https://github.com/bcosca/fatfree-core/issues/192 and https://github.com/bcosca/fatfree-core/commit/6b864dc9c329269b5d1bc2427664d3a5e163aec5
