### ISSUE TITLE
Add TLS1.2 to SMTP?

### ISSUE THREAD

**Issue by ta6rma** [bcosca/fatfree#1115]
The SMTP class uses the constant STREAM_CRYPTO_METHOD_TLS_CLIENT (line 214) 
however since PHP 5.6.7, STREAM_CRYPTO_METHOD_TLS_CLIENT defaults to v1.0
Some mailing services (e.g. Sparkpost) are deprecating TLS v1.0 so emails are failing to send.
Can this be changed to support TLS 1.2 or 1.1?
See http://php.net/manual/en/function.stream-socket-enable-crypto.php#119122

**Comment by bcosca** [comment]
Granted.
