### ISSUE TITLE
find does not return data

### ISSUE THREAD

**Issue by adamsewell** [bcosca/fatfree#1117]
When I'm trying to use find with a where statement, fatfree does not return any data even though if I run the SQL command that it generates shows the correct data. 

For example, 

```
$record = new DB\SQL\Mapper($db, 'users');
$record->find(array('domain like ?', '%' . $domain);

foreach($record as $user){
   echo $user->email;
}
```

gives me no data.

**Comment by mickey9801** [comment]
$list = $record->find(....);
foreach ($list as $user) {
...
}

**Comment by adamsewell** [comment]
> $record->find(array('domain like ?', '%' . $domain);

Well, I feel like an idiot... thanks! lol
