### ISSUE TITLE
\Base::instance()->clear() triggers error if keys has "-"

### ISSUE THREAD

**Issue by webvimark** [bcosca/fatfree#1118]
If the key has "-" in it it will trigger following error

> syntax error, unexpected '-', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) [/path/to/project/vendor/bcosca/fatfree/lib/base.php(474) : eval()'d code:1]

You can reproduce it by calling one of the following examples

```php
\Base::instance()->clear('CACHE.test-name');
\Base::instance()->clear('SESSION.test-name');
\Base::instance()->clear('COOKIE.test-name');
```

**Comment by Rayne** [comment]
Your example uses "unsupported" keys:

> A framework variable may contain any number of letters, digits and underscores. It must start with an alpha character and should have no spaces. Variable names are case-sensitive.

Source: https://fatfreeframework.com/3.6/framework-variables

Technically, keys with `-` characters are supported by some operations. You could delete your key with the following snippet as workaround:

```php
unset($f3['SESSION']['test-name']);
```

---

For the record:

```php
$f3->set('test-name', 'X');        // → Invalid hive key 'test-name'
$f3->set('nested.test-name', 'X'); // → OK
```

I wonder if it is really necessary to use `eval()` to remove keys. :thinking:
