### ISSUE TITLE
Send data to class

### ISSUE THREAD

**Issue by archistico** [bcosca/fatfree#1119]
Hi, 
I have a question:

(file: index.php)
`$f3->route('GET @hello: /hello/@name', '\app\hello->write');`

(file: \app\hello.php)
```
namespace app;
class hello {
    function write($name) {
        echo 'Hi '.$name;
    }
}
```

Not found routing
I have try:
`$f3->route('GET @hello: /hello/@name', '\app\hello->write(@name)');`

**Comment by archistico** [comment]
Ok
```
namespace app;
class hello {
    function write($f3,$args) {
        echo 'Hi '.$args['name'];
    }
}
```

**Comment by bcosca** [comment]
This is not an issue with the framework.

Please post your questions on https://groups.google.com/forum/#!forum/f3-framework.
