### ISSUE TITLE
Session seems to be getting overwritten

### ISSUE THREAD

**Issue by dextermb** [bcosca/fatfree#1121]
I've inherited a project that is currently on version `3.5.0-Release`. I seem to be having an issue where the session is getting overwritten.

Here's some sample code:

Within `index.php` a new database session gets instantiated. Within the database there is the correct structure for the `sessions` table, so force is not required:
```
new \DB\SQL\Session($db);
```

Then we navigate to `/login` which attempts to find a user, compare the password, then set `SESSION` variables.

```
if($auth->login($f3->get('POST.username'), $user['password'])){
	$f3->set('SESSION.user', $user['username']);

	$f3->set('SESSION.group', $user['userGroup']);

	$f3->set('SESSION.id', $user['id']);

	$f3->set('SESSION.venueChoice', $user['venueChoice']);

	$f3->set('SESSION.privs', $user['privs']);

	if($user['userGroup'] == 'Client'){

		$f3->reroute('/client');

	}else{
		var_dump('admin user', $f3->get('SESSION.user')); // Debug outputs

		addActivity($f3, $f3->get('SESSION.user') . ' logged in', 'LOGIN / LOGOUT');

		addSimpleActivity($f3, $f3->get('SESSION.user') . ' logged in', 'LOGIN / LOGOUT');

		$f3->reroute('/admin');

	}
}
```

The interesting issue is that `SESSION.user` does get set with the username. But then when setting `SESSION.group` it then overwrites the session, effectively clearing it and just setting `group`. Then when the code calls 
```
$f3->get('SESSION.user')
``` 

The `SESSION` variable then gets cleared, and becomes an empty array.

Dumping `$f3`:

Here is a dump directly after setting `SESSION.user`, as you can see it is set:
```
object(Base)[2]
  private 'hive' =>
      // <snip>

      'SESSION' => 
        array (size=1)
          'user' => string 'siteAdmin' (length=9)

      // <snip>
```

Here is a dump directly after setting `SESSION.group`, as you can see it is set:
```
object(Base)[2]
  private 'hive' =>
      // <snip>

      'SESSION' => 
        array (size=1)
          'group' => string 'Site Admin' (length=10)

      // <snip>
```

Then when finally dumping after calling `get`. The `get` itself calls `null`:
```
object(Base)[2]
  private 'hive' =>
      // <snip>

      'SESSION' => 
        array (size=0)
          empty

      // <snip>
```

As this is an inherited project, and I know nothing about how f3 works I'd love as much detail on the resolution for this as possible.

**Comment by ikkez** [comment]
Maybe just update to F3 3.6.*

**Comment by ikkez** [comment]
Well 3.5.0 is actually that old that it doesnt even have a release tag on github here.. 
When you check the changelog https://github.com/bcosca/fatfree-core/blob/master/CHANGELOG.md you'll see that the SESSION handlers were refactored in 3.5.1 and got some additional fixes along the other releases.. not to mention that 3.5 probably has more issues and it's php7+ compatible.. i don't think there are big breaking changes, maybe some small ones, depending on what features your project used.. there was something along with alias and routing patterns, see http://slides.com/ikkez/fat-free-v3-6#/2
but i would give it a try.

**Comment by dextermb** [comment]
@ikkez https://github.com/bcosca/fatfree/releases/tag/3.5.0

I do not believe that upgrading should be a solution. If everyone had the issue with `3.5.0` and sessions then it wouldn't of been released.

It is true that PHP7 might be causing issues. I'll drop down to `5.6` and try that before attempting to upgrade.

**Comment by ikkez** [comment]
oh my fault.. I must have overseen that tag.

**Comment by dextermb** [comment]
@ikkez The weird thing is that it seems to work on the _live_ server, but when attempting to run locally it doesn't work. Is there something weird about how f3 interacts with setting sessions?
```php
$f3->set('SESSION.user', $user);
```

[Doesn't seem to call the database handler](https://github.com/bcosca/fatfree/blob/3.5.0/lib/base.php#L325-L374):

```php
	/**
	*	Bind value to hive key
	*	@return mixed
	*	@param $key string
	*	@param $val mixed
	*	@param $ttl int
	**/
	function set($key,$val,$ttl=0) {
		$time=time();
		if (preg_match('/^(GET|POST|COOKIE)\b(.+)/',$key,$expr)) {
			$this->set('REQUEST'.$expr[2],$val);
			if ($expr[1]=='COOKIE') {
				$parts=$this->cut($key);
				$jar=$this->unserialize($this->serialize($this->hive['JAR']));
				if ($ttl)
					$jar['expire']=$time+$ttl;
				call_user_func_array('setcookie',array($parts[1],$val)+$jar);
				return $val;
			}
		}
		else switch ($key) {
		case 'CACHE':
			$val=Cache::instance()->load($val,TRUE);
			break;
		case 'ENCODING':
			ini_set('default_charset',$val);
			if (extension_loaded('mbstring'))
				mb_internal_encoding($val);
			break;
		case 'FALLBACK':
			$this->fallback=$val;
			$lang=$this->language($this->hive['LANGUAGE']);
		case 'LANGUAGE':
			if (!isset($lang))
				$val=$this->language($val);
			$lex=$this->lexicon($this->hive['LOCALES']);
		case 'LOCALES':
			if (isset($lex) || $lex=$this->lexicon($val))
				$this->mset($lex,$this->hive['PREFIX'],$ttl);
			break;
		case 'TZ':
			date_default_timezone_set($val);
			break;
		}
		$ref=&$this->ref($key);
		$ref=$val;
		if (preg_match('/^JAR\b/',$key)) {
			$jar=$this->unserialize($this->serialize($this->hive['JAR']));
			$jar['expire']-=$time;
			call_user_func_array('session_set_cookie_params',$jar);
		}
		$cache=Cache::instance();
		if ($cache->exists($hash=$this->hash($key).'.var') || $ttl)
			// Persist the key-value pair
			$cache->set($hash,$val,$ttl);
		return $ref;
	}
```

**Comment by bjugan** [comment]
@dextermb Check if you get a new row in the session tabel for each request. I had the same problem and I think it was related to CORS (frontend and backend on different addresses trying to share the same cookie...)

**Comment by dextermb** [comment]
@bjugan It does not even create rows within the table. Which is why I think it doesn't get called. But weirdly enough it works on the live server with the exact same codebase

**Comment by ikkez** [comment]
have you checked your error logs locally? maybe you dont see the error message?

**Comment by dextermb** [comment]
@ikkez This is the error I am getting... because it attempts to access `SESSION`:

```
Internal Server Error
PDOStatement: Field 'user' doesn't have a default value

[lib/base.php:2015] Base->error(500,'PDOStatement: Field 'user' doesn't have a default value')
[lib/DB/SQL/Mapper.php:418] DB\SQL->exec(array('INSERT INTO `logs` (`detail`,`category`,`ip`) VALUES (?,?,?)'),array(array(1=>array(' accessed /admin',2),2=>array('SECURITY',2),3=>array('192.168.10.1',2))))
[lib/DB/Cursor.php:241] DB\SQL\Mapper->insert()
[inc/helpers.php:2481] DB\Cursor->save()
```

Here is where it attempts to check session:
```
	if($f3->get('SESSION.user')){
		
		$log->user = $f3->get('SESSION.user');
		
	};
```

Even though it is wrapped in an if statement, I am aware that the previous developer made the field required in the database.

But this shows that `SESSION.user` is not being set even though it should be according to the previously posted code.

**Comment by ikkez** [comment]
The error looks to me like your logs table doesnt have a `user` column.

**Comment by dextermb** [comment]
@ikkez As shown in my example, that is because it attempts to use `SESSION.user` that gets reset before it even gets there. Look through my example code.

**Comment by dextermb** [comment]
This never was resolved. Like the original developer I ended up having to work directly off the server.
