### ISSUE TITLE
Documentation suggestion re: CSRF edge case.

### ISSUE THREAD

**Issue by raymondstaylor** [bcosca/fatfree#1122]
The documentation at https://fatfreeframework.com/3.6/session#csrf currently shows the following example check:

```php
if ($f3->get('POST.token')!=$f3->get('SESSION.csrf'))
```

This can give a false OK on the edge case that the user's session isn't setup correctly _and_ the token wasn't posted (therefore they're both empty and therefore equal).

Maybe the example check should be something like:

```php
    $token = $f3->get('POST.token');
    $csrf = $f3->get('SESSION.csrf');
    if (empty($token) || empty($csrf) || $token != $csrf) {
```

**Comment by Rayne** [comment]
Well spotted! I think the example below should be fixed, too. I would be happy to merge this as a PR against [F3Community/F3com-data](https://github.com/F3Community/F3com-data).
