### ISSUE TITLE
Captcha is showing complete black image

### ISSUE THREAD

**Issue by iamramkey** [bcosca/fatfree#1124]
Hi All,

While using captcha method I am getting complete black image in linux server where as it is completely working fine in my local XAMPP environment.

I have this code in my server for a route

        $img = new Image();
        $img->captcha("PermanentMarker-Regular.ttf", 100, 6, 'SESSION.captcha_code', '', '0X369', '0XEEE');
        $img->render();
        unset($img);

I have included that font in UI folder. 

this is the GD part in the php info of my server : 

GD Support | enabled
-- | --
GD Version | bundled (2.1.0 compatible)
FreeType Support | enabled
FreeType Linkage | with freetype
FreeType Version | 2.4.8
GIF Read Support | enabled
GIF Create Support | enabled
JPEG Support | enabled
libJPEG Version | 8
PNG Support | enabled
libPNG Version | 1.5.26
WBMP Support | enabled
XBM Support | enabled

Please suggest me what I am missing. 

Thanks Alot.

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/4263974/46578488-5b569d00-ca1f-11e8-9f78-832966d5436d.png">

**Comment by ikkez** [comment]
Perhaps the server has problems reading the font or the path isnt correct. So get all server erros that could cause this issue, add

```php
ini_set('display_errors', 1);
error_reporting(-1);
```

and see what it says

**Comment by iamramkey** [comment]
Thanks ikkez for your comment,

I have written all ways to show errors in php.
Please find the below link to show the actual output without any errors.
http://reanin.com/rama

To enable error reporting I have the below code already in my server.

error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);

Dont know why this issue is coming on server only. 

But not able to find the issue as it is not throwing any errors.

**Comment by ikkez** [comment]
now seeing that you have the font size set to 100. This probably doesnt fit into the bounding box of tha captcha with this font.

**Comment by RosyStephen** [comment]
I had same issue. when i remove color code it works fine  -
	$img->captcha ( 'font.ttf', 10, 6, 'SESSION.captcha_code', '', '0xFFFFFF', '0x336799' ); - this is changed  tas 
		$img->captcha ( 'font.ttf', 14, 6, 'SESSION.captcha_code' );

**Comment by RosyStephen** [comment]
remove the single quotes for color code then it works fine
$img->captcha ($font,$size=24,$len=5,	$key=NULL,$path='',$fg=0xFFFFFF,$bg=0x000000);
