### ISSUE TITLE
PostgreSQL support for With Queries in SQL

### ISSUE THREAD

**Issue by didiergm** [bcosca/fatfree#1125]
A few months back I had the need for the SQL layer to accept a WITH Common table expression , unfortunately I constantly received a ssyntax error (not sure of the exact message) when using exec.

After chatting on gitter, I ended up modifying sql.php, line 238
```

if (preg_match('/(?:^[\s\(]*'.
	'(?:EXPLAIN|SELECT|PRAGMA|SHOW)|RETURNING)\b/is',$cmd) ||
	(preg_match('/^\s*(?:CALL|EXEC)\b/is',$cmd) &&
into this version: 
if (preg_match('/(?:^[\s\(]*'.
'(?:EXPLAIN|SELECT|PRAGMA|SHOW|WITH)|RETURNING)\b/is',$cmd) ||
(preg_match('/^\s*(?:CALL|EXEC)\b/is',$cmd) &&
```
I have been running for a few months with this modified version and have not seen any side effects. 

I do not know how to make a pr, so being very simple I thought I would share it here

**Comment by ikkez** [comment]
Thanks, but it has already been added recently, see https://github.com/bcosca/fatfree-core/commit/8fd940b7dccf7d6af51e680ecbf22077286917f1
so it'll be in the next release.
ref. #1021, #1107, #1116
