### ISSUE TITLE
Unknown variables in base.php!

### ISSUE THREAD

**Issue by Necip8** [bcosca/fatfree#1128]
I've been working with the Yii framework for over two years and was surprised when I stumbled across F3 a few days ago. I will use it to implement a prototype of my idea "Sophistica", which only needs four tables and a handful of functions to run a complex system like a CMS. You can read the german description on my homepage (https://ncpup.wordpress.com/2018/09/05/sophistica/). Use the AI from www.deepl.com to translate the text into your language.

PhpStorm shows errors in the function "format" in the file "base.php". Can you fix it please?

With kind regards

**Comment by Rayne** [comment]
The `format()` method utilizes the `extract()` function to populate local variables. PhpStorm does not derive the resulting local variables and therefore shows "unknown variable" errors.

Variable | Extracted Variables
---|---
[`$expr`](https://github.com/bcosca/fatfree/blob/dee4d73918a42076d5ac7db64d6d39706c7f328a/lib/base.php#L887) | `$pos`, `$type`, `$mod`, `$prop`
[`$match`](https://github.com/bcosca/fatfree/blob/dee4d73918a42076d5ac7db64d6d39706c7f328a/lib/base.php#L902) | `$tag`, `$data`
[`$conv`](https://github.com/bcosca/fatfree/blob/dee4d73918a42076d5ac7db64d6d39706c7f328a/lib/base.php#L888) | `$thousands_sep`, `$negative_sign`, `$positive_sign`, `$frac_digits`, `$decimal_point`, `$int_curr_symbol`, `$currency_symbol` and [more](https://secure.php.net/manual/en/function.localeconv.php)
[`$conv`](https://github.com/bcosca/fatfree/blob/dee4d73918a42076d5ac7db64d6d39706c7f328a/lib/base.php#L888) | Depending on [`$pre` (`p` or `n`)](https://github.com/bcosca/fatfree/blob/dee4d73918a42076d5ac7db64d6d39706c7f328a/lib/base.php#L957): `$p_cs_precedes`, `$p_sign_posn`, `$p_sep_by_space`, `$n_cs_precedes`, `$n_sign_posn`, `$n_sep_by_space`

It would be quite easy to help PhpStorm by defining the variables explicitly:

```php
$pos=null;
$type=null;
$mod=null;
$prop=null;
$tag=null;
$data=null;
$thousands_sep=3;
$negative_sign='-';
$positive_sign='';
$frac_digits='';
$decimal_point='.';
$int_curr_symbol='EUR';
$currency_symbol='€';
```

The values don't matter as the following `extract()` calls would immediately overwrite them. According to the documentation of the used functions, all used array keys (exported with `extract()` as local variables) are guaranteed to exist.

It would be nice if PhpStorm wouldn't report these false positive issues but adding the list of variables provides no real benefits. It could even obfuscate the fact that extracted variables are used by providing placeholder values. I personally don't favour the `extract()` function for that reason.

As usual, running the unit tests, located in the `dev` branch, helps to detect breaking changes (or missing local variables in this case). It could be useful to have a second look at the tests to see if all cases are covered.
