### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by digi-brains** [bcosca/fatfree#1132]
This code example:
[Keeping Javascript and CSS on a Healthy Diet](https://fatfreeframework.com/3.6/optimization#KeepingJavascriptandCSSonaHealthyDiet)

`$files = preg_replace('/(\.+\/)/','',$_GET['files'])); // close potential hacking attempts`

Appears to have one to many ')'

Which results in this error:

`Parse error: syntax error, unexpected ')'`

**Comment by ikkez** [comment]
thx @digi-brains & @Rayne
