### ISSUE TITLE
Template::parse problem with PCRE2 in PHP 7.3

### ISSUE THREAD

**Issue by jimwins** [bcosca/fatfree#1133]
The new PCRE2 engine in PHP 7.3 is more strict about the syntax of character classes, so "[\w-.:@!]"  in preg_match() call on line 267 of lib/template.php needs to be rewritten to "[-\w.:@!]".

**Comment by ikkez** [comment]
duplicate, https://github.com/bcosca/fatfree-core/pull/255 & https://github.com/bcosca/fatfree-core/issues/265
