### ISSUE TITLE
PHP Mongo extension is deprecated. The MongoDB extension should be used.

### ISSUE THREAD

**Issue by labsterx** [bcosca/fatfree#1134]
The current version of f3 uses the PHP Mongo extension, which has been deprecated. Instead, the MongoDB extension is the one that's recommended. 

I hope f3 can migrate to use the MongoDB extension instead of Mongo in its MongoDB database mapper.

Thanks!

**Comment by labsterx** [comment]
> As far as I know, it works with both `mongodb` and `mongo` extentions. The F3 implementation has a legacy mode included: https://github.com/bcosca/fatfree/blob/dev/app/mongo.php#L13-L18
> I'm not sure but you probably need to include `composer require mongodb/mongodb` when using `mongodb` extention as well.

Thanks for your reply! That's good to know!

**Comment by joseffb-mla** [comment]
I can confirm you need `composer require mongodb/mongodb`
