### ISSUE TITLE
Format decimal points not working correctly

### ISSUE THREAD

**Issue by SylwesterZarebski** [bcosca/fatfree#1142]
Last revision of fatfree changes number decimals handling and accidentally broke it.
Culprit is commit #3604f7a in fatfree-core:
https://github.com/bcosca/fatfree-core/blob/master/base.php#L995
which goes to:
https://github.com/bcosca/fatfree/blob/master/lib/base.php#L980

Bug is in:
```
isset($prop)?
    $prop:
    $frac?strlen($frac)-2:0,
```
which should be:
```
isset($prop)?
    $prop:
    ($frac?strlen($frac)-2:0),
```
Note parentheses around second ternary. You've been hit by PHP's ternary design bug.

PS. Could You make some tests to check for formatting bugs?

**Comment by ikkez** [comment]
nice catch. thanks.
ref.: https://github.com/bcosca/fatfree-core/commit/3604f7a283a624622afe3f105b0e4ad0af33a623

**Comment by SylwesterZarebski** [comment]
Thanks for quick commit :+1: :)
