### ISSUE TITLE
Unable to open template.htm

### ISSUE THREAD

**Issue by prdip** [bcosca/fatfree#1144]

**Comment by prdip** [comment]
Unable to open template.htm
it shows this error

with this route function
function indexx($prdip)
	{
		$prdip->set('name','world');
		$template=new Template;
		echo $template->render('template.htm');
        // echo \Template::instance()->render('template.htm');
	}

in xampp module

**Comment by ikkez** [comment]
This issue tracker is meant for bug reports in the codebase. For support and questions please visit our google board or the slack channel. thank you ;)
regarding your issue: check your file path.. `template.htm` has to be within your **UI** path.

**Comment by prdip** [comment]
Thanks for the help
