### ISSUE TITLE
better multi language

### ISSUE THREAD

**Issue by noxtras** [bcosca/fatfree#1146]
Hi,
This is not an issue. I just think the multi-language feature could be better, if it also worked like this:
in the template: {{ __('my text here with spaces') }}
DICT/en.php is the same, but supports spaces (or one could use _en.php for backwards compatibility)

Then, I have this in index.php
```
$f3->LANGUAGE = $f3->ml->current; //previously loaded the Multilang::instance()
$f3->TEXT = include($f3->LOCALES."_".$f3->LANGUAGE.".php");

function __( $text) {	
	global $f3;
	if (isset($f3->TEXT[$text])) { //for simplicity, the default language file has an empty value
		if ($f3->TEXT[$text]) {
			return $f3->TEXT[$text];
		} else {
			return $text;//display the original text
		}
	} else {
		return '_'.$text.'_';//default is whatever is in the template, but add underscores to show that a translation is missing
	}
}
```

**Comment by ikkez** [comment]
Hi there. Well I don't get the point here. Is your request about to have the Fallback string directly in the template? Despite of that I can hardly see where this should be better than what we have today. For discussions like this, please let us use the [F3 google board](https://groups.google.com/forum/#!forum/f3-framework)
thank you.

**Comment by noxtras** [comment]
moved the discussion there. 
Thanks again for the awesome framework that allows me to easily customize it to fit my needs!
