### ISSUE TITLE
custom date overwritten

### ISSUE THREAD

**Issue by campZero** [bcosca/fatfree#1147]
I have no clue on how to make a commit or that alike, so here it comes as an issue:

when using {{ '%B %Y', @date | format }} in template, I would always get a different output and nothing I did to the strftime string would make a difference.
Figured that in base.php, $prop gets defaulted to '%d %B %Y', overwriting any custom string.

I changed the block to 
case 'date':
							if (empty($mod) || $mod=='short')
								$prop='%x';
							elseif ($mod!='custom')
							{
								$prop='%d %B %Y';
								if ($mod=='full')
									$prop='%A, '.$prop;
							}
							return strftime($prop,$args[$pos]);

, now it works as intended, but I might have overlooked something.

update: edited to clear up the final template string

**Comment by campZero** [comment]
I think I chose a bad way to explain the issue, cleared up the template part being used to clear up the issue.

**Comment by xfra35** [comment]
Actually, after the [docs](https://fatfreeframework.com/3.6/base#format), the following should be working:

```html
{{ 'Created on: {0,date,custom,%B %Y}', @Date | format }}
```

**Comment by campZero** [comment]
True, according to the docs, it should. 
But look at the code in lib/base.php, starting line 982 - first thing it does is set the $prop to '%d %B %Y' and there goes the custom string. Then the script either shortens or extends said $prop.

`case 'date':
	$prop='%d %B %Y';
	if (empty($mod) || $mod=='short')
		$prop='%x';
	elseif ($mod=='full')
		$prop='%A, '.$prop;
	return strftime($prop,$args[$pos]);`

$mod = custom has no place there.

**Comment by xfra35** [comment]
You're right. Looks like the "custom" modifier was broken in https://github.com/bcosca/fatfree-core/commit/958f0416d6cb7177834e38a0d01edbfdc6682858

**Comment by campZero** [comment]
Thanks for confirming, glad I could help my favourite project.

**Comment by NetLancer** [comment]
Yeah, f3 is one of my favourites too. I think it should draw more attention from community & devGuys for its pragmatic approach and usefulness
