### ISSUE TITLE
Problem F3 at addon domain

### ISSUE THREAD

**Issue by wahono77** [bcosca/fatfree#1148]
I use F3 on addon domain. Addon domain always have 2 domain, the original domain and sub domain.
Example : primary domain: primary.com
addon domain : addon.com
then I have addon.com and addon.primary.com

The problem in F3 when use reroute, SESSION and COOKIE. They use subdomain and not addon domain.

Any trick to use F3 in this situation?

thanks

**Comment by ikkez** [comment]
Try to set `JAR.domain` to a fixed host name, i.e. `JAR.domain = primary.com` in your config file

**Comment by wahono77** [comment]
Thanks @ikkez your solution fix my problem COOKIE and SESSION
