### ISSUE TITLE
How to return a HTTP 201 code

### ISSUE THREAD

**Issue by wranger** [bcosca/fatfree#1154]
Hi,
I have implemented a Rest-Interface with f3, but the client expects an http 201 return code as a result of an POST. When i trigger an f3->error(201), f3 sends also an error message:
```

<!DOCTYPE html>
<html>
<head><title>201 Created</title></head>
<body>
<h1>Created</h1>
<p>HTTP 201 (POST /quota/uid)</p>
<pre>[app/controllers/TestController:97] Base->error()
[lib/base.php:1873] TestController->post()
[lib/base.php:1673] Base->call()
[index.php:57] Base->run()
</pre>
</body>
</html>

```
Is there a way to get only the 201 response?

**Comment by pauljherring** [comment]
`$f3->status(201);`

This is really a question that is better asked on the discussion forum:

https://groups.google.com/forum/#!forum/f3-framework

**Comment by wranger** [comment]
thanks
