### ISSUE TITLE
lang PREFIX doesn't work

### ISSUE THREAD

**Issue by olaulau** [bcosca/fatfree#1160]
[PREFIX](https://fatfreeframework.com/3.6/quick-reference#PREFIX) var doesn't seem to work, here is my little sample (i'm using F3 from composer) :

`index.php` :
```
<?php
require 'vendor/autoload.php';
$f3 = \Base::instance();

$f3->route('GET /',
    function() {
		$f3 = \Base::instance();
        echo $f3->get('DICT.test');
    }
);

$f3->set('PREFIX', 'DICT');
$f3->set('LANGUAGE','de');
$f3->run();
```

`de.php` :
```
<?php
return array(
	'test' => 'TEST',
);
```

**Comment by ikkez** [comment]
Notice the `.`... it's `$f3->set('PREFIX', 'DICT.');`

**Comment by olaulau** [comment]
Oh you're right ... I though it was a typo.
my mistake ... sorry
thanks for the quick answer !
