### ISSUE TITLE
Template extend node

### ISSUE THREAD

**Issue by vinikey** [bcosca/fatfree#1163]
Hello there!

(I think is more a question than an issue)

First of all, thank you for this excellent framework!
This is my first project that I try to make with f3.
Since now everything goes really good and really fast.

The last day I'm trying to extend the Template instance as I can see [here](https://fatfreeframework.com/3.6/extended-templating).
Using the code

`\Template::instance()->extend('testTag',function($node){
 return "<div>".$node[0]."</div>";
});`

for the

`<testTag>{{ @sometitle }}</testTag>`

I found that the extend doesn't render the @sometitle and in the extend function the return is

`<div>{{ @sometitle }}</div>`

I tried to use the extend at beforeRoute and at afterRoute, always before the call of
`echo \Template::instance()->render('template.htm');`

Can anyone help me with that?

Thank you for your time!

**Comment by geniuswebtools** [comment]
It's been asked not to open issues for question.  You can ask for help from these resources.

Technical support is available at the official discussion forum: https://groups.google.com/forum/#!forum/f3-framework. If you need live support, you can talk to the development team and other members of the F3 community via IRC. We're on the FreeNode #fatfree channel (chat.freenode.net). Visit http://webchat.freenode.net/ to join the conversation. You can also download the Firefox Chatzilla add-on or Pidgin if you don't have an IRC client so you can participate in the live chat.

**Comment by vinikey** [comment]
I'm terribly sorry for this and really thank you for the information!
