### ISSUE TITLE
Database connection right way, question

### ISSUE THREAD

**Issue by NetLancer** [bcosca/fatfree#1164]
Hi wiseDevs!
I've been looking for a convenient method of including $db_connection just when/where needed and i've come up so far with confinement of DNS in predefined class.
Then each time i need to require/require_once do:
$f3->call('DBClass::connect'), with great AUTOLOAD help still it seems somewhat awkward and i frankly doubt is the right way.
Plus i'd like the end user to have a clear access to $db_connection params in *.cfg file.
So, what is the right/recommended way to store & use database connection object considering nowadays power & features of f3, could someone please give an example.

Pardon my dummy question, but this is the way i'm presently getting acquainted with this nice php tool :)

**Comment by exodus4d** [comment]
#### Simple:  _Global_ F3 variable 
You can init a DB connection at the "entry point" of your App e.g. in `beforeroute()` callback (see: )
```PHP
function beforeroute(\Base $f3, $params) : bool {
    $f3->set('myDbConnection', )
}
```

**Comment by exodus4d** [comment]
#### Simple:  _Global_ F3 variable 
You can init a DB connection at the "entry point" of your App e.g. in `beforeroute()` handler (see: https://fatfreeframework.com/3.5/routing-engine#event-handlers)
```PHP
function beforeroute(\Base $f3, $params) : bool {
    $db=new \DB\SQL('mysql:host=localhost;port=3306;dbname=mysqldb','username','password');
    $f3->set('myDbConnection', $db);
}
```
... and then use it across the request... `$f3->myDbConnection->exec('SELECT ...');`

#### Advanced: "On demand" DB connection
The above code has some downsides: A new connection is established for each request, even if it is not used later on, for processing the request...
Better way is to have some kind of a "DB pool" config class `set()` in `beforeroute()`, that _manages_ your DB connection. If some method requires a DB connection, the Pool class can either make a new connection, or return an existing connection if already exists.
```PHP
function beforeroute(\Base $f3, $params) : bool {
    $dbPool = Pool::instance($myDbCredentials);
    $f3->set('DB', $dbPool );
}
```
... and then: `$f3->DB->getConnection()->exec('SELECT ...');`

**Comment by Rayne** [comment]
You could also utilize a dependency injection container:

- [`CONTAINER`](https://fatfreeframework.com/3.6/quick-reference#CONTAINER) variable

- https://github.com/bcosca/fatfree-core/pull/221

Anyway, please use the Google Group or Slack ([linked on fatfreeframework.com](https://fatfreeframework.com/3.6/home)) channel for questions.

**Comment by NetLancer** [comment]
Clear, thanx a lot @exodus4d @Rayne
