### ISSUE TITLE
"SameSite" Cookie option should be supported by F3 (PHP 7.3)

### ISSUE THREAD

**Issue by exodus4d** [bcosca/fatfree#1165]
### Issue
Since Chrome `v.76` a warning is shown in JS console if a page receives a **3rd** party cookie where "**SameSite**" Cookie option was not set not by the 3rd party page that creates it.

![sameSite](https://user-images.githubusercontent.com/9299033/66701473-db7fa480-ecfc-11e9-8e91-7204cdf38e07.png)

> The Stable version of Chrome 80 is targeted for enabling this feature by default. The feature will be enabled in the Beta version only, starting in Chrome 78. This feature is available as of Chrome 76 by enabling the same-site-by-default-cookies flag.

source: https://www.chromestatus.com/feature/5088147346030592

### Usecase
Assuming my _F3_ page needs to create a cookie that should be _readable_ by others, I have to create it with `SameSite=lax` : [SameSite cookies explained](https://web.dev/samesite-cookies-explained)

### Required _F3_ changes
1. Since _PHP_ **7.3**, [`setcookie()`](https://www.php.net/manual/en/function.setcookie.php), [`session_set_cookie_params ()`](https://www.php.net/manual/en/function.session-set-cookie-params.php ) have **new** (optional) **associative array** syntax for arguments that allows to set the _new_ "samesite" option.
_F3_ ´s [JAR](https://fatfreeframework.com/3.6/quick-reference#JAR) config does **not** work here, because _F3_ uses e.g.: 
    - `call_user_func_array('setcookie',[$parts[1],$val]+$jar);` 
    - `call_user_func_array('session_set_cookie_params',$jar)`

    ... and there is no unique parameter for "SameSite".

### Hint
To keep backward compatibility for PHP < 7.3, we still need to keep the current **non array** calls.

**Comment by ikkez** [comment]
@exodus4d can you please verify if the latest commit? Works fine here so far.

**Comment by exodus4d** [comment]
@ikkez Looks good to me. - Great work! 🌟
