### ISSUE TITLE
Including of configuration files leads to performance problems

### ISSUE THREAD

**Issue by michalmoravek** [bcosca/fatfree#1166]
When I have started to use configuration files including (https://fatfreeframework.com/3.6/framework-variables#[configs]) the performance of PHP script was affected.
Including of one configuration file has caused deagradation of performance from tens milliseconds to hundreds of milliseconds. Including of two configuration files has caused deagradation of performance to seconds.

**Comment by ikkez** [comment]
What F3 version do you use? There were fixes to improve performance with config files in the past.
Generally speaking: of cause, configuration files need to be parsed and are always slower than setting your variables in php. How do you load the config files? What does impact performance is: very long config files, enabling dynamic variables in config files, and perhabs enabled xdebug in your php environment. In have a config file with mixed content that is like 700 lines long and parsed in 20ms.. so it can also be very fast.. we probably need more details.

**Comment by michalmoravek** [comment]
I use version 3.6. And my case was the following:
1. Main config file contained [globals] (tens of variables), and at the end it included two [configs].
2. The first of included config contained [globals] only - tens of array variables. I wanted to separate it from logical point of view.
3. The second of included config contained [maps] only - tens of rows.

In this situation the performance goes wrong.
When I put everything back into one main config file the performance returned back to nice values.

**Comment by ikkez** [comment]
ensure that you are running at least version 3.6.4.
And use this for config includes:
```ini
[configs]
app/maps.ini=false
```

notice the `false` setting.. this actually means to include the config file without dynamic token/variable resolution, which is much faster
