### ISSUE TITLE
framework not work correctly with virtual host in xampp for windows...

### ISSUE THREAD

**Issue by arcanisgk** [bcosca/fatfree#1167]
https://github.com/bcosca/fatfree/blob/archive/f3-3.0.6.cms.demo.zip

framework not work correctly with virtual host in xampp for windows...

![image](https://user-images.githubusercontent.com/1207306/68401761-4bd8e480-0148-11ea-9cd0-39746fff4a83.png)

**Comment by fmagrosoto** [comment]
Hello... this error seems to be a permissions issue.
You may have to edit your Apache configuration file (_httpd.conf_) and set permission as:

```
User <your username>
Group daemon
```

And that's all.

**Comment by arcanisgk** [comment]
> Hello... this error seems to be a permissions issue.
> You may have to edit your Apache configuration file (_httpd.conf_) and set permission as:
> 
> ```
> User <your username>
> Group daemon
> ```
> 
> And that's all.

this the virtual host permison and directive:

```
<VirtualHost *:80>
	ServerAdmin example@example.com
	DocumentRoot "\xampp\htdocs\dev\t2"
	ServerName test2.me
	ServerAlias *.test2.me
	<Directory "\xampp\htdocs\dev\t2">
		Options Indexes	
		AllowOverride All
		Require all granted
		Allow from all
	</Directory>
</VirtualHost>
```

**Comment by fmagrosoto** [comment]
Nop, you are viewing the httpd-vhost configuration file, you have to edit **httpd.conf file**, you can find this file in _/XAMPP/etc/_ folder.

**Comment by KOTRET** [comment]
As Fernando stated out, this is a problem with the setup of xampp, not a framework issue - at this point, no framework code has been executed yet.
