### ISSUE TITLE
Minify() broken in 3.7.0

### ISSUE THREAD

**Issue by NoobDoAAA** [bcosca/fatfree#1169]
Hi!
 
In 3.7.0 if I try to Minify an array of files - only first file processed.
It seems like Break is not needed in web.php at line 818?
 
In 3.6.5 Minify works just fine so why you change it?
Thanks!

**Comment by ikkez** [comment]
oh yeah that should not happen.. just fixed that and wrote a test for it to keep keep it working in the future. thanks for reporting.
