### ISSUE TITLE
swagger codegen support [feature request]

### ISSUE THREAD

**Issue by albjeremias** [bcosca/fatfree#1171]
Would be awesome to have a codegen for fatfree for generating an api from a swagger file! :)

examples:
https://github.com/swagger-api/swagger-codegen/wiki/Server-stub-generator-HOWTO#php-slim

**Comment by KOTRET** [comment]
F3 distincts between the routes and the controller (in java you'd add annotations at the controller for that), so this is not an easy task. The only thing I could imagine to be generated is a controller stub with the methods for the routes in it, but the whole structure is unclear.
