### ISSUE TITLE
smtp message with image/jpg or image/png header

### ISSUE THREAD

**Issue by jdegraef** [bcosca/fatfree#1173]
Hi, thanks for supplying the world with F3, 
(coming from symphony this is a breeze to hack something together with)

now more of a question than an issue i guess...
how would I send an email with smtp module with an image/png or image/jpg header?

I have some stubborn email clients that show application/octet-stream as an attachment and require image/jpg to show it inline.

As far as i can tell the header is hard-coded in smtp.php
				$out.='Content-Type: application/octet-stream'.$eol;		
but maybe i'm missing something.

thanks!

**Comment by geniuswebtools** [comment]
It's been requested that you posts questions to the F3 Google group, or there's a slack channel as well.

https://groups.google.com/forum/#!forum/f3-framework

https://fatfreeframework-slack.herokuapp.com/
