### ISSUE TITLE
DB/SQL/Mapper Object dehydrating on save() in 3.7.1

### ISSUE THREAD

**Issue by MDBenson** [bcosca/fatfree#1175]
I upgraded a working project from 3.6.5 to 3.7.1 and found that, under some circumstances, where I could ->cast() data from a DB/SQL/Mapper object successfully in 3.6.5 and recover the record data after the update (to for example get the new record ID when creating a record), in 3.7.1 the exact same code fails becase the save() is dhydrating the DB/SQL/Mapper object and it's field values are all reverting to null.

Sure enough I rolled fatfree-core back to 3.6.5 and it now works 100% fine again. 

I can't post the exact code I have an issue with because it's proprietary property, and annoyingly I wrote a simple example and it works flawlessly the way 3.6.5 did but the issue is 100% there, I can see it in a XDebug step-by-step readback.

I know this isn't amazingly helpful but, as the docvumentation for DB explicitly states that objects *must* be reset() to clear them I assumed it weas not working as intended in all cases. If @bcosca wants to contact me personally I might be able to share the code 1-to-1 so they can see what's up...

**Comment by ikkez** [comment]
can you please check if that last commit here is the cause of your issue?!
https://github.com/bcosca/fatfree-core/commit/0c684da63222061f9bda74b02285240317930684
thanks

**Comment by MDBenson** [comment]
It would seem it hasnt, no. I have narrowed the issue down to Insert operations. If I use save() to Update an object it seems cast() returns the updated data without a problem. If I use it to Insert a record it sometimes is dehydrating.

I unfortunately don't have time today to test further but when I do I'll get back to here.

**Comment by pauljherring** [comment]
> If I use it to Insert a record it sometimes is dehydrating.

This is probably it: 3.6.5->3.7.1

```diff
        /**
        *       Insert new record
        *       @return static
        **/
        function insert() {
                $args=[];
                $actr=0;
                $nctr=0;
                $fields='';
                $values='';
                $filter='';
                $pkeys=[];
                $nkeys=[];
                $ckeys=[];
                $inc=NULL;
                foreach ($this->fields as $key=>$field)
                        if ($field['pkey'])
                                $pkeys[$key]=$field['previous'];
                if (isset($this->trigger['beforeinsert']) &&
                        \Base::instance()->call($this->trigger['beforeinsert'],
                                [$this,$pkeys])===FALSE)
                        return $this;
+               if ($this->valid())
+                       // duplicate record
+                       foreach ($this->fields as $key=>&$field) {
+                               $field['changed']=true;
+                               if ($field['pkey'] && !$inc && $field['pdo_type']==\PDO::PARAM_INT
+                                       && !$field['nullable'])
+                                       $inc=$key;
+                               unset($field);
+                       }
                foreach ($this->fields as $key=>&$field) {
                        if ($field['pkey']) {
                                $field['previous']=$field['value'];
                                if (!$inc && $field['pdo_type']==\PDO::PARAM_INT &&
-                                       empty($field['value']) && !$field['nullable'])
+                                       is_null($field['value']) && !$field['nullable'])
                                        $inc=$key;
                                $filter.=($filter?' AND ':'').$this->db->quotekey($key).'=?';
                                $nkeys[$nctr+1]=[$field['value'],$field['pdo_type']];
                                $nctr++;
                        }
                        if ($field['changed'] && $key!=$inc) {
                                $fields.=($actr?',':'').$this->db->quotekey($key);
                                $values.=($actr?',':'').'?';
                                $args[$actr+1]=[$field['value'],$field['pdo_type']];
                                $actr++;
                                $ckeys[]=$key;
                        }
+                       unset($field);
                }
```

**Comment by pauljherring** [comment]
Introduced here: https://github.com/bcosca/fatfree/commit/60ed3169635ed94e8a8c875dae537fdf9d49d2c7#diff-ba2603215b5da69d3f4626f75aefd9d2R437

**Comment by ikkez** [comment]
I'm unable to reproduce this.

```php
$mapper = new \DB\SQL\Mapper($f3->DB,'news');
$mapper->load();
$mapper->insert();
var_dump($mapper->_id);
$mapper->insert();
var_dump($mapper->_id);
var_dump($mapper->cast());
```

**Comment by MDBenson** [comment]
Yes, I did the same simple test and it does not occur here either, however it persists in the place I originally found it, so it's something in the depths of my code that is causing it to manifest. I will have time to investigate next week, hopefully.

**Comment by ikkez** [comment]
I've found something.. when you manually set the `id` (or other pkey autoincrement field used) to zero (0), it'll insert the record with 0, it'll still get a new id, but it'll not be reloaded.
Caused by the change here: https://github.com/bcosca/fatfree-core/pull/290
Easy fix is to not set the ID to 0.. I'm wondering what way to go from here 🤔

**Comment by diapolon** [comment]
Hi ikkez,
for me calling $mapper->cast() on empty record return id=0

**Comment by joseffb-mla** [comment]
At this point it's a philosophy question (which isn't bad). To me, philosophically speaking, it sounds like a bug. If I set an ID to 0 I'm explicitly to false (because there is never a 0 id). Not sure why I would do this but, if I do I expect a 0 to tell the system to do the default behavior.

**Comment by geniuswebtools** [comment]
@joseffb-mla using the beforeinsert or beforesave event handler you could check for id=0 and clear() the value or set() it to null, and see if that resolves your issue.

**Comment by xfra35** [comment]
Hi there, I encountered the same issue. We're wondering why would anybody set id to 0, but that could actually be a consequence of trying to set an autoincrement field to `NULL`.

See this snippet:
```php
// mapper $A is hydrated, mapper $B is dry
// they have a similar structure and we need to import A data to B
$B->copyfrom( ['id'=>NULL] + $A->cast() );
$B->save();
echo $f3->format( 'New row: name={0} id={1} dry={2}', $B->name, $B->id, (int)$B->dry() );
```
Before https://github.com/bcosca/fatfree-core/pull/290/commits/e6f98df911f9804f1e02d5e71e8b402a5afed4a8, this used to work. Output: `New row: name=XXXX id=22 dry=0`
After https://github.com/bcosca/fatfree-core/pull/290/commits/e6f98df911f9804f1e02d5e71e8b402a5afed4a8, this started to fail. Output: `New row: name= id= dry=1`

Now why the `id` field is seen as `0` (at least in MySQL): when we set `$B->id=NULL`, the `Mapper` class actually does `$B->id=0`. This is a consequence of [this line](https://github.com/bcosca/fatfree-core/blob/3a7f03a0acde69d7cf5e8fc479c4d86178388769/db/sql/mapper.php#L100) and the fact that in MySQL an autoincrement key cannot be nullable ([see](https://www.db-fiddle.com/f/iW1hUXWrmZRpru9pZ8WDJC/0)).

**Comment by xfra35** [comment]
Now I'm wondering why we need to write `$field['pdo_type']==\PDO::PARAM_INT && empty($field['value']) && !$field['nullable']` to detect autoincrement fields.

Wouln't it be possible to patch the `SQL->schema()` method to add a `$field['autoincrement']` property?

This would allow to fix this issue as well as [this line](https://github.com/bcosca/fatfree-core/blob/3a7f03a0acde69d7cf5e8fc479c4d86178388769/db/sql/mapper.php#L100).

**Comment by ikkez** [comment]
Well the autoincrement fields cannot be NULL, and when they're NOT NULL you can insert records with the primary key being null or 0:

```sql
Insert into testInno value(null, 'roger right');
Insert into testInno value(0, 'willy wonder');
Insert into testMyisam value(null, 'roger right');
Insert into testMyisam value(0, 'willy wonder');
```

So actually it should not make a difference when inserting. The problem is that reloading the fresh state after insert of that records is based on the value used for `id`. Since https://github.com/bcosca/fatfree-core/commit/e6f98df911f9804f1e02d5e71e8b402a5afed4a8, which was meant as quick fix for accedentially using the wrong primary field, now doesn't accept a `0` anymore. The insert was complete but `$inc` not set and hence the reason for the empty mapper, as it's no longer using the received autoincremented value, but the populated `$filter` var with `id=$field[id][value]`, which is 0.
An `$field['autoincrement']` flag would be nice, but probably not a trivial task,.. guess we would have done this before, if it was easy. But I think an easy fix is to revert https://github.com/bcosca/fatfree-core/commit/e6f98df911f9804f1e02d5e71e8b402a5afed4a8 and adjust the if condition once more and add `&& is_null($field['default'])` instead. Because an autoincrement field cannot have a default other than NULL, and there's only 1 of it

**Comment by xfra35** [comment]
You're right about 0 in MySQL. I didn't know that. Actually:
> This behaviour is by design, inserting 0, NULL, or DEFAULT into an AUTO_INCREMENT column will all trigger the AUTO_INCREMENT behaviour.

But it appears that each SQL engine has its own trigger keywords:
* in MySQL: 0, NULL or DEFAULT
* in PostgreSQL, only DEFAULT triggers the autoincrement sequence. 0 inserts 0 and NULL is rejected.
* in SQLite, only NULL triggers the autoincrement sequence. 0 inserts 0 and DEFAULT is rejected.
* in MS SQL, no keyword triggers the autoincrement sequence. One needs either *not to* specify the autoincrement column or implement a TRIGGER.

See :
* MySQL => https://www.db-fiddle.com/f/iW1hUXWrmZRpru9pZ8WDJC/1
* PostgreSQL => https://www.db-fiddle.com/f/iW1hUXWrmZRpru9pZ8WDJC/4
* SQLite => https://www.db-fiddle.com/f/iW1hUXWrmZRpru9pZ8WDJC/6

As for the `$field['autoincrement']` flag, it may be easier than it sounds:
* MySQL => https://www.db-fiddle.com/f/iW1hUXWrmZRpru9pZ8WDJC/3 (column `extra`)
* PostgreSQL => https://www.db-fiddle.com/f/iW1hUXWrmZRpru9pZ8WDJC/8 (column `autoincrement`)
* SQLite => https://www.db-fiddle.com/f/iW1hUXWrmZRpru9pZ8WDJC/7 (column `sql` to be processed in PHP)
* MS SQL => http://sqlfiddle.com/#!18/fe127/12 (column `autoincrement`)

**Comment by WilliamStam** [comment]
mine is dehydrating after a php upgrade to 7.4 :( lol not sure if related or not. 

was working on this project last week on php 7.3. decided to upgrade my machine a bit and installed 7.4 and now the orm part isnt working. rest seems ok for now. 

````
//var_dump($orm);
D:\Projects\Website-Framework\models\db.php:28:
object(DB\SQL\Mapper)[61]
  protected 'db' => 
    object(DB\SQL)[7]
      protected 'uuid' => string 't8n6pfx8xbjp' (length=12)
      protected 'pdo' => 
        object(PDO)[9]
      protected 'dsn' => string 'mysql:host=xxxx;dbname=xxxx' (length=42)
      protected 'engine' => string 'mysql' (length=5)
      protected 'dbname' => string 'xxxx' (length=11)
      protected 'trans' => boolean false
      protected 'rows' => int 1
      protected 'log' => string '(4.3ms) 

			 SELECT system.* 

			 FROM system

			 WHERE system.ID in (SELECT MAX(s.ID) FROM system s WHERE s.`timestamp` <= '2020-04-16 10:45:12' GROUP BY s.system) 

	  

		

(9.4ms) 

			 SELECT DISTINCT pages.* , templates.label as templates_label, system_users.fullname as user, (SELECT count(ID) FROM pages c WHERE c.uuid = pages.uuid)-1 as edits

			 FROM pages LEFT JOIN templates ON templates.uuid = pages.templateID AND templates.ID in (SELECT MAX(s.ID) FROM templates s WHERE templates.`timestamp` <'... (length=4363)
  protected 'engine' => string 'mysql' (length=5)
  protected 'source' => string 'content_events' (length=14)
  protected 'table' => string '`content_events`' (length=16)
  protected 'as' => null
  protected '_id' => null
  protected 'fields' => 
    array (size=20)
      'ID' => 
        array (size=9)
          'type' => string 'int(6)' (length=6)
          'pdo_type' => int 1
          'default' => null
          'nullable' => boolean false
          'pkey' => boolean true
          'value' => int 5
          'initial' => int 5
          'changed' => boolean false
          'previous' => int 5
      'uuid' => 
        array (size=8)
          'type' => string 'varchar(50)' (length=11)
          'pdo_type' => int 2
          'default' => null
          'nullable' => boolean true
          'pkey' => boolean false
          'value' => string '34c25636-ddbd-4003-9f22-ca38cd39b31a' (length=36)
          'initial' => string '34c25636-ddbd-4003-9f22-ca38cd39b31a' (length=36)
          'changed' => boolean false
      'heading' => 
        array (size=8)
          'type' => string 'varchar(250)' (length=12)
          'pdo_type' => int 2
          'default' => null
          'nullable' => boolean true
          'pkey' => boolean false
          'value' => string 'Corona Party' (length=12)
          'initial' => string 'Corona Party' (length=12)
          'changed' => boolean false
     
     ... snip ...


  protected 'adhoc' => 
    array (size=0)
      empty
  protected 'props' => 
    array (size=0)
      empty
  protected 'query' => 
    array (size=1)
      0 => 
        object(DB\SQL\Mapper)[62]
          protected 'db' => 
            object(DB\SQL)[7]
              ...
          protected 'engine' => string 'mysql' (length=5)
          protected 'source' => string 'content_events' (length=14)
          protected 'table' => string '`content_events`' (length=16)
          protected 'as' => null
          protected '_id' => null
          protected 'fields' => 
            array (size=20)
              ...
          protected 'adhoc' => 
            array (size=0)
              ...
          protected 'props' => 
            array (size=0)
              ...
          protected 'query' => 
            array (size=1)
              ...
          protected 'ptr' => int 0
          protected 'trigger' => 
            array (size=0)
              ...
  protected 'ptr' => int 0
  protected 'trigger' => 
    array (size=0)
      empty


//var_dump($fields_that_are_changing);
D:\Projects\Website-Framework\models\db.php:40:
array (size=1)
  'heading' => 
    array (size=2)
      'w' => string 'Corona Party' (length=12)
      'n' => string 'Corona Partyhhhh' (length=16)

// var_dump($orm);
D:\Projects\Website-Framework\models\db.php:73:
object(DB\SQL\Mapper)[61]
  protected 'db' => 
    object(DB\SQL)[7]
      protected 'uuid' => string 't8n6pfx8xbjp' (length=12)
      protected 'pdo' => 
        object(PDO)[9]
      protected 'dsn' => string 'mysql:host=xxxx;dbname=xxxx' (length=42)
      protected 'engine' => string 'mysql' (length=5)
      protected 'dbname' => string 'xxxx' (length=11)
      protected 'trans' => boolean false
      protected 'rows' => int 1
      protected 'log' => string '(4.3ms) 

			 SELECT system.* 

			 FROM system

			 WHERE system.ID in (SELECT MAX(s.ID) FROM system s WHERE s.`timestamp` <= '2020-04-16 10:45:12' GROUP BY s.system) 

	  

		

(9.4ms) 

			 SELECT DISTINCT pages.* , templates.label as templates_label, system_users.fullname as user, (SELECT count(ID) FROM pages c WHERE c.uuid = pages.uuid)-1 as edits

			 FROM pages LEFT JOIN templates ON templates.uuid = pages.templateID AND templates.ID in (SELECT MAX(s.ID) FROM templates s WHERE templates.`timestamp` <'... (length=4708)
  protected 'engine' => string 'mysql' (length=5)
  protected 'source' => string 'content_events' (length=14)
  protected 'table' => string '`content_events`' (length=16)
  protected 'as' => null
  protected '_id' => string '10' (length=2)
  protected 'fields' => 
    array (size=20)
      'ID' => 
        array (size=9)
          'type' => string 'int(6)' (length=6)
          'pdo_type' => int 1
          'default' => null
          'nullable' => boolean false
          'pkey' => boolean true
          'value' => int 10
          'initial' => int 10
          'changed' => boolean false
          'previous' => int 10
      'uuid' => 
        array (size=8)
          'type' => string 'varchar(50)' (length=11)
          'pdo_type' => int 2
          'default' => null
          'nullable' => boolean true
          'pkey' => boolean false
          'value' => string '34c25636-ddbd-4003-9f22-ca38cd39b31a' (length=36)
          'initial' => string '34c25636-ddbd-4003-9f22-ca38cd39b31a' (length=36)
          'changed' => boolean false
      'heading' => 
        array (size=8)
          'type' => string 'varchar(250)' (length=12)
          'pdo_type' => int 2
          'default' => null
          'nullable' => boolean true
          'pkey' => boolean false
          'value' => null
          'initial' => null
          'changed' => boolean false
     ... snip ...


  protected 'adhoc' => 
    array (size=0)
      empty
  protected 'props' => 
    array (size=0)
      empty
  protected 'query' => 
    array (size=1)
      0 => 
        object(DB\SQL\Mapper)[62]
          protected 'db' => 
            object(DB\SQL)[7]
              ...
          protected 'engine' => string 'mysql' (length=5)
          protected 'source' => string 'content_events' (length=14)
          protected 'table' => string '`content_events`' (length=16)
          protected 'as' => null
          protected '_id' => string '10' (length=2)
          protected 'fields' => 
            array (size=20)
              ...
          protected 'adhoc' => 
            array (size=0)
              ...
          protected 'props' => 
            array (size=0)
              ...
          protected 'query' => 
            array (size=1)
              ...
          protected 'ptr' => int 0
          protected 'trigger' => 
            array (size=0)
              ...
  protected 'ptr' => int 0
  protected 'trigger' => 
    array (size=0)
      empty

````

**Comment by stehlo1** [comment]
I am not sure whether you realise that fiddling with this code introduced backward incompatible changes that absolutely corrupt functionality.
I have been donating to this project exactly for the reason that I could rely on it. Well, not anymore(?).

**Comment by ikkez** [comment]
If you think you've found an issue, please post more details (code) or open a new issue. thank you

**Comment by ikkez** [comment]
@stehlo1 there's no need to spam the same lines everywhere. Please tell me what's the issue.

**Comment by stehlo1** [comment]
These are not the "same lines". Different changes introduced different backward incompatible changes.

Don't you understand the code you are changing? @ikkez @bcosca 

This change corrupted the way the data is inserted into PostgreSQL, namely it is now not inserted at all. This change affects all projects which are using F3.

**Comment by WilliamStam** [comment]
my projects are ok (8 or so projects)? maybe post your code / issue instead of just being a dick?

**Comment by stehlo1** [comment]
@WilliamStam My comments were not for you. Flame elsewhere.

**Comment by WilliamStam** [comment]
@stehlo1 your comments are surely not ment for anyone. no "real" human would talk to another the way you are. especially not the maintainers of this project. so stop being a dick and join the human race

**Comment by joseffb-mla** [comment]
@stehlo1

It's a volunteer based community not a commercial one. You are the only one
who has this issue. Please be respectful in your tone to all the community
members who are also reading this.

If you have an issue, or better yet a solution, please submit it via an
issue ticket so it can be addressed.

**Comment by pauljherring** [comment]
> If you have an issue, or better yet a solution, please submit it via an issue ticket so it can be addressed.

They were too busy throwing their toys out of their pram to have a sensible discussion about it.

**Comment by ikkez** [comment]
@xfra35 I've implemented your suggestion from https://github.com/bcosca/fatfree/issues/1175#issuecomment-583334337 in the latest commit. It wont work in sqlite2 anymore, only 3.1+ and everything beyond mysql,postgre,mssql,sqlite will fallback to the behaviour pre https://github.com/bcosca/fatfree-core/commit/0c684da63222061f9bda74b02285240317930684 ..soo.. it wasn't that easy, but doable with your preparations from DB fiddle.. thanks for that 👍
