### ISSUE TITLE
Web->minify() and Javascript Template Literals removes too much

### ISSUE THREAD

**Issue by marcus-at-localhost** [bcosca/fatfree#1178]
The js minifier has some issues with whitespace between backticks in [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

```js
`xxx ${firstName} ${lastName} xxx`;
```

Web->minify() 

```js
`xxx ${firstName}${lastName}xxx`
```

PS: I noticed that in f3 3.6, but I checked and it looks like the minify regex for js wasn't touched for 3.7 - apologies if I'm wrong.

**Comment by ikkez** [comment]
fixed
