### ISSUE TITLE
find() is slow

### ISSUE THREAD

**Issue by olaulau** [bcosca/fatfree#1183]
hi ;
when I just fetch 1000 objects from a table using the find() method, it is a little slow I think, about 100ms.
getting the same data as array with $db->exec("SELECT * FROM table LIMIT 1000") is really fast (3ms).
I know the framework has to map every fields into the objects, but is there a way to speed it up a little bit ?

**Comment by KOTRET** [comment]
Do not use objects when fetching from database, use arrays instead.
Please use Google Groups for questions.

**Comment by olaulau** [comment]
you mean we shouldn't use the F3's ORM ??
