### ISSUE TITLE
passing array to the view make it slow

### ISSUE THREAD

**Issue by olaulau** [bcosca/fatfree#1184]
Hi ;
passing an array to the view make it render slower, even if the array is unused (no foreach to display data).
I'm using PHP style templates.

about 50ms to render a simple view with the 100 objects array passed, 
`echo $view->render('page.phtml');`
1ms without this line.
the set method itself doesn't take time :+1: 
`$f3->set("objects", $objects);`

any advice ?

**Comment by KOTRET** [comment]
please use google groups for questions, thanks

**Comment by olaulau** [comment]
sorry, I though unexpected performance issue could be considered as a framework bug.

**Comment by KOTRET** [comment]
then it'd be best to have something to reproduce :)
