### ISSUE TITLE
seems that 'SESSION.f3-reroute-info' with any string value runs into error when trying to clear it's content via $f3->clear('SESSION.f3-reroute-info')

### ISSUE THREAD

**Issue by slavino** [bcosca/fatfree#1191]
https://github.com/bcosca/fatfree/blob/495a97c9957a9edfbaea362927be6f3faa96fc52/lib/base.php#L506

syntax error, unexpected '-', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) [/home/html/multi_157459/mydomain.com/_sub/dev/vendor/bcosca/fatfree/lib/base.php(506) : eval()'d code:1]

**Comment by ikkez** [comment]
Actually if works when you need to wrap that key this way: 

```
$f3->clear("SESSION['f3-reroute-info']");
```

But it seems like the compile method just evaluates the expression here, even if it does not need to do it here.. I'm looking for a better fix

**Comment by ikkez** [comment]
fixed in latest commit
