### ISSUE TITLE
SQL Server Identity Insert

### ISSUE THREAD

**Issue by NoToComments** [bcosca/fatfree#1193]
Hello I cant get fatfree working with sqlserver.

On Inserts it sends 0 as id to sqlserver. Instead of leaving the column out of the insert statement.

```SQL
CREATE TABLE [dbo].[example](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
```

Current behavior
```SQL
INSERT INTO [dbo].[example]
           (id,[name])
     VALUES
           (0,'test')
```

Wished behavior

```SQL
INSERT INTO [dbo].[example]
           ([name])
     VALUES
           (<name, varchar(50),>)
```

Looks like https://github.com/bcosca/fatfree/issues/1192

**Comment by xfra35** [comment]
I guess you're talking about the SQL mapper right? Can you provide a code sample?

**Comment by NoToComments** [comment]
Yeah its about the mapper.

Something like that?

```PHP
$database = new \DB\SQL(
            'sqlsrv:server=localhost,1433;database=testDB',
            'sa',
            'P@ssw0rd'
        );

     
        $example=new \DB\SQL\Mapper($database,'example');
        $example->name="SpaceOps";
        $example->save();
```

Error code

`PDOStatement: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the value NULL into column 'id', table 'shortyTest.dbo.project'; column does not allow nulls. INSERT fails.`

**Comment by ikkez** [comment]
Can you please check latest commit https://github.com/bcosca/fatfree-core/commit/95d5f68aa4b8a7c23b3493bfdb8c02f275e4c0ec at master branch. I've just tested it with SQL Server 2017 myself now and it all works fine here.

**Comment by ikkez** [comment]
please reopen if problem persists.
