### ISSUE TITLE
Database mapper cast method

### ISSUE THREAD

**Issue by FrankOssie** [bcosca/fatfree#1195]
I would like to see something like this in the cast method, now i'm overriding the cast method like this
```
public function cast($obj=NULL, $notAllowed=[]){
        if (!$obj)
            $obj=$this;
        return array_map(
            function($row) {
                return $row['value'];
            },
            array_filter(
                $obj->fields+$obj->adhoc,
                function ($key){
                    return strpos($key, 'password') !== false || !in_array($key, $notAllowed);
                },
                ARRAY_FILTER_USE_KEY
            )
        );
    }
```

**Comment by geniuswebtools** [comment]
@FrankOssie it's been requested that we ask for support via the Google group or Slack:

https://groups.google.com/forum/#!forum/f3-framework
https://fatfreeframework-slack.herokuapp.com/

But you can check out the onload() handler and see if that would give you the support you're looking for:
https://fatfreeframework.com/3.7/cursor#onload

Or you could create a view and only return the data you want visible and then use a mapper to pull the data from there.

**Comment by FrankOssie** [comment]
I cannot join the slack channel, it says user_disabled. But maybe add oncast as triggers

**Comment by ikkez** [comment]
Hi. @FrankOssie you can limit the field to work on with the. `$fields` parameter on the constructor. Does that fix your problem? https://fatfreeframework.com/3.7/sql-mapper#Instantiation

**Comment by FrankOssie** [comment]
It helps, but it would be easier to change the context, the not allowed field are most of the time less fields then the allowed fields

**Comment by geniuswebtools** [comment]
You could create a db view w/ only the fields you want, and then point the mapper to read from the view.

**Comment by FrankOssie** [comment]
I get it, but it would be a nice feature to filter the cast method, because it is used as an output method

**Comment by KOTRET** [comment]
_imho_ this is something you can achieve easily with a separate function, as this is not something the fw must provide.
After all it's just a wrapped call: `$foo = DBUtils::filter($bar->cast(), ['password','secretfield'])`.
Also it is not possible to include the hardcoded filter of the `'password'` field ;)

**Comment by FrankOssie** [comment]
Ok i'll fix it with something like that, thanks for the help
