### ISSUE TITLE
OpenID Documentation

### ISSUE THREAD

**Issue by Staja** [bcosca/fatfree#1197]
It would be useful to add sample code or improve the documentation of the OpenID class. It doesn't have sufficient information to help anyone implementing it.

**Comment by Rayne** [comment]
Maybe a look at the tests will help you:

- [OpenID Test](https://github.com/bcosca/fatfree/blob/dev/app/openid.php)
- [Test of OpenID2](https://github.com/bcosca/fatfree/blob/dev/app/openid2.php)

And for the sake of completeness:

- [Documentation](https://fatfreeframework.com/3.6/openid)

Feel free to contribute to the documentation in our [F3com-data](https://github.com/f3-factory/F3com-data) repository.

**Comment by Staja** [comment]
Implementation seems to rely on a XRDS Discovery endpoint but I don't think my IdP has one, only a OpenID Provider Metadata endpoint. I think I'm going to have to read some protocol documents, I must have misunderstood something.

**Comment by Staja** [comment]
I had a look at the implementation and discovered the XRDS discovery implementation and then discovered my problem, I missed the forest for the trees, I was expecting Open ID Connect not the original OpenID, that is why I was so confused about the workflow.
