### ISSUE TITLE
Request redirect() Method like reroute()

### ISSUE THREAD

**Issue by dduers** [bcosca/fatfree#1200]
Hello community,

There is a reroute() method available which is good, if you don't want to pass a query string.
Is there also a redirect() method which can be used when you have a query string?
It would be nice to have something alike, otherwise we have to call header('Location; ...') followed by an exit() call each time.
Maybe there is a better solution?

Thanks for consideration,
Daniel

**Comment by n0nag0n** [comment]
Does this point you in a positive direction? 

https://fatfreeframework.com/3.7/quick-reference#ONREROUTE

**Comment by ikkez** [comment]
as far as I know, you can use a query string in your reroute url

**Comment by dduers** [comment]
Thank you, I found that my BEFOREROUTE callback stripped the querystring.
