### ISSUE TITLE
Unable to render template when using route with token

### ISSUE THREAD

**Issue by Sokhavuth** [bcosca/fatfree#1225]
I love f3 framework. It is similar to Express.js for Node.js. I have tried to build a blog engine with f3 framework as I use to do with Python and Node.js. Everything works fine. However, I am unable to render any template when using route with token (route with parameter in other frameworks). Here the link to the repository: https://github.com/Sokhavuth/tvp, and the link to the working blog on Heroku is here https://khmerweb-tvp.herokuapp.com/ . You could login with email "root@tv.com" and password "password"; the link for login is https://khmerweb-tvp.herokuapp.com/login. On the admin page, click on the second icon on top, and try to click on edit icon of the post at the bottom, you will see the problem (do not click on delete icon, it will delete post).

**Comment by Rayne** [comment]
Your application looks cool, but please do not share credentials publicly. Your message isn't a proper bug report but [we could discuss your problem in our Slack channel](https://fatfreeframework-slack.herokuapp.com/).

**Comment by Sokhavuth** [comment]
The issue is static files are not loaded while using route with parameter. In Node.js and in Python, every framework gives the options to choose folder for "views" and static files such as css, js, and image files. And without static files, there won't be template.

**Comment by ikkez** [comment]
Insert a [base](https://www.w3schools.com/tags/tag_base.asp) tag to your html should fix the path issue.

**Comment by ikkez** [comment]
closing this. please reopen if you need any further assistance or join our slack or discord channel for more direct help.
