### ISSUE TITLE
Lightweight code base with just ~65kb... Really?

### ISSUE THREAD

**Issue by Nils85** [bcosca/fatfree#1227]
I keep seeing this "65kb" on the website and even on the readme but I don't understand where this number come from, because:

- The project size (master branch) is 580kb (compressed to a 218kb zip archive)
- The `lib` folder size is 419kb
- Even the file `base.php` is 92kb

So for me the real size of this framework is between 600 and 400 kb, but definitely more than 65kb.
Or maybe I missed something?

**Comment by Rayne** [comment]
The core (`base.php`) with cache, registry, routing, ISO database, views and comments is even [53KB small](https://github.com/bcosca/fatfree/blob/3.0.4/lib/base.php) (at least the version from nine years ago).

You did not miss anything. This information is outdated and probably not relevant anyway. Most users are certainly using the [non-core features](https://fatfreeframework.com/3.7/api-reference), too.

**Comment by ikkez** [comment]
fixed
