### ISSUE TITLE
Dynamic Route not work on Hosting

### ISSUE THREAD

**Issue by pmtpro** [bcosca/fatfree#1234]
Hello!

I really like fatfree, it really helps me a lot in my coding.

However, everything was fine until I put my product on Hosting.

Dynamic Route doesn't work as I expected, it always returns 404 error

My config:

`GET /@controller/@action = App\Controllers\@controller->action@action`
`GET /@controller = App\Controllers\@controller->actionIndex`

`GET / = App\Controllers\Home->actionIndex`

Only Home is working.

I also tried several other cases and only the latter worked
`
GET /Home/@action = App\Controllers\Home->action@action
`

**Comment by geniuswebtools** [comment]
Sounds like you didn't upload the .htaccess file to the server.

**Comment by pmtpro** [comment]
> Sounds like you didn't upload the .htaccess file to the server.

Sorry, but I already uploaded .htaccess. My .htaccess

```
RewriteEngine On

RewriteRule ^(app|dict|ns|tmp)\/|\.ini$ - [R=404]

RewriteCond %{REQUEST_FILENAME} !-l
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule .* index.php [L,QSA]
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
```

**Comment by geniuswebtools** [comment]
Is the server using Apache?
Is the apache modrewrite turned on?

**Comment by geniuswebtools** [comment]
Does the server require you to use the reweite base rule?
RewriteBase /

**Comment by pmtpro** [comment]
> Does the server require you to use the reweite base rule?
> RewriteBase /

yes, but the result is still the same

**Comment by ikkez** [comment]
when the hosts filesystem is case sensitive, also check the casing of file names. When you goto `/home` but the controller is named `Home.php` it may also fail.

**Comment by pmtpro** [comment]
> when the hosts filesystem is case sensitive, also check the casing of file names. When you goto `/home` but the controller is named `Home.php` it may also fail.

Thank you very much
After I renamed the file everything worked! ^^!
