### ISSUE TITLE
Internal Server Error  Invalid characters passed for attempted conversion, these have been ignored

### ISSUE THREAD

**Issue by ticariofis** [bcosca/fatfree#1237]
Hello there; I keep getting this error. There is no line number either. I don't know how to find the error.

php version : PHP 7.4.23 (cli) (built: Sep  7 2021 11:46:52) ( NTS )

this error :  [Thu Sep 09 09:42:04.972112 2021] [proxy_fcgi:error] [pid 1265427:tid 139716793435904] [client 192.168.4.234:0] AH01071: Got error 'PHP message: Invalid characters passed for attempted conversion, these have been ignored'

Internal Server Error

Invalid characters passed for attempted conversion, these have been ignored

the version I am using :
		PACKAGE='Fat-Free Framework',
		VERSION='3.7.4-Dev';
		
I'm waiting for your answer.

thank you.

**Comment by Rayne** [comment]
Please search for this error message with a search engine. I have my doubts that this issue is related to Fat-Free. Feel free to join our Slack (details on the website).

**Comment by ticariofis** [comment]
thank u..
