### ISSUE TITLE
POST,PUT,DELETE  requests method keeps returning 405 method not found

### ISSUE THREAD

**Issue by peterson-umoke** [bcosca/fatfree#1249]
I have been screaming at my computer for hours now. Everything seems to be done right, but i can't get any other method apart from GET requests to work.

**Comment by peterson-umoke** [comment]
Its keeps returning this error
`<!DOCTYPE html>
<html>

<head>
	<title>405 Method Not Allowed</title>
</head>

<body>
	<h1>Method Not Allowed</h1>
	<p>HTTP 405 (GET /contactz)</p>
	<pre>[vendor/bcosca/fatfree-core/base.php:1835] Base->error()
[index.php:16] Base->run()
</pre>
</body>

</html>`

**Comment by pauljherring** [comment]
You need to add the verb to your route. If none is specified, then it
defaults to just allowing GET.

$f3->route('GET|HEAD|*POST*|DELETE @sessions: /sessions',
'PJH\Page->sessions');

Or use map() if you're doing REST:
https://fatfreeframework.com/3.7/routing-engine#ReST:RepresentationalStateTransfer

**Comment by pauljherring** [comment]
Incidentally, this sort of question is better suited to the group, rather than raising an issue: 

https://groups.google.com/g/f3-framework
