### ISSUE TITLE
Please update the documentation to fix apache configuration

### ISSUE THREAD

**Issue by elieobeid7** [bcosca/fatfree#1250]
[This documentation](https://fatfreeframework.com/3.7/routing-engine#SampleApacheConfiguration), says:

You also need to set up Apache so it knows the physical location of index.php in your hard drive. A typical configuration is:

```
DocumentRoot "/var/www/html"
<Directory "/var/www/html">
    Options -Indexes +FollowSymLinks +Includes
    AllowOverride All
    Order allow,deny
    Allow from All
</Directory>
```

It should be

```
DocumentRoot "/var/www/html"
<Directory "/var/www/html">
    Options -Indexes +FollowSymLinks +Includes
    AllowOverride All
    Require all granted
</Directory>
```

**Comment by Hackmastr** [comment]
Depends on your Apache's version.
For 2.2 the old one should work.
For 2.4 the your suggestion works.

**Comment by Rayne** [comment]
Please create a PR for https://github.com/f3-factory/F3com-data.

**Comment by elieobeid7** [comment]
@Hackmastr No one uses 2.2 in 2022, I doubt it's available in any distro repos anyway.

@Rayne Okay will do.
