### ISSUE TITLE
parse() method doesn't work

### ISSUE THREAD

**Issue by olaulau** [bcosca/fatfree#1253]
Hi ;

executing the sample code from [the parse method](https://fatfreeframework.com/3.8/base#parse) simply doesn't work :

```
<?php
require 'vendor/autoload.php';

$f3 = \Base::instance();

$f3->parse('framework=f3 , speed=fast , features=full');
echo $f3->get('PARAMS.framework');  // 'f3'
die;
```

gives no result.

**Comment by Jonett** [comment]
It looks like the documentation is missleading on this one. 
Parse method does not assign hive variables, only retuns an array.

![kuva](https://user-images.githubusercontent.com/20566934/168398246-07fb6bd7-7b90-4097-bbeb-d06e282a182f.png)
![kuva](https://user-images.githubusercontent.com/20566934/168398370-443232da-a5cd-4cf5-9dc7-e4b6292037ce.png)

I got the expected results like this:
`
<?php
require 'vendor/autoload.php';

$f3 = require('lib/base.php');

$f3->set('PARAMS', $f3->parse('framework=f3 , speed=fast , features=full'));
var_dump( $f3->get('PARAMS'));  
die;
`
![kuva](https://user-images.githubusercontent.com/20566934/168398595-0fc988a9-a380-4848-815f-34591ba27ebe.png)


Hope this helped.

**Comment by Rayne** [comment]
@Jonett I was expecting the behavior you have tested but had not time to check it. Feel free to send a Pull Request updating the documentation at [f3com-data](https://github.com/f3-factory/F3com-data).
