### ISSUE TITLE
Mapper->load() fails if the first parameter is an empty array

### ISSUE THREAD

**Issue by paolobertani** [bcosca/fatfree#1257]
Mapper->load() calls stringyfy() passing the filter

on line 225 of db/sql/mapper.php

if (is_array($filter) )

doesn't check if $filter is an empty array. In that case the function produces an error trying to access $filter[0]

I suggest to change with

if (is_array($filter) && count($filter)>0)

**Comment by pauljherring** [comment]
You should pass `null`, if the filter is otherwise empty.

Because that's what's used if you specify nothing at all in the parens.
