### ISSUE TITLE
undefined array keys in php 8.1

### ISSUE THREAD

**Issue by eliargon** [bcosca/fatfree#1258]
Trying to run an f3 app (using version 3.8.0) with php 8.16 I am getting 
Internal Server Error
Undefined array key for.... ERROR, CLI, VERB  and other $hive[...] keys.
Using the suggestion of checking for isset($hove['key']) first, eliminate the first occurrence but then stop on the next one.

Any ideas on how to eliminate this?

**Comment by ikkez** [comment]
We need more information on this. Please reopen if problem still exists and give us some more information for reproducing the error. thanks.

**Comment by eliargon** [comment]
Thanks Christian, I reverted back to php 7.4.3 in order to eliminate the problem. I will try php 8.1+ in a couple of months, once I change the hosting server.
