### ISSUE TITLE
Dockerized

### ISSUE THREAD

**Issue by ranrinc** [bcosca/fatfree#1261]
Is there an example of setting up the right way for F3 + Docker?

**Comment by ikkez** [comment]
For development of the F3 core itself, we have a Docker setup right here https://github.com/f3-factory/fatfree-dev .. but this is not meant for hosting userland projects.
For own development or a production docker setup, you need to setup your own.. F3 doesn't need any special things, just a bare php image to function.
Check out http://devilbox.org/ and https://github.com/serversideup/docker-php as starting point for creating own containers.
