### ISSUE TITLE
'kz' locale trouble

### ISSUE THREAD

**Issue by diverdm** [bcosca/fatfree#1262]
When I use "kz.php" locale file (i.e. f3->set('LANGUAGE', 'kz' )), I get error "Undefined constant ISO::LC_kz". It is inside "Work around PHP's Turkish locale bug" block in f3's "base.php", line 1136. 
If I delete this block, it is OK, but should I ?

**Comment by xfra35** [comment]
This error is expected because there's no `kz` ISO 639-1 code.

See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

If you're trying to set the kazakh locale, the right code is `kk`.
