### ISSUE TITLE
Form data are not being parsed on patch

### ISSUE THREAD

**Issue by DaliborTrampota** [bcosca/fatfree#1264]
Hello,

after sending a patch request and getting 'PATCH' variable from f3, it is null, 'BODY' contains all the boundaries but thats unusable.
How can I parse the BODY into an array/object? And is there a reason why it is not parsed automatically?

Thanks

**Comment by ikkez** [comment]
Send the PATCH request as `application/json` and you'll be fine. Please use google board or find help in slack / matrix next time before opening an issue. thank you.
