### ISSUE TITLE
Named route incorrectly includes the extra @params in the route

### ISSUE THREAD

**Issue by aymanhs** [bcosca/fatfree#1270]
Using this latest build as of now.

I have this route rule:

`$f3->route('GET @user_edit: /users/@id',`

The route itself works fine.

However when I have this in the template:

`<a href="{{@ALIASES.user_edit}}/{{@user.id}}">`

The link it generates is `/users/@id/3`

The @id is incorrect.

**Comment by Blue3957** [comment]
That's expected behaviour, `{{@ALIASES.user_edit}}` resolves to `/users/@id`.

You want to use `<a href="{{ 'user_edit', 'id=' . @user.id | alias}}">`, as specified in [the documentation](https://fatfreeframework.com/3.8/routing-engine#Namedroutesintemplates)

**Comment by aymanhs** [comment]
Thank you!
May I say that this framework has restored my faith in php ;-)  It is an absolute joy to work with!
