### ISSUE TITLE
Tag `check` doesn't work if the `>` of the opening tag is on the next line.

### ISSUE THREAD

**Issue by cardinal-II** [bcosca/fatfree#1285]
The following code works:
`<check if="{{!@user}}">`

```
<check 
  if="{{!@user}}">
```

But these exampes don't:
```
<check if="{{!@user}}"
>
```
```
<check 
  if="{{!@user}}"
  >
```

I guess this is because the `>` of the opening tag is on the next line. That happens if you let your VS code format the code (ctrl + shift + i).

**Comment by ikkez** [comment]
thanks for reporting.

Fixed in latest commit https://github.com/f3-factory/fatfree-core/commit/d3108e1e56b0ae16769a30333c24a1a0dabb7b34
