### ISSUE TITLE
Invalid characters on url throw a 500

### ISSUE THREAD

**Issue by kurbanatabinen** [bcosca/fatfree#1287]
Hello :) 

In some case, if there is a %0A in url, fat free throw a 500.

Exemple : 

GET /api/users%0A

Return : ERROR 500: Invalid class \apis\users

The trace : 

[vendor/bcosca/fatfree-core/base.php:1401] Base->call()
[vendor/bcosca/fatfree-core/base.php:2388] Base->error()
[vendor/bcosca/fatfree-core/base.php:1922] user_error()
[vendor/bcosca/fatfree-core/base.php:1966] Base->grab()
[vendor/bcosca/fatfree-core/base.php:1793] Base->call()
Base->run()

**Comment by ikkez** [comment]
the error message looks correct to me.
