### ISSUE TITLE
Support for PHP8.4

### ISSUE THREAD

**Issue by teamayu** [bcosca/fatfree#1289]
Will FF3 ever be officially updated for PHP8.4? I have updated it myself (there aren't many files to update actually), so it seems an easy update to push?

**Comment by ikkez** [comment]
Feel free to create a pull request on https://github.com/f3-factory/fatfree-core if you have something to add. Some php 8.4 fixes were already made. The session handlers needs some more adjustments and will cause a breaking change. I need to check some other parts before getting this out of the door.
