### ISSUE TITLE
Minify removes the space following "and", which causes certain media queries not to work

### ISSUE THREAD

**Issue by ghost** [bcosca/fatfree#163]
The minify plugin takes this original CSS:

```
@media(min-width:768px) and (max-width:979px){body{background:green;}}
```

and minifies it to this (note the space removed after the "and"):

```
@media(min-width:768px) and(max-width:979px){body{background:green;}}
```

This causes the media query and any CSS rules within it not to take effect. When the space is preserved on both sides of the "and", then the media query works again. So, the minify plugin should try to maintain these spaces around "and" so that these media queries work.

Tested in Safari and Firefox.

**Comment by jordilondoner** [comment]
the same issue happens when using calc() css function, 
before minify : margin: 0 20px 0 calc(50% - 400px);
after minify: margin: 0 20px 0 calc(50%- 400px);
the fix for the above solution does not help in this case.

**Comment by bcosca** [comment]
Not too fast. That `-` surrounded by spaces is not indicative of a negative value. Hence the CSS is invalid.

**Comment by ikkez** [comment]
`calc` is indeed a function in CSS that accepts an expression and can do calculation. It's widely supported: http://caniuse.com/#search=calc
i.e. 
```css
.column-3-7 {
   width: calc(100% / 7 * 3);
}
```

**Comment by jordilondoner** [comment]
[yes I do](https://developer.mozilla.org/en-US/docs/Web/CSS/calc).
it is not a preprocessed language, it is vanilla CSS.

thanks
