### ISSUE TITLE
Set URL-Prefix for subdirectories

### ISSUE THREAD

**Issue by synthomat** [bcosca/fatfree#183]
Hi,

is there a way, to set some sort of prefix for REQUEST_URI? Unfortunatey I didn't find anything so I extended the base.php with this (dirty?) piece of code:

``` PHP
static function setURIPrefix($prefix) {
        $uri = $_SERVER["REQUEST_URI"];
        // replace just once!
        $r = substr_replace($uri, '', strpos($uri, $prefix), strlen($prefix));
        $_SERVER["REQUEST_URI"] = $r;
    }
```
### Example

(assuming you configured mod_rewrite with: RewriteRule .\* index.php [L,QSA])

When the application php-file is _/example/index.php_ and you want to use _/hello/world_ as your route (instead of _/example/hello/world_), you could do it this way:

``` PHP
$main=require_once 'lib/base.php';
$main->setURIPrefix("/example");

$main->route('GET /hello/world', function() {
   // ...
});
```

**Comment by dyslexicdrakness** [comment]
Either I'm not getting it or you're not getting it.

As far as I can understand this would apply to ANY situation when your app is not the root directory... which is fairly common. I for one am developing a separate app that should be installed alongside (in a folder, not the root) of another common cms and i'm having trouble trying to figure out the best fat free way of doing it... I understand it's a microframework but there should be a clear simple way of installing the app to a different folder that is not the root folder...

**Comment by xfra35** [comment]
> there should be a clear simple way of installing the app to a different folder that is not the root folder

Just move your code inside that folder, and you're set.

If you can't get it working, check your web server configuration. For example, in Apache you might need to enable the `RewriteBase` directive (see [.htaccess](https://github.com/bcosca/fatfree#sample-apache-configuration)).

**Comment by dyslexicdrakness** [comment]
Yeah no I got it working but I had to use this hideous {{@BASE}} on every url in the templates...

but it's ok I just wanted to know if there was a clean cool way of doing this, usually whenever I do something like this I learn later that F3 had a good solution for it, but it appears not this time....

Thanks!
> > there should be a clear simple way of installing the app to a different folder that is not the root folder
> 
> Just move your code inside that folder, and you're set.
> 
> If you can't get it working, check your web server configuration. For example, in Apache you might need to enable the `RewriteBase` directive (see [.htaccess](https://github.com/bcosca/fatfree#sample-apache-configuration)).

**Comment by xfra35** [comment]
Your issue is not directly related to the framework. You can solve it using the HTML `<base>` tag.
See https://fatfreeframework.com/3.6/views-and-templates#DocumentPaths

**Comment by dyslexicdrakness** [comment]
As I said, maybe I'm not getting something... I asked this over on the google group and they suggested the {{@BASE}} there...

If you use the ALIAS and your app is installed in a subdirectory of the root domain directory, then your URLS will be absolute (/xxcontroler) and you have to add the {{@BASE}} even if you use the <base> tag...

This would all work out if you declare routes as "controller" instead of "/controller".

**Comment by ikkez** [comment]
it's kind of true... the alias method always gives an absolute path with a leading `/`.. I mostly overwrite the alias filter method in templates to overcome this issue for me and use a simple `ltrim` to remove the slash... I've started a new v4 branch locally, where I already adjusted this behaviour.
