### ISSUE TITLE
STICKY: Use Google Groups for questions BEFORE submitting an issue

### ISSUE THREAD

**Issue by stevewasiura** [bcosca/fatfree#255]
we seem to have a recurring problem with questions and comments being posted in the GitHub Issues section, when they are not directly related to bugs in the code.

Please use Google Groups (https://groups.google.com/forum/?fromgroups#!forum/f3-framework) for questions and topics that are not directly related to fxing bugs in the code
![f3gg](https://f.cloud.github.com/assets/206041/125117/e927c874-6f09-11e2-8ed9-bdce0e640094.jpg)

(please consider leaving this issue open [sticky] for all to view when they are tempted to add an issue that is really a  question or opinion)

**Comment by sn0opy** [comment]
Since this is likely to appear on page 2 of the open issues, I'll just close it. -1 open issue.
