### ISSUE TITLE
Suggestion: Oauth3 integration

### ISSUE THREAD

**Issue by ram-you** [bcosca/fatfree#294]
It will be very interesting server and consmer integration within F3.
What do you think ?

**Comment by rafaelmoraissantos** [comment]
Hi @ikkez,
any thoughts on how to implement opauth? I've been struggling with this for a long time...

Thanks

**Comment by ikkez** [comment]
sorry i haven't implemented that anywhere so far. But there are certain examples and other framework integrations. There should be a way that works somewhere.

**Comment by ikkez** [comment]
regarding F3's OpenID 2.0 plugin: The unit test uses an auth test with google. That complains that google with stop to support OpenID 2.0 for Google-Accounts on 2015-04-20. They advice to migrate to OpenID Connect asap.

**Comment by bcosca** [comment]
I guess we have to move on to OpenID Connect soon. Deprecating the plugin for 3.4.1 is not an option anymore. It now becomes necessary.

**Comment by coolaj86** [comment]
http://oauth3.org

**Comment by ikkez** [comment]
> @rafamds commented on 10 Feb
> any thoughts on how to implement opauth? I've been struggling with this for a long time...

yes, finally. https://github.com/ikkez/f3-opauth
