### ISSUE TITLE
F3 promoting notices to errors?

### ISSUE THREAD

**Issue by 123Haynes** [bcosca/fatfree#542]
Hi,

i'm currently working on a Project where i have to use NET_LDAP2 of the PEAR framework as a component.
With the current Version of f3 this seems to be impossible.
Pear is quite old, so it generates several notices.
Normally that is no problem since i can disable them in the php.ini, but f3 treats notices as internal server errors even if they are disabled in the error_reporting.

Here is a very simple example for this behaviour:

```
<?php
$f3=require('../private/lib/base.php');

    if($foo == "") {
        $foo="weird";
                echo $foo;
    }
?>
```

Without f3 this will generate a notice that $foo is undefined, but it'll work.
With f3 this will trigger an internal Server error and the script will stop.

**Comment by jcrawford** [comment]
I am also having this issue after including the wordpress core into our F3 API.  I saw the fix suggested and tried that in my index.php file for F3 but it did not seem to work..  It is still using the F3 error handler and it is still promoting warnings from undefined indexes (in wordpress crappy plugins) to a fatal error and halting execution.

**Comment by xfra35** [comment]
F3 defines reporting as: `error_reporting((E_ALL|E_STRICT)&~(E_NOTICE|E_USER_NOTICE))`.

If you want to remove warnings as well, just add the following line after requiring base.php:
`error_reporting((E_ALL|E_STRICT)&~(E_NOTICE|E_USER_NOTICE|E_WARNING))`

**Comment by jcrawford** [comment]
That did not solve the issue, it is still promoting warnings up to be fatals.

[Mon Jun 08 19:19:41.792607 2015] [:error] [pid 9580] [client 71.181.125.154:61155] Fatal error: Undefined index: HTTPS, referer: http://staging.heytix.com/guestlist/

and that is on your own internal code

**Comment by jcrawford** [comment]
I have also tried the solutions found in this Google Group thread but they did not solve the issue of this happening either.

https://groups.google.com/forum/#!msg/f3-framework/UcPIWBd6vrU/kUcBY4dQioIJ

**Comment by ikkez** [comment]
Can you tell us the file and line where this happens? The only occurrence in the Base class for a `HTTPS` index is https://github.com/bcosca/fatfree/blob/master/lib/base.php#L2039, which already has a preceding isset check.

**Comment by xfra35** [comment]
That's a WP issue. Maybe [that one](https://wordpress.org/support/topic/plugin-wordpress-mu-domain-mapping-undefined-index-https-1).

The error_reporting is obviously overriden by WP. After [this article](https://codex.wordpress.org/Editing_wp-config.php), you could try to disable `WP_DEBUG`...

**Comment by jcrawford** [comment]
Ahh xfra35 you are correct we are including the WP core so it must lie there.  Thanks and apologies.

**Comment by kavin-90** [comment]
Other Framework those Error if there is an undefined variable or index so how to archive it with F3?

**Comment by ikkez** [comment]
set the appropriate error level with [error_reporting()](http://php.net/manual/de/function.error-reporting.php). If you want them all, set `error_reporting(E_ALL);` and the F3 error handler will trigger them.

**Comment by kavin-90** [comment]
Is not there any F3 solution?

**Comment by Rayne** [comment]
@kavin-90 You could create your [own error handler](http://fatfreeframework.com/quick-reference#ERROR). Details should be discussed on the [Google Group](https://groups.google.com/forum/?hl=de#!forum/f3-framework) or [gitter.im/F3Community/fatfree](https://gitter.im/F3Community/fatfree#).
