### ISSUE TITLE
Unable to access cache under certain circumstances

### ISSUE THREAD

**Issue by slifin** [bcosca/fatfree#629]
Due to how F3 works internally, if you include f3 separately on two parts of your website and then utilise the cache you cannot share cache instances between two parts of your site because F3 adds a prefix to every cache instance that is derived from $_SERVER['SERVER_NAME'] and $f3->get('BASE').

I propose that $this->prefix inside cache be user configurable to allow for cache sharing in unusual website configurations

**Comment by ikkez** [comment]
it's now configurable with the `SEED` var. https://github.com/bcosca/fatfree-core/pull/149
