### ISSUE TITLE
Documentation: document html formating 

### ISSUE THREAD

**Issue by 123Haynes** [bcosca/fatfree#662]
Hi,

i really like the feature introduced in this pull request: #550 
But so far this hasn't been documented anywhere in the docs. (Or at least i haven't found it)
As this is a really useful feature, we should make sure that new users can easily find it.
I'll probably create a Pull request for this in the coming days when i have time unless someone else beats me to it.

kind regards,
Haynes

**Comment by bcosca** [comment]
Hunting for easter bunnies?

**Comment by ikkez** [comment]
just spring-cleaning some dusty things ;)

**Comment by adaniello** [comment]
:)
