### ISSUE TITLE
Serious issues caused by an attempt to start new session, when it has already been started

### ISSUE THREAD

**Issue by stehlo** [bcosca/fatfree#673]
Hello Bong,

I strongly recommend to change all lines reading:
```php
@session_start();
```
With the following:
```php
if(!isset($_SESSION))
	session_start();
```

Reason for this:
When having a custom error handler, e.g. for specialised database operations, the changes to the F3's "SESSION" variable (e.g. via `Base::push()`, then via `Base::ref()` (lib/base.php, line 215)) cause premature interruption of this database operation, due to the error being thrown:

> 8, A session had already been started - ignoring session_start

I understand that it is tempting to save a few characters, but this situation is causing serious problems.

Thank you for considering this case.

**Comment by sam-at-github** [comment]
"cause premature interruption of this database operation, due to the error being thrown". @stehlo Can you explain further how exactly this causes an Error? Docs and my testing show multiple calls to session_start() causing non fatal E_NOTICE errors (unless of course you have PHP configured such that E_NOTICE is fatal), and returns true if a session exists or a new sessions is started, or false if not.

**Comment by stehlo** [comment]
@sam-at-github Should I indeed react to your comment, when you obviously don't understand even your own train of thoughts, not just my report?

**Comment by sam-at-github** [comment]
@stehlo Your right I don't understand. Could you please explain the error the change you requested more clearly? Your response is appreciated.

**Comment by stehlo** [comment]
@sam-at-github No. It is clear as it is [to everyone who needed to get it]. Thanks.

**Comment by sam-at-github** [comment]
Your a dick.

**Comment by stehlo** [comment]
@sam-at-github I shall refrain from calling you names, but I politely ask you not to comment on issues that have been already concluded by the project owner and are in waiting state for possible implementation. Thank you for understanding.

**Comment by bcosca** [comment]
Guys, let keep this discussion civil.

This request has been considered, but it is tabled for version 4 of the framework due to the PHP5.4 feature that is known to fix this issue. The following code in my opinion is really just a workaround due to 5.3's language deficiency:

```
if(!isset($_SESSION))
    session_start();
```

**Comment by stehlo** [comment]
@bcosca Thank you for the update. Very happy with your framework. Another donation coming soon.

**Comment by xfra35** [comment]
@sam-at-github to answer your question, I can see that the error reporting changed from 3.3.0 to 3.4.0:
```php
//3.3.0
error_reporting(E_ALL|E_STRICT);
//3.4.0
error_reporting((E_ALL|E_STRICT)&~E_NOTICE);
```
That probably explains the difference (E_NOTICE ignored in 3.4.0).

**Comment by Rayne** [comment]
As @bcosca introduced PHP 5.4 features to `fatfree-core` this issue is now resolvable.

**Comment by stehlo** [comment]
@Rayne Good morning, grandma. You're 20 months late.
