### ISSUE TITLE
Building a route from template

### ISSUE THREAD

**Issue by HwapX** [bcosca/fatfree#693]
example

```
    GET      @sample_route:           /sample/route/@id    = Sample->route
```

when i use `{{ @ALIASES.sample_route }}` i get `/sample/route/@id`
if i do`@PARAMS.id=5` the returns its the same.

i want something like reroute does `$f3->reroute('@sample_route(@id=5)');` redirect to `/sample/route/5`.

**Comment by rafamds** [comment]
Hi, sorry for digging this up. How to do it with php insted of fatfree templating.

**Comment by ikkez** [comment]
hi @rafamds.
with php do can do this with the new alias function: http://fatfreeframework.com/base#alias
`$f3->alias('sample_route','id=456');`
