### ISSUE TITLE
Template hash collision 

### ISSUE THREAD

**Issue by Kekec852** [bcosca/fatfree#702]
Hi,

I have notice hash collision when having a lot of templates first i thought it was outdated framwork (3.0.9-Release) so i update it to 3.3.0-Release.

This problem can be describe as framework is serving wrong cached file on request.

**Comment by xfra35** [comment]
While answering [this](https://groups.google.com/forum/#!topic/f3-framework/gVlQWibXhkA), I came to realize that `base_convert` could introduce collisions, even on a 64 bit platform.

Here's a quick test:
```php
$res=array();
for($i=0;$i<10000;$i++) {
  $str='a812ef423c73'.str_pad($i,4,'0',STR_PAD_LEFT);
  $base10=base_convert($str,16,10);
  $base36=base_convert($str,16,36);
  if (!in_array($val=$base10.' / '.$base36,$res))
    $res[$str]=$val;
}
foreach($res as $k=>$val)
  echo "$k => $val<br>";
```
After processing 10,000 different hex values (potentially resulting from the sha1 substring), it returns only 20 different values.

I'm writing this here for the record, as no one complained yet :P
