### ISSUE TITLE
using fat-free with composer

### ISSUE THREAD

**Issue by PavloPoliakov** [bcosca/fatfree#716]
Hi,

I've installed the fat-free with composer and found just one way to run the application for now:

``` php
<?php

require "vendor/autoload.php";

$f3 = require('vendor/bcosca/fatfree/lib/base.php');

$f3->config('application.cfg');
$config = $f3->get('config');

$f3->route('GET /', function($f3) use ($config) {
    $template = new Template();
    echo $template->render('templates/index.htm');
}
);

$f3->run();
```

The only thing which confuses me is the direct require of the base.php file.

Does anyone have any other suggestion how to run the application in more elegant way?

Any thoughts are appreciated.

Regards,

**Comment by kavin-90** [comment]
yes, that is not bug. because you're using it wrong.

correct is

`<?php`
`require_once("../vendor/autoload.php");`

`$f3 = Base::instance();`

`$f3->run();`

**Comment by daslicht** [comment]
If you are not already know, there is also a F3 freenode IRC channel, please join

**Comment by kavin-90** [comment]
My Dir Sturturtue.

app/
app/controller
app/dict
app/models
app/views/
app/tmp/
public/
public/css/
public/js/
public/img/
public/fonts
lib/
vendor/

index.php is in public folder.

<?php
require_once("../vendor/autoload.php");

$f3 = Base::instance();

$f3->config("../app/config.ini");
$f3->config('../app/routes.ini');

$f3->run();

**Comment by Phisherman** [comment]
You should add this to the "Getting started" guide.

`$f3 = Base::instance()` works like a charme.
