### ISSUE TITLE
Invalid parameter number: Columns Parameters are 1-based error on sql.php

### ISSUE THREAD

**Issue by yjiq150** [bcosca/fatfree#740]
$db->exec('UPDATE users SET name= ? WHERE user_id= ?', array($newValue, $user_id));

If I execute sql like this, it causes "Invalid parameter number: Columns Parameters are 1-based error". 
I found the cause of this error on framework's  "sql.php" file.

---
## $query->bindvalue($key,$val, $type=$this->type($val));

When it calls bindvalue(), the $key should be started from '1' (cause it is 1-based parameter). However $key value starts from 0.

I hope this could fix the bug.

**Comment by geniuswebtools** [comment]
I'm curious.  The issue people seem to have w/ this is the array starting with array key 1 for indexed arrays.  

Based on comments made in this duplicate issue: https://github.com/bcosca/fatfree/issues/853#issuecomment-124520217

The exec() method converts a single param to the 1 based array automatically.  Is it possible for the exec() method to detect if the array is indexed, and refactor the array to start at 1?
