### ISSUE TITLE
PSR-4 Autoloading

### ISSUE THREAD

**Issue by marxo** [bcosca/fatfree#741]
Is there a plan to make F3 compatible with PSR-4 autoloading. It does require namespacing, and I was wondering if anyone is able to work with PSR-4 now?

Thanks.

**Comment by sam-at-github** [comment]
@ikkez I don't think it is possible for fatfree to be PSR-4 or PSR-0 compliant because there is no "vendor" classname. [PSR spec](http://www.php-fig.org/psr/psr-4/) states:

> 1. The fully qualified class name MUST have a top-level namespace name, also known as a "vendor namespace".

**Comment by ikkez** [comment]
The autoloader itself is or can be PSR-X compatible. Maybe F3 lacks on having a vendor name, but when using F3 as application base, i don't see why it should be a problem to load vendor prefixed 3rd party libraries.

**Comment by marxo** [comment]
@sam-at-github I think that @ikkez is right, there shouldn't be a problem loading 3rd party libraries with the PSR-x compatible autoloader. The only thing that we're missing is loading the F3 itself as a module, but in terms of PSR-4 compatibility, that's only a matter of namespacing it, which is a trivial task I suppose.

**Comment by boussou** [comment]
btw 2/ states:
>  2/The fully qualified class name MAY have one or more sub-namespace names.
so the top level could be Fatfree. and having a sub-name is optional (MAY)
