### ISSUE TITLE
Return Json Header

### ISSUE THREAD

**Issue by mevsme** [bcosca/fatfree#756]
I'm making similar functionality as in [this article](https://github.com/bcosca/fatfree/wiki/AJAX-Form-Post-example) but instead of `$.post` i'm making `$.ajax`. Than in php file I'm doing `echo json_encode($response);` Header of response is `Content-Type	text/html; charset=UTF-8` so javascript see response as string but not Object. I need `JSON.parse(response);` to make my code working. How can I set header without need use template with custom header like in documentation (`$flow = $tmpl->render('widgets/tweeter-feeds.html', 'application/json', NULL, 300 ); // cache for 5 minutes`)?

**Comment by bcosca** [comment]
```
header('Content-Type: application/json');
echo json_encode(...);
```

Please use Google groups for Q&A. This issue tracker is for bug reports.
