### ISSUE TITLE
Improve version control history (for master)

### ISSUE THREAD

**Issue by sorbits** [bcosca/fatfree#761]
It would be nice if `dev` was merged into `master` via a (fast-forward) merge commit rather than squashing all commits deemed ready for release.

The reason is that if there are actual (non-squashed) commits on `master` it is much easier to audit what changes have gone into `master`. For example GitHub will show, for any commit, which release (tag) it is part of.

This isn’t purely academic, I have needed this several times in the past, and I’m only a casual user of the F3 framework. Sometimes the issue is that something has broken, and I want to figure out which commit broke it, other times a fix on `dev` seems to be missing in `master` even though the date of last release is later than the date of the fix having been merged.

**Comment by xfra35** [comment]
The framework core has been moved into a separate repository 2 months ago: https://github.com/bcosca/fatfree-core. Since then, you can track all commits there.

**Comment by sorbits** [comment]
@xfra35 I don’t see how that has helped, as new commits done to master are still squashed changes, but now from a different repository. So the history of `master` is still not useful.

The submodule is actually another thing I wanted to question, as the flow of a fix now seems to be:

1. `fatfree-core/master` receives the commit.
2. `fatfree/dev` receives an “updated submodules” commit.
3. `fatfree/master` receives a squashed commit of stuff from `fatfree-core/master`!?!

If I want to live on the cutting edge, I would use `fatfree-core/master`, but this repository is not compatible with [Composer](https://getcomposer.org/), so I have to use `fatfree/dev`, but that introduces a delay, e.g. right now I got bcosca/fatfree-core#16 merged, but it’s not in `fatfree/dev` yet.

Adding to this, it is very likely I want to point Composer to my own `bugfix` branch, this would now fork what? It seems I would fork both `fatfree-core/master` and `fatfree/dev`, the latter would be changed to point to my own `fatfree-core/bugfix` — now, whenever I want to rebase with upstream, I need to push commits to two different repositories…

**Comment by Rayne** [comment]
* Issue identifiers are ambiguous
* Changes to the core library with updated tests (not part of core) are out of sync

On the other hand it's nice to be able to checkout the core library without assets and tests. Unfortunately, there is no official `Composer` package for the core.

**Comment by sam-at-github** [comment]
AKAIK squashing commits and FF merge are two different things? I don't have an issue with squashing commit but they should be squashed in dev and master. But :+1: for:
 
* dev branch on bcosca/fatfree-core
* Getting the submodule change over bcosca/fatfree master done.
* More timely submodule updates in upstream - OK that is being picky:). Had a bit of a look for a post commit hook to do it but nothing came up.

"
Adding to this, it is very likely I want to point Composer to my own bugfix branch, this would now fork what? It seems I would fork both fatfree-core/master and fatfree/dev, the latter would be changed to point to my own fatfree-core/bugfix — now, whenever I want to rebase with upstream, I need to push commits to two different repositories…
"
@sorbits what fix are you proposing for that? If the code base is split into submodules, which is I think generally considered a good thing, there is no away around that? Is it a big deal anyway?

**Comment by sorbits** [comment]
> AKAIK 

What does that mean?

> squashing commits and FF merge are two different things? 

They are different, yes.

> I don't have an issue with squashing commit but they should be squashed in dev and master.

Squash all you want on `dev` to improve the history. Don’t _throw away history when you do a release_ is my point.

These are the 16 commits that made it to latest release: https://github.com/bcosca/fatfree/compare/3.3.0...3.4.0

The history there is not useful. Commit https://github.com/bcosca/fatfree/commit/b8f7277e8f7c29341c7b3d3b91e5c402ca275d20 has 4,028 additions and 1,544 deletions across 193 files.

What makes it worse is that `master` actually do see “real” commits, i.e. **not** (squashed) merges from `dev`. So are these fixes/improvements lacking from `dev`? There is no easy way to tell.

> @sorbits what fix are you proposing for that? If the code base is split into submodules, which is I think generally considered a good thing, there is no away around that? Is it a big deal anyway?

The fix I am proposing is to not use submodules. Why are they “considered a good thing”? I think most people agree that git submodules are cumbersome to work with, and it’s certainly not made easier by only having `dev` use a submodule, as we now need to manually format-patch/apply to move bug fixes from `fatfree-core` over to `fatfree/master` (rather than just cherry-pick).

I don’t want to sound too negative, fatfree is a great framework, but the way version control is handled is downright bizarre and counterproductive.

**Comment by sam-at-github** [comment]
@sorbits  AKAIK = As Kar As I Know. IMO the submodule in bcosca/fatfree pointing to bcosca/fatfree-core absolutely makes sense.

Thinking about it, I don't think it is even possible to keep the version history from fatfree-core in fatfree#master, while one is using a submodule and the other is not. I agree with @xfra35, see bcosca/fatfree-core for the version history, until master is updated to run a submodule too. The minor issue with that is the branching and tagging on fatfree-core is not there.

@sorbits Out of interest, why would you need to use bcosca/fatfree anyway? Why don't you just use bcosca/fatfree-core?

**Comment by sam-at-github** [comment]
"
If I want to live on the cutting edge, I would use fatfree-core/master, but this repository is not compatible with Composer, so I have to use fatfree/dev, but that introduces a delay, e.g. right now I got bcosca/fatfree-core#16 merged, but it’s not in fatfree/dev yet.

Adding to this, it is very likely I want to point Composer to my own bugfix branch, this would now fork what? It seems I would fork both fatfree-core/master and fatfree/dev, the latter would be changed to point to my own fatfree-core/bugfix — now, whenever I want to rebase with upstream, I need to push commits to two different repositories…
"
So the real issue being raised here is *"make fatfree-core compatible with composer"*? This should be raised in fatfree-core. Also it is compatible with Composer, just not with Packagist. I agree that would be nice to have.

**Basic composer.json for fatfree-core:**

    {
      "name": "test/test",
      "minimum-stability": "dev",
      "prefer-source": true,
      "require" : {
        "bcosca/fatfree-core": "master"
      },
      "repositories": [
        {
          "type": "package",
          "package": {
            "name": "bcosca/fatfree-core",
            "version": "master",
            "source": {
              "url": "https://github.com/bcosca/fatfree-core",
              "type": "git",
              "reference": "master"
            }
          }
        }
      ]
    }

**Comment by sorbits** [comment]
> So the real issue being raised here is "make fatfree-core compatible with composer"?

The issue I raised was the disconnect between `master` and `dev`.

Is `dev` a functional superset of `master`?

That should be easy to answer using `git`, but for this repository, it is not. It is also not possible to figure out what commits have made it into a release.

For the submodule, if I want to add my fixes to latest release, I still use `fatfree/master`, but when I want to submit a PR for a fix, then I normally rebase against `dev` (or cherry-pick). How do I do that with the submodule? Again, something that should be easy with `git`, but for this repository, it is not.

Maybe we are in a transition, if so, it would be nice to know what the end goal is, that is partly why I opened this issue, because we have gone from bad to worse, and I don’t know if @bcosca shares that assessment (and plan to improve things).

**Comment by ikkez** [comment]
I think the current constellation is:

* fatfree-core/master contains the real framework files
* fatfree/dev contains the unit test package and a submodule pointing to the core
* fatfree/master contains the release package and the core-files, i guess they were just copy&pasted from the core with adjusted doc headers each time on a release.

Basically i think it's a good idea to have a sub-module, so it should get easier to place that as own sub-module in your project. An additional composer config in there could be useful. But maybe some tags in the fatfree-core for each release would also be nice. That would make it easier to use it as a dependency in your own project, and then you wouldn't need to care about the fatfree package anymore.

I was sad that the version history got lost somehow when the sub-module was created, but there doesn't seem to be a way in git to copy that. I left a branch in my fork that still contains all references to the time before the submodule was made, to be able to use the git blame function, see https://github.com/ikkez/fatfree/blame/dev-3.3.1-ref/lib/base.php
If you compare, the blame of that file in the core repo is nearly empty https://github.com/bcosca/fatfree-core/blame/master/base.php
I'll let it stay there, since i also needed it for some change reviews.

**Comment by xfra35** [comment]
:+1: for the fork, really smart :sunglasses: 
I also found myself several times looking for the lost commit history. Now I know it's not completely lost :P

**Comment by bcosca** [comment]
If you take a look at the git log of the dev branch, all is not lost. The history goes back to:

Revision: f33a714
Author: Bong Cosca
Date: 2013-11-13 23:27:03
Bug fix: DB Exec does not return affected row if query contain subselect (Issue #437)

**Comment by ikkez** [comment]
and even beyond that!! see https://github.com/bcosca/fatfree/network
If you scroll back in time (hold down left-arrow-key), you'll find all commits back to version 2.0

**Comment by sorbits** [comment]
> I was sad that the version history got lost somehow when the sub-module was created, but there doesn't seem to be a way in git to copy that

This can be done: http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository/17864475#17864475

I too have been needing blame, so maybe worth rebasing the current commits on fatfree-core against a repository that has history.

As for a better setup, as implied above, I’m a little unclear about what the goal is, but I think there should be just one repository for the actual (core) library that third party applications would specify as a requirement (via composer). This repository would only need a `master` branch and then use release tags — that way `master` is the development branch, and tags point to “stable” releases. Using such scheme would also work better with GitHub, as viewing a commit on GitHub will show which release (tag) includes the commit, and the _Releases_ tab of GitHub lists all release tags and makes it easy to see history for each, how many new commits since latest release, etc.

Of course for experimental work, there could be short lived topic branches. But with release tags there is no need for a special `dev` branch.

For unit tests, if these are not desired to be included with the library, then these could be in their own repository and specified in the library’s `composer.json` via `require-dev` (no need for submodules).

If it is desired to also have a release with documentation then that could be the repository that adds the library as a submodule (pointing to latest release tag) — but I think it should be encouraged that users specify the fatfree requirement in their `composer.json`, and the repository with docs and the core library as a submodule does not need a `composer.json`.

Makes sense?

**Comment by sam-at-github** [comment]
@sorbits  :+1: for:
 * composer.json for, and history/tags rebuild on bcosca/fatfree-core.
 * composer based dep mangagement in bcosca/fat-free rather than submodule, in the long run.

I think the first one is the most important, will solve most of the issues raised, and can be done independently of proposed change in bcosca/fafree.

> Of course for experimental work, there could be short lived topic branches. But with release tags there is no need for a special dev branch.

I guess the only real advantage to have a master branch is it's easy to tell which is the latest stable, and I think its more conventional to have a master branch. I have no real preference though.

>For unit tests, if these are not desired to be included with the library, then these could be in their own repository and specified in the library’s composer.json via require-dev (no need for submodules).
>
>If it is desired to also have a release with documentation then that could be the repository that adds the library as a submodule (pointing to latest release tag) — but I think it should be encouraged that users specify the fatfree requirement in their composer.json ...

AFAIK holding unit tests and documentation is the primary purpose of bcosca/fatfree. I personally don't know about having tests in a separate repo. I guess it works. The branching a tagging scheme of fatfree should mirror that used in fatfree-core. Each release in fatfree will need either the composer.json, or git submodule updated. Given the role of bcosca/fatree don't think it's a major issue whether it's linked via composer or git submodule.

**Comment by bcosca** [comment]
Any pull request now that this issue has somewhat settled down?

**Comment by sorbits** [comment]
> Any pull request now that this issue has somewhat settled down?

Do you want to have the history preserved for fatfree-core? If so, a PR could be made for this.

Do you agree that users of composer should only be pointed to fatfree-core? If so, a PR could be made to move `composer.json` from fatfree → fatfree-core. Though without changing the name, I’m unsure how packagist will handle it. It would probably have been better to move docs/unit tests out of fatfree, so that this could still be the repository with the actual framework.

Do you agree to use release tags for releases (rather than copy/paste files around)? And is there somewhere we can find the commits corresponding to each previous release, so that release tags can be created for these? Though even with the info, I don’t think we can do a PR for this, would need to be collaborator.

How do yu want to handle unit tests? Does the `require-dev` solution work for you? Where are the unit tests currently?

**Comment by ikkez** [comment]
just a slight update
- [x] composer.json on fatfree-core
- [x] history rebuild on fatfree-core, fixed in bcosca/fatfree-core#26
- [ ] version tags on fatfree-core (will be added with the next release)

I think fatfree#master will stay a hand-crafted package with demo application, ready for download and drop-in. fatfree#dev, an app with all unit tests and a submodule to the fatfree-core. Unfortunately it seems not to be possible with github to track a branch in a submodule, only a commit. So just checkout the master branch on the submodule in your local clone to live on the nightly edge. We just update the submodule pointer from time to time and not with every commit.

This should sum this up. Anything left to consider here?
