### ISSUE TITLE
Template caching of cookie values

### ISSUE THREAD

**Issue by ajjjjjjjj** [bcosca/fatfree#763]
After upgrade from 3.3.1 to 3.4.0 serialized template cache still sometimes contain cookies (i.e. PHPSESSID).

**Comment by KOTRET** [comment]
? code or it did not happen...
please always provide enough informations and at best an example to reproduce the issue. You activated appending the sessionid to links by php?

**Comment by ajjjjjjjj** [comment]
My starting point is f3 boilerplate from [here](https://github.com/vijinho/f3-boilerplate).
Code is simple. I'm not doing anything fancy, as I use AngularJS to whole view logic:

```php
class Index extends Base {
    public function index($f3, $params) {
        echo \View::instance()->render('views/index.phtml');
    }
}
```

>You activated appending the sessionid to links by php?

No, no cookies are ever in URIs.

My app is using Facebook OAuth2 implementation for auth, with session created this way:
```php
public function authorize($f3, $params) {
		$client = new \OAuth2\Client(Auth::APP_ID, Auth::APP_SECRET);
		
		// ...
		if ($user) {
			@$f3->clear('SESSION');
			$f3->set('SESSION.user_id', $user->id);
			$f3->reroute('/#/whatever');
		}
```

Created cache file content:
```
a:3:{i:0;a:3:{i:0;a:9:{i:0;s:103:"Set-Cookie: PHPSESSID=here_is_the_cookie; path=/; domain=www.example.com; secure; HttpOnly";i:1;s:31:"X-Content-Type-Options: nosniff";i:2;s:27:"X-Frame-Options: SAMEORIGIN";i:3;s:32:"X-Powered-By: Fat-Free Framework";i:4;s:31:"X-XSS-Protection: 1; mode=block";i:5;s:40:"Expires: Tue, 20 Jan 2015 08:18:43 +0000";i:6;s:29:"Cache-Control: max-age= 86400";i:7;s:46:"Last-Modified: Mon, 19 Jan 2015 08:18:43 +0000";i:8;s:38:"Content-Type: text/html; charset=UTF-8";}i:1;s:3709:"<!DOCTYPE html>
<html>
<head>(...)
```

I'm going to check f3 sources next week, to better understand cache creation and hopefully find out what's going on.

**Comment by ajjjjjjjj** [comment]
So I finally managed to put some work on this and found out what was going on:

base.php:1426:
```php
if (isset($cache) && !error_get_last())
						// Save to cache backend
						$cache->set($hash,
							array(headers_list(),$body,$result),$ttl);
				}
```
F3 framework is putting any header in cache file.
Solution which removes all possible cookies:
```php
if (isset($cache) && !error_get_last()) {
						$headers = headers_list();
						foreach ($headers as $key => $value) {
							if (strrpos($value, 'Set-Cookie', -strlen($value)) !== FALSE)
									unset($headers[$key]);
						}
						// Save to cache backend
						$cache->set($hash,
							array($headers,$body,$result),$ttl);
					}
```

**Comment by KOTRET** [comment]
mhm, i'm not quiet sure how the header is set (by oauth? via your application?), but this definately looks like a bug. maye `$this->hive['HEADERS']` must be used instead of `headers_list()`?
Sorry that i cannot help, never used OAuth :(
@bcosca

**Comment by bcosca** [comment]
```
	$cache->set($hash,array(
		// Remove cookies
		preg_grep('/Set-Cookie\:/',headers_list(),
		PREG_GREP_INVERT),$body,$result),$ttl);
```
