### ISSUE TITLE
Use of http_response_code()

### ISSUE THREAD

**Issue by ameir** [bcosca/fatfree#764]
Since F3 3.4.0 was (per an email on the distro list) is said to be PHP 5.4+ compatible (although the README says otherwise), a good bit of code can be cleaned up in the library by using `http_response_code()` (http://php.net/manual/en/function.http-response-code.php).  This should help trim more fat, plus using native functions where possible is typically the best route.

**Comment by bcosca** [comment]
You may have made a mistake in interpretation. AFAIK, there was never a claim that 3.4.0 requires a minimum of PHP 5.4.

**Comment by ameir** [comment]
I referenced https://groups.google.com/forum/#!searchin/f3-framework/5.4/f3-framework/IuwlCpNvyMs/QrpYKXLpRlQJ for this, where it says:

`* PHP 5.4 will be the new minimum. 5.3 has already reached its end of life. No use beating a dead horse.`

No biggie; this can be revisited at a later time.

**Comment by bcosca** [comment]
Out of context. The topic was about 4.0, not 3.4.
