### ISSUE TITLE
Can't use aliases and tokens in the same route definition

### ISSUE THREAD

**Issue by incyclum** [bcosca/fatfree#765]
Hi,

I was stuck with an HTTP DELETE route. I expected the ability to use aliases and tokens
at the same time but I can't.

e.g:
````
POST @showtimes: /api/showtimes [ajax] = ShowtimeController->add
GET @showtimes [ajax] = ShowtimeController->getall
DELETE @showtimes/@id [ajax] = ShowtimeController->delete
````

In this example, the DELETE route leads to a 404 error.
I had to do a `DELETE api/showtimes/@id`.

**Comment by ikkez** [comment]
Yo missed the slash of the route definition. 
It's `DELETE /@showtimes/@id [ajax] = ShowtimeController->delete`

**Comment by incyclum** [comment]
I think you are right. Can't re-use route alias in routes definitions, only with templates. I made a mistake.

(first use of F3 for a final year project at my university)
