### ISSUE TITLE
mapper's 'insert' omits to specify some field-value pairs when adding record to db

### ISSUE THREAD

**Issue by paolobertani** [bcosca/fatfree#770]
On some circumstances an `insert` after a `load` omits to specify some field-value pairs when adding a record resulting in an error (if the missing field(s) must be non-null) or data not be stored properly.

I'll make an example to describe the "circumstamces"

I have a table with **objects** where fields are `id`, `shape`, `color` and `size`

The operation I need to perform is:
1) search for an object with given "shape" and "color"
2) update the "size" if the record exists, otherwise create a new record with the given "shape", "color" and "size".

```
if( ! $mapper->load(array('shape = ? AND color = ?', 'square', 'red')) ) {
    $mapper->shape = 'square';
    $mapper->color = 'red';
    $mapper->size = 10;
    $mapper->save(); // bad here
} else {
    $mapper->size = 10;
    $mapper->save(); // ok here
}

```
The problem arises when no records are found and the first code block of the `if` statement is executed.

Only `size` is in the sql `INSERT` statement, while no field-value pairs are given for `shape` and `color`.
It seems fields values are "saved" upon the `load` (even if no records are found) then assumed "unchanged" upon the `insert`.

This (at least to me) makes no sense as the operation to perform is an insert and all specified fields have to be passed even if "unchanged" from the field value requested on a previuos `load`.

A `$mapper->reset()` before the `save` fixes things.

---

I have this problem on a production server with PHP 5.5.5. DB engine is mySql.

Strangely I'm not able to reproduce it on my dev. machine with PHP 5.5.3

**Comment by adaniello** [comment]
Why not check the "dry state", as documentation suggest at http://fatfreeframework.com/databases?

**Comment by paolobertani** [comment]
Sorry, it was a bug in my code.

@adaniello 

You're right. Even better between `load`s and `save`s or between `save`s the mapper should be flushed with `reset`.
