### ISSUE TITLE
constant(): Couldn't find constant

### ISSUE THREAD

**Issue by onursa** [bcosca/fatfree#772]
hi,

When trying to use \DB\SQL\Mapper consistently get the following error:

<p><code>$news = new \DB\SQL\Mapper($this->db, 'news');</code></p>

<p>
<pre>
constant(): Couldn't find constant \PDO::PARAM_iNT

• web/lib/db/sql.php:316 constant()
• web/lib/db/sql/mapper.php:602 DB\SQL->schema()
• web/app/controller/news.php:14 DB\SQL\Mapper->__construct()
• web/lib/base.php:1422 Base->call()
• web/index.php:10 Base->run()
</pre>
</p>

**Comment by bcosca** [comment]
First, this doesn't look like the latest version of the framework.
Second, PDO::PARAM_iNT (notice the lowercase i) doesn't look like something the framework will produce (see line 327 of latest version of F3).

There's nothing we can deduce/conclude from the stack trace.

**Comment by Rayne** [comment]
It should be `\PDO::PARAM_INT` instead of `…iNT`. Which F3 version? The stable version enforces uppercase constants in `sql.php:316`: `strtoupper($parts[0])`.

**Comment by onursa** [comment]
It might be PHP based problem. When you write 'i' letter in Turkish, equals to 'İ' letter. I use PHP 5.6.5 and Fat-Free FW 3.4.0

<pre>
<code>
echo strtoupper('int');
// result: iNT
</code>
</pre>

When I had written <code>mb_strtoupper</code> it was fixed.

**Comment by Rayne** [comment]
Why did you close the issue? This appears to me as a serious locale based problem.

**Comment by KOTRET** [comment]
`I` `ı``İ` `i` converts vice versa to
`I` `I` `İ` `İ` because `strtoupper` depends on the locale.
converting back is even more complicated :grin:

This is a valid bug, `strtoupper` should be replaced with the `mb_`-equivalent

**Comment by xfra35** [comment]
Good catch :+1: 

I'd never have suspected that strtoupper was locale-sensitive. See phpfiddle [here](http://main.xfiddle.com/134dabc9/issue772.php).

**Comment by bcosca** [comment]
Then we have a problem with all usage of `strtoupper` if that's the case.

**Comment by xfra35** [comment]
I've been thinking about it too. But actually not all calls to `strtoupper/strtolower` are problematic. Only those where we expect an English string. For example, the `strtoupper` used in `$f3->camelcase` is fine, since it expects a string in the current locale.

**Comment by xfra35** [comment]
There could be a problem with the autloader, for example on Windows if we have a class named `INT` and the file is `int.php`.. but that really looks like an edge case.

I'd be interested in knowing if there are many languages with that kind of unusual case conversion.

**Comment by KOTRET** [comment]
another option is to explicitly set english locale for framework internal things...

**Comment by bcosca** [comment]
Windows is a case-insensitive OS, so I don't think that would cause any issues.

**Comment by KOTRET** [comment]
what about shifting the ascii value of the chars? ^^

**Comment by bcosca** [comment]
Nahh... bcosca/fatfree-core commit 15ceea4 ought to fix this

**Comment by KOTRET** [comment]
hehe :)
ps: pull before pushing or always rebase ;)

**Comment by bcosca** [comment]
I did. For some reason, rabbitvcs just froze. So I had to do the thing all over again with a force. Hence the jumbled history.
