### ISSUE TITLE
CSS Minify engine breaks the calc() function

### ISSUE THREAD

**Issue by jordilondoner** [bcosca/fatfree#773]
before minify :
``` margin: 0 20px 0 calc(50% - 400px);```
after minify: 
```margin: 0 20px 0 calc(50%- 400px);```

Ther was a very [similar issue](https://github.com/bcosca/fatfree/issues/176) but [the solution](https://github.com/ikkez/fatfree/commit/6d1623c16df5199aaebbbaa6c893de35037527f2) does not seem to be working on this case since in the mentiones example the espace is removed towards right and on my case it is towards left.

Please, can anyone provide a better way to deal with spaces in css? 
thanks

**Comment by bcosca** [comment]
Seems like this issue is not uncommon among [various](https://ajaxmin.codeplex.com/workitem/17110) [minifiers](https://github.com/yui/yuicompressor/issues/59).

**Comment by bcosca** [comment]
Let me know if we can close this now.

**Comment by jordilondoner** [comment]
True, but most of Less and Sass compilers offer a way to scape code. Is there any on this minifier tool? that would solve the issue also.
Calc function is not a minor matter in CSS, it is very used coding for smartphones, tablets, and also deskops, everywere basically in modern apps. Only certain 'old' 'minor' browsers don't support it...

thanks

**Comment by KOTRET** [comment]
the difference is: the other tools are preprocessors, F3 compresses regular code (maybe the result of preprocessors). So: no, there is no way to escape the code, as you could'nt deliver it without minification in this case. That makes no sense.

**Comment by jordilondoner** [comment]
Well actually makes quite a lot of sense to leave the calc function unminified, it needs to remain as it is in the unminified version, so yes, being able to scape that particular function would solve the issue. Anyway trying the solution above.

**Comment by jordilondoner** [comment]
calc function needs to remind in the minified file as it is in the unminified code, so it makes quite a lot of sense actually.

**Comment by jordilondoner** [comment]
The fix seems to work.
thanks a lot.

**Comment by KOTRET** [comment]
you did not read my answer: introducing an escaping mechanism does not make sense, since the source file will not work in browsers, instead the file is valid only when pushing it through F3 minification. This means you cannot use any other minification tools on the same file and cannot deliver the uncompressed file (for debugging purposes).

**Comment by bcosca** [comment]
@KOTRET I think he meant space, not escape.

**Comment by jordilondoner** [comment]
I see, thanks for the clarification.
