### ISSUE TITLE
MongoMapper problem with latest MongoDB (2.6.7) and latest Driver (1.6.1)

### ISSUE THREAD

**Issue by artakus** [bcosca/fatfree#776]
If you just load a single document, eg, 
```php
$col->load(array('_id' => 1))
```
You'll get empty result.
Take same look in source code, it seem problem lies in db/mongo/mapper.php:157
```php
$result=array();
while ($this->cursor->hasnext())
	$result[]=$this->cursor->getnext();
if ($options['group'])
	$tmp->drop();
```
Changing to below seem fixed the problem
```php
$result = iterator_to_array($this->cursor);
/*
$result=array();
while ($this->cursor->hasnext())
$result[]=$this->cursor->getnext();
 */
if ($options['group'])
	$tmp->drop();
```
And yes, there may be a better solution.

**Comment by francodgstn** [comment]
Hi, I've a similar problem with the load method of the Mongo mapper. I reported it on F3 google groups page https://groups.google.com/forum/#!topic/f3-framework/nqeQKQb3V7E

I tried your solution but for my problem it didn't work.

**Comment by KOTRET** [comment]
seems (http://php.net/manual/en/mongocursor.next.php)[MongoCursor::getNext()] returns null instead of an element. Please try to change `getnext()` to `next()`, getNext is an alias, maybe the implementation is incomplete?

PS: `iterator_to_array` is a nice "know your api" case :)

**Comment by KOTRET** [comment]
related to #781 this could be closed too?

**Comment by ikkez** [comment]
well if that is a driver problem, that could be fixed with a workaround like you said (switch `getnext()` to `next`) we probably should consider to rename that in the mapper for convenience if `next()` is backward compatible.

**Comment by ikkez** [comment]
i reviewed the mongo driver changelog. you're right. this was more a mongo driver issue. we don't need to touch anything here.
