### ISSUE TITLE
Markdown::instance()->convert() not converting tables 

### ISSUE THREAD

**Issue by rafaelmoraissantos** [bcosca/fatfree#777]
I'm using `Markdown::instance()->convert($file)` to convert a markdown file type, but when it is about tables, this don't work. 

Is there a bug or something, or could it be my code?

**Comment by KOTRET** [comment]
this is not the github markdown parser, tables are not part of the original markdown language.

**Comment by rafaelmoraissantos** [comment]
Oh ok, didn't know about that. Thanks
