### ISSUE TITLE
PDOStatement: You have an error in your SQL syntax

### ISSUE THREAD

**Issue by joseespinadote** [bcosca/fatfree#778]
Hi there!
I'm using F3 (last stable release, must be 3.4.0) on ubuntu 14.10, apache2 and mysql (installed from official repos)
I've this route on the index.php:
...
  $f3->route('POST /registro',
    function($f3, $params) use ($db){
      $reg=new DB\SQL\Mapper($db,'registro');
      $reg->copyFrom('POST');
      $reg->fecha=date("Y-m-d H:i:s");
      echo $reg->save();
    }
  );
...
It's a very simple POST route to insert a new "registro" at the DB.
When I test it using curl:
curl -X POST --data "nombre=jose&contrasena=qmail=email@email.com&dispositivo=qwerty" localhost/registro
The row is inserted with success, but as response, at curl, I recieve the following error

Internal Server Error
PDOStatement: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

The SQL log is the following:
150211 16:08:31    78 Connect   tkpuser@localhost on tokenpush
                   78 Query     SET NAMES utf8
                   78 Query     SHOW columns FROM `tokenpush`.`registro`
                   78 Query     INSERT INTO `registro` (`nombre`,`email`,`dispositivo`,`contrasena`,`fecha`) VALUES ('jose','email@email.com','qwerty','qwerty','2015-02-11 19:08:31')
                   78 Query     SELECT `registro`.`nombre`,`registro`.`email`,`registro`.`dispositivo`,`registro`.`contrasena`,`registro`.`fecha`,`registro`.`sistema` FROM `registro` WHERE
                   78 Quit
150211 16:08:39    79 Connect   root@localhost on
                   79 Query     select @@version_comment limit 1
150211 16:08:41    79 Query     SELECT DATABASE()
                   79 Init DB   tokenpush
                   79 Query     show databases
                   79 Query     show tables
                   79 Field List        alerta
                   79 Field List        apns_device_history
                   79 Field List        apns_devices
                   79 Field List        apns_messages
                   79 Field List        asociados
                   79 Field List        boton
                   79 Field List        correos
                   79 Field List        dispositivo
                   79 Field List        invitaciones
                   79 Field List        registro
                   79 Field List        users
                   79 Field List        usuarios
150211 16:08:42    79 Query     select * from registro

Why fails? and why it's doing the insert despite of the error?

Many thanks in advance

**Comment by bcosca** [comment]
Does the registro table have a **primary key**?

**Comment by joseespinadote** [comment]
Nop. [1]

I'll try with a auto incremental id

[1]
mysql> describe registro;
+-------------+--------------+------+-----+-------------------+-------+
| Field       | Type         | Null | Key | Default           | Extra |
+-------------+--------------+------+-----+-------------------+-------+
| nombre      | varchar(255) | YES  |     | NULL              |       |
| email       | varchar(255) | YES  |     | NULL              |       |
| dispositivo | varchar(255) | YES  |     | NULL              |       |
| contrasena  | varchar(255) | YES  |     | NULL              |       |
| fecha       | timestamp    | YES  |     | CURRENT_TIMESTAMP |       |
| sistema     | tinyint(4)   | YES  |     | NULL              |       |
+-------------+--------------+------+-----+-------------------+-------+
6 rows in set (0.00 sec)

**Comment by bcosca** [comment]
Then you can't use the mapper without the primary key. This is a requirement.

**Comment by joseespinadote** [comment]
Thanks man
