### ISSUE TITLE
Other data removed from session when it's set via $f3->mset()

### ISSUE THREAD

**Issue by oliverhermanni** [bcosca/fatfree#779]
By setting a Session via $f3->mset() all other data is removed from the session. Eg.

    $f3->set('SESSION.test', 12345);
    $f3->set('SESSION.alert_msg', true);
    $f3->set('SESSION.alert_text', $text);
    $f3->set('SESSION.alert_type', $alert_type);

works fine. But

    $f3->set('SESSION.test', 12345);

    $f3->mset([
        'SESSION.alert_msg => true,
        'SESSION.alert_textt => $text,
        'SESSION.alert_type => $alert_type
    ])

does not include 12345 after the mset.

**Comment by bcosca** [comment]
You're missing some quotes.

**Comment by KOTRET** [comment]
as the code does not work at all, there must be a parse error (3 single quotes in the code calling mset - open, close, open), so possibly just a typo here. Nevertheless i tested the code, it works as expected.
Hint: you can write
```php
$f3->mset([
    'msg' => true,
    'text' => $text,
    'type' => $type
],'SESSION.alert_');
```

**Comment by oliverhermanni** [comment]
Sorry, this was a typo late at night. If I had a parse error, I would have known. ;)

I'm at work and can't check my code right now. But I'm pretty sure, that the code _with_ closing quotes does not work either. I'll try the suggestion from KOTRET later.

**Comment by xfra35** [comment]
@oliverhermanni any update on this?

From your description, it looks as if you've typed:
```php
$f3->mset(['SESSION'=>[
  'alert_msg' => true,
  'text' => $text,
  'type' => $alert_type
]]);
```
In which case, the result was expected.
