### ISSUE TITLE
PHP input stream already open, cannot get PUT parameters

### ISSUE THREAD

**Issue by oguzgelal** [bcosca/fatfree#782]
Hello,

I'm trying to implement a RESTful api using F3 framework. I'm having trouble getting PUT request parameters.

Since PHP doesn't have a built in array that it populates for PUT parameters (like $_PUT as in $_POST), I have been trying to read the PUT parameters from PHP input stream. However there is a problem with that, I noticed that PHP input stream is already opened (therefor emptied) in lib/web.php on line 173. Here is that line :

```php
$src=@fopen('php://input','r');
```
The stream empties on this line and I cannot read PUT parameters. Is the any global variable that F3 populates with the parameters by any chance ?

Thanks,
Oguz

**Comment by ikkez** [comment]
Yes, it's `BODY` http://fatfreeframework.com/quick-reference#BODY

**Comment by oguzgelal** [comment]
@ikkez Oh right. Thanks a lot :+1:
