### ISSUE TITLE
Using vars in sub-template names

### ISSUE THREAD

**Issue by developer99** [bcosca/fatfree#785]
How come these two conventions work...

```
<include href="{{ @UI_HEAD }}" />
<include href="page_head.html" />
```

But this does not?  Seems like it should.
```
<include href="{{ @UI }}elements/page_head.html" />
```

The error is...

Fatal error: syntax error, unexpected 'elements' (T_STRING)

-- Actually turns out that I don't actually need it but would seems it should be doable.

Thanks for a great framework!

**Comment by ikkez** [comment]
a working syntax would be `<include href="{{ @UI.'elements/page_head.html'}}" />`

**Comment by developer99** [comment]
Yes.  I see that now.  But it seems this is inconsistent to the way variables are used in the view templates.  Unless I missed the syntax you mention as a documented method of doing it.  That is how I stumbled upon the issue.  I had been using {{ @UI }}elements/page_head.html throughout the view template and then used the same method to do an include and it didn't work.

**Comment by ikkez** [comment]
It depends on the implementation of each template directive (tag-handler). For the sake of simplicity, most of them allow you to have a static attribute value like `foo="bar"` or put a token into the attributes for dynamic variables `foo="{{@bar}}"` or expressions like `foo="{{ \Bar->baz() < 10 ? @narf : 5 }}"`. To make the result of such things somehow predictable and managable to implement in the tag handler, you should stick to one or the other method, but not mix it. You can of course add your static path to `@bar`, or use the string concatenation in building the token itself. The full token syntax can be found in the unit tests, right here: https://github.com/bcosca/fatfree/blob/dev/app/template.php#L133
Looks like that portion did not made it into the website docs yet.

**Comment by developer99** [comment]
Ok.  Thanks.  that seems reasonable.
