### ISSUE TITLE
Composer vendor/autoload.php fails to get required along with lib/base.php

### ISSUE THREAD

**Issue by oguzgelal** [bcosca/fatfree#786]
Hello,

I was trying to require the vendor/autoload.php file so that my composer packages could get autoloaded. However, I get an Internal Server Error telling me "Cannot redeclare Cache".

This is **index.php**, where I try the autoload:
```php
<?php
// INIT THE APP
require 'vendor/autoload.php';
$f3=require('lib/base.php');
$f3->config('config.ini');
$f3->set('AUTOLOAD','app/classes/');
// GLOBAL DB SETUP
$db = new DB\SQL('mysql:host='.$f3->get('dbhost').';port='.$f3->get('dbport').';dbname='.$f3->get('dbname'), $f3->get('dbusername'), $f3->get('dbpassword'));
$f3->set('db', $db);
// ERROR HANDLER
$f3->set('ONERROR', function(){ Error::sys_error(); });
// LISTEN FOR CONNECTIONS
$f3->run();
```

This is my **composer.json** file :
```json
{
	"name": "bcosca/fatfree",
	"description": "A powerful yet easy-to-use PHP micro-framework designed to help you build dynamic and robust Web applications - fast!",
	"homepage": "http://fatfreeframework.com/",
	"license": "GPL-3.0",
	"require": {
		"php": ">=5.3.6",
		"league/oauth2-server": "~4.1"
	},
	"repositories": [
	{
			"type": "vcs",
			"url": "https://github.com/bcosca/fatfree"
		}
	],
	"autoload": {
		"files": ["lib/base.php"]
	}
}
```

And this is the error I get :
```
PHP Fatal error: Cannot redeclare class Cache in /.../lib/base.php on line 2251
Fatal error: Cannot redeclare class Cache
```

Obviously this is because Cache class is being defined twice, somewhere in the composer classes and base.php but I think this was't supposed to happen. Is this a bug ? Or am I missing something ?

Thanks,
Oguz

**Comment by oguzgelal** [comment]
Never mind, I'll just use Slim Framework which has composer support. I liked this Framework, its a shame I can't get it to work with other composer packages.

@bcosca You should seriously consider making F3 available for composer and you definitely should use the power of Composer's autoloader. I understand you are trying to make an independent stand-alone framework but I don't think it will be that hard to make Composer an option for the devs.

**Comment by ghazispeakserve** [comment]
I use this framework with composer with some customisations. We really all wish this repository maintainer give us an ear, or two. The framework is excellent, some other things could be better if we see more effort on listening to us.

**Comment by rdiaztushman** [comment]
In your init script, change 
$f3=require('lib/base.php'); 
to 
$f3 = \Base::instance();

**Comment by oguzgelal** [comment]
@rdiaztushman Nope, didn't work.

**Comment by ghazispeakserve** [comment]
In this repository you can find a good example of using composer with f3 https://github.com/vijinho/f3-boilerplate
I will be happy to help

**Comment by oguzgelal** [comment]
@ghazispeakserve Using F3 autoloader for composers vendor directory seems like a good idea. Thanks for the example :+1: 

But still, composer has an autoloader just for that which might be more stable than this.

**Comment by ghazispeakserve** [comment]
What happens is that F3 autoloads composer dependencies for you instead of using composer autoload. I was not able yet to do better, my commercial project is ongoing we will see how much we can get far. I still repeat that F3 is lighweight, has a descent memory footprint and fast....but the maintainers have to give an ear or two...or three :smiley:

**Comment by oguzgelal** [comment]
@ghazispeakserve Agreed :+1: Perfect framework, needs improvements.

**Comment by sam-at-github** [comment]
> This is my composer.json file :

Erm, is that *your* composer file? Doesn't make sense.

**Comment by oguzgelal** [comment]
@sam-at-github Yes. The only difference from the one that comes with f3 is this line
```json
"league/oauth2-server": "~4.1"
```
I tried to install an OAuth library.

**Comment by sam-at-github** [comment]
If your trying to use fatfree with that it ain't gonna work. You can't take another module's composer file and use it as your composer file. They are different things. One describes the module, the other describes *your* module - your web app.

Also if your using composer I don't know what this line is about.

> $f3=require('lib/base.php');

**Comment by sam-at-github** [comment]
Try:

    {
      "name": "test/test",
      "require":
      {
        "bcosca/fatfree": "dev-master"
      }
    }

$f3 = \Base::instance();

**Comment by oguzgelal** [comment]
@sam-at-github I'm not trying load fatfree with composer, I'm only trying to load other composer packages that I have installed. I'm loading f3 as I'm supposed to, requiring the base.php file. The autoload is only for other composer packages. The problem is, they don't work alongside each other.

**Comment by sam-at-github** [comment]
Well then @rdiaztushman's suggestion should work. Otherwise, try:

 * Using composer to require fatfree.
 * Using require_once() not require().

**Comment by ikkez** [comment]
here is a little minimal setup to use fatfree with composer
https://github.com/F3Community/fatfree-composer-app
I hope this finally solves all the questions and hassle with composer ;)

**Comment by kavin-90** [comment]
You can use Composer when you know Composer how it works.

My Index.php

`<?php`
`require_once("../vendor/autoload.php");`

`$f3 = Base::instance();`

`$f3->config("../app/config.ini");`
`$f3->config('../app/routes.ini');`

`$f3->run();`
