### ISSUE TITLE
Question: HTML UI file permissions?

### ISSUE THREAD

**Issue by ChrisBAshton** [bcosca/fatfree#787]
When I go to http://127.0.0.1:8000/ui/layout.html, I would expect to get a 403 forbidden error, but as it is, I  see the HTML (and any embedded PHP is displayed rather than executed, which is as to be expected).

I know we shouldn't store sensitive PHP logic in the UI, but it seems odd that by default the UI directory is is publicly available (provided the user knows the path).

I tried chmod-ing the ui directory as per [this StackOverflow ticket](http://stackoverflow.com/questions/2096255/what-permissions-for-php-scripts-directories), to 0644 - which hides the HTML but stops F3 from working. I then tried 0755 but the HTML is viewable again. Is there another way around this that I've missed?

(If not, might be worth considering changing F3 to dynamically chmod the UI directory on the fly, to 0755 when rendering and then 0644 after rendering, to stop people from being able to view your HTML and embedded PHP.

**Comment by geniuswebtools** [comment]
You should handle this at the server level, not rely on the framework.  The quick fix would be to put a htaccess file in your UI folder and deny from all.  Or you could force a 403 error on any request for a .html? file in your ui folder.

**Comment by KOTRET** [comment]
agree with @geniuswebtools, additionally you should place your app data in a folder located in a subfolder of the parent of htdocs:

```
mydomain
┣━┳ /app
┃ ┣ /controller
┃ ┗ /ui
┣━┳ /f3
┃ ┗ base.php
┗━┳ /www (the public dir)
  ┣ /css
  ┣ /js
  ┗ index.php
```

**Comment by bcosca** [comment]
`.htaccess` file in your document root can also be used to accomplish what you want:

```
RewriteRule (\.(htm|ini|sql))$ - [R=403]
```

This prevents access to files with `.htm`, `.ini`, and `.sql` name extensions.

**Comment by ChrisBAshton** [comment]
Thanks for your responses.
