### ISSUE TITLE
Small request to SQL->schema

### ISSUE THREAD

**Issue by developer99** [bcosca/fatfree#788]
Can we add the FULL keyword to the SHOW COLUMNS command for MYSQL?

I am going to plant some other field meta data in the comments field that I would like access to.  I hope there is something like this in the other SQL drivers as well so this can be expanded for all of them.

Thanks.

David

**Comment by ikkez** [comment]
Hi. Do you really still need this? I made some quick google searches, for >sql table schema column comments< for some engines. The point is, that the way to query those comment fields (if there is such a comment meta field existing) is quite different and sometimes even more complex than just adding a `FULL` statement, like in mysql. Even if it would be theoretically possible to include such a comment meta field in the output array of the sql->schema method, it rather seems to add too much overhead if we think of all users who do not use this field. I could imagine to have a `meta` method that returns existing meta information to a table. That would probably be the more appropriate place to add this portion, which does not hurt the usual schema query performance and could be cached independently. What do you think?

**Comment by developer99** [comment]
Hi.  Yes, a separate method like it would work.  Then I guess it would be a unique return based on which SQL driver was queried.  Some return blank, some return what they can that is not part of SHOW COLUMNS or other existing methods that give back DB data.

I am basically doing data/form validation from the database schema already and thought why not add some more information to the database schema that my app could use to gain even more information about the fields (eg. field prompts for forms, understandable field names for error messages, etc.).

**Comment by ikkez** [comment]
I'm closing this, since this is more application specific and can be achieved by writing an own function that returns table meta data. If you have a generic solution to your request, feel free to reopen this issue again, but for now i see no reason to over-complicate working things. thanks ;)
