### ISSUE TITLE
Feature Request: Route Groups

### ISSUE THREAD

**Issue by sam-at-github** [bcosca/fatfree#789]
I keep on wanting to do this. Still not sure about it. Maybe I need to be educated. Proposal:

 * There is a default route group which is what you add routes to if you don't specify a route  group. nothing changes unless you define route groups in your route setup.
 * You can optionally start and end route groups. The only special thing about a route group is you can add before and after route handlers. Just limit to one handler, and use chain() to support more if you need it.
 * Duplicate routes are handled as per usual - take the first.

Example scenario:
```
  $f3->route('GET /', 'PagesController->home');
  $f3->route('GET /about', 'PagesController->about');
  $f3->beginRouteGroup('Auth');
  $f3->beforeRoute('POST /api/login', 'Auth->login');
  $f3->route('GET /videos/@id', 'VideoController->videos');
  $f3->endRouteGroup();
```
I think the currently accepted approach for the specific use case of auth is to do it in a parent class but that is a bit argh.

**Comment by KOTRET** [comment]
this feature looks very limited. As far i understood you want to add `AuthController->login` in beforeroute and if that fails reroute to `/api/login`?
I know many devs do not want to hear that, but maybe try annotations in PHP :grin:

**Comment by oguzgelal** [comment]
Actually there is this feature on other frameworks. For example in Slim Framework that I have recently switched to.

http://docs.slimframework.com/#Route-Groups

It lets you combine groups, but not with begin & end statements but with nested codes like this:
```php
<?php
$app = new \Slim\Slim();
// API group
$app->group('/api', function () use ($app) {
    // Library group
    $app->group('/library', function () use ($app) {
        // Get book with ID
        $app->get('/books/:id', function ($id) {
        });
        // Update book with ID
        $app->put('/books/:id', function ($id) {
        });
        // Delete book with ID
        $app->delete('/books/:id', function ($id) {
        });
    });
});
```

This would actually be a pretty powerful feature.

**Comment by KOTRET** [comment]
this does not look very portable... The Example you provided is exactly what the map-function does.

**Comment by xfra35** [comment]
@sam-at-github, an eventing system is on the wishlist for V4. So hopefully, it will provide a finer-grained control over route events (`beforeRoute` and `afterRoute`).

**Comment by sam-at-github** [comment]
@xfra35 Cool. Im not in still not entirely sure about it anyway. Just wanted to see how other felt.

**Comment by bcosca** [comment]
It's easier to write a parent class that doesn't have any before/afterroute for your special "route group".

**Comment by sam-at-github** [comment]
@bcosca  Your right, it is easier, and easy enough. Although I still don't like tying strategy to inheritance I think its being picky, and really, unavoidable in the long run. Closing this one.

**Comment by bcosca** [comment]
Strategy cannot exist in a vacuum.

**Comment by sam-at-github** [comment]
Use case: I have a set of json-rpc controllers, under /api/json/.  Currently they all extend JsonRpcController, which handles encoding the response. But "no such method" is a valid JSON-RPC error response. If some client class /api/json/user/29/nosuchmethod, I should return a JSON rpc error repsonse for "no such method". But since the end point is not mapped to a controller, no beforeRoute is ever called, no JSON-RPC error handling can be setup there. This mechanism could be used in such a situation.

Any suggestions on a better fix?

**Comment by ikkez** [comment]
yeah, use the ONERROR handler for errors. That's what it's used for.
