### ISSUE TITLE
Add cookie to curl options in Web _curl

### ISSUE THREAD

**Issue by ghazispeakserve** [bcosca/fatfree#791]
We need to send session id to the remote server, we have finished by adding 

```php
curl_setopt($curl, CURLOPT_COOKIE, "PHPSESSID=" . session_id());
```
Isn't it better to add a new $options entry named "cookie" like done for "follow_location", "max_redirects" and their sisters?

**Comment by ikkez** [comment]
I think to be compatible between the request engines, we should use the header option for setting cookies:

```php
$key = 'foo';
$val = 'bar';
$date = date("D, d M Y H:i:s",strtotime('1 January 2016')) . 'GMT';
\Web::instance()->request('http://www.domain.com/foo', array(
  'header' => array('Set-Cookie: '.$key.'='.$val.'; EXPIRES'.$date.';')
));
```

**Comment by ghazispeakserve** [comment]
The line I wrote is to keep same session ids across servers. Isn't it ok?

**Comment by ghazispeakserve** [comment]
Works perfectly. No need to extend the framework !!!

**Comment by ghazispeakserve** [comment]
Not giving the same result. When I use my code the PHPSESSID is correctly detected in the other side, but not when using @ikkez code.

**Comment by ikkez** [comment]
Can you please investigate what headers were being send that will cause your different result? I guess you maybe just need to add a domain or path argument to your set-cookie header. I don't think this method itself is not to blame.

**Comment by ghazispeakserve** [comment]
My server accepted this

```
  'header' => array('Cookie: '.$key.'='.$val.'; EXPIRES'.$date.';')
```

Cookie instead of Set-Cookie, what is the difference?
