### ISSUE TITLE
Issue with cache system

### ISSUE THREAD

**Issue by Zenohactagamat** [bcosca/fatfree#792]
Hi,

I recently discovered fatfree and the more I use it the more I love it ! This being my first time posting in such place, I hope I did things the proper way ^^

So about my issue, I'd want to now if anyone ever signaled having warning errors generated on page loading after activating the cache ? (didn't find that in the issue list)
It's nothing bad, but, well, no warnings at all would be better.

Here's how things goes after digging a bit (if you don't already know about that, hope this will help) : 
- My configurations :
  - local : wampserver 2 on windows 8
  - online : linux server hosted by 1and1

The problem happens on both.
  
- Warning examples :
```ini
Sat, 28 Feb 2015 14:44:41 +0100 [::1] "C:\wamp\www\site\lib\base.php : 1501","(Warning) file_get_contents(tmp/cache/0e3vp6g1xbj.0db0g2fyuf3.var): failed to open stream: No such file or directory"
Sat, 28 Feb 2015 14:44:41 +0100 [::1] "C:\wamp\www\site\lib\base.php : 1501","(Warning) file_get_contents(tmp/cache/0e3vp6g1xbj.0cm0h0x8lor.var): failed to open stream: No such file or directory"
```
I also tried with memcache and got the same problem :
```
<564 new auto-negotiating client connection
564: going from conn_new_cmd to conn_waiting
564: going from conn_waiting to conn_read
564: going from conn_read to conn_parse_cmd
564: Client using the ascii protocol
<564 get 0e3vp6g1xbj.0db0g2fyuf3.var
> NOT FOUND 0e3vp6g1xbj.0db0g2fyuf3.var
>564 END
564: going from conn_parse_cmd to conn_mwrite
564: going from conn_mwrite to conn_new_cmd
564: going from conn_new_cmd to conn_waiting
564: going from conn_waiting to conn_read
564: going from conn_read to conn_parse_cmd
<564 get 0e3vp6g1xbj.0cm0h0x8lor.var
> NOT FOUND 0e3vp6g1xbj.0cm0h0x8lor.var
>564 END
564: going from conn_parse_cmd to conn_mwrite
564: going from conn_mwrite to conn_new_cmd
564: going from conn_new_cmd to conn_waiting
564: going from conn_waiting to conn_read
564: going from conn_read to conn_parse_cmd
<564 get 0e3vp6g1xbj.0bo3ru7ion7.url
> FOUND KEY 0e3vp6g1xbj.0bo3ru7ion7.url
>564 sending key 0e3vp6g1xbj.0bo3ru7ion7.url
>564 END
```

Those are generated by Base::set right after my config file reads the parameter CACHE.
All the parameters read after CACHE will also generate a warning.

After adding a bit of info in Base::set, we get :
```ini
Sat, 28 Feb 2015 14:58:34 +0100 [::1] ========== Base::set ============
Sat, 28 Feb 2015 14:58:34 +0100 [::1] Base::set - key : eurocookie
Sat, 28 Feb 2015 14:58:34 +0100 [::1] Base::set - cacheexists : bool(false)
Sat, 28 Feb 2015 14:58:34 +0100 [::1] ========== Base::set ============
Sat, 28 Feb 2015 14:58:34 +0100 [::1] Base::set - cache load
Sat, 28 Feb 2015 14:58:34 +0100 [::1] Base::set - cache dsn : folder=tmp/cache/
Sat, 28 Feb 2015 14:58:34 +0100 [::1] Base::set - key : CACHE
Sat, 28 Feb 2015 14:58:34 +0100 [::1] "C:\wamp\www\site\lib\base.php : 1529","(Warning) file_get_contents(tmp/cache/0e3vp6g1xbj.0db0g2fyuf3.var): failed to open stream: No such file or directory"
Sat, 28 Feb 2015 14:58:34 +0100 [::1] Base::set - cacheexists : bool(false)
Sat, 28 Feb 2015 14:58:34 +0100 [::1] Base::config : app/config/routes.ini
Sat, 28 Feb 2015 14:58:34 +0100 [::1] ========== Base::set ============
Sat, 28 Feb 2015 14:58:34 +0100 [::1] Base::set - key : DB
Sat, 28 Feb 2015 14:58:34 +0100 [::1] "C:\wamp\www\site\lib\base.php : 1529","(Warning) file_get_contents(tmp/cache/0e3vp6g1xbj.0cm0h0x8lor.var): failed to open stream: No such file or directory"
Sat, 28 Feb 2015 14:58:34 +0100 [::1] Base::set - cacheexists : bool(false)
Sat, 28 Feb 2015 14:58:34 +0100 [::1] Base run
```

Of course we only get 2 warnings here because I put the CACHE parameter at the bottom of my config.ini

If someone knows how to fix that, he is welcome :)

**Comment by xfra35** [comment]
Hi @Zenohactagamat, can you clarify which version you're running and what's the code at line 1501 of base.php?

**Comment by Zenohactagamat** [comment]
Hi @xfra35,
I'm running the latest version (3.4)
As for line 1501 of base.php I have this
```php
	/**
	*	Read file (with option to apply Unix LF as standard line ending)
	*	@return string
	*	@param $file string
	*	@param $lf bool
	**/
	function read($file,$lf=FALSE) {
		$out=@file_get_contents($file);
		return $lf?preg_replace('/\r\n|\r/',"\n",$out):$out;
	}
```
Which is Config::read

**Comment by xfra35** [comment]
The framework makes use of the silent operator `@` to check if cache file exists.

In your case, the silent operator seems to be ignored (E_WARNING is raised instead of being silenced). So it could be something in your PHP configuration that forces all errors to be reported.

Can you check the values of `scream.enabled` and `xdebug.scream`? They should be disabled.

**Comment by KOTRET** [comment]
as the `@`-operator is somewhat dirty, maybe we should add a `is_readable($file)` instead of silencing?

**Comment by Zenohactagamat** [comment]
Both those values are inexistant in my php.ini, and they value false if I display them :) (on both local and server)

**Comment by xfra35** [comment]
What about `echo extension_loaded('scream')` and `echo extension_loaded('xdebug')`?

**Comment by Zenohactagamat** [comment]
Same, both false

**Comment by xfra35** [comment]
That's weird. Does it generate a HTTP 500 error?

Also can you check if it goes through the framework [custom error handler](https://github.com/bcosca/fatfree/blob/master/lib/base.php#L1849)? If yes, what's the value of `error_reporting()` at that place?

**Comment by Zenohactagamat** [comment]
Well, speaking of custom handler made me think of some code I put a while ago in my index.php to try having error display on my shared hosting, and so the warnings are displayed this way : 
```php
// Handling errors on 1and1 server
error_reporting(-1);
ini_set('display_errors',1);
$old_error_handler = set_error_handler('ServerErrorHandler::errorHandler');
```

My `ServerErrorHandler::errorHandler` justs uses the fatfree `Log` class and displays the warnings.

If those warnings are not a problem and shouldn't be displayed, then problem solved !

**Comment by xfra35** [comment]
Oh now I understand. Your error handler treats "silent" errors as normal errors. You should filter them out using `error_reporting`:

```php
function errorHandler($code,$text) {
  if ($code & error_reporting()) {
    //do something
  }
}
```

Anyway, the framework having its own error handler, I would advise not to override it and play with [ONERROR](http://fatfreeframework.com/quick-reference#ONERROR) instead.

**Comment by Zenohactagamat** [comment]
Thanks for the tip @xfra35, I put this code instead :) :
```php
// Handling errors on 1and1 server
$f3->set('ONERROR',
    function($f3) {
        $logger = new Log('error.log');
        $logger->write($f3->get('ERROR.text') . ' - '. $f3->get('ERROR.code') . ' '. $f3->get('ERROR.status') );
    }
);
```

**Comment by xfra35** [comment]
Yeah much better :P
