### ISSUE TITLE
mapper set 

### ISSUE THREAD

**Issue by hakanca** [bcosca/fatfree#793]
hi,

i created the following query

$this->news = new \DB\SQL\Mapper($this->db, 'news');
 $this->news->set('current_news_name',sprintf('news_name_%s', $this->f3->get('LANGUAGE')));
 $this->f3->set('news_list', $this->news->select(sprintf('news_name_%s AS current_news_name, news_photourl, news_date, news_seourl', $this->f3->get('LANGUAGE')), null, array('order' => 'news_id DESC', 'limit' => 3)));
        
how to call the current_news_name variable in the template?

**Comment by ikkez** [comment]
please use the [google board](https://groups.google.com/forum/#!forum/f3-framework) for questions.
if current_news_name is a field or virtual field, it usually should just be `{{@news_list[0].current_news_name}}` for the first record found.

**Comment by hakanca** [comment]
thank you @ikkez 
, sorry.

How do I use on the repeat group?

following code not work:
<repeat group="{{ @news_list }}" value="{{ @news }}">
{{ @news[0].current_news_name }}
</repeat>

**Comment by ikkez** [comment]
try this
```html
<repeat group="{{@news_list}}" value="{{@news}}">
  <p>{{@news.current_news_name}}</p>
</repeat>
```

**Comment by hakanca** [comment]
not work,

{{ var_dump(@news.current_news_name) }} => NULL

**Comment by bcosca** [comment]
This is not a bug. Your usage is simple incorrect.
