### ISSUE TITLE
$f3->config method

### ISSUE THREAD

**Issue by xmory** [bcosca/fatfree#794]
As I'm new in fatfree, when I use $f3->config, sometimes I get wrong while value add a space inadvertently. I think it is a common problem for beginners.

How about add a second parameter to trim value autoly?

Or even, trimming every value is default. If I want to get value with space, add quotes.

**Comment by ikkez** [comment]
Well, if you want to be precise, use quotes
```ini
foo = "bar"
foo = "bar "
foo = " bar"
```

**Comment by xmory** [comment]
Yes, I realize :)
As the user guide show codes without quotes, I missed it.
Thanks.

**Comment by xmory** [comment]
But, if I want to define an array like this:
arr = a,b,c
I can't add quotes,,which means a string. So I still have to pay more attention to delete nessesary space.
