### ISSUE TITLE
Problem in determining pdo_type with preg_match() in sql.php

### ISSUE THREAD

**Issue by nodesiremonk** [bcosca/fatfree#795]
In line#312-317 of ````sql.php```` file (i.e. in ````schema()```` function of class ````\DB\SQL````), the ````preg_match()```` function is used to determine the ````pdo_type````.  Basically any field type ending with "int" (such as "bigint") will be classified as ````\PDO::PARAM_INT````.

````
'pdo_type'=>
	preg_match('/int\b|int(?=eger)|bool/i',
		$row[$val[2]],$parts)?
	constant('\PDO::PARAM_'.
		strtoupper($parts[0])):
	\PDO::PARAM_STR,
````

Although I think 99.99% of time it should be fine, however, when I try to set one of my field type to something like ````enum("point", "paint", "joint", "print", "mint", "hint")````, it would be interpreted as "int" rather than "string", which leads the return value from SQL query always to be 0 after being processed by the ````value()```` function.

I am not sure if there is any solution for this problem.  In MySQL, you might be able to eliminate the problem by only looking into part of the "type" before the "(" sign.  In other words, just ignore everything after the "(" sign.  But I am not familiar with other SQL such as MSSQL, so not sure this change will cause new problem for other SQL database.

**Comment by ikkez** [comment]
`enum` field types are something esoteric for mysql. i.e. there is no enum in sqlite or mssql. since we use PDO and support all types of db engines, consider to simply use a varchar field or tinyint and map the values elsewhere.
