### ISSUE TITLE
Bug: framework errors ignored

### ISSUE THREAD

**Issue by xfra35** [bcosca/fatfree#796]
From 3.3.0 to 3.4.0, the error reporting has changed from `E_ALL|E_STRICT` to `(E_ALL|E_STRICT)&~(E_NOTICE|E_USER_NOTICE)`.

Now I can see that every call to `user_error` made by the framework is ignored, while previously it used to be shouted aloud and treated as a fatal error. (`user_error` raises `E_USER_NOTICE` by default)

**Comment by xfra35** [comment]
The bug has been introduced here: https://github.com/bcosca/fatfree-core/commit/ee11337f59fc2f1e7e29d0a6e42ad6a4b61392f3

**Comment by sam-at-github** [comment]
Isn't it just a default? Whats wrong with:

    require_once '.../fatfre-core.php';
    error_reporting(error_reporting()|E_USER_NOTICE|E_NOTICE);
    ...

**Comment by xfra35** [comment]
I can't believe that F3 defaults to ignoring its own errors ;)

**Comment by sam-at-github** [comment]
Well I default to ignoring my own errors all the time :). But also in code. For example I have a logger class with $logger->debug() logging method, but set the default log level to info, which makes $logger->debug()  a null op. If I want to see debug I set the log level lower. This is a pretty common pattern. I don't see the real difference here.

**Comment by bcosca** [comment]
Promoted all framework errors to E_USER_ERROR
