### ISSUE TITLE
Mocking HTTP requests containing $f3->reroute makes real reroutin

### ISSUE THREAD

**Issue by ghazispeakserve** [bcosca/fatfree#799]
When mocking HTTP requests containing ```$f3->reroute``` the framework does a real rerouting. Any way to avoid this?

**Comment by xfra35** [comment]
Yes! Meet the [ONREROUTE](http://fatfreeframework.com/quick-reference#ONREROUTE) hook :)

**Comment by ghazispeakserve** [comment]
Works fine for the case :smile:
