### ISSUE TITLE
Unit test the render content of a controller

### ISSUE THREAD

**Issue by ghazispeakserve** [bcosca/fatfree#800]
Is it possible to test the HTML content rendered by a controller?

**Comment by xfra35** [comment]
Yes, set `QUIET` to TRUE and read the value of `RESPONSE`.

**Comment by ghazispeakserve** [comment]
There is should review my F3 coding !!! Is there any documentation about that ```RESPONSE```? And how should I render my parsed templates? Using ```RESPONSE``` instead of echoing template like that ```echo Template::instance()->render(....```

**Comment by ghazispeakserve** [comment]
I see here http://fatfreeframework.com/quick-reference#RESPONSE that it says

The body of the last HTTP response. F3 populates this variable regardless of the QUIET setting.

But my RESPONSE is empty when I render a template !!!

**Comment by xfra35** [comment]
Don't change anything to your controller code, `echo $tpl->render()` is fine. If you're still stuck with it, please create a topic on [Google group](https://groups.google.com/forum/#!forum/f3-framework) as this repository is for bugs only.
