### ISSUE TITLE
load triggers called repeatedly

### ISSUE THREAD

**Issue by dexwerx** [bcosca/fatfree#801]
Not a major issue as it can be worked around by hooking an observer after the recordset is loaded. Ideally onload should only be triggered after the move to the first record. Maybe this behavior can be configured in a later version.

onload is also called twice for the last mapper after iterating through the recordset using next()...
it looks like the load trigger is called even when the cursor is dry.
\DB\SQL\Mapper::skip() should check $this->dry() similar to the way \DB\Jig\Mapper::skip() and \DB\SQL\Mapper::skip() checks $this->document.
```
349		if (!$dry && isset($this->trigger['load']))
350			\Base::instance()->call($this->trigger['load'],$this);
```

**Comment by ikkez** [comment]
I think this is intented behaviour. Whenever a query result row is mapped to the mapper object, this load hook is called, which is reasonable. Think of transforming values before assing them to the mapper or something else. Same would go for dry mappers. Maybe you'd like to add some default values to the mapper in the load hook when the mapper itself is dry?! If you have a hard time with while loops, load and next methods, maybe just use the [find](http://fatfreeframework.com/sql-mapper#find) method, which returns an array of mapper objects.

**Comment by dexwerx** [comment]
I can't really argue with that. that makes sense. I'll just adjust my trigger to check the special case of  a dry mapper

**Comment by ewesseloh** [comment]
I understand the intention of triggering the load event, whenever a **raw** dataset has been mapped to the mapper object. But what's the point of retriggering the load event on same and already transformed data? 
First of all this was a huge surprise for me to see load event triggering multiple times for the first dataset after load has been called.
Even bigger surprise was it to see that it has been retriggered for every (already processed) dataset in each new iteration.
So isn't there something wrong? Or do I have to mark my transformed data somehow, to be able to recognise that in repeated onload event?
And how can I safely determine whether onload event has been called by factory and contains single dataset, or onload has been triggered on a model with a query of multiple datasets?
