### ISSUE TITLE
\SQL\Mapper::count() - returns entire table count...

### ISSUE THREAD

**Issue by dexwerx** [bcosca/fatfree#802]
if the filter is not specified it should just return the count of the current records, or whatever filter was used to load the records? this would be in line with every other count() implementation, including the \DB\Cursor::count()

```
function count($filter=NULL,$ttl=0) {
        return $filter?parent::count($filter,$ttl):count($this->query);
	}
```

**Comment by ikkez** [comment]
There is [loaded](http://fatfreeframework.com/cursor#loaded) to get the count of the current loaded records.

**Comment by dexwerx** [comment]
My mistake.

**Comment by dexwerx** [comment]
I actually use loaded in my user model not sure why I missed it this time. Thanks

**Comment by Phisherman** [comment]
Shouldn't this be added to the docs?

**Comment by ikkez** [comment]
It's here: http://fatfreeframework.com/cursor#loaded
