### ISSUE TITLE
Error with PHP 6.2.1 HTTP Raw Post

### ISSUE THREAD

**Issue by santhoshvkumar** [bcosca/fatfree#804]
Error while running in PHP 6.2.1

Fatal error: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead.

What's the exact solution for this I tried to change it in php.ini. But still facing the error.

Regards,
SK

**Comment by xfra35** [comment]
F3 doesn't use `$HTTP_RAW_POST_DATA` and rely on `php://input` instead (cf. the [BODY](http://fatfreeframework.com/quick-reference#BODY) variable).

So the problem is in your PHP config. (don't forget to restart Apache after modifying php.ini)
