### ISSUE TITLE
"Web->receive" can not handle complex arrays of file fields

### ISSUE THREAD

**Issue by HwapX** [bcosca/fatfree#806]
When a complex field like `slides[1][background]` is sent the method `Web->receive` fails with the following error message `basename() expects parameter 1 to be string, array given`.

**Comment by xfra35** [comment]
I also noticed that bug:
* a file named `foo[]` works
* a file named `foo[bar][]` doesn't

**Comment by xfra35** [comment]
It should be fixed now. See https://github.com/bcosca/fatfree-core/commit/9415af589adf095bf4f8aca3bee0c9706ac0d7f6
