### ISSUE TITLE
table name quotation produces incorrect syntax in MSSQL 2012

### ISSUE THREAD

**Issue by d3m3tr1s** [bcosca/fatfree#807]
Hello, I have discovered that this line

https://github.com/bcosca/fatfree/blob/master/lib/db/sql.php#L393

Produced quotation for tables names which is not acceptable by MSSQL 2012 and produces sql syntax error.

I.e. table name Clients or dbo.Clients or [dbo].[Clients] would bring results

'Clients' , 'dbo'.'Clients' ,  '[dbo]'.'[Clients]' , any of those is wrong syntax at least in MSSQL 2012

I connected to mssql server using 'dblib'

**Comment by xfra35** [comment]
What's the exact error? What makes you think that brackets are rejected?

The docs (MSSql 2008/2012/2014) say that double quotes may be used as delimiters *only* when `QUOTED_IDENTIFIER` is enabled, while brackets are always valid.

**Comment by d3m3tr1s** [comment]
Sorry, I didnt mean that brackets rejected, I meant single quotes are rejected.

Line that I have pointed encloses with single quotes, instead of double quotes

$key="'".implode("'.'",explode('.',$key))."'"

works:
select * from Clients
select * from dbo.Clients
select * from [dbo].[Clients]
select * from "dbo"."Clients"
select * from "Clients"

does not:
select * from 'Clients' - Incorrect syntax near 'Clients'.
select * from 'dbo'.'Clients' - Incorrect syntax near 'dbo'.
select * from '[dbo]'.'[Clients]' - Incorrect syntax near '[dbo]'.

**Comment by xfra35** [comment]
Ah ok, well I guess that the delimited identifier for `sybase|dblib` should be the same as for `mssql|sqlsrv|odbc` then. [Sybase docs](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc32300.1570/html/sqlug/X86464.htm) say that brackets are perfectly valid.

**Comment by ikkez** [comment]
looks good. :+1:
