### ISSUE TITLE
View instance cannot render template

### ISSUE THREAD

**Issue by dreammakr** [bcosca/fatfree#808]
The shortened version to render a template does not seem to be working.

Using PHP v5.5.3

```
echo View::instance()->render('template.htm');
```

**Comment by Rayne** [comment]
Which `F3` version are you using? Is your `UI` path correct?

**Comment by dreammakr** [comment]
Argh! Disregard.

Seems to be working now. Was getting message that it could not find template earlier. Switched to long version and it worked. Just switched back to verify and it's still working. *shrug*
