### ISSUE TITLE
MySQL view with group by fails

### ISSUE THREAD

**Issue by FrankOssie** [bcosca/fatfree#809]
When using a group by on a view the query failse because there are no primary keys in a view

**Comment by bjornbos** [comment]
That is, using the group parameter in a load using the db mapper. For example:

    $mysqlView->load(array('color=:color', array(':color' => $color)), array('group' => 'shape'));

**Comment by bcosca** [comment]
Use `find()` instead of `load()`.

**Comment by bjornbos** [comment]
Unfortunately, find() generates exactly the same error

**Comment by ikkez** [comment]
Can you clearify the error? Which exact error message you get? Is that a badly build SQL query or something the mapper itself complains about? Check this issue: https://github.com/bcosca/fatfree/issues/805 and its solution. Maybe this already solves your problem as well. Would be nice if you can tell us about it ;)

**Comment by bjornbos** [comment]
The problem is that the GROUP BY does not work for views without primary keys. This commit fixes the problem for us: https://github.com/SoSocio/fatfree/commit/54314ed95bb1e403d704972ac74515ba30a18933

**Comment by ikkez** [comment]
The current nightly libs already use a completely different approach, which probably fixes your issue https://github.com/bcosca/fatfree-core/blob/master/db/sql/mapper.php#L225

**Comment by bjornbos** [comment]
Thanks, that will probably fix the issue as well. We'll use our custom fix until the new version is released.
