### ISSUE TITLE
Virtual Fields in SELECT

### ISSUE THREAD

**Issue by joedub** [bcosca/fatfree#812]
After getting assistance here

https://groups.google.com/forum/#!topic/f3-framework/jlvgoJ3I2OE

with using an alias in select(), I was shown how to properly do this with find() by first defining a virtual field. My code then worked.

I then tried to modify the code using select() instead of find() and it did not work. The select() query results (which I pass to an html document) did not return the field as it did with find(). But it did NOT result in a server error that occurs if attempting to reference a non-existent virtual field.

Related to this, please note that the documentation shows the select() example as follows:

select(
    'foo, bar, MIN(baz) AS lowest',
    'foo > ?',
    array(
        'group'=>'foo, bar',
        'order'=>'baz ASC',
        'limit'=>5,
        'offset'=>3
    )
);

Thus it uses "lowest" as a "virtual field" without defining it first. (Regardless, I did define the "virtual field" in select() just as with find()).

I really want to use select() as it is a bit more intuitive and especially because it returns the desired columns instead of all columns in the table.

Sorry if I am trying to implement this incorrectly, but at this point it does look like a bug in select(), Please see the groups links for additional details.

**Comment by xfra35** [comment]
`find()` is a wrapper for `select()` which automatically sets the field list according to the mapping definition. So:
```php
$mapper=new DB\SQL\Mapper(...);
$mapper->set('lowest','MIN(baz)');
$mapper->find($filter,$options);
```
is exactly the same as:
```php
$mapper=new DB\SQL\Mapper(...);
$mapper->set('lowest','MIN(baz)');//mandatory!!
$mapper->select('*,MIN(baz) AS lowest',$filter,$options);
```
In any case, the 2nd line can't be omitted, as it is part of the mapping definition and as `select()` ignores any non-mapped column.

I think the confusion comes from `select()` being public, while its purpose is obviously internal. 

@ikkez @bcosca Shouldn't we declare it as protected instead?

**Comment by joedub** [comment]
Thanks, things are working now. No bug.

**Comment by ikkez** [comment]
If you are just about to limit the fields returned while using find, you can use the 3rd constructor argument to limit the active fields:

```php
$mapper=new DB\SQL\Mapper($db,$table,'foo,bar');
$mapper->set('lowest','MIN(baz)');
$mapper->find($filter,$options);
```

We could think about moving the appropriate adhoc loop directly into the select method. https://github.com/bcosca/fatfree/blob/master/lib/db/sql/mapper.php#L298
