### ISSUE TITLE
language() call accepts only specific language codes

### ISSUE THREAD

**Issue by dmig** [bcosca/fatfree#814]
Currently, `Base::language()` accepts only 'en-US' parameter value, which isn't obvious and not described in documentation.

Considering that LANGUAGE hive var is initialized from `Accept-Language` header, which often contains 'en_US' values, this is a bug.

I suggest modifying regexp in https://github.com/bcosca/fatfree/blob/master/lib/base.php#L897 to `/^(\w{2})(?:[-_](\w{2}))?\b/i` to fix the issue.

**Comment by xfra35** [comment]
[HTTP/1.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4) does specify hyphen as a separator.

You should simply set `LANGUAGE` instead of calling `language()`. See [here](http://fatfreeframework.com/base#language).
