### ISSUE TITLE
Bug in Match routes against incoming URI

### ISSUE THREAD

**Issue by amard** [bcosca/fatfree#815]
if user type a double backslash or slash for the URI the F3 encountered an Internal Server Error.
```
for example :

    domain.com//user-data 
   
Result : 

Internal Server Error
Undefined index: path

```
this can be fixed in BASE class line 1343 by replacing "//" to "/" for $this->hive['URI'] or checking that 'path' index was set in line 1367.
```
$req=preg_replace(
			'/^'.preg_quote($this->hive['BASE'],'/').'(\/.*|$)/','\1',
			$this->hive['URI']
		);
```

Thanks

**Comment by Rayne** [comment]
This problem should be fixed in the development branch.

**Comment by ikkez** [comment]
It is. please re-open if the problem persists.
