### ISSUE TITLE
select method in sql mapper does not cover case of query via dblib driver with limit/offset option

### ISSUE THREAD

**Issue by d3m3tr1s** [bcosca/fatfree#816]
Hello, I'm using dblib driver to connect to MSSQL server, MSSQL does not support LIMIT operator, and using it in query as option produces error.

https://github.com/bcosca/fatfree/blob/master/lib/db/sql/mapper.php#L234

Here you have covered other drivers but no dblib, also dblib does not have $db->version() method implementation in the current version, so it should be added, or separate case added to generate proper query for dblib driver usage.

**Comment by xfra35** [comment]
Do you mean that we should change line 234 to `if (preg_match('/mssql|sqlsrv|odbc|dblib/', $this->engine)`?

> also dblib does not have $db->version() method 

The `version()` method is not coming from PDO. It's a simple `$this->pdo->getattribute(\PDO::ATTR_SERVER_VERSION)`. Do you get an error message when you call `$db->version()`?

**Comment by d3m3tr1s** [comment]
Yes, when I added dblib there like you said, 

preg_match('/mssql|sqlsrv|odbc|dblib/ ...

I was getting error 

$db->version() - method does not exist

**Comment by ikkez** [comment]
dblib is oldschool. Try to use one of the other drivers (sqlsrv,mssql,odbc) instead.

**Comment by d3m3tr1s** [comment]
Thank you, I would definitely do that when I'm able to pick an environment myself, for now, I have to work with what is given.

**Comment by xfra35** [comment]
> $db->version() - method does not exist

Are you sure it's `version()` which is not found? I'd rather expect `pdo->getattribute()` not to be found...

**Comment by ikkez** [comment]
If the version attribute is not found (not implemented) in the used PDO driver then it becomes tricky. Well maybe we could fallback to SQL Server 2012 behaviour in general. What type of sql is it, that you need to use? Maybe you can also ask the hosting provider to install updates or other pdo drivers, when you tell them that it would be better for all.

**Comment by xfra35** [comment]
> Well maybe we could fallback to SQL Server 2012 behaviour in general

I thought about it too, but in the code we make a distinction between `OFFSET x ROWS` and `OFFSET x`. The first syntax is for the newest SQL Server. What's the second syntax for?

**Comment by d3m3tr1s** [comment]
I use SQL Server 2012, but i think its more about what your code is going to support and what isn't , than about my specific environment. I picked it, as i found it has dblib driver support, its appeared to be partial, for my personal needs I just have added separate condition for dblib as you have for 2012 server without checking db version, though, that was just quick custom patch.

**Comment by xfra35** [comment]
> i think its more about what your code is going to support

You're right about it.

Could you just help us clarify where the code fails on your setup? Is it that `pdo->getattribute()` is not supported? or the specific `PDO::ATTR_SERVER_VERSION` attribute? You could run this simple code:
```php
$db=new \DB\SQL(...);
echo $db->pdo()->getattribute(\PDO::ATTR_DRIVER_NAME);
echo $db->pdo()->getattribute(\PDO::ATTR_SERVER_VERSION);
```

**Comment by d3m3tr1s** [comment]
I'm sorry you are right the error is from 

getattribute(parent::ATTR_SERVER_VERSION)

call

PDO->getAttribute(4)

**Comment by xfra35** [comment]
From the [source code](https://github.com/php/php-src/blob/master/ext/pdo_dblib/dblib_driver.c#L288), it looks like `getattribute()` is not implemented at all.

@d3m3tr1s does `$db->pdo()->getattribute(\PDO::ATTR_DRIVER_NAME)` return `dblib`?

**Comment by d3m3tr1s** [comment]
Yes, sure, the result of ```$db->pdo()->getattribute(\PDO::ATTR_DRIVER_NAME)``` call  is ```dblib```

**Comment by xfra35** [comment]
Ok now I understand: that's because [PDO](https://github.com/php/php-src/blob/master/ext/pdo/pdo_dbh.c#L850) handles itself generic attributes like `ATTR_DRIVER_NAME`.

Then if we want to keep support for dblib, looks like we should:
* prefix the call to `getattribute()` by `@` in `$db->version()`
* include `dblib` in the MS SQL [loop](https://github.com/bcosca/fatfree/blob/master/lib/db/sql/mapper.php#L234)
* fallback to latest MS SQL syntax if  `$db->version()` returns nothing

That would provide support for dblib offset/limit on MS SQL >= 2012.

@ikkez what do you think?

**Comment by ikkez** [comment]
Well I think, maybe we should drop dblib support :laughing: even the PHP docs itself warn about using it and call them "ancient" http://php.net/manual/en/ref.pdo-dblib.php I guess getting the version attribute is not the only thing that is not implemented. Nevertheless, your approach to this fix looks good, but it feels wrong to fix driver issues in the framework layer (something that simple like the version number). We can patch this slight glitch, but if more rocks appear on the road, I would advice to take the highway :)

**Comment by xfra35** [comment]
I agree. [Latest](https://pecl.php.net/package/PDO_DBLIB) release is from 2005!

**Comment by bcosca** [comment]
@ikkez: +1
