### ISSUE TITLE
Problem with UTF-8 when select from database

### ISSUE THREAD

**Issue by sajaddp** [bcosca/fatfree#817]
Hello,
When i select data from database my result is "??????"  ):
![capture](https://cloud.githubusercontent.com/assets/3147493/7071795/e8e93e82-defc-11e4-980f-30600416c61c.PNG)

how i can fix it?
it's my function:
```
	function GetPost($f3, $args)
	{
		$db = $this->db;
		$result = $db->exec(' SELECT * FROM oc_post,oc_user WHERE oc_post.user_id = oc_user.ID ORDER BY oc_post.ID DESC; ');
		$f3->set('post', $result);
	}
```
and it's my table:

```
CREATE TABLE IF NOT EXISTS `oc_post` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `massage` varchar(255) DEFAULT NULL,
  `date` varchar(255) DEFAULT NULL,
  `editdate` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;
INSERT INTO `oc_post` (`ID`, `user_id`, `title`, `massage`, `date`, `editdate`) VALUES
(1, 5, 'عنوان نمونه', 'نوشته ی نمونه', '2015-04-01 22:34:39', NULL);
```

**Comment by ikkez** [comment]
try to create your table with defining a unicode collation:

```sql
CREATE TABLE IF NOT EXISTS `oc_post` (
 ...
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;
```

and: if you use a custom web-font in your frontend, make sure that is contains those unicode chars as well. Define a fallback font-family or try a system font like Arial for testing purpose to see where it breaks.

**Comment by sajaddp** [comment]
Thanks, I do it but it doesn't work
the font for utf8 is standard
also I tried Arial!

Usually we use this code for fixing this problem in our config file: 
```
	$conn = new mysqli($servername, $username, $password, $dbname);
	 mysqli_query($conn,"SET NAMES utf8");
``` 
**but I do not know how change it for use in F3 ):**

**Comment by xfra35** [comment]
See [here](https://github.com/bcosca/fatfree-core/blob/master/db/sql.php#L440). F3 issues it automatically.

You can force it:
```php
$db=new DB\SQL($dsn,$user,$pw,array(
  \PDO::MYSQL_ATTR_INIT_COMMAND=>'SET NAMES utf8'
));
```
but that should not be necessary...

**Comment by sajaddp** [comment]
Very tanks!
the problem is fixed.

Final code for UTF-8:
```
	$this->db = new DB\SQL(
		'mysql:host='.$this->_DBhost.';
		port='.$this->_DBport.';
		dbname='.$this->_DBname.'',
		''.$this->_DBadmin.'',
		''.$this->_DBpass.'',
		array(\PDO::MYSQL_ATTR_INIT_COMMAND=>'SET NAMES utf8;')
	);
```

**Comment by xfra35** [comment]
Out of curiosity, what does `echo $f3->get('ENCODING')` output?

**Comment by sajaddp** [comment]
result: UTF-8 
In most scripts for Persian, Arabic and etc we need set 'SET NAMES' when connect to database

**Comment by xfra35** [comment]
What I don't understand is that F3 should set it for you (see [here](https://github.com/bcosca/fatfree-core/blob/master/db/sql.php#L440)). Maybe you're running an old version where this behaviour was not implemented yet?

**Comment by sajaddp** [comment]
We use latest version in our project!
https://github.com/Dideban/ourcarrot
https://github.com/Dideban/ourcarrot/blob/master/lib/db/sql.php

**Comment by xfra35** [comment]
Ok now I understand. That's because your connexion string contains newlines: `mysql:host=localhost;\nport=3306;\ndbname=test`. Therefore the regex at [L435](https://github.com/bcosca/fatfree-core/blob/master/db/sql.php#L435) didn't detect the database name.

It could be fixed by adding the `s` modifier (dot match newlines) to the regex. I was about to write "but why would we support a dsn string with newlines?" and then realized that PDO does support it, since you didn't encounter any connexion problem.

So maybe add that `s` modifier? @ikkez @bcosca?

**Comment by bcosca** [comment]
Done
