### ISSUE TITLE
How i can set and use function in special page with F3

### ISSUE THREAD

**Issue by rjz1371** [bcosca/fatfree#819]
Hello EveryBody !

i want to use my function in page.php but i receive this error : " Call to undefined function func "

Attention : it is important for me that just use $view->render() for show my template.

Every one can answer my question , please ?

my php code is : 

<?php
class Test
{
	function show($f3, $args)
	{
		$f3->set('func', function($id)
		{
			return $id;
		});
                $view = new View();
                echo $view->render('page.php');
	}
}

$f3 = require('lib/base.php');

$f3->set('DEBUG',1);

$f3->config('config.ini');

$f3->route('GET /','Test->show');

$f3->run();
?>

------------------

page.php : 

<?php echo func('4');  ?>

**Comment by ikkez** [comment]
since the function/closure is stored in a varialbe, please try `<?php echo $func('4'); ?>`. Please use our [google group](https://groups.google.com/forum/#!forum/f3-framework) for application questions the next time. and welcome to F3 ;)

**Comment by rjz1371** [comment]
Thank you for your response.
