### ISSUE TITLE
sqlsrv "Invalid object name" when using a schema other than dbo

### ISSUE THREAD

**Issue by keanemcgough** [bcosca/fatfree#820]
If my table uses dbo, everything works fine. If I use a custom schema I get 
`PDOStatement: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid object name ...`

I tried specifying the schema when creating the table:
`$table = $db->getTable ( $table, "schema.table" );` 
but the generated code would be missing all the column names:
`SELECT schema.table. FROM [schema].[table] WHERE id>1`

I think I fixed it by adding this line to sql.php inside the schema function :
```
if (strpos ( $table, '.' )) {
        $split = explode ( '.', $table )[1];
    }else
        $split = $table;
```
and replace the corresponding $table variables with $split. 

This might be a terrible fix but it works with my very limited testing. If there is better way to fix this, please let me know.

**Comment by ikkez** [comment]
hi. thanks for reporting.
Well F3 is a little bit fat free regarding different db schemes that are different from the defaults and other edge cases. I think when you do not really need to rename the schema, just stick to the dbo default and it would save you some headaches. Nevertheless, I've tested your suggestion, which seems to solve this issue.
