### ISSUE TITLE
404 on route

### ISSUE THREAD

**Issue by n0per** [bcosca/fatfree#825]
Hi,

I have this issue with routing i'm not sure what i'm doing wrong. This works fine with 3.0.5. 
I have even tried to declare the routes manually using $f3->route(), but still nothing I keep getting 404.
Is it something wrong with autoloading? 

config/config.ini:
-----------------------

[gobals]

AUTOLOAD=app/controllers/|app/models/|app/repositories/|app/services/|app/utils/

DEBUG = 3

db_dns=mysql:host=localhost;port=3306;dbname=
db_name=yellownotes
db_user=root
db_pass=1234

UI=app/views/
site="yellow Notes"

config/routes:
-----------------

[routes]
; BEGIN Note Routes

GET /=NoteController->index
GET|POST /note/create=NoteController->create

; END Note Routes

index.php:
-------------

<?php
// Kickstart the framework
$f3=require('lib/base.php');
$f3->config('config/config.ini');
$f3->config('config/routes.ini');
$f3->run();

**Comment by sn0opy** [comment]
In which folder is your NotesController.php? Could you paste its code here too?

Btw, next time, I recommend you use the [Google grouo](https://groups.google.com/forum/#!forum/f3-framework) for such questions, since we use the issue tracker for actual issues / bugs.
