### ISSUE TITLE
Use ENV to override config

### ISSUE THREAD

**Issue by cimnine** [bcosca/fatfree#827]
To easily use F3 apps in PaaS environments such as Heroku, or within Docker, it would be great if F3 would allow config variables to be overridden through ENV variables.

**Comment by xfra35** [comment]
Can't it be easily implemented at app level?

**Comment by cimnine** [comment]
It could. It would require every app built on fatfree to implement the exact same, right?

**Comment by ikkez** [comment]
This is really easy to add in your bootstrap file:
```php
$f3->mset($f3->get('ENV'));
```
Put this after you have loaded all your configs. I think that is the only reasonable place where it belongs to.

**Comment by cimnine** [comment]
I see your point. Maybe a shortcut would do it. Something like

    $f3->configfromenv('prefix'); // naming of the function could be better :-/

where an application could define a prefix and only the ENV variables that begin with the prefix would be added to the hive. This would also make it explicit, how to quickly add something from ENV to the hive.

**Comment by cimnine** [comment]
I've made an implementation based on your advice and with my prefix suggestion for the "selfoss" project:

https://github.com/SSilence/selfoss/pull/649/files?diff=unified

**Comment by xfra35** [comment]
I understand that you don't want to import the whole `ENV`, so here's an alternative to the prefix method:

**Bash:**
```bash
export SELFOSS="rss_max_items=100, rss_title=Custom feed"
```

**F3:**
```php
$f3->mset($f3->parse($f3->ENV['SELFOSS']));
```

**Comment by cimnine** [comment]
I would argue against this. It's not strictly against the 12factor paradigm, as the configuration is still through the ENV. But all PaaS that I know of follow the principle "one configuration setting = one environment variable".

**Comment by xfra35** [comment]
I don't think that adding a `configfromenv()` method is a good idea, as it's a bit too much application-specific.

But maybe we could add a more generic method that would extract prefixed keys from an array. It would complete the set of array utilities provided with the framework (`flip()`, `push()`, `pop()`, etc...). Also such an utility would be used by the `constants()` method, as it is part of it now.

It would work like this:
```php
$arr=array(
  'SELFOSS_foo' => 'bar',
  'SELFOSS_bar' => 'baz',
  'SOMETHING' => 'somewhere',
);
$extracted=$f3->extract('SELFOSS_',$arr);
print_r($extracted);// array('foo'=>'bar','bar'=>'baz')
// or via a hive variable:
$f3->set('ARR',$arr);
$extracted=$f3->extract('SELFOSS_','ARR');
```

And importing ENV variables to the hive would be accomplished by:
```php
$f3->mset($f3->extract('SELFOSS_','ENV'));
```

**Comment by cimnine** [comment]
This sounds like a good compromise.

**Comment by xfra35** [comment]
Done here: https://github.com/bcosca/fatfree-core/commit/2f189071e5397ff5a298a0c42220cd0e9e51da53

Now you should be able to extract the subset of `$_ENV` dedicated to Selfoss using the following syntax:
```php
$f3->mset($f3->extract($_ENV,'SELFOSS_'));
```
