### ISSUE TITLE
Identicon crashed apache in Ubuntu 14.04

### ISSUE THREAD

**Issue by artakus** [bcosca/fatfree#829]
Hello,
I tried to run my code in lastet Ubuntu LTS (14.04.2) with Apache 2.4.7 and
PHP 5.5.9 with GD2 (2.1.1-dev) installed from official repository.
Tried with simple code 
```php
$img = new Image();
$img->identicon('BAKA',160,5);
$img->render('jpeg',NULL,90);
```
will crash the Apache with error:
```
[Thu May 07 22:01:38.996878 2015] [core:notice] [pid 32621] AH00051: child pid 32627 exit signal Segmentation fault (11)
```
After enabling coredump and open it with gdb, it showed something like this:
```
Core was generated by `/usr/sbin/apache2 -k start'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f6593633f53 in gdImageClone () from /usr/lib/x86_64-linux-gnu/libgd.so.3
```
I know its not F3 fault, but is there anyway to fix this?

Thanks.

**Comment by xfra35** [comment]
Looks like a GD bug. I'd advise to produce a reduced test case and open an issue [here](https://github.com/libgd/libgd/issues).

Have you tried other methods from the `Image` class? Do they all crash PHP or is it only `identicon()`?

**Comment by xfra35** [comment]
@artakus any update on this?

**Comment by artakus** [comment]
still no update for php or gd in ubuntu 14.04 repository.
