### ISSUE TITLE
PDO syntax error

### ISSUE THREAD

**Issue by justasSav** [bcosca/fatfree#830]
Sqlite database.

schema:
users (
    email VARCHAR(255),
    password VARCHAR(255)
);

example code:

$user=new DB\SQL\Mapper($db,'users');
$user->email = 'email';
$user->password = 'password';
$user->save();

Saves to database, but renders errors at the end:

PDO: near " ": syntax error

/lib/db/sql/mapper.php:262 DB\SQL->exec()
/lib/db/sql/mapper.php:302 DB\SQL\Mapper->select()
/lib/db/cursor.php:164 DB\SQL\Mapper->find()
/lib/db/sql/mapper.php:412 DB\Cursor->load()
/lib/db/cursor.php:231 DB\SQL\Mapper->insert()
/index.php:131 DB\Cursor->save()
/index.php:151 Base->run()

**Comment by ikkez** [comment]
The SQL Mapper requires at least one primary key field. I guess the error occurs, because it's missing in your schema.

**Comment by justasSav** [comment]
Thank you! You are correct. 

Proper syntax to have primary key in a table: 
```
CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    email VARCHAR(255),
    password VARCHAR(255)			
);
```

**Comment by GhaziTriki** [comment]
Hi there,

Looking at SQLite documentation https://www.sqlite.org/lang_createtable.html it says

With one exception noted below, if a rowid table has a primary key that consists of a single column and the declared type of that column is "INTEGER" in any mixture of upper and lower case, then the column becomes an alias for the rowid.


Isn't it possible to make F3 use the default "oid" for SQLite databases?

**Comment by ikkez** [comment]
From the docs:

> A PRIMARY KEY column only becomes an integer primary key if the declared type name is exactly "INTEGER". Other integer type names like "INT" or "BIGINT" or "SHORT INTEGER" or "UNSIGNED INTEGER" causes the primary key column to behave as an ordinary table column with integer affinity and a unique index, not as an alias for the rowid. 

So as far as I understand: If you only define a single column as `INTEGER` and let all other integer columns be `INT` you can have any primary key name as alias to rowid / oid / _rowid_ which should fit your desired behaviour already :)
