### ISSUE TITLE
f3 and phpunit

### ISSUE THREAD

**Issue by aslabs** [bcosca/fatfree#831]
Hello,
What is the best way to implement phpunit in f3 based application?
Can mock() be used inside phpunit?

**Comment by Rayne** [comment]
There should be no problem using `Base->mock()` in `phpunit` tests.

More information for HTTP unit tests:

* http://fatfreeframework.com/unit-testing#MockingHTTPRequests
* http://fatfreeframework.com/base#mock (see also https://github.com/F3Community/F3com-data/pull/74)

**Comment by Rayne** [comment]
[Basic FatFreeFramework/Base->mock() + PHPUnit example](https://gist.github.com/Rayne/5afcf404d334465850db)

**Comment by aslabs** [comment]
Wow thanks.  All the links were perfect, specially the last one,  thanks
