### ISSUE TITLE
suggestion: regexp on routes

### ISSUE THREAD

**Issue by aslabs** [bcosca/fatfree#832]
I encountered this issue many times. When creating multilanguage sites, rout should look like this:
/@lang/@page/@etc
where @lang should be optional. Now the optional part is hard to accomplish right now.

My solution currently is to have a general route: GET|POST /@var1/@var2/@var3
if (in_array (@var1, $languages)){
  $lang=@var1
  $page=@var2
} else {
  $lang=@var2
  $page=@var3
}
with regexp I could do 1 rout for everything:
GET|POST /@lang=^(a-z){2}?/@page/@etc

**Comment by Rayne** [comment]
This F3-plugin could be interesting for you: https://github.com/xfra35/f3-multilang

**Comment by aslabs** [comment]
Well languages is only 1 possible implementation. It was an example.
what if I want a number only param, or a 2 options only:
/@account/@{id:(0-9){3,4}/@action
/@account/@id/@{action:{edit|delete}? }

**Comment by ikkez** [comment]
I think it'll confuse you and the router if you start to mix complicated regex routes with optionally wildcards (*). From the similar issue https://github.com/bcosca/fatfree/issues/275 the solution is to use route groups:
```php
$f3->route(array(
  'GET /@page/@etc',
  'GET /@lang/@page/@etc'
), 'Controller->func');
```

**Comment by bondz** [comment]
@xfra35 :+1: Nice plugin

**Comment by bcosca** [comment]
This is one feature of Sinatra that F3 won't imitate. @ikkez is right. Regexes are more a liability than they attempt to solve. There are other more declarative ways of defining routes.
