### ISSUE TITLE
Dead code in Base->call()

### ISSUE THREAD

**Issue by Rayne** [bcosca/fatfree#833]
`isset($parts[1])` is never `true` at https://github.com/bcosca/fatfree-core/blob/dc40b0b218b99a197df5d3c12c3e7f4801533dfe/base.php#L1631

**Comment by ikkez** [comment]
Hm, looks like this is about the `$parts` variable that was moved into the grab() method https://github.com/bcosca/fatfree-core/blob/dc40b0b218b99a197df5d3c12c3e7f4801533dfe/base.php#L1594

**Comment by xfra35** [comment]
Should be fixed now: https://github.com/bcosca/fatfree-core/commit/4dcace4d97f734b8aea13515080d7bfb1963628f
