### ISSUE TITLE
500 generated for all errors no matter how severe

### ISSUE THREAD

**Issue by bensechrist** [bcosca/fatfree#836]
The error handler now assumes all errors should produce a 500 no matter how severe. It would be nice if there was a check for the level of severity before generating a 500. 

https://github.com/bcosca/fatfree/blob/5c69a469d8fce406270ee4aa5642870ed9462e42/lib/base.php#L1849

**Comment by Rayne** [comment]
This is the default error handler. Please define a custom error handler with [`ONERROR`](http://fatfreeframework.com/quick-reference#ONERROR) and provide appropriate error codes with `Base->error($code,$text='',array $trace=NULL)`.

**Comment by bensechrist** [comment]
What I want is a way to prevent a 500 if it is an error I don't care about.

**Comment by xfra35** [comment]
By [default](https://github.com/bcosca/fatfree/blob/5c69a469d8fce406270ee4aa5642870ed9462e42/lib/base.php#L1841), the framework ignores `E_NOTICE` errors and throws a 500 on everything else.

Nothing prevents you from changing the error_reporting to fit your needs.
