### ISSUE TITLE
No Bcrypt support for Auth

### ISSUE THREAD

**Issue by danben-72** [bcosca/fatfree#841]
As of now, Auth's "login" method technique for password verification is always based on regular comparison operations.
I suggest providing a way to define the comparison method, for example through a new argument for the login method. This enhancement would require a rework of the storage handlers. It should also be supported in "basic" method.

**Comment by bcosca** [comment]
It is unclear how user-defined or third-party storage handlers should be integrated with the existing Auth class. I move that this issue be closed until further clarification.
