### ISSUE TITLE
Include tag no longer allows partially dynamic href value

### ISSUE THREAD

**Issue by kwebble** [bcosca/fatfree#842]
After running a Composer update that updated F3 to 3.5.0 the handling of the include tag changed. This used to work:

    <include href="form-{{ @formName }}.html" />

to include a file based on a variable value. In 3.5.0 it generates an error:
**Unable to open 'form-' . {{ @formName }} . '.html**

Changing the include to this format works:

    <include href="{{ 'form-' . @formName . '.html' }}" />

Perhaps this has to do with the '''Change in behavior: Strict token recognition in <include> href attribute''' I read in the release notes.

I am not completely sure if F3 adheres to semantic versioning, but this breaks existing code.

**Comment by ikkez** [comment]
Sorry for the trouble. Unfortunately it's a necessary evil, to end up in a more stable and reliable way of static and dynamic attributes. See duplicate here https://github.com/bcosca/fatfree-core/pull/62
