### ISSUE TITLE
Redundant ttl checking?

### ISSUE THREAD

**Issue by richgoldmd** [bcosca/fatfree#844]
I see this construct in a few places (this one from View::render):

		$cached=$cache->exists($hash=$fw->hash($file),$data);
		if ($cached && $cached[0]+$ttl>microtime(TRUE))
			return $data;

Which seems redundant because Cache::exists has:

		if (!empty($raw)) {
			list($val,$time,$ttl)=(array)$fw->unserialize($raw);
			if ($ttl===0 || $time+$ttl>microtime(TRUE))
				return array($time,$ttl);
			$val=null;
			$this->clear($key);
		}

Is this redundant or am I missing something?

-Rich

**Comment by bcosca** [comment]
You are correct. It seems like this passed the radar far too long without being detected. No harm though but it can be made optimal. Done.

**Comment by richgoldmd** [comment]
It occurs to me that the redundancy would catch the case where a developer shortened the ttl after the data was cached.  Not sure if that was intended, but thought I'd point it out.

**Comment by bcosca** [comment]
That is a possibility indeed, although it can also be said that it's the price to pay for rushing things. Expedition must give way to conservatism in this case.
