### ISSUE TITLE
Fatal error: Undefined index: HTTP_X_FORWARDED_PROTO

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#846]
Hi,

When deploying an application to a server I get the following error

Fatal error: Undefined index: HTTP_X_FORWARDED_PROTO

I think it may come from the lines below :
https://github.com/bcosca/fatfree/blob/master/lib/base.php#L2040-2041

How can this be fixed?

**Comment by bcosca** [comment]
There's an isset() there that's guaranteed to short-circuit if no such index exists. That error is most likely in your app, not the framework. Have you looked at your error_log for the exact line number?
