### ISSUE TITLE
Issue with Mapper Load/Find single field

### ISSUE THREAD

**Issue by dabiddo** [bcosca/fatfree#847]
Hello, i'm having a little issue with the SQL Mapper
I'm using Mysql to get my list of users, but SQL mapper returns empty, but when I use the exec command, it retrieves the data without issues.

Example:
$miCliente=new DB\SQL\Mapper($db,'users');
 $miCliente->load(array('idUser=?',$iUsuario)); 
Result: NOTHING/NULL

$miCliente=new DB\SQL\Mapper($db,'users');
$miCliente->load('idUser=.$iUsuario);
Result: Nothing/Null

$miCliente=$db->exec('SELECT * FROM users where idUser='.$iUsuario);
result: Correct array with 1 object;

I have tried using the DB->log(); but the query it generates works when I test it on Mysql
I have the DB sql mapper working on other functions and those do not fail, only when I search using single field.

Does this ever happen to anyone else?

**Comment by ikkez** [comment]
The load method actually does not return any data array directly. It maps the data to your $miCliente object, see http://fatfreeframework.com/databases#TheSmartSQLORM 
Otherwise have a look at the find or findone method instead.

**Comment by ikkez** [comment]
please ask for additional help at our google board, if you still have problems with the mapper. thanks.
