### ISSUE TITLE
Undefined variable $prop for ICU decimal

### ISSUE THREAD

**Issue by Rayne** [bcosca/fatfree#848]
`Base->format()` tries to use the undefined variable [`$prop`](https://github.com/bcosca/fatfree/blob/9cc485be8db3b2b9d7c1f098db24afd05e5259da/lib/base.php#L894):

```php
$f3->route('GET /format-decimal', function(Base $f3) {
	error_reporting(E_ALL);
	$f3->format('{0,number,decimal}', 1.23);
});
```

**Comment by ikkez** [comment]
The decimal formatter expects another property, which defines the decimal places:
```php
echo $f3->format('Decimal Number: {0,number,decimal,2}', 0.171231235);
//--------------------------------------------------^
```

**Comment by Rayne** [comment]
You are right. Thank you!

**Comment by bcosca** [comment]
Latest commit defaults to 2 decimal places in the absence of a value
