### ISSUE TITLE
Persian User Guide

### ISSUE THREAD

**Issue by sajaddp** [bcosca/fatfree#849]
Hi
I believe many designers and developers would welcome F3 if all parts of the 'User Guide'
and 'API Reference' should be translated in Persian, the language that is common in Iran, Afghanistan, Tajikistan, Uzbekistan, and also Persian speakers living in 43 countries. 
If you want to work together, we can help you to add Persian language to the fatfreeframework.com or create a Persian-language website to introduce and educate the framework for the Persian-language Web designers and developers .

**Comment by xfra35** [comment]
Hey @sajaddp, that's a great idea!
Since the fatfreeframework.com is a separate project, can you please open a new issue there?

Here's the repository: https://github.com/F3Community/F3com
