### ISSUE TITLE
checking for system errors on Base initialization

### ISSUE THREAD

**Issue by timbotron** [bcosca/fatfree#851]
**Problem**

When trying to run F3 on a server that has an error in the PHP Startup, the `base.php __construct() `will see that there is an error on the error stack, and immediately throw a 500. Note the user normally would not see this error, and PHP runs fine otherwise.

This is the culprit:

https://github.com/bcosca/fatfree/blob/9cc485be8db3b2b9d7c1f098db24afd05e5259da/lib/base.php#L2157

```
if ($error=error_get_last())
			// Error detected
			$this->error(500,sprintf(self::E_Fatal,$error['message']),
				array($error));
```

Many shared hosting sites, including Rackspace Cloud Sites has some slightly misconfigured PHP installations for whatever reason. This bug inhibits someone from using F3 on that service, unless they comment out that if block.

It also makes it really hard to troubleshoot, since the error may look like something totally unrelated. In my case, it was that postgresql on Rackspace Cloud Sites is misconfigured, but I thought problem was in how I was using DB::SQL.

![f3](https://cloud.githubusercontent.com/assets/283604/8387045/684b3c30-1c0a-11e5-962d-d4451a85e13d.png)

**Possible Solution**
Instead of checking the general error stack to see if something has thrown an error in `base.php __construct()`, any error that crops up is put on a custom stack (array, whatever), then **that** is checked at the end to see if any errors exist.

If the powers that be agree, I'd be happy to write it and submit a pull request.

**Comment by ikkez** [comment]
Isn't it good to know about any server issues right in the first place, rather than only recognizing them when a (possibly critical) action failed, which you maybe didn't even noticed? I think a stable application begins with a solid surface. If the server is already the problem, the dev guy should feel happy to see that errors, before he starts wondering about his own application code, or am I wrong?

**Comment by geniuswebtools** [comment]
I would agree that it's better to know these things going into the app.  This has helped me two times.  The first was an incorrect path to memcache after a serer migration.  The second was when the sqlite lib wasn't loading at start up.

**Comment by timbotron** [comment]
@geniuswebtools  @ikkez I agree, but in cases of shared hosting, the rackspace cloud sites team is aware of the config error, and is not going to correct it. So, unless a developer is aware enough to hop into base.php and troubleshoot to figure out where/what they should comment out, there is no way for them to use F3.

In addition, the feedback makes it not obvious either. When I was troubleshooting, if I ran a plain php script, it worked fine. If I ran something including F3s base.php, I would get a strange postgresql error. I assumed the problem was with F3.

What if errors were checked for at the start of the `base.php __construct()`, and if any were found, the error is presented with additional description? Like "Errors detected in server configuration before F3 initialized:"?

Maybe even there is away to set a global config var to ignore server initialization errors? (Otherwise, I can't really use F3 via composer because I would need to go in and manually edit the base.php every time I ran `composer update`.

**Comment by ikkez** [comment]
rackspace hosting for $150/mo and they are not willing to fix the config bug? Well I would ask for the complaint department, or change the hoster.. really, I'm not kidding.
Regarding the code, I guess it would be sufficient to add a config check at https://github.com/bcosca/fatfree/blob/9cc485be8db3b2b9d7c1f098db24afd05e5259da/lib/base.php#L2157. This is already the appropriate point of checking for startup errors.

**Comment by timbotron** [comment]
I like that solution @ikkez , I will work on this tonight. I haven't worked on a public project like this very much; I am assuming my path should be: make changes > submit pull request > if accepted then we close this issue.

Is that correct?

RE: rackspace, I agree, I wish I could switch. This is client work I am doing, they chose that host for a variety of reasons, and changing isn't really an option.. :disappointed:

**Comment by geniuswebtools** [comment]
Question, before you try to resolve this issue by adjusting the framework, can you add a php.ini file to the host, and try loading the missing lib that way?

Another issue we had w/ the missing memcache lib was that it went unnoticed for quite a while, and every request to the server on every domain, was writing to it's own error_log.  The result was gigabytes of storage space being claimed by hundreds (if not thousands) of little error_logs all w/ the same message to the missing lib.

So fixing the issue w/ the framework, will allow you to work w/ F3 on this host, but you still have a problem w/ the host that should be addressed.

**Comment by timbotron** [comment]
@geniuswebtools I will check that out tonight, but I am pretty sure I just have access to a directory that all the content is served up out of; no real way to edit any PHP config items.

Just to be clear, I think this edit will be helpful for F3 and not just for my use case. Who knows how many people tried using F3 but came up against a similar issue and just abandoned using it? I love F3 and want it to get more traction. :grinning:

**Comment by ikkez** [comment]
Actually, I don't think that it makes much sense to skip the check for a startup error in the Base->__construct(), since the same error would then be thrown at another point. And I also have no idea how to make this configurable and moreover if that is really necessary.
I think the best way to mitigate the erroneously call to the error handler during initialization, is to clear the pending server errors before loading F3:
```php
error_clear_last();
$f3=require('lib/base.php');
```

**Comment by xfra35** [comment]
PHP7? A much awaited feature :)

**Comment by ikkez** [comment]
Oh it's a PHP 7 only feature. I guess I missed that.. aaargh.. :sweat_smile:

**Comment by xfra35** [comment]
Yeah.. good to know that it's finally there though :)

**Comment by daninfpj** [comment]
This is surely problematic. I was trying to run a worker from php-rescue and it kept dying because of a warning it generates (due to php-rescue using cli_set_process_title). There was no output at all (the worker is run from the command line) which made it really difficult to debug.

**Comment by ikkez** [comment]
:+1: 
We should really add a check for a constant or something so we can A) adjust the error level for the startup check, B) disable the startup check. 
This behaviour should be documented an the very first beginning of the user guide.

**Comment by xfra35** [comment]
Here's an alternative solution: https://github.com/bcosca/fatfree-core/pull/125.

**Comment by xfra35** [comment]
Should be fixed now. Just add `error_reporting(0)` at the top of `index.php` to have F3 skip the initial error check.
