### ISSUE TITLE
DB\SQL\Mapper save data from array not $_POST

### ISSUE THREAD

**Issue by tablecell** [bcosca/fatfree#852]
for example 

 ```A

$user=new DB\SQL\Mapper($db,'user');
 


$arr=array('username'=>'xxx','email'=>'yyy','password'=>'zzz');
print_r($arr);


$user->copyFrom($arr);
$user->save();
```
preg_split() expects parameter 2 to be string, array given

**Comment by xfra35** [comment]
Which version of the framework are you using? Array inputs in `copyFrom()` have been introduced in 3.5.0.

**Comment by tablecell** [comment]
Version 3.1 

i try version 3.5

**Comment by xfra35** [comment]
Nope. You have to implement it yourself or use [Cortex](https://github.com/ikkez/f3-cortex).
