### ISSUE TITLE
Invalid parameter number: Columns/Parameters are 1-based

### ISSUE THREAD

**Issue by tablecell** [bcosca/fatfree#853]
```A
$param=array(2015);

$out=$db->exec(" SELECT title,FROM_UNIXTIME(create_time,'%Y-%m-%d') as date  FROM posts where FROM_UNIXTIME(create_time,'%Y')=?",$param);
print_r($out);
```
error message  is :
Invalid parameter number: Columns/Parameters are 1-based

```B
$param=array(2015);
array_unshift($param,'xxx');
 unset($param[0]);
$out=$db->exec(" SELECT title,FROM_UNIXTIME(create_time,'%Y-%m-%d') as date  FROM posts where FROM_UNIXTIME(create_time,'%Y')=?",$param);
print_r($out);
``` 
it works 

why not use $pdo->execute($arr); 
```C
$stmt = $pdo->prepare(" SELECT title,FROM_UNIXTIME(create_time,'%Y-%m-%d') as date  FROM posts where FROM_UNIXTIME(create_time,'%Y')=?");
$arr=array('2015');
$stmt->execute($arr);
$out=$stmt->fetchAll();
print_r($out);

```

**Comment by ikkez** [comment]
duplicate to https://github.com/bcosca/fatfree/issues/740

**Comment by tablecell** [comment]
PDO can use 
```A
$arr=array('2015');
$stmt->execute($arr);
```

**Comment by papa-smurf** [comment]
It's because F3 uses pdo->bindValue for parameter binding. Might as well just use $db->pdo()->prepare/execute as the DB\SQL class doesn't have much added value anyways

**Comment by ikkez** [comment]
The `$input_parameter` for execute is limited in PDO (http://php.net/manual/en/pdostatement.execute.php#refsect1-pdostatement.execute-parameters) and will just treat any parameter as string. With `bindvalue` you are able to enforce a datatype, which is important. 
If you don't like the 1-based key paramter arrays, try named parameter ;)
`$db->exec('INSERT INTO mytable VALUES(:id,:name)',array(':id'=>5,':name'=>'Jim'))`

**Comment by papa-smurf** [comment]
Why not use prepare/execute($data) when the type parameter is omitted then? Will save from a lot of hackisch array manipulations just to make the data 1-based.

Or alternatively add functionality in your wrapper that will manipulate the data array for you seeing as you already do sanitation and typecasting on input data yourself to make up for the pretty useless built-in pdo datatype parameters.

**Comment by bcosca** [comment]
Noted, but I'll leave this to @ikkez' best judgment.

**Comment by ikkez** [comment]
Alright, fixed in the latest commit.
