### ISSUE TITLE
Setting empty template variable renders bogus PHP in some cases

### ISSUE THREAD

**Issue by Bloke** [bcosca/fatfree#854]
Not sure if this has been reported, or it's peculiar to my set up, but there seems to be some weirdness when using the template's `<set>` mechanism to set an empty variable. In my application code I'm setting a variable for use in an HTML `class` to either have "some-class" or an empty class.

Here's a stripped-down template test case:

    <!DOCTYPE html>
    <html>
    <head>
        <title>Fat-free template empty string test</title>
    </head>

    <body>
        <set regularClass="hello-world" />
        <set emptyClass="" />

        <pre>
        Regular: ##{{ @regularClass }}##
        Empty: ##{{ @emptyClass }}##
        </pre>

        <check if="1">
            Renders internal server error and bogus PHP.
            Does not render error if no F3 tags are used after setting empty,
            but the 'set' tag is output verbatim.
        </check>
    </body>
    </html>

The `<check>` could be pretty much any F3 template tag that takes an attribute (`include`, etc), it's just used here to trigger the error. Running the above template from a suitable Route renders the following PHP template in the cache directory:

    <!DOCTYPE html>
    <html>
    <head>
        <title>Fat-free template empty string test</title>
    </head>

    <body>
        <?php $regularClass='hello-world'; ?>
        <?php $emptyClass=NULL; $pre=NULL; $Regular=NULL; $0=$regularClass; $Empty=NULL; $1=$emptyClass; $check=NULL; $if='1'; ?>

Without the `<check>` block in the above template, this is the result:

    <!DOCTYPE html>
    <html>
    <head>
        <title>Fat-free template empty string test</title>
    </head>

    <body>
        <?php $regularClass='hello-world'; ?>
        <set emptyClass="" />

        <pre>
        Regular: ##<?php echo $regularClass; ?>##
        Empty: ##<?php echo $emptyClass; ?>##
        </pre>
    </body>
    </html>

I have bypassed the issue for now by using `<set emptyClass=" " />`.

Is this repeatable, or just me?

**Comment by xfra35** [comment]
This is indeed repeatable: `<set foo=""/>` doesn't get parsed because tag attributes are not expected to be empty.

Replacing `+` by `.` at [this line](https://github.com/bcosca/fatfree/blob/master/lib/template.php#L276) should fix it.

**Comment by xfra35** [comment]
Fixed.
