### ISSUE TITLE
Prevent complete overwriting of superglobals

### ISSUE THREAD

**Issue by papa-smurf** [bcosca/fatfree#855]
We get access to superglobal properties by using `F3::get('POST.field1')` or `F3::get('SESSION.username')`, while using `F3::set('SESSION.username', 'MyUserName')` allows us to set properties.

Not particularly semantic or user friendly, but it gets the job done. The following however can cause some serious issues:

`F3::set('POST', 'MyFirstForumPost');`

The statement above completely overwrites the `$_POST` array and turns it into a string with a value of `'MyFirstForumPost'`.

First of all, as all superglobals, `$_POST` should always be an associative array according to PHP's definitions. Secondly, imagine the following situation which actually caused us some trouble:

We use environment recognition to decide which configuration files to load and what exactly to do with errors and exceptions. To keep track of the environment throughout our application we set an ENV property with an environment identifier which is a string, `'production'` for example.

To set this property we used `F3::set('ENV', 'production')`.

Needless to say this caused a lot of issues, as completely overwriting the `$_ENV` superglobal and setting it to a string value `'production'` results in a lot of unwanted consequences. This was a stupid move on our part of course as we didn't realised the global `ENV` was accessible through the getters and setters as well.

A big improvement in my opinion would be creating wrappers for superglobals.
For example we could use:

`F3::Session->set('Foo', 'Bar');`

Or when properly namespaced:

`Session::set('Foo', 'Bar');`

As a result, `F3::set()` and `F3::get()` wouldn't have to tamper with superglobals at all.

**Comment by stehlo** [comment]
You can't expect the framework to guard mediocre programmers from their own stupidity. Let's not unnecessarily inflate this lean framework. It is called *fat*free for a reason.

**Comment by papa-smurf** [comment]
+1 on making yourself look stupid

If lean is key to you then why use `get` or `set` in the first place? Why not simply use `$var = $_GET['myVar']` instead of `$var = F3::get('GET.myVar')`. Needless to say your post doesn't make any sense at all. Be constructive or let someone else comment on this.

**Comment by stehlo** [comment]
I'm not explaining what I use and how I use it. I just commented on an unnecessary request. It is very constructive, as it sums up the idea per se.

**Comment by papa-smurf** [comment]
If you want to go on an ego trip with your "You can't expect the framework to guard mediocre programmers from their own stupidity", then go elsewhere.

Fat-Free has more issues, especially in terms of scoping, than I care to elaborate on. This particular one seemed to make no sense so we decided to add an issue. If it is closed without action, so be it, in the meantime I'm not keen on bogus comments like yours, might as well spend your time on actually doing something for the community.

**Comment by stehlo** [comment]
For community? Are you joking? 

A long time ago, I have decided to pay money to the the creator of this product as a token of my gratitude, rather than to bother him with nonsense.

Howgh.

**Comment by papa-smurf** [comment]
Good for you, pat yourself on the back, you're not the only one.

Closing due to moronic rants

**Comment by geniuswebtools** [comment]
I think you missed reading about the naming rules in the documentation:

http://fatfreeframework.com/framework-variables#NamingRules

A framework variable may contain any number of letters, digits and underscores. It must start with an alpha character and should have no spaces. Variable names are case-sensitive.

F3 uses all-caps for internal predefined global variables. Nothing stops you from using variable names consisting of all-caps in your own program, but as a general rule, stick to lowercase (or camelCase) when you set up your own variables so you can avoid any possible conflict with current and future framework releases.

You should not use PHP reserved words like if, for, class, default, etc. as framework variable names. These may cause unpredictable results.

**Comment by papa-smurf** [comment]
That's why I'm not talking about a bug here :)

**Comment by geniuswebtools** [comment]
I don't think you're request will gain any support. This is an issue that has to be resolved by the development team writing the code.

These statements have the same result:
F3::set('POST', 'MyFirstForumPost');
$_POST = 'MyFirstForumPost';

From the documentation again:
http://fatfreeframework.com/quick-reference#COOKIE,GET,POST,REQUEST,SESSION,FILES,SERVER,ENV

Framework equivalents of PHP globals. For your convenience, F3 automatically synchronizes these variables with the underlying PHP globals. These variables may be used throughout an application.

**Comment by papa-smurf** [comment]
I totally agree, but there is one major difference.

By just looking at this: $_POST = 'MyFirstForumPost'`

**Comment by stehlo** [comment]
@geniuswebtools Marion, I am afraid, you didn't understand his request. Please read it again.

**Comment by boussou** [comment]
F3 automatically synchronizes these variables with the underlying PHP globals. 
And the F3 teams deliver a very opinionated framework.

A framework doesn't have to be foolproof. A developer has some responsabilites ;-)
Besides, I am not even sure Laravel or Symfony would do that.

**Comment by xfra35** [comment]
@papa-smurf why did you erase your post contents? There's always room for discussion. Also it's important for the community to keep track of such requests.

Concerning your suggestion to add an extra check before overwriting superglobals, I agree with what @boussou and @geniuswebtools wrote, this is something that can easily be handled at the application level.

Concerning your example about a framework variable erased by an application variable, I find it interesting. I also don't find it optimal that everything is mixed up in the same hive. Anyway I'm pretty sure that @bcosca would answer that a clear separation can be achieved by assigning lowercase names to the application variables (uppercase names being reserved for framework variables and superglobals). So in your case, `env` would contain your environment identifier while `ENV` would contain the superglobal.

**Comment by papa-smurf** [comment]
@xfra35 I decided to remove the contents and comments regarding this issue because most comments where either beyond the scope of the issue or failed to see the problem involved here at all.

From my perspective: keeping track of what is and is not reserved by a framework or programming language when using a wrapper should not be up to the programmer, as future updates can completely destroying big chunks of your codebase this way (namespaces anyone?). As such it should be up to the wrapper to prevent major collisions or simply not provide the functionality at all.

**Comment by stehlo** [comment]
Frankly, I am so glad that this framework doesn't allow "open development". ( Thank you @bcosca )
If this was permitted fat-free would become fat-full.

Don't get me wrong. I am not against new ideas. However, there are so many overblown products already. As many people as many opinions. Just see how so many hopeful products became corrupt by opening gates to each and every single request...

**Comment by papa-smurf** [comment]
Care to elaborate what exactly it is your comments have to offer for the subject at hand? Since open development is not allowed, feel free to let someone who actually has a say in this matter make a choice. I'm just a guy giving his two cents, if you don't like the idea, good for you.

**Comment by xfra35** [comment]
@papa-smurf that's also my point of view, but it can be achieved at the moment by sticking to lowercase names. In that case, collisions with framework variables won't happen.

Maybe a different approach can be taken for the next version. Ideas are welcome.

NB: please restore the post contents, otherwise newcomers will have a hard time trying to understand what this topic is about..

**Comment by stehlo** [comment]
@papa-smurf I am hoping to discourage nonsensical requests. That's actually very relevant to the subject at hand. If you don't like how matters are handled in this product, then use another one or write your own.

**Comment by papa-smurf** [comment]
@stehlo I wasn't aware that you are the one who decides "how matters are handled in this product", good to see that donating got you somewhere.

**Comment by stehlo** [comment]
@papa-smurf Maybe you don't understand what I meant by that. So here we go:
- New people come to adopt the product and the first thing they do they try to change how things work. I made this mistake once (in 2011 or 2012). However, @bcosca's explanation taught me a lesson straight-away and I refrained from doing so ever since.
- Some people (including myself) are heavily invested (and, obviously, I don't mean [just] donations) into certain technologies. Now, every change is potentially producing a number of problems to existing applications. This issue came to existence, when F3 v.3 was introduced with a plethora of non-trivial, non-backward-compatible changes. I, and many other people, had a serious problem of rewriting large portions of code due to this upgrade.

Now, with that in mind:
- I understand that the above points may not be relevant to you, if you don't write a dependable software using F3. Yet, many others are affected by these.
- Your proposal (which I understood well, by the way) is not going to bring anything substantial to the table, except for guarding programmer against his or her own silliness. Seriously, we can't expect a lean framework to do this job for us. (Suggestion, write your own plug-in for something like that, if you need it.)

**Comment by ikkez** [comment]
Gentlemen, I understand both of you, but this doesn't lead to anything. Be gentle. :bowtie:

**Comment by papa-smurf** [comment]
@stehlo 

1) No they wouldn't be affected by these changes if executed correctly
2) We depend entirely on F3 for all our platforms with hundreds of thousands of visitors a month

So no, your up close and personal ranting still doesn't make any sense and feels more like a litte boy clinging desperately on to his teddybear.

I'll say it once more and hopefully for the last time:
If you don't like my proposal, great! If an F3 representative doesn't like it, fine by me.
It's just me giving my two cents about something that in my opinion could be improved on.

@ikkez: I agree, but something had to be said ;)
