### ISSUE TITLE
Extending Templates no longer works ?

### ISSUE THREAD

**Issue by daslicht** [bcosca/fatfree#857]
Hello,
I have the following:

/lib
```
<?php
class ExtTemplate extends \Template {

	/**
	 * Returns a trimmed string 
	 * @param  [type] $string Text to trim
	 * @param  [type] $length how long should teh new string become
	 * @return [type]         [description]
	 */
	public function trim( $string, $length) {
		if(strlen($string) > $length) {
			return substr( strip_tags($string) , 0, $length). ' ...';
		}else{
			return $string;
		}
	}	

	/**
	 * Converts a UNIX Timestamp to human readable date
	 * @param  [type] unix-timestamp
	 * @return [type] [description]
	 */
	public function date( $timestamp) {
		return date('d-m-Y' , $timestamp);
	}

}
```

```
echo \ExtTemplate::instance()->render($f3->get('frontendlayout'));
```

And this in my template:
```
{{ @item.created_at | date }}
```
But it just returns the unix timestamp and the date function seams not to be called at all.

I remember that it worked for me some time ago but I don't see what I am missing now.
Anyone please?

**Comment by daslicht** [comment]
just tested with a fresh unmodified fatfree-master , Extending no longer works ?

**Comment by Rayne** [comment]
I tested it with `fatfree-core` ([Source](https://gist.github.com/Rayne/2278d9078f8ccfd93e37)) and it compiles `Hello {{ @date | date }}` to `Hello <?php echo ($date); ?>`.

It looks like you have to register the function first, which invalidates the [current documentation](http://fatfreeframework.com/extended-templating#3.Preview). Example:

```
$f3->route('GET /', function(\Base $f3){
	ExtTemplate::instance()->filter('date', 'ExtTemplate::instance()->date');
	…
	echo ExtTemplate::instance()->render(…);
});
```

See also: https://github.com/bcosca/fatfree-core/pull/50

**Comment by daslicht** [comment]
aha ok looks like something changed. try it !

**Comment by daslicht** [comment]
So my approach above no longer works ?

**Comment by Rayne** [comment]
The [mentioned example](https://gist.github.com/Rayne/2278d9078f8ccfd93e37) is compatible with Fat-Free Framework `3.4.0`. Looks like we have to update the documentation.

**Comment by daslicht** [comment]
THANK YOU !

**Comment by ikkez** [comment]
It does work but you should use the Template->extend method to register your template extension. You dont need to extend the Template class directly. 

Von meinem iPhone gesendet

**Comment by Rayne** [comment]
`Template->extend()` is for registering node handlers. @daslicht added filters compatible with `3.4.0`. The [user guide](http://fatfreeframework.com/extended-templating#3.Preview) doesn't state how to register a filter (for the record, it's [`Preview->filter()` and the API reference is up to date](http://fatfreeframework.com/preview#filter)). Instead it suggests to extend `Template` with custom methods as filters.

**Comment by ikkez** [comment]
Yeah I meant `Preview->filter` of course. The user guide needs an update. I think it's better cross-plugin compatible not to extend the template class itself.

**Comment by daslicht** [comment]
Shouldnt something like this work either:
```
Template::instance()->filter('doit', '\daslicht\DasLichtFilter::instance()->doit'); ?
```
is instance() a php function ?

**Comment by daslicht** [comment]
Setting up the Filters using ***Preview*** is only of use when using the ***Preview Engine*** no?

So I need to extend the Template with my ***DasLichtFilter*** Class ?
