### ISSUE TITLE
Problem with $f3->exists('var')

### ISSUE THREAD

**Issue by joris-** [bcosca/fatfree#858]
Hi!

I'm trying to use isset function but I get this error : 

>Internal Server Error
>Fatal error: Cannot use isset() on the result of a function call (you can use "null !== func()" instead)

So I must to use exists function of F3.

In the doc, it says : 
>Notice: exists uses PHP's `isset()` function to determine if the hive key is set and is not NULL.

But when I use on POST variables, it returns 1 instead of 0 whereas inputs are nulls

Thanks for help

**Comment by ikkez** [comment]
You probably want the [devoid](http://fatfreeframework.com/base#devoid) method.

**Comment by xfra35** [comment]
`exists` works exactly as stated in the docs:

```php
var_dump($f3->exists('foo'));// boolean false
$f3->foo=NULL;
var_dump($f3->exists('foo'));// boolean false
$f3->foo='something';
var_dump($f3->exists('foo'));// boolean true
```

the same goes with POST variables:

```php
var_dump($f3->exists('POST.foo'));// boolean false
$f3->set('POST.foo',NULL);
var_dump($f3->exists('POST.foo'));// boolean false
$f3->set('POST.foo','something');
var_dump($f3->exists('POST.foo'));// boolean true
```

**NB**: if you like `isset`, you can use `isset($f3->foo)` and `isset($f3->POST['foo'])` instead. The only difference is that `exists` checks for cache content while `isset` doesn't.

**Comment by joris-** [comment]
Hi!

devoid works fine but exists no..

With empty input : 

    var_dump($f3->exists('POST.name')); //True instead of false ??

With not empty input : 

    var_dump($f3->exists('POST.name')); //True

If input is empty, it's like NULL ?

NB : I cannot ue isset, i get an error message

**Comment by xfra35** [comment]
`$f3->exists('POST.name')` should return FALSE if `$_POST['name']` doesn't exist or if it exists and is NULL.

Which version of the framework are you running?

**Comment by joris-** [comment]
I use the latest version.
If input named name is empty, it's like NULL ?

**Comment by xfra35** [comment]
No, `empty` is for falsy values (`NULL`,`0`, `FALSE`, `''`, etc..):

```php
$var=NULL;
echo isset($var);// FALSE
echo empty($var);// TRUE
$var='';
echo isset($var);// TRUE
echo empty($var);// TRUE
```

That's the main difference between `$f3->exists` and `$f3->devoid`. The former uses `isset`, while the latter uses `empty`.
