### ISSUE TITLE
Image imageinterlace

### ISSUE THREAD

**Issue by ram-you** [bcosca/fatfree#860]
Hi,
How can make an imageinterlace before rendering.
Thank you

**Comment by KOTRET** [comment]
As interlace is not included in the Image-Class and the $data is protected, you need to load the produced image again and call [imageinterlace](http://php.net/manual/de/function.imageinterlace.php).

Additional: the forum is located here: https://groups.google.com/forum/#!forum/f3-framework

**Comment by ram-you** [comment]
I suggest adding function : $img->Interlace(1) to the Image class for the next release.
Thanks.

**Comment by KOTRET** [comment]
i suggest to either offer access to the raw image object (make $data public) or redirect all `image...`-function-calls. There is no need to wrap all function calls.

**Comment by xfra35** [comment]
Now the `Image->data()` method returns the image resource.

So the following should be working:
```php
imageinterlace($img->data(),1);
```

**Comment by KOTRET** [comment]
beware that you cannot revert changes made to the imageobject or respective the reverts made by Image-Class are not longer consistent to what you've done with the image-object outside the class.

**Comment by xfra35** [comment]
Unless you save your changes:
```php
//direct changes to the image resource
imageinterlace($img->data(),1);
$img->save();
//revert changes
$img->undo();
```
