### ISSUE TITLE
Quotes in filename when using Web::send()

### ISSUE THREAD

**Issue by derdogan** [bcosca/fatfree#862]
I tried out the file download example[1] and I noticed a received file has single quotes around the filename (e.g.: `'file.jpg'`).
I peeked into the source of the Web class and saw there's a call to var_export while forming the HTTP header:
in F3 3.5.0 (2 June 2015), lib/web.php
line 136: `'filename='.var_export(basename($file),TRUE));`

Removing the var_export results in a normal filename, but it isn't quite clear to me why it is even there and what problems could be caused by removing it.

[1] http://fatfreeframework.com/plug-ins#HandlingFileDownloads

**Comment by ikkez** [comment]
Oh yes. I haven't encounered this yet, maybe it is browser-dependend, but from the W3 RFC at http://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html#sec19.5.1 it looks like we should use double-quotes:
```
Content-Disposition: attachment; filename="fname.ext"
```

**Comment by derdogan** [comment]
Ah, of course! I didn't think of that. I used Firefox and just tested some other browsers. With Chrome and Opera the filename is normal, with IE and Safari for Windows I get the quoted filename, too.

But yes, sticking to the standard seems like a good idea :)
(I would submit a fix but I'm still too unfamiliar with git, sorry)

**Comment by bcosca** [comment]
This was already fixed in commit edb93c1
