### ISSUE TITLE
Not working on iOS, OS X Chrome

### ISSUE THREAD

**Issue by onuraktas** [bcosca/fatfree#866]
Even if your web page is not working on OS X with Chrome. Return 500

**Comment by xfra35** [comment]
Which web page are you talking about? http://fatfreeframework.com/?

Could be related to #774...

**Comment by onuraktas** [comment]
all of them. http://fatfreeframework.com/home

**Comment by adaniello** [comment]
For me (OS X 10.10.4 + Chrome 45.0.2454.85 64-bit) works fine.

**Comment by onuraktas** [comment]
OS X 10.10.5 - Version 45.0.2454.85 (64-bit) fail

Also ios 8.4.1  from safari is not working. 

I have removed all extension and tried again. Same error. 

Also tried from second laptop with same version. Same error.

**Comment by onuraktas** [comment]
Here is my ip: 104.238.169.5x you can check your error log for http://fatfreeframework.com/home

**Comment by matpb** [comment]
OSX 10.10.5 - Chrome 45.0.2454.85 (64-bit)
Everything works fine from here.

**Comment by xfra35** [comment]
Let's wait for @sn0opy to report the contents of the server error log. That could be related to the Turkish locale as in #774.

**Comment by sn0opy** [comment]
Short excerpt from the `error.log`.

	[Wed Sep 02 21:20:36 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: PHP Fatal error:  Interface 'IteratorAggregate' not found in /var/www/virtual/f3/F3com/lib/db/cursor.php on line 26, referer: https://www.google.com.tr/
	[Wed Sep 02 21:20:36 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: Fatal error: Interface 'IteratorAggregate' not found, referer: https://www.google.com.tr/
	[Wed Sep 02 21:20:36 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: [/var/www/virtual/f3/F3com/lib/db/cursor.php:26] , referer: https://www.google.com.tr/
	[Wed Sep 02 21:20:36 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: Invalid argument supplied for foreach(), referer: https://www.google.com.tr/
	[Wed Sep 02 21:20:36 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: [/var/www/virtual/f3/F3com/inc/common.php:23] Base->{closure}(), referer: https://www.google.com.tr/
	[Wed Sep 02 21:20:36 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: PHP Fatal error:  Interface 'IteratorAggregate' not found in /var/www/virtual/f3/F3com/lib/db/cursor.php on line 26, referer: http://fatfreeframework.com/framework-variables
	[Wed Sep 02 21:20:36 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: Fatal error: Interface 'IteratorAggregate' not found, referer: http://fatfreeframework.com/framework-variables
	[Wed Sep 02 21:20:36 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: [/var/www/virtual/f3/F3com/lib/db/cursor.php:26] , referer: http://fatfreeframework.com/framework-variables
	[Wed Sep 02 21:20:36 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: Invalid argument supplied for foreach(), referer: http://fatfreeframework.com/framework-variables
	[Wed Sep 02 21:20:36 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: [/var/www/virtual/f3/F3com/inc/common.php:23] Base->{closure}(), referer: http://fatfreeframework.com/framework-variables
	[Wed Sep 02 21:20:51 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: PHP Fatal error:  Interface 'IteratorAggregate' not found in /var/www/virtual/f3/F3com/lib/db/cursor.php on line 26
	[Wed Sep 02 21:20:51 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: Fatal error: Interface 'IteratorAggregate' not found
	[Wed Sep 02 21:20:51 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: [/var/www/virtual/f3/F3com/lib/db/cursor.php:26]
	[Wed Sep 02 21:20:51 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: Invalid argument supplied for foreach()
	[Wed Sep 02 21:20:51 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: [/var/www/virtual/f3/F3com/inc/common.php:23] Base->{closure}()
	[Wed Sep 02 21:20:51 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: PHP Fatal error:  Interface 'IteratorAggregate' not found in /var/www/virtual/f3/F3com/lib/db/cursor.php on line 26, referer: http://fatfreeframework.com/framework-variables
	[Wed Sep 02 21:20:51 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: Fatal error: Interface 'IteratorAggregate' not found, referer: http://fatfreeframework.com/framework-variables
	[Wed Sep 02 21:20:51 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: [/var/www/virtual/f3/F3com/lib/db/cursor.php:26] , referer: http://fatfreeframework.com/framework-variables
	[Wed Sep 02 21:20:51 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: Invalid argument supplied for foreach(), referer: http://fatfreeframework.com/framework-variables
	[Wed Sep 02 21:20:51 2015] [warn] [client 104.x.x.x] mod_fcgid: stderr: [/var/www/virtual/f3/F3com/inc/common.php:23] Base->{closure}(), referer: http://fatfreeframework.com/framework-variables

**Comment by xfra35** [comment]
Since this is a PHP bug, I've forced the locale to English so that Turkish users can access the website.

@onuraktas does it fix it for you?
