### ISSUE TITLE
How to require additional php library

### ISSUE THREAD

**Issue by davidrhoderick** [bcosca/fatfree#867]
I tried to add phpass to my project to further protect my users' passwords.  I put it first in the "lib" folder in a folder called "phpass" then I tried putting it in the root directory before finally putting it in the "ui" folder.  All gave me permission denied errors.  How can I add a basic PHP library to my installation?

**Comment by xfra35** [comment]
Hi David, see [the docs](http://fatfreeframework.com/routing-engine#the-f3-autoloader) for details about autoloading. Also see [this SO thread](http://stackoverflow.com/questions/27262719/implementing-namespaces-in-fatfree-framework/27312633#27312633).

In short, if you're talking about [this project](https://github.com/rchouinard/phpass), you can put `Phpass.php` and  `Phpass/` in the `lib/` folder and it should work.

NB: if you have extra questions, please ask them on the dedicated [forum](https://groups.google.com/forum/#!forum/f3-framework).

**Comment by davidrhoderick** [comment]
Thanks a lot @xfra35.  Now I remember looking at `autoload` from before.  Thank you also for pointing me towards the forum; I didn't find that earlier and it should help a lit.
