### ISSUE TITLE
ERROR.trace is now multiline string

### ISSUE THREAD

**Issue by fousheezy** [bcosca/fatfree#868]
Is there a way to still get the trace as an array? The docs still say that ERROR.trace is an array so it wasn't until I saw the 3.5.0 changelog message that I realized the string change is new.

I'd still like to be able to access the raw trace array.

**Comment by bcosca** [comment]
I admit it was my mistake for committing that code. It was definitely not on purpose. The trace array will be back in the next version.

**Comment by ikkez** [comment]
You can get back the old trace array now, when you call `$f3->trace(null,false);`. Is that okay? I think we should keep the multiline string now to keep backward compatibility.

**Comment by ChiefORZ** [comment]
how is `$f3->trace(null,false);` supposed to be implemented?

if i call it in my my custom error function like so:

```php
$logger->write(
    'ERROR: ' . $f3->get('ERROR.code') . PHP_EOL
    . "\t". $f3->get('ERROR.status') . PHP_EOL
    . "\t". $f3->get('ERROR.text') . PHP_EOL
    . "\t". print_r($f3->trace(null, false), true)
    );
```
i am just receiving 
`
(
    [0] => Array
        (
            [file] => C:\etc\_dev\_www\jwt-dropper\Controller\Error.php
            [line] => 15
            [function] => trace
            [class] => Base
            [type] => ->
            [args] => Array
                (
                    [0] => 
                    [1] => 
                )
        )
)
`

**Comment by ikkez** [comment]
That's correct. It's an array, isn't it? If the trace is too short, increase the DEBUG level or produce errors further down the road, so your trace will contain some more details about the program flow that turned to this error.
