### ISSUE TITLE
dependency injection for F3

### ISSUE THREAD

**Issue by aslabs** [bcosca/fatfree#869]
I have used this framework since long time in may projects. the project i'm currently on however start becoming a bit larger, and maintaining code harder.
I started thinking about this good practice to create better testable and maintainable code: dependency injection.
I'm horrified however of the very few options available for PHP. I defiantly exclude other frameworks "modules". the remaining options are nice, but either they depend on other packages or are too unknown.
And then the brilliant idea: what if F3 has its own DI? maybe as a plugin for start.

I would like to open a discussion about this. I think that some very lightweight software can be done with all the basic features in one small file, much by the same philosophy of F3 (see https://github.com/TomBZombie/Dice/blob/master/Dice.php as an example).

I offer my help on programming this, although I'm not an expert.

**Comment by ChrisFrench** [comment]
We use fatfree as our base for our library.

https://github.com/dioscouri/f3-lib

We have decency in injection, you can use the library or copy how we have
it.

**Comment by aslabs** [comment]
The whole point of f3 in my humble opinion,  is to have a framework that doesn't force you on anything, and being lightweight it doesn't hit your app performance and mostly doesn't take from you the freedom of vanilla php. 
In the other hand the framework should accomplish basic tasks.

What you sent me, is a good use of the framework,  but I would never add all that stuff in my app. No offence.
It whould be against f3 philosophy itself.

I would have done a small plugin of a bounch of files, no more.

**Comment by xfra35** [comment]
@aslabs can you show an example of how you would see it working?

The framework offers a global hive which can be used as a central repository for services or dependencies, so there's probably not much to add to have it cover all the possible use cases.

For example, at the moment, a DB dependency can be implemented like this:
```php
//index.php
$f3->DB=function()use($conf){
    if (!Registry::exists('DB'))
        Registry::set('DB',new DB\SQL($conf['dsn'],$conf['user'],$conf['pwd']));
    return Registry::get('DB');
};
//model.php
class Model extends DB\SQL\Mapper {
  function __construct(){
    $f3=Base::instance();
    parent::__construct($f3->DB(),'mytable');
  }
}
```

**Comment by aslabs** [comment]
Well using the hive make a lot of sense, but I wanted to use the 1 general class to inject any class anywhere.

for example the reflection class can be used to inject a dependencies and the hive to achieve lazy-loading (a class instance is created or retrieve only when used).
Then a normal class could use injected classes as:

```php
//Given:
class A {
  function get(){
     ...
  }
}
//Then:
class B {
  var $a;
  function __construct(A $a){
    $this->a = $a;
  }
  function custom(A $a){
    $this->a->get();
  }
}
//OR
class C {
  __construct(){
    ...
  }
  function custom(A $a){
    $a->get();
  }
}
```

**Comment by nanawel** [comment]
Just my two cents on this topic, I've just [proposed a tiny modification to allow using a third-party DI library on fatfree-core](https://github.com/bcosca/fatfree-core/pull/221). I'm using it with PHP-DI and it works very well (but of course this library itself is not as light as the rest of F3).

**Comment by NeoVance** [comment]
Just use [auryn](https://github.com/rdlowrey/auryn) or [Dice](https://github.com/Level-2/Dice).

Use composer's autoloader or F3's AUTOLOAD property if you don't want to pollute your F3 lib directory with third party files.

I don't see much use in re-inventing the wheel here.

**Comment by neosin** [comment]
I use F3 hive or [Dice](https://github.com/Level-2/Dice)

**Comment by pgrzego** [comment]
@neosin @xfra35 Isn't hive more a Service Locator in this scenario? There is a slight difference between the two patterns, but it may be important, as some call Service Locator an antipattern (and I kinda see their point)...

**Comment by ikkez** [comment]
closing this, because we have configurable dependency injection container now, see https://github.com/bcosca/fatfree-core/pull/221
@pgrzego yes using the HIve would be a service locator and I can see the point between those two implementations too.
