### ISSUE TITLE
Minify Single-line comment

### ISSUE THREAD

**Issue by Vincentdevreede** [bcosca/fatfree#870]
When you use the minify function and in your JS file you have a comment on the last line, i will not remove the full comment only the two slashes (//). Which will result in a JS error.

It can be fixed with a simple modification of minify function:
Original: 
```
// Single-line comment
$str=strstr(
	substr($src,$ptr+2),"\n",TRUE);
$ptr+=strlen($str)+2;
```

Modified: 
```
// Single-line comment
$str=strstr(
	substr($src,$ptr+2),"\n",TRUE);
$ptr+=(empty($str)) ? strlen(substr($src,$ptr)) : strlen($str)+2;
```

**Comment by ikkez** [comment]
fixed
