### ISSUE TITLE
Template filters

### ISSUE THREAD

**Issue by MaximZavitaev** [bcosca/fatfree#872]
Now, the filters are not added dynamically expanding class of "Templates"?  Or, for some reason, it is broken?

**Comment by ikkez** [comment]
Instead of extending the class, you now just use a callable string to register a filter:
`\Preview::instance->filter('badwords','\Helper::instance()->badwords');`
http://fatfreeframework.com/preview#filter

**Comment by MaximZavitaev** [comment]
I saw it. I do not know how much it's convenient. Well, we will create a class, extend \ Prefab already prescribe filters. Thank you. And for some reason, this feature was removed?

**Comment by MaximZavitaev** [comment]
And why not create any chat room, in which people working with FatFree, could help each other and share their experiences of using this framework. For example used for this purpose Gitter.

**Comment by KOTRET** [comment]
see http://fatfreeframework.com/development#Support for informations about the F3-Channel in freenode

**Comment by MaximZavitaev** [comment]
Was there. Is it really so few people are FatFree?

**Comment by KOTRET** [comment]
please open a seperate issue for that :grin:

**Comment by bcosca** [comment]
Closing this topic. Issue diverted.
