### ISSUE TITLE
Template Var in include tag not working?

### ISSUE THREAD

**Issue by developer99** [bcosca/fatfree#873]
test.html contains...
```
{{ @APP_BASE }}
<include href="{{ @APP_BASE }}/view/page-element/html-head.html" />
```
```echo Template::instance()->render('page/test.html')``` outputs the following...

http://domain.com/desktop
Internal Server Error
Unable to open {{ @APP_BASE }}/view/page-element/html-head.html

What in the world am I doing wrong?  Thanks.  Love this framework!

**Comment by ikkez** [comment]
It is `<include href="{{ @APP_BASE.'/view/page-element/html-head.html' }}" />`

**Comment by developer99** [comment]
Perfect.  Thanks.
