### ISSUE TITLE
Allowed memory size of 536870912 bytes exhausted

### ISSUE THREAD

**Issue by ashokkumarjuly** [bcosca/fatfree#874]
Suddenly my site stopped working and throwing the error  " PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 3999336473 bytes) in /home/xxxxxx/public_html/lib/base.php on line 1602 ". 

F3 VERSION='3.2.2-Release';
I do phpinfo on my server and found out the memory_limit as 512 M.

But When I downloaded the files and run it on my local server, it working normal.
I have been googled for almost a day about this issue in F3,  still no positive sign.
Anyone have idea, please share it.

![bug1](https://cloud.githubusercontent.com/assets/4641914/10278092/32757f5e-6b78-11e5-8015-731c76b3f3e5.jpeg)

**Comment by ikkez** [comment]
That logs do not help that much. This could be anything and doesn't need to be F3 releated. On line 1602 @3.2.2-Release, we'll find the exception handler: https://github.com/bcosca/fatfree/blob/3.2.2/lib/base.php#L1602
I guess your script or server already produces an error, even before F3 finished starting.

**Comment by ashokkumarjuly** [comment]
Thanks for spending your time,
In my index.php 
I write out  echo "sample";  and die ,  before the line " $f3 = require('lib/base.php'); " -> the browser displays the text.
But when i placed the script after the line, it is not rendering any thing on browser, then if i go to error log & i  got is "memory allocation error" .

I didn't either a issue is on hosting end / our f3 end.

**Comment by xfra35** [comment]
Try to set `DEBUG=0` to see if it helps.

**Comment by xfra35** [comment]
You can check if your environment is free of error by running `var_dump(error_get_last());` at the very beginning of your code. It should output `NULL` if no error happened before.

**Comment by ashokkumarjuly** [comment]
Hi @xfra35 ,

1) If i set debug = 0 in config.inc
Then my error log file output is,

[05-Oct-2015 17:21:29 Asia/Kolkata] PHP Warning:  set_exception_handler() expects the argument (33) to be a valid callback in /home/xxxx/public_html/lib/base.php on line 1602
[05-Oct-2015 17:21:29 Asia/Kolkata] PHP Warning:  set_error_handler() expects the argument (33) to be a valid callback in /home/xxxx/public_html/lib/base.php on line 1608
[05-Oct-2015 17:21:29 Asia/Kolkata] Fatal error: set_error_handler() expects the argument (33) to be a valid callback
[05-Oct-2015 17:21:29 Asia/Kolkata] PHP Warning:  array_filter() expects parameter 2 to be a valid callback, no array or string given in /home/xxxx/public_html/lib/base.php on line 994
[05-Oct-2015 17:21:29 Asia/Kolkata] PHP Warning:  Invalid argument supplied for foreach() in /home/xxxx/public_html/lib/base.php on line 1000
[05-Oct-2015 17:21:29 Asia/Kolkata] PHP Fatal error:  Function name must be a string in /home/xxxx/public_html/lib/base.php on line 687

2) If i put  " var_dump(error_get_last());", then in browser the output is NULL only.

**Comment by xfra35** [comment]
Which version of PHP are you running? 5.3 is the minimum requirement. From your log file, it looks like closures are not supported..

**Comment by ashokkumarjuly** [comment]
When i do php info, it showing the PHP Version 5.4.45

**Comment by xfra35** [comment]
What's at line 1602?

**Comment by ashokkumarjuly** [comment]
https://github.com/bcosca/fatfree/blob/3.2.2/lib/base.php#L1602

**Comment by xfra35** [comment]
So nothing different from the repository? I'm trying to understand why the error identifies the callback as "33" in `PHP Warning: set_exception_handler() expects the argument (33) to be a valid callback`

**Comment by ashokkumarjuly** [comment]
@xfra35  Thank for your effort once again.
Yes, i hadn't modified the original repository file,

**Comment by xfra35** [comment]
Well, if your site used to work and now fails with such errors as " array_filter() expects parameter 2 to be a valid callback, no array or string given", I'd suggest to ask your hosting provider what has changed.

It looks as if you're running a version of PHP 5.4 with no support for anonymous functions.. I didn't know it was possible :P

**Comment by ashokkumarjuly** [comment]
OKay thanks for your effort, I will go to hosting provider with the information you had provided.

**Comment by bcosca** [comment]
Ample time has been allotted to this issue without feedback. Closing.
