### ISSUE TITLE
Multilingual Support and passing Variables

### ISSUE THREAD

**Issue by Norcoen** [bcosca/fatfree#877]
Hi guys,
I just started learning F3 by trying some stuff from the UserGuide.

I can't figure out some things concerning templates, multi language and how variables and functions are passed between them, e.g. why there is a zero preprended to variables in language files.

dict/en.php
```php
<?php
return array(
    'love'=>'I love F3',
    'today'=>'Today is {0,date, custom, %d %B %Y}',
    'pi'=>'{0,number}',
    'money'=>'Amount remaining: {0,number,currency}'
);
```
ui/test.html
```html
<h1>{{ @love }}</h1>
<p>
{{ @today,time() | format }}.<br />
{{ @money,365.25 | format }}<br />
{{ @pi, 3.1415 | format }}
</p>
```
Does 0 mean take the n-th variable passed to it?
If so, how do I pass multiple?

Other thing that is confusing me is that it is declared 0,date yet we pass a timestamp from time()-function.
So I guess it's n-th variable (0) passed, run through function (date)

Also, why is | format passed to it? Where is it coming from and what does it do?
As you can see I found out how to customize the date format, so I wonder what the other format is used for.

Kind regards,
Frank

**Comment by ikkez** [comment]
> Does 0 mean take the n-th variable passed to it?

Yes

>  If so, how do I pass multiple?

`{{ 'Current date: {0,date} - Current time: {0,time} - Other date: {1,date} - Other time: {1,time}', time(), strtotime('2015-10-13 12:15') | format }}`

**Comment by Norcoen** [comment]
aaaaah, thank you very much, I think I get it now.

So date is also a shortcut to telling format() how to handle the incoming string instead of doing something similar to this?
```echo $f3->format('Name: {0} - Age: {1}','John',23); //outputs the string 'Name: John - Age: 23'```

**Comment by ikkez** [comment]
Exactly! See the various available format types, listed in the documentation that I've linked above ;)
Also have a look at our google board https://groups.google.com/forum/#!forum/f3-framework which is the more suitable place for questions like this. We usually use github issues only for code related topic.
So be welcome to F3, and good luck :)
