### ISSUE TITLE
csrf return blank on first visit

### ISSUE THREAD

**Issue by chinkung** [bcosca/fatfree#878]
csrf should be generated since first session is created

STR:
1. Remove all session from DB
2. Write code to call new session and print csrf via csrf() method
$s = new DB\SQL\Session($db);
echo $s->csrf();
3. Open browser and visit page

Expected result:
csrf() return result.

Actual result:
csrf() return blank

This has been tested on 3.5.0 and I have looked in DB and found csrf column blank.

**Comment by Rayne** [comment]
I don't use Fat-Free Framework's CSRF protection feature, but this looks like a bug to me.

**Example with `CACHE` backend**

```php
$f3 = Base::instance();
$f3->set('CACHE', true);

$f3->route('GET *', function(Base $f3){
	$session = new Session();

	var_dump(['SESSION.csrf' => $f3->get('SESSION.csrf')]);
	var_dump(['$session->csrf()' => $session->csrf()]);

	$f3->set('SESSION.csrf', $session->csrf());
});

$f3->run();
```

**First GET**

```
array (size=1)
  'SESSION.csrf' => null

array (size=1)
  '$session->csrf()' => boolean false
```

`Session->csrf()` returns `false`, but should return a valid token for the next request.

**Second GET**

```
array (size=1)
  'SESSION.csrf' => boolean false

array (size=1)
  '$session->csrf()' => string '1o25572lk25tb.3vhlehsw0ukgo' (length=27)
```

As expected, `SESSION.csrf` holds the invalid and predictable `false` token.

**Third GET**

```
array (size=1)
  'SESSION.csrf' => string '1o25572lk25tb.3vhlehsw0ukgo' (length=27)

array (size=1)
  '$session->csrf()' => string '1o25572lk25tb.b3c1clj78w65' (length=26)
```

**Comment by Rayne** [comment]
The results for the latest commit (https://github.com/bcosca/fatfree-core/commit/95178293f689f259c788b2b4493496c4c584530c):

- [X] Cache
- [X] JIG
- [ ] Mongo (Not tested)
- [X] SQL

Source: [Cache, JIG, Mongo and SQL](https://gist.github.com/Rayne/b5bc2914ed3dd9243359)

**Comment by xfra35** [comment]
Just tested with Mongo. Thanks @Rayne.
