### ISSUE TITLE
| raw - template error

### ISSUE THREAD

**Issue by r3sist** [bcosca/fatfree#879]
Hi!

I tried to render some unescaped data in my template file like this:

`{{ strip_tags(@result.summary | raw, '<br><small><em><i><i><a><b><strong>') }}`

And the rendered temporary php file became:

`<?php echo $this->raw(strip_tags($result['show']['summary']); ?>` - Note the missing bracket at the end.

Without the `| raw` suffix it works fine. The plus parameter of the strip_tags() function doesn't affect the result.

Is it a bug, or am I wrong? Thank you!

F3: `VERSION='3.5.0-Release';`

(I know it is not the best practice, and using strip_tags() not even safe.)

**Comment by geniuswebtools** [comment]
Try: 

{{ strip_tags(@result.summary, '<br><small><em><i><i><a><b><strong>')   | raw }}

**Comment by r3sist** [comment]
Works! It's quite obvious now...

Thank you very much
