### ISSUE TITLE
php7mar Results (Checking F3 PHP7 compatibility)

### ISSUE THREAD

**Issue by phaziz** [bcosca/fatfree#880]
# https://github.com/Alexia/php7mar

#### /base.php
* funcGetArg
 * Line 24: ` $args=func_get_args();`
 * Line 756: ` $args=func_get_args();`
* foreachByReference
 * Line 141: ` foreach ($url as &$var) {`

#### /db/jig/mapper.php
* foreachByReference
 * Line 159: ` foreach ($data as $id=>&$doc) {`
 * Line 248: ` foreach ($data as $id=>&$doc) {`

#### /db/sql/mapper.php
* foreachByReference
 * Line 257: ` foreach ($result as &$row) {`
 * Line 258: ` foreach ($row as $field=>&$val) {`

#### /image.php
* foreachByReference
 * Line 52: ` foreach ($color as &$hue) {`
* funcGetArg
 * Line 436: ` $args=func_get_args();`
 * Line 450: ` $args=func_get_args();`

#### /smtp.php
* foreachByReference
 * Line 187: ` foreach ($headers as $key=>&$val) {`

#### /template.php
* arrayValueByReference
 * Line 276: ` $stack[$depth]=&$node;`

Is there a plan to fix this?

**Comment by ikkez** [comment]
Would you please explain your request. These results doesn't say anything. As far as I can see they are only recommendations for PHP7 only improvements and hints for potential issues. I think the code will continue to work as it is in PHP7.

**Comment by bcosca** [comment]
Closing for lack of clarity. PHP7 still supports references in foreach and arrays.
