### ISSUE TITLE
SQL UNION Support

### ISSUE THREAD

**Issue by thomascoding** [bcosca/fatfree#881]
I tried to make query like this

    $sql = '(SELECT user_id, max(time) as time FROM `messages` WHERE `recipient`= '.$user_id.' GROUP BY user_id)
      UNION 
    (SELECT recipient, max(time) as time FROM `messages` WHERE `user_id`= '.$user_id.' GROUP BY recipient)
    ORDER BY time DESC';
    $list = $this->db->exec($sql);

but result was some integer value.

Fix below (file sql.php line 201) added \(* to regex

				if (preg_match('/^\s*'.
					'\(*(?:EXPLAIN|SELECT|PRAGMA|SHOW|RETURNING)\b/is',$cmd) ||

**Comment by ikkez** [comment]
Similar issue occurred here https://groups.google.com/forum/#!topic/f3-framework/5-5NTCVbjwA

**Comment by xfra35** [comment]
Should be fixed now.
