### ISSUE TITLE
Extending Template with custom HTML Tags not working without XHTML

### ISSUE THREAD

**Issue by Norcoen** [bcosca/fatfree#883]
I tried following the documentation to try extending the parser for the "img" tag
http://fatfreeframework.com/extended-templating

It does not seem to work with HTML4/5 tags in some cases, only with properly closed Tags as required in XHTML.
http://www.w3schools.com/tags/tag_img.asp

So this sample code in the documentation should reproducibly not work
```php
\Template::instance()->extend('img',function($node){
	var_dump($node);
	/*
	array(1) {
		["@attrib"]=> array(1) {
			["src"]=> string(25) "{{'ui/images/'.@article.image}}"
		}
	}
	*/
});
```
when your template has non closed image tag.

**Comment by Norcoen** [comment]
Maybe something is weird in my installation again or I really found a bug this time ... :D
It seems to work if there is at least ONE correctly closed image tag, so this is working fine:
```html
<div id="logos">
  <img src="" />
  <img id="left-logo" alt="test" src="pics/left.png">
  <a href="index.php">
    <img id="right-logo" alt="test2" src="pics/right.png">
  </a>
</div>
```

**Comment by Rayne** [comment]
Duplicate of https://github.com/bcosca/fatfree-core/issues/75. Please have a look at the patch https://github.com/bcosca/fatfree-core/pull/77.

**Comment by Norcoen** [comment]
weird, it was patched long before I checked out the repository.
I'll update my installation and see if it works.

**Comment by Norcoen** [comment]
turns out I checked out fatfree not fatfree core, so I had 3.5.0 release, not the updated master branch...
Anyhow it got even weirder now, since it works on the first visit, but when I refresh the page it does not work again.

**Comment by Norcoen** [comment]
Never mind, it's working as intended. Since we don't return anything it does not put the result in the pre-compiled template.
Although a hint in the documentation might be nice to avoid confusion.
