### ISSUE TITLE
Suggestion: Allow sending output buffer contents on Base->abort()

### ISSUE THREAD

**Issue by rbiegel** [bcosca/fatfree#886]
Since version 3.5.0 there is the new function `abort()` in the Base class. The online API reference states:
> ...to abort the connection to the client and send the current response...

The current implementation doesn't fit this description, since `ob_end_clean()` is called there and HTTP header `Content-Length: 0` is hardcoded.

My suggestion is to add an optional parameter to select the behavior of `abort()`. Something like:
```
function abort($senddata=false) {
  @session_start();
  session_commit();
  if ($senddata)
    $bufsize=ob_get_length();
  else
    $bufsize=0;
  header("Content-Length: $bufsize");
  while (ob_get_level()) {
    if ($senddata)
      ob_end_flush();
    else
      ob_end_clean();
  }
  flush();
  if (function_exists('fastcgi_finish_request'))
    fastcgi_finish_request();
}
```
Since I'm not sure about the use and behavior of `ob_*()` I'm posting here only as suggestion. The code works for my simple application with a single-depth template.

**Comment by ikkez** [comment]
please check the 3.5.1-dev version at https://github.com/bcosca/fatfree-core/blob/master/base.php#L1589
It already includes some modifications here.

**Comment by rbiegel** [comment]
Code from dev works a treat. Sorry for the noise.
