### ISSUE TITLE
Custom Class Inherit from Prefab Reinstantiate In Every Calls

### ISSUE THREAD

**Issue by lsafelix75** [bcosca/fatfree#887]
I have a plugin  class inherited from Prefab because I want to keep 1 copy only and maintain its lifespan and not destroying it. 

When I define $x= \X::instance() on an index page for a specific route/page, the first time it runs,  the statement returns a fresh new instance as expected. However,  when I access the same page again,  $f3 can't find the previous X instance anymore and instead create a new one.

Is this a bug or expected behavior?  If not a bug,  how do i maintain the same object like View,  Base?  
Thanks

**Comment by ChrisFrench** [comment]
Prefab are constant  for a single request

**Comment by lsafelix75** [comment]
OK but why it creates another copies for subsequent calls? My understanding
is Prefab creates once and use multiple times

**Comment by xfra35** [comment]
You're confusing `Prefab` and `Cache`:

**Prefab:**
Instance is created once in a single script call
```php
$x=\X::instance(); // first instantiation
//...
$x=\X::instance(); // reuse of the same instance
```

**Cache:**
Data is read once and shared with subsequent script calls
```php
$cache=\Cache::instance();
if (!$mydata=$cache->get('mydata')) {
  $mydata=...; // data is read here on the first call
  $cache->set('mydata',$mydata);
}
// $mydata available here on every call
```

**Comment by lsafelix75** [comment]
That is right. Thanks.
