### ISSUE TITLE
Undefined vars in code, where they come from ?

### ISSUE THREAD

**Issue by Ifnot** [bcosca/fatfree#889]
Hi,

I am using PhpStorm as primary IDE for all my projects, using Laravel for my big projects and fatfree for the lightweight ones.

By looking for `lib/base.php` i got several "majors problems" thrown by PhpStorm. Here is the undefined used vars i found :

$pos on https://github.com/bcosca/fatfree/blob/master/lib/base.php#L824
$mod on https://github.com/bcosca/fatfree/blob/master/lib/base.php#L831
$tag on https://github.com/bcosca/fatfree/blob/master/lib/base.php#L836
$data on https://github.com/bcosca/fatfree/blob/master/lib/base.php#L837
$thousands_sep on https://github.com/bcosca/fatfree/blob/master/lib/base.php#L844
$negative_sign on https://github.com/bcosca/fatfree/blob/master/lib/base.php#L867
$positive_sign on https://github.com/bcosca/fatfree/blob/master/lib/base.php#L871
vars from https://github.com/bcosca/fatfree/blob/master/lib/base.php#L878 to https://github.com/bcosca/fatfree/blob/master/lib/base.php#L881
and $decimal_point + $thousands_sep in https://github.com/bcosca/fatfree/blob/master/lib/base.php#L890 / https://github.com/bcosca/fatfree/blob/master/lib/base.php#L891 and just below

Is it me or something went wrong here ?

**Comment by ikkez** [comment]
That's just fine. PhpStorm isn't able to inspect vars which are [extracted](http://php.net/manual/en/function.extract.php) from the environment at runtime. The variables come form `extract($conv);` and `extract($expr);`, which comes from [localeconv](http://php.net/manual/en/function.localeconv.php) and the format expression itself.
ref: https://github.com/bcosca/fatfree/pull/865

**Comment by Ifnot** [comment]
Hoo, i got it. Didnt notices the extract. Sorry for thé incnvenience :-)
