### ISSUE TITLE
Using stdObject (or any object) from within templates

### ISSUE THREAD

**Issue by Fohlen** [bcosca/fatfree#891]
Is there any chance I can use stdObjects within repeating statements using F3's templating?

**Comment by Rayne** [comment]
It's possible to use objects within repeating statements.

Please be careful with structures which aren't scalars or arrays when `ESCAPE` is enabled:

> **Notice:** To invoke the callback `$func` on objects `PHP >= 5.4` is required. Otherwise objects are returned without further processing. Please keep in mind that the returned objects are clones and the callback is only applied to accessible non-static properties.
>
> [Source](http://fatfreeframework.com/base#recursive)

**Template**

```
<repeat group="{{ @articles }}" value="{{ @article }}">
	<h1>{{ @article->title }}</h1>
</repeat>
```

**Full Example**: [ Fat-Free Framework: Templating with objects and the `Template` class](https://gist.github.com/Rayne/71bae67f0e1d804d1ed3)

**Comment by Fohlen** [comment]
Alright, got it working.
