### ISSUE TITLE
DB $log and long running application like socket

### ISSUE THREAD

**Issue by Abbadon1334** [bcosca/fatfree#896]
Hi,
i know that only 1% ( i'm optimistic ) use f3 in long running applications like sockets.

I tried to use it in combination with reactphp and i found a "leak" in this special case.

by default f3 mapper logs all queries, if you use it in a long running process you end up with the variable $DB->log filled with all the executed queries.

Can a config variable be added to disable this?

Something like DB_LOG_QUERY = false

**Comment by Rayne** [comment]
A side note for later: injecting/defining logging services (e.g. PSR-3 `Logger` or callbacks) or allowing to clear the logged values is also interesting. This could be a task for Fat-Free Framework v4's event system.
