### ISSUE TITLE
Web->recieve method slug callback missing parameter 

### ISSUE THREAD

**Issue by sand123** [bcosca/fatfree#898]
```php
$files = $web->receive(function($file,$formFieldName){
        return true;
    },
    true,
    function($fileBaseName, $formFieldName){
        return "uploaded_{$fileBaseName}";
    }
);
```

If 3rd param in `recieve()` is a callback, then, according to docs http://fatfreeframework.com/web#receive, it should accept 2 params

But in `web.php line 194` only one param is passed

```php
(is_callable($slug)? $slug($base): ($this->slug($parts[1]). (isset($parts[2])?$parts[2]:'')))
```

**Comment by ikkez** [comment]
That 2nd parameter is only used in `POST` uploads, line 228, see https://github.com/bcosca/fatfree-core/blob/master/web.php#L228

the part in line 194 is only for `PUT` uploads, and there is no form field available, which could be pushed to the callback, at this point.

**Comment by sand123** [comment]
Now I see, should look through sourcecode more carefully
