### ISSUE TITLE
Problem with DB\SQL\Session on Microsoft SQL Server

### ISSUE THREAD

**Issue by ethanpil** [bcosca/fatfree#899]
I often use the session handler with MySQL. A few days ago, I transitioned an existing app to use the session handler with a Microsoft SQL Server for the first time, instead of a MySQL server. The code has been working fine via MySQL.

On first run, it created the sessions table as expected, but it seems that it isn't working properly after that.

```
Internal Server Error
PDOStatement: [Microsoft][SQL Server Native Client 11.0][SQL Server]Table 'sessions' does not have the identity property. Cannot perform SET operation.
```

I tried the same code with only one switch back to the MySQL DSN, and I also tried via the JIG DSN and everything worked as expected, so it seems like a MSSQL implementation issue here...

FYI, this was posted to the Google Groups a few days ago.
https://groups.google.com/forum/#!topic/f3-framework/qMOy_veelCg

**Comment by ikkez** [comment]
finally fixed 😅 
If there's a `session` table existing already, delete that first.
