### ISSUE TITLE
JIG: fields() command don't returns all fields

### ISSUE THREAD

**Issue by chule143** [bcosca/fatfree#900]
Hi guys, I'm new with the FatFree framework that I really loves :)

I really don't know I'm doing wrong but when I have the next json schema:

```json
{
    "567ddb04aa51d7.51374121": {
        "name": "Mack Koch",
        "status": "1"
    },
    "567de4359564b7.23212048": {
        "name": "Trina Friesen",
        "city": "Keshawnville",
        "status": "0"
    }
}
```
The command ```$fields = $table->fields();``` returns "name" and "status" but not "city".

But with the next Json schema the command ```$fields = $table->fields();``` returns "name", "city" and "status"

```json
{
    "567ddb04aa51d7.51374121": {
        "name": "Mack Koch",
        "city": "Keshawnville",
        "status": "1"
    },
    "567de4359564b7.23212048": {
        "name": "Trina Friesen",
        "status": "0"
    }
}
```

**Comment by bcosca** [comment]
Like the built-in MongoDB (a document-centric storage) mapper, the Jig mapper returns only the fields/keys in the **current** document.

**Comment by chule143** [comment]
Hi @bcosca, thanks for your answer :) , I looked about, and I was thinking something like this: [http://snipplr.com/view/59334/](http://snipplr.com/view/59334/), iterate over the collection and get a unique values of the keys

**Comment by geniuswebtools** [comment]
I would recommend extending the Jig mapper and using the beforesave() event handler.  

http://fatfreeframework.com/cursor#beforesave,aftersave

When you extend the class you can define the list of keys each document should have.  When the record is saved you can check for any of the missing keys and add them as empty or null values.

**Comment by chule143** [comment]
Hi @geniuswebtools, the link looks great!!, but I'm building a dynamic system to grant the ability to create collections and fields dynamically, so the frontend don't know what fields are available from the backend.

**Comment by geniuswebtools** [comment]
If that's the case, I would recommend using the aftersave() event handler and keeping 1 Jig document that stores all of the defined keys.  The biggest issues I see with what you want, is that as the documents and the data inside of the documents grow, your application will slow down having to loop every request to find unique keys.  If you cache them and simply read the cache, you can better predict how your application will preform over time.

**Comment by ikkez** [comment]
Jig is a **schema-less** NoSQL storage. If you want to keep track of your record fields, implement that elsewhere.
