### ISSUE TITLE
Template <include> and relative path

### ISSUE THREAD

**Issue by chutburin** [bcosca/fatfree#902]
when including another template
include href="/template/user/navbar" It only works with absolute paths
if it's include href="navbar" should look good but not working

AND 
link href="{{ @val }}/path/..." work fine
But include href="{{ @val }}/path/..." not working
I had to change it to "{{ @val }}.'/path'" just like the doc say.

**Comment by ikkez** [comment]
The include path depends completely on your [**UI**](http://fatfreeframework.com/quick-reference#UI) var setting. If configured correctly, it will also work with relative paths, i.e. `$f3->UI = 'template/user/';`
The correct token concatenation syntax is: `href="{{@val.'/path'}}"`
