### ISSUE TITLE
HTTP_RAW_POST_DATA

### ISSUE THREAD

**Issue by hmacube** [bcosca/fatfree#903]
Hello
When I send POST request with parameters there is no problem but when In request body I place data this error shown

Fatal error
"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead."

**Comment by geniuswebtools** [comment]
This isn't a bug, you should post your question to the Google group or ask on the IRC channel.  You can get more information regarding support from here:

http://fatfreeframework.com/development#Support

Asking for support in the right place will get you a better response to your question faster ;)

**Comment by ikkez** [comment]
GIYF: http://stackoverflow.com/questions/26261001/warning-about-http-raw-post-data-being-deprecated
set `always_populate_raw_post_data` to `-1` in your `php.ini`, restart apache and cross the finger.
good luck.
duplicate #804
