### ISSUE TITLE
IBM DB2 Database Not Working

### ISSUE THREAD

**Issue by liko28s** [bcosca/fatfree#904]
Hi Guys, i'm trying to start with F3 an web site that use IBM DB2, however is not working.

I've modified the /lib/db/sql to matching with the [#69](https://github.com/ikkez/fatfree/commit/049d3b1e6d6edbef33775c491c5a70efd0f5d749) and [049d3b1e6d6edbef33775c491c5a70efd0f5d749](https://github.com/ikkez/fatfree/commit/049d3b1e6d6edbef33775c491c5a70efd0f5d749)
but no luck
I think in the current release IBM iSeries, DB2 aren't properly implemented.

Any idea?

**Comment by ikkez** [comment]
We dropped the IBM DB2 support with F3 v3.0 because the PDO driver is incomplete (for our needs) and not maintained anymore (see https://pecl.php.net/package/PDO_IBM). Better choose another database engine, there are a lot of alternatives, so no need to beat a dead horse here.
