### ISSUE TITLE
map() function not working at all

### ISSUE THREAD

**Issue by mrigess** [bcosca/fatfree#910]
I included fatfree via composer in a project. After "composer dump-autoload" I am able to kickstart fatfree with just few lines.

`require_once("vendor/autoload.php");`

`$f3 = Base::instance();`
`$f3->config("app/config.ini");`
`$f3->config("app/routes.ini");`

`$f3->run();`

in index.php file.

routes.ini has [routes] and [maps] variables. [routes] entries are obeyed well but not  the [maps] entry. I am creating RESTful api server so need the map() work for me. I even tried specifying maps directly via map function. that also didn't work. 

`$f3->map('/blogger','Blog'); #not working`

By the way, config.ini has set AUTOLOAD var properly.

**Comment by xfra35** [comment]
Try `echo class_exists('Blog')` to see if `Blog` is in the `AUTOLOAD` path.

**Comment by mrigess** [comment]
Pretty dumb issue I must say. On rush setting up nginx and apache on same server, I disabled mod_rewrite of apache. Thus the problem. Thanks for supporting @xfra35. re-enabling rewrite solved everything.
