### ISSUE TITLE
MongoDB PHP Driver 1.1.2 + F3

### ISSUE THREAD

**Issue by AmarettoSlim** [bcosca/fatfree#912]
Hi Everyone,

Is anyone else using PHP 5.6 and the MongoDB 1.1.2 PHP driver with F3?

I'm getting the following:

```
"Fatal error: Class 'MongoDB' not found"
f3/lib/db/mongo.php:107]

```
When using a basic script like:

```
    $f3 = require('resources/php/frameworks/f3/lib/base.php');
    $f3->set('DEBUG', 1);
    $f3->config('config.ini');

    $f3->route('GET / ',
        function($f3) {

            $db = new DB\Mongo('mongodb://localhost:27017');

       }
    );

    $f3->run();
```

But I know PHP can talk to MongoDB just fine because the following sample (without F3) works fine:

```
    $manager = new MongoDB\Driver\Manager("mongodb://localhost:27017");

	$filter = array();
	$options = array(
	    /* Only return the following fields in the matching documents */
	    "projection" => array(
	        "name" => 1,
	        "type" => 1,
	    ),
	);

$query = new MongoDB\Driver\Query($filter, $options);

$cursor = $manager->executeQuery("demo.beer", $query);

foreach($cursor as $document) {
    var_dump($document);
}
```

Looks like a compatibility issue ... any idea on if F3 will support the 1.1.2 driver in the future?

Thanks!
AmarettoSlim

**Comment by ChrisFrench** [comment]
The error you are getting means the php  driver is not installed.

**Comment by ptdev** [comment]
The old mongo driver that f3 supported has been deprecated. You can still use it though.

But if you wish to use the new driver as you seem to be trying to, then you should probably use the recommended php library (https://github.com/mongodb/mongo-php-library). This library is installed using composer and provides the new driver with a similar API as the legacy driver.
Not sure if the F3 wrappers will work with it though.

It would be nice to have F3 support the new driver as it seems to be where future development as well as php7 and hhvm support is going to be happening. Maybe put it as a TODO for v4?

more info at:
http://php.net/manual/en/set.mongodb.php
http://mongodb.github.io/mongo-php-library/
https://github.com/mongodb/mongo-php-library
https://www.mongodb.com/blog/post/call-feedback-new-php-and-hhvm-drivers

**Comment by sn0opy** [comment]
Has been reported already: https://github.com/bcosca/fatfree-core/issues/111
