### ISSUE TITLE
get db error code

### ISSUE THREAD

**Issue by Phisherman** [bcosca/fatfree#914]
Hi,

I'm using the `DB\SQL\Mapper` mapper and would like to handle DB errors
not with the `$f3->get('ONERROR')` function. Is this possible?

**Comment by KOTRET** [comment]
errorhandlers are stackable, so just add your own errorhandler or use an existent.

**Comment by ikkez** [comment]
You can enable the PDO Exceptions like this:
```php
$f3->set('DB', new DB\SQL('mysql:host=localhost;dbname=test;charset=utf8',
 'username', 'password', array(\PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION)));
```
Now try to wrap your mapper calls:
```php
try {
    $mapper->save();
} catch(Exception $e) {
    echo 'Sorry, something went wrong: '.$e->getMessage();
}
```

**Comment by Phisherman** [comment]
@ikkez Thanks. That's what I had been looking for!

**Comment by emanwebdev** [comment]
> enable the PDO Exceptions 

imho worths figuring in the Doc,

but where?
here http://fatfreeframework.com/sql#schema 
or
around here ? 
http://fatfreeframework.com/sql#pdo

**Comment by ikkez** [comment]
It is mentioned in the constructor example here http://fatfreeframework.com/sql#Constructor but not explicit described, yeah that's true.

**Comment by emanwebdev** [comment]
@ikkez great, imho it's enough 
thanks for the link
