### ISSUE TITLE
Error SQLSTATE[42P01] with postgres and non integer primary keys

### ISSUE THREAD

**Issue by ccrobopid** [bcosca/fatfree#916]
I've this table:

```
create table usuarios(
    id_usuario  character varying(64) not null,

[...]
    constraint id_usuario_pkey primary key (id_usuario)
);
```

and this class:

```
Class Users extends DB\SQL\Mapper {

    public function __construct() {
        $db = DBFactory::getInstance();

        parent::__construct($db,'usuarios');
    }
[...]
}
```

When I try to insert a new record with

```
$user = new Users;
// populate $user with valid values
$user->id_usuario = 'someuniqueidvalue';

// and then insert into db
$user->insert();
```

It gives a very strange error:
**SQLSTATE[42P01]: Undefined table: 7 ERROR: no existe la relación «usuarios_id_usuario_seq»**
Translation: The relation «usuarios_id_usuario_seq» doesn't exists.

It's true that this sequence (the spanish text is a bad translation in my opinion) doesn't exists. But this is because my primary key is not a sequence. It's a varchar.

IMHO this is a bug because not all primary keys are autoincrementable values. I find that not desirable at all from a security point of view.

I've traced the error to line 425 and 426 of f3/db/sql/mapper.php

```
if ($this->engine!='oci' )
                $this->_id=$this->db->lastinsertid($seq);
```

I've changed them in my version to:

```
if ($this->engine!='oci' && count($pkeys) == 1 && $this->fields[$pkeys[0]]['pdo_type'] == \PDO::PARAM_INT)
                $this->_id=$this->db->lastinsertid($seq);
```

So, if we have more than one primary key or the primary key is not of type int, then don't invoke lastinsertid which is what returns that error.

Maybe someone more knowledgeable could check if this is a correct fix

Thanks for this awesome library!

Carlos

**Comment by bcosca** [comment]
F3 is aware of autoincrement fields if defined as such in the schema, but I'm not sure if oci reveals this metainfo when requested by PHP.

**Comment by ccrobopid** [comment]
Hello,

If it helps, I'm using pdo_pgsql driver in Windows 7 with Postgres v9.0.4.

As far as I know oci is for oracle... but maybe I'm wrong.

**Comment by ikkez** [comment]
That's okay. Got nearly the same setup at home. I'll have a look soon.

**Comment by ikkez** [comment]
I've tested this with `PostgreSQL 9.3.5` and cannot reproduce the error. It works here just as usual without any modifacation to the code.

**Comment by eolandro** [comment]
I have almost the same problem.
I've this table

```
CREATE TABLE IF NOT EXISTS tokenDeAcceso (
Token VARCHAR(256) NOT NULL ,
idusuarios INT NOT NULL ,
Generada timestamp NOT NULL ,
UltimoUso timestamp NULL ,
Activa SMALLINT NULL ,
PRIMARY KEY (Token)  )
;
```

and my class is like this

```
class TokenDeAcceso {
function __construct(){
		global $DBCONFIG;
		$TABLA_NOMBRE =  'tokenDeAcceso';
		$this->DB = new \DB\SQL($DBCONFIG['CON'],
			$DBCONFIG['USR'],
			$DBCONFIG['PWD'],
			array(\PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION)
		);
		$this->TABLA = new DB\SQL\Mapper($this->DB,$TABLA_NOMBRE);
	}
	function agregarRegistro($DATA){
		if (empty($DATA))
			return false;
		$this->TABLA->reset();
		$this->TABLA->idusuarios = $DATA['idusuarios'];
		$this->TABLA->Token = $DATA['Token'];
		$this->TABLA->Generada = $DATA['Generada'];
		$this->TABLA->UltimoUso = $DATA['UltimoUso'];
		$this->TABLA->Activa = $DATA['Activa'];
		$this->TABLA->save();
		return true;
	}
}
```

and run with code like this:

```
$TKA = new TokenDeAcceso();`	
$resp = $TKA->agregarRegistro(array(
		'idusuarios' => 1,
		'Token' => "4545454545444544545",
		'Generada' => date("Y-m-d H:i:s"),
		'UltimoUso' => date("Y-m-d H:i:s"),
		'Activa' => 1
	));
```

on the terminal says something like this:

```
SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ","
LINE 1: SELECT ,(1) AS "idusuarios",(4545454545444544545) AS "Token"...
```

What's wrong?

i have psql (9.3.12) and my system is in spanish too.

**Comment by eolandro** [comment]
Ok i think, i found it.
In my ubuntu server posgresql when i do "create table" always put my columns in lowercase even when i typed in uppercase, this is not a problem in windows because it isn't case sensitivity. that's why this cannot reproduce on windows. i think. @ikkez

Another posibility it can be something like this problem in cakephp:
[cake](http://stackoverflow.com/a/12806856)

it's something about php cannot find the secuence in the public scheme and it needs i full tablename.


@ccrobopid  sometimes posgres it's unfriendly about some kind of words or case, have you ever tried renaming your "id_usuario" to "idusuario"?.
