### ISSUE TITLE
How to use the orm with a xml or json column?

### ISSUE THREAD

**Issue by eolandro** [bcosca/fatfree#917]
Is possible use the integrated orm with a xml or json columm?

**Comment by bcosca** [comment]
F3's DB\SQL class is just a thin wrapper for PHP's PDO module, which means those columns are treated as strings and you should provide the mechanism to convert from/to XML or JSON yourself.

**Comment by ChrisFrench** [comment]
I use fat free for almost everything, I needed to do something  like this.

I found a really good package you can install with composer.
Joomla/registry

It supports, xml,json,php etc to object

**Comment by ikkez** [comment]
Just use a custom getter and setter method, which transforms the data into a sql text field, using json_encode / decode. Everything else is currently out of scope for the mapper. Maybe native json support for v4, but for now.. stick with a custom convert function.
