### ISSUE TITLE
sql transactions with f3 mapper

### ISSUE THREAD

**Issue by karamelichkin** [bcosca/fatfree#918]
Hello! is there way to use sql transaction with fatfree sql mapper?

**Comment by xfra35** [comment]
Sure:

```php
$db->begin();
$mapper1->save();
$mapper2->save();
$db->commit();
```
NB: transactions are not supported by all SQL engines (e.g: MyISAM).

See [the docs](http://fatfreeframework.com/sql#begin,rollback&commit).
