### ISSUE TITLE
Automatically populating $HTTP_RAW_POST_DATA is deprecated

### ISSUE THREAD

**Issue by Fohlen** [bcosca/fatfree#919]
Recently stumbled upon the following warning when I used F3 with PHP5.6 and upstream
`Fatal error: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead.
`
Occurs when one tries to read POST data that is not x-url-encoded (for example jSON data).

**Comment by ikkez** [comment]
This is a problem with your php config, not F3. F3 does not use `HTTP_RAW_POST_DATA`.
Duplicate: #804 #903
