### ISSUE TITLE
Saving emails in files in non production

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#920]
Hello,

The SMTP class does a great job in a very few lines. However we want to run unit tests and avoid being spammed by sent emails. Is it possible to add a feature that saves the emails to files instead of sending them? The send method of the SMTP class does what it needs to be done it just needs to be improved to save files instead of sending emails.

**Comment by emanwebdev** [comment]
+1

while mail server settings can do the trick as well

**Comment by KOTRET** [comment]
clone the class, modify for your needs and place it in a seperate folder that gets (only in test-case) included in AUTOLOAD before the original SMTP-class does.

**Comment by GhaziTriki** [comment]
@KOTRET That is what I have done before posting here. I was thinking about making this feature available in fatfree.

**Comment by bcosca** [comment]
Check out the dev branch. The latest commit fixes a lot of things, improves the transmission envelope, and allows mocking. If the third arg of send() is TRUE, the mail is not actually sent. Use the string return value of log() and save it to a file.

**Comment by GhaziTriki** [comment]
Very good works fine and.

Can youj please add it to the current docuemntation?

And if someone needs to extract the the mail content and save it to a file you can share this code in documentation

```php
// assuming that $messageId is a unique id you have created and 'MAIL_STORAGE' is defined in your configuration
@file_put_contents($this->f3->get('MAIL_STORAGE') . substr($messageId, 1, -1) . '.eml',
                explode("354 Go ahead\n", explode("250 OK\nQUIT", $this->smtp->log())[0])[1]
            );
```

**Comment by ikkez** [comment]
added this portion to my mailer plugin here https://github.com/ikkez/f3-mailer/blob/master/mailer.php#L237 but changed the inspection a bit, as it seems like some SMTP servers might respond a little different here.
