### ISSUE TITLE
Routing does not work when the relative URL contains a special character, e.g., dot 

### ISSUE THREAD

**Issue by pmcao** [bcosca/fatfree#921]
F3 routing does not work when the relative URL contains a special character, for example, getting `/test.js/about` returns 404 error.

```
index.php
$f3->route('GET /test.js/about', function(){
    echo "Hello";
});

$ php -S localhost:8000 index.php

$ curl http://localhost:8000/test.js/about
404 Not found
```

Is there any workaround for this issue?

**Comment by xfra35** [comment]
This look like a restriction of the PHP built-in server. Your example works very well with Apache. And `/test.js` also works with the built-in server. Only `/test.js/about` is rejected.

**Comment by sn0opy** [comment]
I'd say we close this, since it's in fact an issue with the built-in server, not the framework.
