### ISSUE TITLE
Extending SQL Session class won't save the session in the database

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#924]
Hello,

I have extended SQL Session class to add some features to it, however when the script finishes executing no session data is saved to the database. Any idea?

**Comment by ikkez** [comment]
Probably we cannot help you without some code and hints how you use it. But this is not the right place to discuss such things. But I'm sure that the helpful folks at the [google board](https://groups.google.com/forum/#!forum/f3-framework) can help you.

**Comment by ikkez** [comment]
no update for a month. I'm closing this. please feel free to reopen this issue if the problem persists.
