### ISSUE TITLE
Cookie not sent - when using multiple domains on one vhost

### ISSUE THREAD

**Issue by module0x90** [bcosca/fatfree#925]
Hiya, 

I am using "bcosca/fatfree": "3.5.0" on a PHP 5.6.19-0+deb8u1.
I made a little management app for renting.

I realized now that the live site doesn't support login anymore. My code is very close to
https://github.com/ikkez/fabulog/blob/master/app/controller/auth.php in regards to user management
and login.

It seems the problem is that the session cookie is not sent at all. I inserted some $logger->write('User John logged in.'); and it goes all through authentication, creates the session - on the server, but the client never sees 
Cookie  PHPSESSID=hh2brsm71lu86n0fqp04m4hi24 
for example (verified with HttpFox on FF).
The my parent controller checks for an empty session and reroutes to /login - same starts again.

The really odd thing is that it works on one on my renting domains, but not on the other. Both domains are on the same NginX Vhost, SSL cert is having all domains (+www.) as well. Chrome shows the same behaviour, same for Android tablets, the WebConsole in any browser doesn't show any error. The code doesn't mind where it is running, ie. the domain are not hard coded.
It runs all fine on -dev, PHP 7.0.5 (cli) (built: Apr  2 2016 23:10:23) ( NTS ), but there is only one domain, localhost.

My \Controller\Auth->login() is like this:

    public function login($f3, $params) {
        if ($f3->exists('POST.username') && $f3->exists('POST.password')) {
            sleep(3); // login should take a while to kick-ass brute force attacks

            // the $db is handled internally in \Model\User
            $user = new \Model\User();
            $user->load(array('username = ?',$f3->get('POST.username')));

            if(!$user->dry()) {
                if(password_verify($f3->get('POST.password'), $user->password)) {
                    $f3->clear('SESSION');
                    $f3->set('SESSION.user', $user->username);
                    $user->lastlogin = date("Y-m-d H:i:s");
                    $user->ip = $f3->get('IP');
                    $user->save();

                    $f3->reroute('/');
                } 
            }
            \Flash::instance()->addMessage('Wrong Username/Password', 'danger');
        }

        $this->response->setTemplate('templates/login.htm');
    }

I don't know where else to look, I checked all NginX access.logs, error.logs, FPM error logs - nothing in anywhere.

Any clues, why PHPSESS is not sent here?

Regards

Thomas

**Comment by ikkez** [comment]
Do you use the default system Sessions or any F3 Session handler?
Try to add the valid cookie domain to `JAR.domain`. Maybe it was not detected automatically due to server config things...

**Comment by module0x90** [comment]
Interesting. Thanks, I think we are getting closer.
I am using the default system sessions, like /var/lib/php5 built in session file based thingy.

If I set JAR.domains with 

$f3->set('JAR.domain', 'www.XX.com');
$f3->set('JAR.domain', 'www.XX.co.uk');

explictely, it *does not work* on any domain. I cannot login (same behaviour, I am just routed back to the login).

I have outputted 
echo "sn:" . $_SERVER['SERVER_NAME'];
and that gives me ww.XX.com - this is the domain where it was working originally.

So... got another idea. Checked my NginX vhost and it says:

server_name www.XX.com www.XX.co.uk XX.com XX.co.uk;

After I swapped the www.XX.com with the www.XX.co.uk SERVER_NAME is now the www.XX.co.uk and ... 

this made it working now again (I now have the problem on the other domain, www.XX.com - but that's just "secondary").

But still odd.

Do you think this is worth persuing?
I don't mind spending the time on it/trying things out.


Thanks again for the quick answer.
I have never ever written anything in PHP, and F3 really helped a lots here, in particular implementing MVC based paradigms. I tried others, but failed horribly. F3 is really awesome.

**Comment by ikkez** [comment]
hi. nice that you're getting closer,... unfortunately I am not that into nginx server config things.. I would have assumed that the cookie is delivered regardless of the SERVER_NAME config setting, as long as the cookie domain and path is setup correctly. maybe there is a security setting in nginx or maybe you use any privacy browser plugin that drops the cookie when server_name != cookie.domain?! Haven't seen that problem yet,.. and if there was trouble, JAR.domain always helped here to solve it.

**Comment by geniuswebtools** [comment]
This sounds like the same domain security issue w/ setting and reading the cookie.  

Try setting JAR.domain to .XX.co.uk <-- with the preceding .(dot) and JAR.path to '/' the web root.

This should allow you to log in on any subdomain and the cookie should be read by any path accessible to the domain.

If the domain is set explicitly in the JAR, and you're accessing XX.co.uk and on log in it redirects to www.XX.co.uk (or vice versa) the cookie won't be set or read.

**Comment by module0x90** [comment]
@geniuswebtools - Thanks. The thing is, I am not using subdomains, I am using www.XX.co.uk and www.XX.com. I am also not doing any redirect at all, not even from http->https, trying to access my webapp via http gives you a 403 from the server.

I disabled SSL on the main site and then captured the network traffic (on the client) when visiting /login for both cases - www.XX.co.uk (works) and www.XX.com (doesn't let me login, as I don't see the cookie with HttpFox in my browser.

To summarize my findings, it is kind of insisting to send the cookie always back for www.XX.co.uk - disregarding that I am accessing it via .com. My F3 app is domain-unaware, ie. the domain it resides is nowhere in the code (or in configs or database for that matter), it doesn't even care about the directory.

Where does this "cookie domain value" come from by default, is it SERVER_NAME usually? Remember I am not setting any JAR.* values at all right now.
If it is SERVER_NAME then the interesting questions are:
1) It seems it is always www.XX.co.uk - the first server_name in my NginX config.
2) What does the "standard" say in this configuration - is the SERVER_NAME the first/primary and HTTP_HOST the actual domain I was visiting?

I am so not liking this. Part of the problem could be that there are multiple domains sitting on the same IP (but a different vhost) and there is no reverse resolution back to any of the domains.

Any ideas?


Cheers
Thomas

**Comment by ikkez** [comment]
Found answer here http://stackoverflow.com/questions/31479341/nginx-server-directive-with-multiple-server-name-entries-always-first-one-i

You have two options:
A) Set a config var in your nginx fastcgi_param section:
`fastcgi_param   SERVER_NAME     $host;`
B) Use `$f3->set('JAR.domain',$_SERVER['HTTP_HOST']);` to use the domain the user comes from. As this value comes from the user request, it could become a sequrity issue.

**Comment by geniuswebtools** [comment]
Let me clarify.  I was referring to troubleshooting the issue and confirming your problem is the same domain origin issue.  Using www is a subdomain, and that small variation between www.XX.co.uk and XX.co.uk will keep the cookie from being set or read because the browser will see them as two different domains.  Using the preceding .(dot) in front of the domain will allow it to be read for the primary domain as well as any subdomains.  ".XX.co.uk" is what you should use w/o the double quotes ;) 

My point was if you set the JAR.domain to the domain for the host, you should be able to test your code on the production server, and see that it works w/o issue.  If you still have problems setting the domain dynamically from the server configuration isn't going to help you too much.

**Comment by module0x90** [comment]
@geniuswebtools Now that''s clearer, thanks.
@ikkez I just changed my NginX fastcgi_param config to "fastcgi_param SERVER_NAME $host;" and that solved it. Many thanks ... for taking your time and searching that and sharing it.

Issue closed - NginX problem, but fix provided.
Awesome. :-)
