### ISSUE TITLE
Implement reset feature for xcache

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#928]
Hi there,

I can see in reset method of Cache class that xcache case returns true and the is a comment ```/* Not supported */```. However looking at xcache Api https://xcache.lighttpd.net/wiki/XcacheApi they provide a ```xcache_unset_by_prefix``` function. Could it be added please?

And instead of using ```xcache_get``` in exists method, isn't it better to use ```xcache_isset```?

**Comment by bcosca** [comment]
`Cache::exists()` is interwoven with `Cache::get()` so `xcache_isset` is not going to be "better".
