### ISSUE TITLE
Update Web->receive method to use custom methods instead of "PHP upload methods" for testing purpose

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#930]
Hi there,

We want to add unit tests for file upload, however the use of ```is_uploaded_file``` and ```move_uploaded_file```in the following lines https://github.com/bcosca/fatfree/blob/master/lib/web.php#L232-L236 makes unit testing of upload files impossible as the implementation in the PHP interpreter is locked https://github.com/php/php-src/blob/master/ext/standard/basic_functions.c#L5722-L5795.

I know it is completely insecure but could it be possible to override the use of  ```is_uploaded_file``` and ```move_uploaded_file``` in the ```Web``` class in any way?

**Comment by bcosca** [comment]
`Web->receive()` allows a function as its first argument. If the function returns `FALSE`, `move_uploaded_file` will not be called.

**Comment by GhaziTriki** [comment]
This is only done for the PUT HTTP verb while we are using a POST in our code. Is there any reason that this behaviour is limited to PUT?

**Comment by bcosca** [comment]
Are your sure? Check the source.

**Comment by GhaziTriki** [comment]
Hi Bong,

I have been testing this feature since some days and there is a restriction for running the handler. If sen request is sent via PUT we only use ```file_exists``` then call the handler function https://github.com/bcosca/fatfree-core/blob/master/web.php#L174-L207 else we use ```is_uploaded_file``` then call the handler then call ```move_uploaded_file``` https://github.com/bcosca/fatfree-core/blob/master/web.php#L234-L238

Did I miss anything?

**Comment by ikkez** [comment]
Have you read the rest of the code? Of course you cannot use `is_uploaded_file` for `PUT`, because the storage mechanics are different. If you want to test your upload controller, I recomment you build a unit test that really uploads a file. There are plenty of example codes how to do that with curl [[1](http://stackoverflow.com/questions/4223977/send-file-via-curl-from-form-post-in-php)] [[2](http://stackoverflow.com/questions/12667797/using-curl-to-upload-post-data-with-files?rq=1)]. This way you can also test if the route exists, the upload dir exists & is writable, and be able to test against php.ini settings like max_upload_size. If you only want to test you custom handler function, I recommend you encapsulate it into a class, so testing that as standalone filter function becomes easy:

```php
class Files {
  function handleUpload($file,$formFieldName){        
        if($file['size'] > (2 * 1024 * 1024)) // if bigger than 2 MB
            return false; // this file is not valid, return false will skip moving it
        // everything went fine
        return true; 
    }  
}

$web->receive('Files->handleUpload', true, true);
```

**Comment by GhaziTriki** [comment]
Yes I have read it all the custom handler is used in addition of php ```is_uploaded_file``` and ```move_uploaded_file```, the challenge we have is that we are running unit tests in both command line and browser mode and we are trying to mock file upload to have as much as possible code coverage.

**Comment by bcosca** [comment]
I'm not so sure I understand the purpose of overriding `is_uploaded_file`. It's a security measure that you want to skip on purpose?

**Comment by GhaziTriki** [comment]
That's it ```is_uploaded_file``` cannot be used if unit tests are run in CLI mode and without having a PHP internal server.

What I finished by doing is the following when running unit test, but I am not satisfied with it for a long term

```
$webFile = file_get_contents('../vendor/bcosca/fatfree-core/web.php');
$webFile = str_replace('is_uploaded_file', 'file_exists', $webFile);
$webFile = str_replace('move_uploaded_file', '@copy', $webFile);
file_put_contents('../vendor/bcosca/fatfree-core/web.php', $webFile);
```

Can you de better?

**Comment by bcosca** [comment]
But `is_uploaded_file` is meant to fail if a file was deliberately and directly saved in the filesystem by a hacker. Your unit test becomes misleading then.

**Comment by GhaziTriki** [comment]
That's it the internal implementation of ```ìs_uploaded_file``` checks if the files was really sent via an HTTP request. I think it is better to review my unit tests using command line and thing about using the PHP internal server + curl.

**Comment by bcosca** [comment]
I think we can relax the implementation a bit, i.e. forego the `is_uploaded_file` check because `move_uploaded_file` does practically the same thing before the actual transfer to a different directory.

**Comment by GhaziTriki** [comment]
That is correct the implementation of ```move_uploaded_file``` contains a all what is implemented by ```is_uploaded_file``` before moving the file. I think it is better, however ```move_uploaded_file``` is still problematic for full CLI mode :smile:

**Comment by bcosca** [comment]
Not if you short-circuit the `move_uploaded_file` with the first function argument. I don't think it would be wise to disable/replace this function with another for the sake of testing alone.

**Comment by GhaziTriki** [comment]
The shortcut will be complete effective if the code looks like this:

```php
$out[$file['name']]=!$file['error'] &&
(!file_exists($file['name']) || $overwrite) &&
( (!$func || $fw->call($func,[$file,$name])!==FALSE) ||
move_uploaded_file($file['tmp_name'],$file['name']) );
```

**Comment by bcosca** [comment]
Not exactly true. The function argument can be used for other things BEFORE the actual file movement is done, e.g. transcoding an audio/video file, editing a photo, not when the file has already been moved because errors may occur during transcoding/editing.

**Comment by GhaziTriki** [comment]
Cannot ```move_uploaded_file``` be used inside the custom handler?

**Comment by bcosca** [comment]
Yes, but `receive()` isn't going to be intuitive anymore.

**Comment by GhaziTriki** [comment]
I am using ```move_uploaded_file``` the inside my handler because depending on the files type, files are placed on different folder inside the ```UPLOADS```folder. As example files uploaded in chat are not  saved where site logo is saved and the ```$file['name']``` does not give the correct folder for me.

**Comment by bcosca** [comment]
Why not just return FALSE inside the function, at least for your specific testing needs? It would be such a big bother for everyone else who rely on `receive()` to alter their code.

**Comment by GhaziTriki** [comment]
Wise thinking, it will not use the ```move_uploaded_file``` and as the ```is_uploaded_file``` has been removed it will go inside the handler for sure. Let me try that.

**Comment by GhaziTriki** [comment]
Works great !!! Thanks @bcosca
