### ISSUE TITLE
SQL mapper has problem with mysql bit type

### ISSUE THREAD

**Issue by sbraaa** [bcosca/fatfree#932]
With MySQL  if you retrieve a record using load method of SQL mapper it returns void string for fields wich has type "bit".
Converting that fields into type tinyint(1) (not the same but close enought) it runs well.

**Comment by ikkez** [comment]
Well since the mapper is PDO based, and there is no PARAM_BIT PDO type, and there are some [glitches with the bit type](http://stackoverflow.com/a/10542145/2038179), you probably have a better deal using tinyint(1). BOOL / BOOLEAN is also just an alias for tinyint(1), so it should do what you want.
