### ISSUE TITLE
Unable to load dynamic library 'imagick.so'

### ISSUE THREAD

**Issue by nerdyorion** [bcosca/fatfree#934]
Error occurs on shared hosting 

`Fatal error: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20100525/imagick.so' - libMagickWand.so.2: cannot open shared object file: No such file or directory`

Please assist

**Comment by geniuswebtools** [comment]
This isn't a bug with F3... you should keep the issue in the Google group ;)

https://groups.google.com/forum/#!searchin/f3-framework/php$20startup$20error/f3-framework/kDxqyRbRq9k/9cdXnNYQAgAJ
