### ISSUE TITLE
Web::send() with custom filename and additional header values

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#937]
Hi,

I would be great to make possible for the developer to give a custom name to a file send to the HTTP client using Web::send(), it will also be great to add extra headers.
As example if I load a file name ```file_0fa1da98b3b9bb55ada1.jpg``` from the storage drive and I want to send it to the user with its original name ```cat_one_million_image.jpg``` :smile:

**Comment by ikkez** [comment]
duplicate to https://github.com/bcosca/fatfree-core/pull/124
