### ISSUE TITLE
DB\SQL\Mapper::load fails due to missing column or wildcard

### ISSUE THREAD

**Issue by Kagurame** [bcosca/fatfree#939]
The function `DB\SQL\Mapper::load` failes due to missing column name or wildcart.

Following code:
`$lastChange = self::getDBInstance()->load();`
> getDBInstance() returns a new instance of DB\SQL\Mapper - table is automatically determined to 'font' in my case

try to execute the following SQL:
`'SELECT  FROM `font``

The source code (without testing) was following:
`$lastChange = self::getDBInstance()->load(array("DELETED=?", "0"), array("order" => "MODIFIED DESC", "limit", 1));`
Which raised the error:
`[app/core/class/db/sql/mapper.php:277] DB\SQL->exec('SELECT  FROM `font` WHERE DELETED=? ORDER BY `MODIFIED` DESC',array(1=>'0'),0)`

Im using the 3.5.1 release which seems the newest for me currently, right?

**Comment by ikkez** [comment]
It should be `"limit" => 1`, but you don't need that for a load, as it is limited to 1 by default.
please use the [google board](https://groups.google.com/forum/#!forum/f3-framework) for questions like that.

**Comment by xfra35** [comment]
Which SQL engine are you using?

The columns are fetched by the [DB\SQL->schema()](http://fatfreeframework.com/sql-mapper#schema) function.

**Comment by Kagurame** [comment]
@ikkez Thanks for the hint, ive fixed this. But this is more a bug report than a question :/
@xfra35 Im using MySQL. I should not have to use this function manually, right? Also i dont have the ability to use a column parameter to decide which columns i want to select.

Generally [Line 314 of `lib/db/sql/mapper.php`](https://github.com/bcosca/fatfree/blob/master/lib/db/sql/mapper.php#L314) returns an empy string for my table and pass this to the `select` function.

If it takes a role, here is my table i try to load from:
```SQL
CREATE TABLE `font` (
  `GUID` varchar(36) COLLATE utf8_bin NOT NULL DEFAULT '',
  `CREATED` datetime NOT NULL,
  `MODIFIED` datetime NOT NULL,
  `DELETED` tinyint(1) DEFAULT '0',
  `FILENAME` varchar(64) COLLATE utf8_bin NOT NULL,
  `FONTNAME` varchar(64) COLLATE utf8_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


ALTER TABLE `font`
  ADD PRIMARY KEY (`GUID`);
```

An easy fix would be to [change Line 209 in `lib/db/sql/mapper.php`](https://github.com/bcosca/fatfree/blob/master/lib/db/sql/mapper.php#L209) to the following:
```PHP
$sql='SELECT '.($fields?:'*').' FROM '.$this->table;
```

But i havent looked that deep into code to tell if this fix should happen at any other point - but here it would be the last place to fix the $fields parameter and prevent using NULL or similar parameter type.
