### ISSUE TITLE
Mocking ajax for unit tests in CLI is borken

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#945]
Hi,

I am running unit tests in CLI mode with the following code

```php
$f3->mock('DELETE /users/delete/' . $user->id . ' [ajax]');
```

It was working until the commit https://github.com/bcosca/fatfree-core/commit/3712073bf23028e207d25121f113fc44c764f217 which returns me 404 Not found.

**Comment by xfra35** [comment]
Should be fixed now: https://github.com/bcosca/fatfree-core/commit/64976a57729024657cd7ee4cc01ea7f74d5b0e43
