### ISSUE TITLE
Cannot use $this as parameter

### ISSUE THREAD

**Issue by e-anima** [bcosca/fatfree#946]
Error form the apache log. I use php 7.0.8. is that because of php 7?
[Thu Jun 30 18:42:26.286701 2016] [:error] [pid 8264] [client 127.0.0.1:55588] PHP Fatal error:  Cannot use $this as parameter in /mnt/480SSD/http/php_scripte/GFM/lib/base.php on line 1296

**Comment by xfra35** [comment]
What's there on line 1296? I don't see any `$this` neither [here](https://github.com/bcosca/fatfree/blob/master/lib/base.php#L1296) nor [there](https://github.com/bcosca/fatfree-core/blob/master/base.php#L1296).

**Comment by mstaack** [comment]
looks like you have changed base.php or extended that class (and removed finally in base.php).

@bcosca smartest way to extend base.php without touch base-repository? have a special usecase for this

**Comment by e-anima** [comment]
well i did not hack the core base.php
this is an error beeing passed on. it defeinitely worked with a lower php version 7.0.2. they must habe added something in the 7.0.8 (from 23 july)

**Comment by e-anima** [comment]
ok had 3.5.0, updated to 3.5.1 made it work.
