### ISSUE TITLE
Cannot force language with multiple DICT files for same language

### ISSUE THREAD

**Issue by ethanpil** [bcosca/fatfree#948]
[Cross reference to Google Groups](https://groups.google.com/forum/#!searchin/f3-framework/force$20language/f3-framework/cOnmbCNHGBE/op6a1MmWBAAJ).

When multiple dictionary files are added for the same language, the directive to force user's language with **$f3->set('LANGUAGE','es');** is ignored. And the **FALLBACK** is always presented instead.

[Per @xfra35 suggestion in Google Groups](https://groups.google.com/forum/#!topic/f3-framework/IvaPbAWhyeA) I have added multiple dictionary files for the same language. 

    $f3->set('LOCALES','data/dict/general/');
    $f3->set('LOCALES','data/dict/tooltips/');

When this is enabled, then **$f3->set('LANGUAGE','es');**  fails and the system always uses the fallback language. If I comment out the second **LOCALES** entry, then the system properly displays the localized text.

I setup a fresh F3 to test. You can replicate the problem by simply commenting out the following in the index.php: 

`$f3->set('LOCALES','dict/two/');`

The details of my setup are below. You can also [download the code to replicate the issue from my dropbox](https://www.dropbox.com/s/1fpd1vjuxp71spw/www.zip?dl=0). Note, I will remove this link once the issue is resolved.

Here is my index.php:

```
<?php

//Composer Autoload
require __DIR__ . '/lib/autoload.php';


// Load Fat Free Framework
$f3 = \Base::instance();


// Load configuration
$f3->set('LOCALES','dict/one/');
$f3->set('LOCALES','dict/two/'); //If this line is commented out then ES language text is displayed, otherwise is always EN

$f3->set('LANGUAGE','es');
$f3->set('FALLBACK','en');


//Route
$f3->route('GET /',
    function($f3) {
        echo \Template::instance()->render('template.html');
    }
);


// Launch
$f3->run();
```

template.html
`<h1>{{@TXT.hello}}</h1>`

dict/one/en.ini
`TXT.hello=Hello`

dict/one/es.ini
`TXT.hello=Hola`

**Comment by ethanpil** [comment]
Some additional information

**$f3->get('LOCALES')** only displays the last path added via **$f3->set('DICT','xxxx')** but the translated texts do work from all the files.

**Comment by ikkez** [comment]
From the code https://github.com/bcosca/fatfree-core/blob/master/base.php#L984 it should work with a split-able string, just like `AUTOLOAD`

```php
$f3->set('LOCALES','dict/one/;dict/two/');
```

**Comment by xfra35** [comment]
The multiple `LOCALES` folder does only work if you specify it *after* setting up the language. So:

```php
$f3->set('LANGUAGE','es');
$f3->set('FALLBACK','en');

$f3->set('LOCALES','dict/one/');
$f3->set('LOCALES','dict/two/');
```

Here's why your code didn't work:
```php
$f3->set('LOCALES','dict/one/'); // <-- load dict/one/ in English
$f3->set('LOCALES','dict/two/'); // <-- load dict/two/ in English

$f3->set('LANGUAGE','es'); // <-- set Spanish language and load dict/two/ in Spanish
$f3->set('FALLBACK','en'); // <--set English fallback and load dict/two/ in Spanish
```
As you can see, `LOCALES` does only remember the latest selected locales folder.

**Comment by xfra35** [comment]
@ikkez oh yeah! I totally missed that [commit](https://github.com/bcosca/fatfree-core/commit/22ed653ffca6a5073f00e22e8f33f40bea8a9929). :+1: 

So @ethanpil, forget about what I wrote. Can you confirm that ikkez's suggestion fix your issue? Then I can update my answer on the forum.

**Comment by ikkez** [comment]
Nevertheless I think the order could make a difference, good point @xfra35 
As the dictionary files are scanned once you set them and when you change the language, you'll save performance on the first scan, if you set the LANGUAGE var first.

**Comment by ethanpil** [comment]
Yes! I can confirm that the both of the scenarios below work as expected. Thank you for your help. 
We definitely need to document all of this in the user's guide. I have been digging at this for a while.

The only problem with this, which I believe is significant, is that it minimizes the utility of the config system. 

A percentage of individual users will certainly want to override the default language with their own choice. Using this preferred order, how can I load the config files, and then override the defaults via the app? It won't work.

So, for now will need to move LOCALES, LANGUAGE and FALLBACK all out of config.ini and set them all manually in the controller before_route function.

#### Combined Locales
```
$f3->set('LANGUAGE','en');
$f3->set('FALLBACK','en');
$f3->set('LOCALES','dict/one/;dict/two/;dict/three/');
```

#### Separate Locales
```
$f3->set('LANGUAGE','es');
$f3->set('FALLBACK','en');

$f3->set('LOCALES','dict/one/');
$f3->set('LOCALES','dict/two/');
$f3->set('LOCALES','dict/three/');
```

**Comment by xfra35** [comment]
Hmm now I remember why I [advised](https://groups.google.com/forum/#!topic/f3-framework/IvaPbAWhyeA) 2 separate `LOCALES` instead of one combined.

The idea was to allow some modular structure. Let's say you're having a structure with 10 modules. You may not want to load all 10 dictionaries on every request. In that case, you could load a global dictionary first, and every subsequent module dictionary on the fly.

Something like:
```php
// index.php
$f3->LOCALES='commons/';
$f3->run();

// modules/blog/basecontroller.php
namespace Modules\Blog;
class BaseController {
  function __construct($f3) {$f3->LOCALES='modules/blog/dict/';}
}

// modules/shop/basecontroller.php
namespace Modules\Shop;
class BaseController {
  function __construct($f3) {$f3->LOCALES='modules/shop/dict/';}
}
```

But as discovered by @ethanpil, this will only work if `LANGUAGE` is defined once and for all.

**Comment by xfra35** [comment]
> The only problem with this, which I believe is significant, is that it minimizes the utility of the config system.

@ethanpil why?

**Comment by ethanpil** [comment]
> >The only problem with this, which I believe is significant, is that it minimizes the utility of the config system.

> @ethanpil why?

As I wrote above: 

A percentage of individual users will certainly want to override the default language with their own choice. Using this preferred order, how can I set language and locale via the config files, and then override the defaults via the app only when necessary? It won't work.

**Comment by xfra35** [comment]
If I understand you well, `LOCALES` is set in `index.php` while `LANGUAGE` is set in the controller. Am I right?

In that case indeed, there's no meaning in setting `LANGUAGE` in a config file. But you can still store `LOCALES` and `FALLBACK` there, as long as `LOCALES` is a splittable string.

**Comment by ethanpil** [comment]
I used to have all, `LANGUAGE`, `FALLBACK` and `LOCALES` in `config.ini`.  Simple. Then, in my controller which loaded user's prefs from DB I would override `LANGUAGE` if selected by user. This is how we found the problem, because it will not recognize `LANGUAGE` again after `LOCALES` is set.

Now because all instances of `LANGUAGE` must be before `LOCALES` I cannot set any of these values, which belong in `config.ini`  inside of there.  I must load config and wait until routing starts and user's prefs are loaded and `LANGUAGE` is decided before I can declare `LOCALES` because `LOCALES` always must be last. It's not clean and certainly not the F3 way!

**Comment by xfra35** [comment]
> Now because all instances of LANGUAGE must be before LOCALES

Only when using the "separate" locales folders, which is a sort of hack.

The official F3 way is to use the splittable string, as indicated by @ikkez:

```ini
FALLBACK = en
LOCALES = "dict/one/;dict/two/;dict/three/"
```

**Comment by ethanpil** [comment]
Ahhh, just tested that and it worked. I did not realize that splittable string vs multiple declarations was the issue here.
