### ISSUE TITLE
Image quality lost in render method

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#949]
Hello,

This commit breaks https://github.com/bcosca/fatfree-core/commit/a9e5776550eeecc989c5be8079071930e3d8fb0e the image quality when I keep my old code `$logo->render('jpeg', null, 100)` or put the new one `$logo->render('jpeg', 100)` the image quality is not taken in account, only if revert the code of that commit.

**Comment by xfra35** [comment]
That's weird. I've just tested `$img->render('jpeg',10)` and the quality is obviously bad.

**Comment by GhaziTriki** [comment]
Any update?

**Comment by ikkez** [comment]
no problem here.
