### ISSUE TITLE
Hardcoded cache $prefix makes impossible to find key with a subodmain redirection

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#951]
Hello,

We have following configuration. We have an F3 application that have pseudo-CDN feature under `/cdn/*`. We have added a redirection in `.htaccess` from `/cdn/*` to `cdn.domain.com/*`. It results in different cache prefixes and keys added in main domain cannot be found in subdomain. And it does not work because of the following line.

https://github.com/bcosca/fatfree-core/blob/64976a57729024657cd7ee4cc01ea7f74d5b0e43/base.php#L2462

A good example, one of our keys is `avatar.user.60.90x90`
Cache prefix is `$this->prefix . $key;`
In `cdn.domain.com` :  `$this->prefix = 'h6qqa2jvtoez'`;
In `domain.com`  : `$this->prefix = '3awbd3dh8n400'`;

Cache `$prefix` should be configurable and should not be hardcoded.

**Comment by ikkez** [comment]
Hi. The used application specific hash is now globally configurable with the new $f3->SEED var.

**Comment by GhaziTriki** [comment]
Hi, good idea for the implementation. It should be added to the official documentation.

**Comment by ptdev** [comment]
Hey, just came across this issue when using multiple domains and cache where I had to set this variable.

It should be stated that one should set the SEED variable before setting the CACHE variable, otherwise it won't work.
