### ISSUE TITLE
How to set an deafult value

### ISSUE THREAD

**Issue by leafx** [bcosca/fatfree#952]
When i get a request data use $f3->get('REQUEST.agr'), and this data is empty ,how to set an default value for this.

I think it might be  $f3->get('REQUEST.agr', 'default value'), but not.

Thx.

**Comment by xfra35** [comment]
**PHP 5:**
```php
isset($_REQUEST['agr']) ? $_REQUEST['agr'] : 'default value'
```
**PHP 7:**
```php
$_REQUEST['agr'] ?? 'default value'
```
**PHP 5 & 7:**
*(if empty value is not valid)*
```php
$_REQUEST['agr'] ?: 'default value'
```

NB1: you'd better use `$_GET` and `$_POST` instead of `$_REQUEST`.
NB2: please use the [forum](https://groups.google.com/forum/#!forum/f3-framework) for such questions.
