### ISSUE TITLE
Using transactions with exception handling

### ISSUE THREAD

**Issue by Phisherman** [bcosca/fatfree#958]
I'm using exception handling to catch *unique constraint violations*. I'm doing this to add data and if the data already exists, it just skips the data. Is there an possibility to use exception handling with f3' transactions?

The [documentation](https://fatfreeframework.com/databases#Transactions) says that *"A rollback will occur if any of the statements encounter an error.*" But that's not the behaviour I want.

My code looks like the following:
```php
try{
    $db->exec("DELETE ...");
    foreach($members as $member){
        try{
            $rows = $db->exec("INSERT INTO ...");
        } catch(\Exception $ex){
            $code = $ex->getCode();
            
            if($code === "23505") {
                //unique constraint violation (no problem at all)
            }
            else {
               //roll only here back
               $db->rollback();
                return;
            }
        }
    }
}
catch(\Exception $ex){
}
```

**Comment by xfra35** [comment]
`\DB\SQL` is a subclass of `PDO` so it can throw catchable PDO exceptions. Since these are disabled by default, you need to enable them first. This can be done in 2 different ways:

**at instantiation time, for all transactions:**
```php
$db = new \DB\SQL($dsn, $user, $pwd, array( \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ));
```

**later on in the code, on a per-transaction basis:**
```php
$db->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
```

Once PDO exceptions are enabled, just catch them as other exceptions:

```php
try {
  $db->exec('INSERT INTO mytable(id) VALUES(?)','duplicate_id');
} catch(\PDOException $e) {
  $err=$e->errorInfo;
  //$err[0] contains the error code (23000)
  //$err[2] contains the driver specific error message (PRIMARY KEY must be unique)
}
```
This also works with DB mappers, since they rely on the same `DB\SQL` class:

```php
$db=new \DB\SQL($dsn,$user,$pwd,array(\PDO::ATTR_ERRMODE=>\PDO::ERRMODE_EXCEPTION));
$mytable=new \DB\SQL\Mapper($db,'mytable');
try {
  $mytable->id='duplicate_id';
  $mytable->save();//this will throw an exception
} catch(\PDOException $e) {
  $err=$e->errorInfo;
  echo $err[2];//PRIMARY KEY must be unique
}
```

**Comment by Phisherman** [comment]
@xfra35 Thanks for your detailed explanation. But my problem isn't the exception handling per se but the  transaction. I set the error mode already to exception mode. Sorry that I didn't mention this in my starting post.

I want an transaction out of multiple exec(...) commands:

```php
$db = new \DB\SQL(...);
$db->begin();
$db->exec("...");
$db->exec("...");
$db->commit();
```

The problem is that sometimes an exception will be thrown and not every exception is "bad" because it could be a unique constraint violation. As far as I understood the docs and what I have experienced isit automically rollbacks the transaction if an exception would be thrown.

**Comment by xfra35** [comment]
Ah ok, indeed I've misunderstood your question.

Have you thought about using the [ON DUPLICATE KEY UPDATE](http://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html) syntax (or equivalent)?

**Comment by ikkez** [comment]
Does it make a difference if you @Phisherman comment out this block https://github.com/bcosca/fatfree-core/blob/master/db/sql.php#L215-L220 ?

**Comment by Phisherman** [comment]
I'll test it next week.

**Comment by Phisherman** [comment]
@ikkez I didn't see any changes. I'm using Composer. So I changed the lines in the sql.php file and ran `composer dump-autoload`. Do you by sheer chance know if I missed something  here?

@xfra35 I'm now using [Upserts](https://www.postgresql.org/docs/devel/static/sql-insert.html) and it's working.

Thank you all four your help. I really appreciate it.
