### ISSUE TITLE
when i use composer's autoload.php, it comes to a problem  'Fatal error: Cannot redeclare class Cache'

### ISSUE THREAD

**Issue by sscrates** [bcosca/fatfree#959]
I  need help

**Comment by Rayne** [comment]
If you are using `composer` to manage `fatfree` or `fatfree-core`, don't include library files manually (e.g. don't include `base.php`).

**Comment by adamlibusa** [comment]
In another words, replace this: `$f3 = \Base::instance();` with `$f3 = \Base::instance();`. Leaving this here if it helps somebody.
