### ISSUE TITLE
markdown dies (php7)

### ISSUE THREAD

**Issue by eazyliving** [bcosca/fatfree#960]
Hi,

since I moved to php7 (7.0.8-1~dotdeb+8.1), the parser dies while convert().
There's no error message, just no response and I can't get my php to tell me what the problem is.

Only converting an empty string "works". Any other string doesn't.

```
$f3=require('lib/base.php');
echo Markdown::instance()->convert("Any text. Even without markdown.");
```

Maybe someone could confirm this with his own installation. Thanks!

**Comment by Rayne** [comment]
I can't reproduce the problem with the latest `fatfree-core`, `fatfree` `Version 3.5.1-Release` and PHP `7.0.8-0ubuntu0.16.04.2`.

**Comment by xfra35** [comment]
Same as @Rayne, no problem with 7.0.10 on Arch.

Nothing in the error log?

Also check out which version of PCRE is in use.

**Comment by Microgamer** [comment]
On my server it works properly as well. Ubuntu 16.04.2 PHP7 On the php-development-Server
Newest version of f3

**Comment by sn0opy** [comment]
@eazyliving do you still experience this issue? On wich F3 version are you by the way? Was playing around with it on my Arch server as well without any issues so far.

**Comment by eazyliving** [comment]
Urm... forgot about that one. No, it's ok. Closed :)

**Comment by unfinishedteleporter** [comment]
Interesting, I'm having what sounds like the exact same issue (finally) moving to php7.
Using PHP 7.1.20-1+0~20180725103117.2+jessie~1.gbpd5b650
I get the same result, F3 version 3.6.4
Was working in php 5.6. Must be something odd.
@eazyliving can you remember what fixed this for you?

I'll try to fix it here and report back.

**Comment by unfinishedteleporter** [comment]
I'm not sure why nothing is showing in my logs, but I've isolated the 'problem' to the `build()` function in The `Markdown` class,  in the `foreach` block in the else of the main loop. It cycles over `$this->blocks`, and fails when it reaches the 'raw' one. Specifically when it calls `preg_match($regex,substr($str,$ptr),$match)` and the value of $regex is:

```
'/^((?:<!--.+?-->|'.
'<(address|article|aside|audio|blockquote|canvas|dd|'.
'div|dl|fieldset|figcaption|figure|footer|form|h\d|'.
'header|hgroup|hr|noscript|object|ol|output|p|pre|'.
'section|table|tfoot|ul|video).*?'.
'(?:\/>|>(?:(?>[^><]+)|(?R))*<\/\2>))'.
'\h*(?:\n{2,}|\n*$)|<[\?%].+?[\?%]>\h*(?:\n?$|\n*))/s'
```

**Comment by unfinishedteleporter** [comment]
Summary
=======
Leaving this here in case someone else runs into same problem. For me it was (most likely, haven't confirmed) caused by using an older version of PCRE (8.35) in php7.1 with pcre.jit enabled (the default) which caused a segmentation fault (hence the lack of error or log entries) when a specific regex was encountered in the Markdown class. 

I don't know why that regex in particular caused issues.

**Comment by bcosca** [comment]
That PCRE 8.35 library is quite old and may have trouble running out of memory due to the recursive nature of the regex.

**Comment by unfinishedteleporter** [comment]
Update (in case anyone else stumbles on this with similar issue): Definitely PCRE being too old.  Now using version 8.39 2016-06-14 and there are no problems. Luckily our production environment is also moving to newer version. This was probably going to cause issues elsewhere in our code separate from markdown :+1:
