### ISSUE TITLE
subtemplate bug

### ISSUE THREAD

**Issue by aleroma** [bcosca/fatfree#961]
When I `<set myvar="333" />` in subtemplate,
and do `{{ var_dump(@myvar) }}` in root template some lines later after include of subtemplate,
than I get NULL as result of var_dump()

**Comment by Rayne** [comment]
This isn't a bug. This is the expected sandbox behavior preventing nested templates to overwrite data of outer templates.

**Comment by aleroma** [comment]
So what if I want my behavior, not sandboxing?

**Comment by aleroma** [comment]
What can go wrong without sandboxing?

**Comment by bcosca** [comment]
Is `@myvar` altered in a subtemplate? If so, why do you think it should persist and affect the main template?

**Comment by aleroma** [comment]
I dont care about it anymore. I found another way to do what I need
