### ISSUE TITLE
OpenID issue

### ISSUE THREAD

**Issue by elitetheespeon** [bcosca/fatfree#965]
I'm trying to use the OpenID module with Steam and keep getting the following error:

`preg_grep() expects parameter 2 to be array, string given`

In the trace, I can see: 
`preg_grep('/http:\/\/specs\.openid\.net\/auth\/2.0\/(?:server|signon)/','http://specs.openid.net/auth/2.0/server')`

Just using the following will generate the error:
```php
$openid = new Web\OpenID();
$openid->set('identity','https://steamcommunity.com/openid');
$openid->auth();
```

**Comment by Rayne** [comment]
Did you already look at the content of that second parameter?

It could be possible that `OpenID` will be dropped with the next release as @bcosca "deprecated" (read: removed) `OpenID` from `fatfree-core` (see https://github.com/bcosca/fatfree-core/commit/4974a64178dce631bfd1906953f2fb0e1ea95a5a) and added a `OAuth2` class (see https://github.com/bcosca/fatfree-core/commit/34a98f0d68fe3e9f51e83b88a8d0b9c2467cb1ee).

**Comment by elitetheespeon** [comment]
Thanks, it does seem like OpenID support will be dropped. I figured since it was there I'd use it instead of requiring another lib.

**Comment by ikkez** [comment]
@bcosca did you drop that plugin because it had issues or only because google doesn't use open id anymore? maybe it's worth keeping it?

**Comment by bcosca** [comment]
The class has been unmaintained for a while and it appeared like there was no demand to keep it, until now. Sure, let's resurrect this class and fix this standing issue.

**Comment by ikkez** [comment]
fixed. You can find a new sample for a steam login here https://github.com/bcosca/fatfree/blob/dev/app/openid.php (init) and here https://github.com/bcosca/fatfree/blob/dev/app/openid2.php (verify).
