### ISSUE TITLE
 Undefined variable: error base.php on line 1950

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#966]
When running fat free I get this error 
Notice: Undefined variable: error in /var/www/html/vendor/bcosca/fatfree-core/base.php on line 1950 and it prevents me to load some javascript.

**Comment by ikkez** [comment]
fixed in https://github.com/bcosca/fatfree-core/commit/577aa14f21cc16bf9a845b122b3d754c06de3b3b
