### ISSUE TITLE
Bcrypt file deleted while commit is saying it has been deprecated

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#968]
Hello,

We are using `Bcrypt` class in a production application, However it has been deleted in commit https://github.com/bcosca/fatfree-core/commit/9f1bd837cae0a99ec2936ddaaa4da31b896bc2e5 while the comment is saying that it has been deprecated. What should be done to replace it?

**Comment by KOTRET** [comment]
we are fine with [PasswordHash](http://www.openwall.com/phpass/) for years

**Comment by xfra35** [comment]
I'm also wondering why it has been removed. There are native [password hashing functions](http://php.net/manual/en/ref.password.php) in PHP but they require PHP 5.5 while the framework supports PHP 5.4.

**Comment by ikkez** [comment]
same here. `password_hash` is fine to use as fallback, but since it's php5.5 only, the Bcrypt class should be marked as deprecated with a proper `@deprecated` phpdoc tag, but not deleted completly for now.

**Comment by bcosca** [comment]
Sorry, I'm now at a loss which PHP version to support in each framework release. @ikkez, perhaps you could draw the road markers for us? PHP 5.4 has reached end-of-life, 5.5 is on its last breath.

**Comment by GhaziTriki** [comment]
@bcosca you can find php supported version list here http://php.net/supported-versions.php
PHP 5.5 has reached its end of life, however the deletion of classs BCrypt should be done in a major release branch not directly in the master. We all support @ikkez to mark the class as deprecated.

**Comment by sn0opy** [comment]
Eventhough @KOTRET gave an alternative to this, I highly recommend to use https://github.com/ircmaxell/password_compat instead, since it's "forward compatible" and useses the same names as the PHP5.5 equivalent.

**Comment by ikkez** [comment]
Well, of course nobody is willing to use php 5.3 anymore and we would highly recommend to upgrade PHP asap, but the current v3.5.x is still supporting that version. That does not mean that it's not possible to use it with php5.5, 5.6 or 7. It's tested and we encouraged users to pick up that extra performance boost with the newer php versions. Nevertheless, for some business clients the gears are spinning a bit slower. I'd say we raise the minimum required version slightly but constantly. We're on PHP5.4 now for F3 v3.6, which we actually wanted to launch this month :D  
I think we should stick on that now, before raising new issues, and aim for php 5.6 for F3 v3.7... php7 for v4.

**Comment by xfra35** [comment]
I agree with that. I even vote for keeping the requirement at a reasonable value (5.4) since the future v4 will most probably not support PHP5 at all. At that time, it will be nice to have our good old v3 supporting PHP5 at a broad level.

**Comment by ikkez** [comment]
it's back again, now with phpdoc hint about its deprecation
