### ISSUE TITLE
How to use localization with plurals in languages other than english?

### ISSUE THREAD

**Issue by SylwesterZarebski** [bcosca/fatfree#970]
I would like to know how to use localization with plurals in languages other than english, e.g polish, which has 3 cases:
a) 1
b) numbers ending with 2, 3 or 4 except those ending with 12, 13, or 14 (e.g. 2, 23, 2194),
c) all other.

Is it possible with fatfree localization engine?

**Comment by xfra35** [comment]
No it's not. The framework only handles the following cases: 0/1/2/3+

Obviously the framework can't handle all existing languages, but it would be nice if it could allow custom formats, such as:

```
{0, polish, caseA {# linia}, caseB {# linie}, caseC {# linii}}
```

**Comment by SylwesterZarebski** [comment]
Please add it as a feature request. Case definition could be similar to gettext's:
https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Plural-forms.html
e.g.:
```
<?php
return array(
    '!format'=> function($n) => { return $n==1 ? 0 : $n%10>=2 && $n%10<=4 && ($n%100<10 || $n%100>=20) ? 1 : 2; }
);
?>```

**Comment by xfra35** [comment]
@SylwesterZarebski see https://github.com/bcosca/fatfree-core/pull/156
