### ISSUE TITLE
fail to save bigint values in fatfree in db\sql.php file

### ISSUE THREAD

**Issue by baranii** [bcosca/fatfree#974]
fat free fails to save bigint values via ORM.
i found a solution to this problem.
pls. check it
in  db\sql.php on line 112
modify the value() function as this for integets
**case \PDO::PARAM_INT:
				return ctype_digit($val) ? $val : (int)$val ;**

**Comment by KOTRET** [comment]
you are executing the app on a 32bit-system?

**Comment by ikkez** [comment]
see duplicates: #443 and #694
