### ISSUE TITLE
Poorly encoded cgi parameters cause no route to be matched in base->mask

### ISSUE THREAD

**Issue by gobfrey** [bcosca/fatfree#975]
The url

http://url.whatever/feedback.php?message=%E4

causes a 404 at:

https://github.com/bcosca/fatfree/blob/master/lib/base.php#L1532

This appears to be due to the mask function's regular expression being problematic.  Fixed locally by the following function before $f3->run():

```php
  #handle fat free issue where badly encoded cgi parameters cause 404
  function scrub_cgi_params()
  {
        global $f3;

        $params = $f3->get('REQUEST');
        foreach (array_keys($params) as $p)
        {
                $v = $params[$p];
                $fixed = mb_convert_encoding($v, 'UTF-8', 'UTF-8'); #make it valid utf8
                if ($fixed != $v) #if the value has changed, it was previously invalid
                {
                        $params[$p] = $fixed;
                }
        }

        $path = $f3->get('PATH');
        $uri = $path . '?' . http_build_query($params);

        $f3->set('URI',$uri); #overwrite the uri in the f3 object -- when there are bad characters, this is what causes 404s
  }
```

**Comment by xfra35** [comment]
Which version of the framework are you using?

Because this issue has been raised in the past and was supposed to be fixed. See:
* https://github.com/bcosca/fatfree-core/pull/71
* https://github.com/bcosca/fatfree-core/issues/121
* https://github.com/bcosca/fatfree-core/issues/126

**Comment by ikkez** [comment]
Closing due to lack of response. Please repoen if the problem persists in the latest framework version.
