### ISSUE TITLE
SQL Sessions don't work when MySQL database has a "." in its name

### ISSUE THREAD

**Issue by sburlot** [bcosca/fatfree#977]
I have a database name like "github.com". When using \DB\Sessions, the sessions table creation fails because it's:
CREATE TABLE IF NOT EXISTS github.com.sessions
it should be
CREATE TABLE IF NOT EXISTS \`github.com\`.sessions

correctly quoting the database in lib/db/sql/session.php line 179 corrects the problem

**Comment by sburlot** [comment]
Not fixed because $db->quotekey('github.com') = `github`.`com`;
Query is still invalid:
CREATE TABLE IF NOT EXISTS `github`.`com`.`sessions` (
	`session_id` VARCHAR(40),
	`data` TEXT,
	`ip` VARCHAR(40),
	`agent` VARCHAR(255),
	`stamp` INTEGER,
	PRIMARY KEY (`session_id`)
);

**Comment by ikkez** [comment]
fixed
