### ISSUE TITLE
F3 Default port number is 0 instead of 80

### ISSUE THREAD

**Issue by AndrewEQ** [bcosca/fatfree#981]
Hi guys,

When using `$f3->reroute('/');` to redirect to the root of the website, the redirected url becomes  "https://domain.com:0" instead of "https://domain.com" when `$_SERVER['SERVER_PORT']` is not set which has happened to us in a cloud environment.

I tested it and found the problem to be with the default port number set:
https://github.com/bcosca/fatfree/blob/master/lib/base.php#L2239

Setting it to `80` currently resolves the issue.

**Comment by ikkez** [comment]
fixed in https://github.com/bcosca/fatfree-core/commit/945f8bfe81bbd3f40dc2e731cc2902c9c55b4c33

**Comment by GhaziTriki** [comment]
Isn't this issue critical to put a release for 3.6.1?

**Comment by ikkez** [comment]
This issue only appears when using google app engine, because the `$_SERVER['SERVER_PORT']` is not populated there. To mitigate this you can also just set the working port like `PORT = 80` in your config. So not that critical IMO.
