### ISSUE TITLE
driver does not support lastinsertid() sql server odbc linux

### ISSUE THREAD

**Issue by tuzoftware** [bcosca/fatfree#982]
I have a proble when connect F3 by SQL SERVER in Linux Sytem.
![message](https://cloud.githubusercontent.com/assets/24213237/21067117/dea997b0-be2e-11e6-9200-21bfda78462c.png)

**Comment by ikkez** [comment]
The odbc driver is pooly implemented and lacks of some features from the PDO interface. The missing `lastinsertid` method is probably not the only issue with this driver. Please install and use `pdo_sqlsrv` instead.
