### ISSUE TITLE
include with not treating booleans correctly

### ISSUE THREAD

**Issue by devzing** [bcosca/fatfree#983]
In my template I have:
`<include href="blocks/answers.html" with="guest=false" />`

This gets "compiled" to:
`<?php echo $this->render('blocks/answers.html',$this->mime,array('guest'=>'false')+get_defined_vars(),0); ?>`

So comparisons like:
`<check if="@guest==false">`
always fail.

**Comment by KOTRET** [comment]
does `with="guest=0"` and `<check if="!@guest">` work?

**Comment by devzing** [comment]
Yes, that will work. However, I guess the undocumented fact is that all constants in the **with** attribute get passed as strings.

**Comment by xfra35** [comment]
Well maybe then we should force strings to be quoted, so that with can have `with="guest=FALSE"` or `with="guest=MY_CONSTANT"`?

That would break backwards compatibility though..

**Comment by ikkez** [comment]
It's already possible and IMO intuitive:

```html
<F3:include href="blocks/answers.html" with="guest={{TRUE}}" />
```
```

**Comment by ikkez** [comment]
Okay this sound odd, but it actually really works:

```php
<F3:include href="blocks/answers.html" with="guest={{@tmp=TRUE}}" />
```

**Comment by devzing** [comment]
Looking at Template::_include() the logic seems to be if the value starts with "$" or is surrounded by single quotes then leave it alone, otherwise call \Base::instance()->stringify() which will always end up calling var_export() which will always wrap the value in single quotes. There is something else happening in cases where there is an expression with a variable.

guest=false becomes 'guest'=>'false'
guest=1 becomes 'guest'=>'1'
guest=@bob becomes 'guest'=>$bob
guest='bob' becomes 'guest'=>'bob'
guest="bob" becomes 'guest'=>'"bob"'
guest="(true)" becomes 'guest'=>'(true)'
guest=true==@value becomes 'guest'=>true==$value
guest=1+2 becomes 'guest'=>'1+2'
guest=1+@bob becomes 'guest'=>1+$bob

**Comment by ikkez** [comment]
fixed
