### ISSUE TITLE
SQL Session "IP" column (still) to short

### ISSUE THREAD

**Issue by exodus4d** [bcosca/fatfree#985]
The `ip` column was already extended in #950 . But this is still not big enough.

I got this Issue from a guy, running my F3 project behind a CDN (Cloudflare) setup:

#### Description (copy&paste):

***

I've just had a user report being unable to log into my self-hosted pathfinder instance while others and myself were experiencing no issues. The PHP error log thankfully pointed me in the right direction quite fast:

```
2016/12/09 15:43:41 [error] 27418#27418: *28375 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ip' at row 1 in /var/www/pathfinder/app/lib/db/sql.php:202
Stack trace:
#0 /var/www/pathfinder/app/lib/db/sql.php(202): PDOStatement->execute()
#1 /var/www/pathfinder/app/lib/db/sql/mapper.php(418): DB\SQL->exec(Array, Array)
#2 /var/www/pathfinder/app/lib/db/cursor.php(242): DB\SQL\Mapper->insert()
#3 /var/www/pathfinder/app/lib/db/sql/session.php(94): DB\Cursor->save()
#4 [internal function]: DB\SQL\Session->write('k04agv589ijaoms...', '')
#5 /var/www/pathfinder/app/lib/base.php(1910): session_commit()
#6 [internal function]: Base->unload('/var/www/pathfi...')
#7 {main}
  thrown in /var/www/pathfinder/app/lib/db/sql.php on line 202" while reading upstream, client: CLIENT_IPV6_ADDRESS, server: , request: "GET / HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "PATHFINDER_MY_HOST", referrer: "https://login.eveonline.com/oauth/authorize?response_type=code&redirect_uri=PATHFINDER_REDIRECT_URI"
```

Taking a look into the session table of pathfinder's database, I realised all IPs were stored as "pairs" (e.g. "123.123.123.123, 123.123.123.123". I assume this is caused by the way my instance is set up/proxied.

My current setup is: `Cloudflare --> nginx Loadbalancer --> nginx/php pathfinder instance`
The nginx loadbalancer is only accepting connections from Cloudflare's network and acts as a public front for all internal services, apps and websites run by me. All other instances are not reachable to the public and only accept connections over the private network from the loadbalancer.

Due to the double proxying as well as Cloudflare, the request ends up with the "X-Forwarded-For" header of "123.123.123.123, 123.123.123.123" when it reaches the pathfinder instance. I assume pathfinder/the framework you're using stores the whole "X-Forwarded-For" header, thus saving the same IP address multiple times. This works fine for IPv4 addresses (since the maximum for that is 32/40 chars with the "double proxy"), but the column is too short for IPv6 adresses.

I have circumvented this issue by increasing the max column length form 45 to 255, now allowing all users to log in just fine. The max. length of this column was already increased from 40 to 45 in 65108d22058b8ad260deb6ea236cc15fbd826529 referencing #273.
I'm honestly not sure what the best way to prevent this problem would be - either increasing the limit again or somehow changing the way pathfinder stores the client's IP address...

**Comment by Rayne** [comment]
According to Wikipedia, the first IP address in the header is the client's real address.

> The general format of the field is:
> 
> > X-Forwarded-For: client, proxy1, proxy2[3]
> 
> where the value is a comma+space separated list of IP addresses, the left-most being the original client […]

Extracting the first IP could therefore be sufficient at [base.php#L1163](https://github.com/bcosca/fatfree-core/blob/3c5792767add91cb933e2a30360598a92676fbef/base.php#L1163).

**Comment by exodus4d** [comment]
Thanks for the fast answer. I guess, we can close this issue.

**Comment by xfra35** [comment]
Why closing it? @Rayne's suggestion to extract the first IP from the `X-Forwarded-For` header makes sense.

**Comment by exodus4d** [comment]
@xfra35 I thought he was talking about doing this on the server side and change the header. Something like this: http://nginx.org/en/docs/http/ngx_http_realip_module.html

**Comment by Rayne** [comment]
I believe that the problem should be fixed in Fat-Free Framework. Its [documentation states that the system variable `IP` contains the client's *IP address*](https://fatfreeframework.com/3.6/quick-reference#IP).

> Remote IP address. The framework derives the address from headers if HTTP client is behind a proxy server. Default value: First match of Client-IP then X-Forwarded-For then $_SERVER['REMOTE_ADDR'], otherwise set to ''
