### ISSUE TITLE
Error handler doesn't display file/line info

### ISSUE THREAD

**Issue by hessodreamy** [bcosca/fatfree#987]
Similar to issue #967, it would be helpful for the error handler to include file & line info, for debugging purposes, rather than just the bare text of the error. 

I suggest adding this information to the error message by amending lines 2029-2034 (in v3.5.1) in Base.php
```
set_error_handler(
	function($code,$text, $file, $line) use($fw) {
		if ($code & error_reporting())
			$fw->error(500, "Error level ".$code.": ".$text." in ".$file." line ".$line);
	}
);

**Comment by bcosca** [comment]
Wouldn't the error message be evident in the stack trace already?

**Comment by dexwerx** [comment]
the file/line info is already available in the trace.
It's up do the error handler to display it.

`echo $fw->ERROR['trace'];`
