### ISSUE TITLE
base->unserialize() throws errors

### ISSUE THREAD

**Issue by exodus4d** [bcosca/fatfree#989]
This error appears very very rare. And is not re-produceable  on my installation :( 

I set a HIVE var by `$f3->set($cacheKey, $cacheData, $data_ttl);` and I saw some logs like this:

```
2017/01/12 15:31:17 [error] 2423#2423: *44112 FastCGI sent in stderr: "PHP message: igbinary_unserialize_string: end-of-data
PHP message: [app/lib/base.php:2152] Base->error()
PHP message: [app/lib/base.php:1084] igbinary_unserialize()
PHP message: [app/lib/base.php:2389] Base->unserialize()
PHP message: [app/lib/base.php:2411] Cache->exists()
PHP message: [app/lib/base.php:403] Cache->set()
PHP message: [app/main/model/basicmodel.php:399] Base->set()
```

**Comment by xfra35** [comment]
What's the cache backend? Couldn't it be that `$cacheData` gets truncated when it's getting too big?

**Comment by exodus4d** [comment]
This was a Redis Backend. Could this be a bad Redis config issue?

**Comment by xfra35** [comment]
How big are cached values ?
I found this topic https://groups.google.com/forum/#!topic/redis-db/-IfPc3NTqKw but it's old.

Could also be a memory allocation issue. There are a few PHPRedis [issues](https://github.com/phpredis/phpredis/issues) out there.

Or maybe did you hit the max memory limit? In which case, I guess you should find it in Redis logs.

**Comment by ikkez** [comment]
maybe a problem with the igbinary serializer. Try to explicit use the default and see if this makes a different:

```php
$f3->set('SERIALIZER', 'php'); 
```

**Comment by exodus4d** [comment]
It looks like this is a PHP/Redis and/or config problem with the environment F3 is running at.  And has nothing to do with F3 itselfe.

Ill play around with the Redis config if I figure out anything F3 related, Ill let you know and re-open this issue.
