### ISSUE TITLE
Unexpected variable types from the DB / POST variables

### ISSUE THREAD

**Issue by module0x90** [bcosca/fatfree#991]
Hi,

I am checking in my POST submit() function whether the resource has actually been changed via changed(), after load() of course. I noticed that in my case changed() is always TRUE, even when I didn't change any records.
After definitely getting more gray hair and some debug statements in copyfrom() in db/sql/mapper.php I figured that the *value* hasn't changed, it's the variable *type * what's changed from the actually record to the relevant POST.x variable.

So, an example:
In my application I am editing/submitting a **existing** booking record with startdate (MySQL type "date"), price ("DECIMAL"), numberpeople ("TINYINT") and customer_id ("INT") among other values which are not relevant for this case.
$booking->changed() (Parent \DB\SQL\Mapper) is always TRUE, also when I have nothing changed.

So drilling down the DB record loaded into $booking is this:
```
startdate(string): #2017-03-03#
price(string): #395#
numberpeople(integer): #5#
customer_id(integer): #146#
```

But the POST. coming back looks like this, this is the debug output from within copyfrom():
```
key: customer_id oldvalue(string): #146# newval(string): #146#
key: numberpeople oldvalue(string): #5# newval(string): #5#

```

I have these problems with this:
1. "customer_id" comes from the form as a "STRING" back - it's a dropdown in the form. In the DB it's an INT, an INTEGER in PHP.
2. "numberpeople" comes back as a "STRING" as well, but it should be an INTEGER, in the DB it's defined as a TINYINT
3. "price" is a simple number, it's stored as a DECIMAL in MySQL DB, but comes back as a STRING in PHP?

I helped myself now by reformatting some POST. variables via intval(), this fixed the problem with changed() then. But this appears to me a bit like a hack.

I see potentially two underlaying problems:
1. The mapping from datatype MySQL -> PHP or better: my "unusual" use of MYSQL datatypes causing this, ie. if I were to change all to INT, would that mean "price" for example is also an "integer" in PHP then (I wouldn't need floating point)?
2. How should I handle the returning dropdown/select ID? I just checked my HTML and I am setting 'value="34"' for example. Can this be forced to be INTEGER from the POST?

Where did I screw up?

Regards

Thomas

**Comment by ikkez** [comment]
Which framework version are you using? With 3.6, the mysql <-> php handling for numbers were improved. 
I once had an issue that might be related: when you pass a mapper object into a template, it could happen that its values are changed due to the auto-escaping mechanism in the template sandbox. this is usually not a big deal, but should be considered when you i.e. want to continue doing things after you have rendered and dumped a template.

**Comment by module0x90** [comment]
On Tue, Jan 31, 2017 at 03:53:53PM -0800, Christian Knuth wrote:
>    Which framework version are you using? With 3.6, the mysql <-> php
>    handling for numbers were improved.

Oh sorry, I am on 3.5.

**Comment by ikkez** [comment]
please reopen if there any issue left in the latest version.
