### ISSUE TITLE
Non-English locale doesn't work when locale is not UTF-8

### ISSUE THREAD

**Issue by pgrzego** [bcosca/fatfree#992]
We have an issue when we respond to requests which have accept-language headers set like: `en-FR;q=1, fr-FR;q=0.9`. The problem doesn't exist when locale is set with the default charset (which in our case is UTF-8). The thing when FFF sets locale with the `Base->language` method, the definition of language without default charset takes precedence over the one with it:

```php
$locales[]=$locale;
$locales[]=$locale.'.'.ini_get('default_charset');
```

Shouldn't it be the other way around? I mean `setlocale` method goes from left to right, so imho it will always choose the version without default charset or will skip both if it doesn't have it at all...

**Comment by xfra35** [comment]
This has been fixed in https://github.com/bcosca/fatfree-core/pull/180
