### ISSUE TITLE
Routing Params changed in 3.6?

### ISSUE THREAD

**Issue by ChrisFrench** [bcosca/fatfree#996]
I am currently in the middle of upgrading my application which runs on fatfree. 

I am also upgrading to php 7.1 at the same time. I have everything working except I have a stange issue. 

 Example I have a route like
```php
\Base::instance()->route( 'GET /shop/address/regions/@country_isocode_2', '\Shop\Site\Controllers\Address->regions');
```
I used to be able to do 

```php
$country_isocode_2 = $f3->get('PARAMS.country_isocode_2');
```
However now I am getting an array that looks like this.  
 ```php       
array(2) {
 [0]=>
 string(24) "/shop/address/regions/US"
 ["*"]=>
 string(2) "US"
}

 var_dump($f3->get('PARAMS')); die();
        ```

**Comment by ChrisFrench** [comment]
@ikkez we have chatted before about fatfree issues, I am scared I have hit some kind of big blocking bug.

**Comment by ChrisFrench** [comment]
I have confirmed that putting the 3.4 version of the run function  does give me the right routes. 

So I am thinking that something with this new mask() method has this issue

**Comment by xfra35** [comment]
This is due to [this line](https://github.com/bcosca/fatfree-core/blob/e33c7a65d9006851cd80d693a07d9d2b5f94e53a/base.php#L1476), which has been introduced [here](https://github.com/bcosca/fatfree-core/commit/3808ba83a604d7561098691405a5fb5aab0985b9), but I'm not sure what's the rationale.

If you name your token `@country_isocode2` it should work.

**Comment by ChrisFrench** [comment]
@xfra35  ahhh so it was the combo of an underscore and digit, Thanks a million i was about to start ripping everything apart.

**Comment by ChrisFrench** [comment]
@xfra35  confirmed and fixed in our application thank you very much.

**Comment by xfra35** [comment]
Fixed.

`@country_isocode_2` should work now but not `@_2`, which I guess nobody will use.
