### ISSUE TITLE
Suggestion: Memcached extension (re-submission of #623)

### ISSUE THREAD

**Issue by valtonia** [bcosca/fatfree#997]
Please implement memcached module support in F3.

I realise from #623 that you say there's no need to implement both memcache and memcached module support I should point out that AFAIK the memcache module does not work with PHP 7 or above, whereas the memcached module does.  Given that PHP 7.0 has been out for some time now and support for the memcache module is still not forthcoming, it would make sense to now include memcached module support in F3.

Thanks

**Comment by bcosca** [comment]
I disagree. I use 7.1.1 with both memcache and mongodb extensions without any trouble whatsoever. Nothing in the PHP docs nor blogs state that these modules are being deprecated or abandoned either.

**Comment by xfra35** [comment]
The [official repo](https://github.com/php/pecl-caching-memcache/releases) is unmaintained, and so is the PECL [package](https://pecl.php.net/package/memcache). But there's an [unofficial repo](https://github.com/websupport-sk/pecl-memcache) which has ported the extension to PHP7.
@bcosca which one are you using?

**Comment by bcosca** [comment]
I use the 3.0.9-dev package that comes along with ArchLinux.

**Comment by valtonia** [comment]
I really don't understand the reluctance to support a popular caching mechanism, but whatever, I implemented it myself and it took all of 15 minutes.

**Comment by xfra35** [comment]
@bcosca so that means ArchLinux has integrated the *unofficial* php7 port of php-memcache. But that's not the case for all distributions. For example, Debian gives only the choice between php5-memcache (3.0.8) and php7.0-memcached (3.0.1).
