### ISSUE TITLE
Allow using custom error handler

### ISSUE THREAD

**Issue by jtojnar** [bcosca/fatfree#999]
I would like to use [Tracy](https://github.com/nette/tracy) for handling errors and exceptions since it has interesting features like [AJAX error handling](https://github.com/nette/tracy/blob/1a37c7b6c74cf1dc8e1bbf043e1a2123e69d4153/examples/ajax.php).

**Comment by Rayne** [comment]
Fat-Free Framework doesn't forbid to use a third party debugger or error handler. I did a few successful tests with a custom `ONERROR` handler which forwards the errors to `Tracy`.

Two notes:

* I didn't test the `AJAX` part
* The snippet is using the `public` method `Debugger::exceptionHandler` which is declared as `@internal`.

```php
$f3->set('ONERROR', function () use ($f3) {
    Debugger::barDump($f3->get('ERROR'), 'ERROR');
    $e = $f3->get('EXCEPTION');
    // There isn't an exception when calling `Base->error()`.
    if (!$e instanceof Throwable) {
        $e = new Exception('HTTP ' . $f3->get('ERROR.code'));
    }
    Debugger::exceptionHandler($e);
});
```

Full example: [ Fat-Free Framework with PHP Debugger Tracy
](https://gist.github.com/Rayne/55e098e48a5742301671bee358e0be41)

**Comment by jtojnar** [comment]
The issue with using `ONERROR` is precisely that it requires us to connect fatfree with whatever handler we want manually, rather than just using the other library’s defaults.

Additionally, even if we set `ONERROR` handler, fatfree still changes the HTTP status code, spams the `stderr` with `error_log` function and then dies, even though we might want to avoid any of that.
